# -*- coding: utf-8 -*-
"""
Complete generator for Book 7: Aesop's Classic Fables (Part 2): Moral of the Town
15 Pages x 20 Sentences = 300 Sentences.
"""

fables = [
    # 1. The Fox and the Crow
    {
        "page_no": 1,
        "title": "The Fox and the Crow",
        "tr_title": "Tilki ile Karga",
        "sentences": [
            ("A glossy black crow had perched high upon the branch of a tall pine tree.",
             "Parlak siyah bir karga, uzun bir çam ağacının dalına yüksekçe tünemişti.",
             "glossy black | Parlak siyah; 'perched' tünemiş."),
            ("In her beak she held a delicious, fragrant morsel of rich yellow cheese.",
             "Gagasında lezzetli, mis kokulu zengin sarı bir peynir lokması tutuyordu.",
             "fragrant morsel | Güzel kokulu lokma."),
            ("She had snatched it from an open cottage window and was preparing to enjoy her feast.",
             "Onu açık bir kulübe penceresinden kapıp kaçmıştı ve ziyafetinin tadını çıkarmaya hazırlanıyordu.",
             "snatched | Kapıp kaçmak; 'cottage' köy evi/kulübe."),
            ("A hungry fox was prowling silently through the grove in search of breakfast.",
             "Aç bir tilki, kahvaltı arayışıyla korulukta sessiz adımlarla kol geziyordu.",
             "prowling silently | Sessizce kol gezmek."),
            ("The tempting scent of aged cheese immediately attracted his keen nostrils.",
             "Eski peynirin iştah açıcı kokusu anında onun keskin burun deliklerini cezbetti.",
             "keen nostrils | Keskin burun delikleri / koku duyusu."),
            ("He looked up into the branches and spied the crow sitting proudly with her prize.",
             "Dalların arasına yukarı doğru baktı ve karganın ödülüyle gururla oturduğunu fark etti.",
             "spied | Gözetlemek, aniden görmek."),
            ("'That cheese must be mine,' murmured the cunning fox, licking his whiskers.",
             "Kurnaz tilki bıyıklarını yalayarak, 'O peynir benim olmalı,' diye mırıldandı.",
             "licking whiskers | Bıyıklarını yalamak."),
            ("Knowing that he could not climb the tree, he resolved to employ smooth flattery.",
             "Ağaca tırmanamayacağını bildiğinden, tatlı dilli dalkavukluğa başvurmaya karar verdi.",
             "smooth flattery | Tatlı dilli dalkavukluk / pohpohlama."),
            ("He trotted to the foot of the pine, bowed low, and looked up with feigned admiration.",
             "Çamın dibine doğru koşturdu, derin bir reverans yaptı ve sahte bir hayranlıkla yukarı baktı.",
             "feigned admiration | Sahte / yapmacık hayranlık."),
            ("'Good morning, most beautiful creature of the woodland!' he purred sweetly.",
             "Tatlı bir dille mırıldanarak, 'Günaydın ormanın en güzel yaratığı!' dedi.",
             "purred sweetly | Tatlı tatlı mırıldanmak."),
            ("'How remarkably glossy and lustrous are your magnificent black feathers!'",
             "'O muazzam siyah tüyleriniz ne kadar da dikkat çekici biçimde parlak ve ışıltılı!'",
             "lustrous | Işıltılı, pırıl pırıl."),
            ("'Your graceful shape and noble carriage surpass those of the imperial eagle himself.'",
             "'Zarif endamınız ve asil duruşunuz imparatorluk kartalınınkini bile geride bırakıyor.'",
             "noble carriage | Asil duruş / tavır; 'surpass' geride bırakmak."),
            ("The crow listened with vanity, tilting her head from side to side in delight.",
             "Karga sevinçle kafasını bir o yana bir bu yana eğerek kibriyle dinledi.",
             "vanity | Kibir, kuruntu; 'in delight' sevinçle."),
            ("'If only your melodious voice equalled your incomparable beauty,' continued the fox.",
             "Tilki devam etti: 'Keşke o ahenkli sesiniz de emsalsiz güzelliğinize denk olsaydı.'",
             "melodious voice | Ahenkli, nağmeli ses."),
            ("'Then you would undoubtedly be crowned the supreme Queen of all birds.'",
             "'O vakit hiç şüphesiz bütün kuşların yüce Kraliçesi olarak taç giyerdiniz.'",
             "supreme Queen | Yüce kraliçe; 'crowned' taçlandırılmış."),
            ("Anxious to prove that her musical talent was as exquisite as her plumage, she opened her bill.",
             "Müzik kabiliyetinin de tüyleri kadar enfes olduğunu kanıtlamak için can atan karga gagasını açıverdi.",
             "anxious to prove | Kanıtlamak için can atan; 'plumage' kuş tüyleri."),
            ("'Caw! Caw!' she croaked loudly, flapping her wings with eager ostentation.",
             "Hevesli bir gösterişle kanatlarını çırparak, 'Gaaak! Gaaak!' diye avazı çıktığı kadar öttü.",
             "eager ostentation | Hevesli gösterişçilik; 'croaked' gakladı."),
            ("The very moment her beak opened, the heavy morsel of cheese tumbled down through the air.",
             "Gagasının açıldığı tam o anda, ağır peynir lokması havada süzülerek aşağı düştü.",
             "tumbled down | Aşağı yuvarlanmak."),
            ("The nimble fox caught it neatly in his jaws before it even touched the forest grass.",
             "Çevik tilki, peynir henüz orman çimenlerine bile değmeden onu çenesiyle ustaca havada kaptı.",
             "caught neatly | Ustaca yakalamak; 'nimble' çevik."),
            ("Never trust flatterers, for those who offer false praise always seek their own selfish gain.",
             "Dalkavuklara asla güvenmeyin; zira sahte övgüler düzenler daima kendi bencil çıkarlarını gözetirler.",
             "flatterers | Dalkavuklar, pohpohçular; 'selfish gain' bencil çıkar.")
        ],
        "vocab_focus": [
            ("glossy", "parlak, cilalı"),
            ("fragrant morsel", "mis kokulu lokma"),
            ("smooth flattery", "tatlı dilli dalkavukluk"),
            ("feigned", "sahte, yapmacık"),
            ("lustrous", "ışıltılı, parıldayan"),
            ("vanity", "kibir, kendini beğenmişlik"),
            ("plumage", "kuş tüyleri"),
            ("ostentation", "gösterişçilik, caka satma")
        ]
    },

    # 2. The Wolf and the Crane
    {
        "page_no": 2,
        "title": "The Wolf and the Crane",
        "tr_title": "Kurt ile Turna",
        "sentences": [
            ("A voracious wolf was devouring his prey in greedy haste when a sharp bone stuck in his throat.",
             "Obur bir kurt avını açgözlü bir telaşla yiyip yutarken boğazına sivri bir kemik saplandı.",
             "voracious | Obur, doymak bilmez; 'stuck in throat' boğaza saplanmak."),
            ("The obstruction caused him excruciating agony, preventing him from swallowing or drawing breath.",
             "Bu tıkanıklık ona dayanılmaz bir acı veriyor, yutkunmasını veya nefes almasını engelliyordu.",
             "excruciating agony | Dayanılmaz, kahredici ızdırap."),
            ("He ran frantically back and forth across the forest, howling in muffled distress.",
             "Boğuk bir çaresizlikle inleyerek ormanda çılgınca bir ileri bir geri koşturdu.",
             "muffled distress | Boğuk sıkıntı / ızdırap."),
            ("To every creature he encountered, he promised a magnificent reward if they would extract the bone.",
             "Karşılaştığı her canlıya, kemiği çıkarırlarsa muazzam bir ödül vadetti.",
             "extract | Çekip çıkarmak; 'magnificent reward' muhteşem ödül."),
            ("However, no beast dared to put its head inside the jaws of so treacherous a predator.",
             "Fakat hiçbir hayvan böylesine hain bir yırtıcının çenesinin içine kafasını sokmaya cesaret edemedi.",
             "treacherous predator | Hain yırtıcı."),
            ("At last, a gentle crane took pity on the suffering brute and agreed to undertake the dangerous task.",
             "Nihayet nazik bir turna kuşu acı çeken hayvana acıdı ve bu tehlikeli vazifeyi üstlenmeyi kabul etti.",
             "took pity on | Birine acımak; 'undertake' üstlenmek."),
            ("The wolf lay down and opened his enormous, fang-filled maw as wide as he possibly could.",
             "Kurt yere uzandı ve sivri dişlerle dolu kocaman ağzını açabildiği kadar geniş açtı.",
             "maw | Hayvan ağzı / kursağı; 'fang-filled' sivri dişlerle dolu."),
            ("The slender bird extended her long, graceful neck deep down into the wolf's throat.",
             "İnce uzun kuş, zarif uzun boynunu kurdun boğazının derinliklerine kadar uzattı.",
             "slender bird | İnce narin kuş; 'graceful neck' zarif boyun."),
            ("With the tip of her sharp, tweezers-like beak, she skillfully seized the pointed bone.",
             "Cımbızı andıran keskin gagasının ucuyla sivri kemiği ustaca kavradı.",
             "tweezers-like | Cımbız gibi; 'skillfully seized' ustaca yakaladı."),
            ("With a gentle pull, she extracted the painful obstruction without injuring the beast's flesh.",
             "Nazik bir çekişle, canavarın etini yaralamadan acı veren engeli çekip çıkardı.",
             "gentle pull | Nazikçe çekiş; 'obstruction' engel, tıkanıklık."),
            ("The wolf gave a deep sigh of immense relief as the agonizing pain vanished instantly.",
             "Kahredici acı anında yok olunca kurt derin ve muazzam bir rahatlama nefesi aldı.",
             "sigh of relief | Rahatlama nefesi; 'agonizing' ıstırap verici."),
            ("'Now, noble wolf,' chirped the crane politely, 'kindly bestow upon me the promised reward.'",
             "Turna nezaketle cıvıldayarak, 'Şimdi asil kurt,' dedi, 'lütfen vadettiğin ödülü bana bahşet.'",
             "bestow upon | Birine bahşetmek, vermek."),
            ("The wolf bared his gleaming teeth and snarled with ferocious arrogance.",
             "Kurt parıldayan dişlerini gösterdi ve vahşi bir kibirle hırladı.",
             "snarled with arrogance | Kibirle hırlamak."),
            ("'Ungrateful creature!' growled the wicked beast, snapping his jaws menacingly.",
             "Kötü kalpli canavar çenesini tehditkarca şaklatarak, 'Nankör yaratık!' diye homurdandı.",
             "snapping jaws menacingly | Çenesini tehditkarca şaklatmak."),
            ("'Is it not sufficient reward that you put your head into a wolf's mouth and drew it out safely?'",
             "'Başını bir kurdun ağzına sokup sağ salim geri çıkarabilmiş olman yeterli bir ödül değil midir?'",
             "sufficient reward | Yeterli / kafi ödül."),
            ("'You ought to thank your lucky stars that I did not bite off your slender neck.'",
             "'O incecik boynunu ısırıp koparmadığım için şanslı yıldızlarına şükretmelisin.'",
             "thank lucky stars | Şansına şükretmek deyimidir."),
            ("The crane realized that arguing with a ruthless predator would only endanger her life.",
             "Turna, acımasız bir yırtıcıyla tartışmanın yalnızca kendi hayatını tehlikeye atacağını anladı.",
             "ruthless predator | Acımasız avcı / yırtıcı."),
            ("Without uttering another word, she spread her broad white wings and flew swiftly away.",
             "Tek bir kelime daha etmeden geniş beyaz kanatlarını açtı ve hızla uçup uzaklaştı.",
             "flew swiftly away | Hızla uçup uzaklaşmak."),
            ("She vowed never again to place her faith in the promises of unprincipled scoundrels.",
             "Ahlaksız ve ilkesiz alçakların vaatlerine bir daha asla güvenmemeye yemin etti.",
             "unprincipled scoundrels | İlkesiz alçaklar / namussuzlar."),
            ("In serving the wicked, expect no reward, and consider yourself fortunate if you escape injury.",
             "Kötülere hizmet ederken hiçbir ödül beklemeyin; zarar görmeden kurtulursanız kendinizi şanslı sayın.",
             "escape injury | Yaralanmadan / zarar görmeden kurtulmak.")
        ],
        "vocab_focus": [
            ("voracious", "obur, doymak bilmez"),
            ("excruciating", "dayanılmaz derecede acı veren"),
            ("extract", "çekip çıkarmak"),
            ("maw", "hayvan ağzı/boğazı"),
            ("obstruction", "tıkanıklık, engel"),
            ("bestow", "bahşetmek, hediye etmek"),
            ("ruthless", "acımasız, merhametsiz"),
            ("scoundrels", "alçaklar, namussuzlar")
        ]
    },

    # 3. The Fox and the Stork
    {
        "page_no": 3,
        "title": "The Fox and the Stork",
        "tr_title": "Tilki ile Leylek",
        "sentences": [
            ("A mischievous fox invited a dignified stork to dine with him at his cozy forest den.",
             "Muzip bir tilki, ağırbaşlı bir leyleği ormandaki sıcak ininde birlikte akşam yemeği yemeye davet etti.",
             "mischievous | Muzip, hınzır; 'dignified' ağırbaşlı, vakur."),
            ("The stork gladly accepted the hospitable invitation, anticipating a pleasant evening among friends.",
             "Leylek dostlar arasında hoş bir akşam geçirmeyi umarak bu misafirperver daveti memnuniyetle kabul etti.",
             "anticipating | Ummak, beklemek; 'hospitable' misafirperver."),
            ("When dinner was served, the sly fox placed before them a very shallow stone dish.",
             "Yemek servis edildiğinde kurnaz tilki önlerine son derece sığ bir taş tabak koydu.",
             "shallow dish | Sığ tabak / çanak."),
            ("In the dish was a thin broth of aromatic herbs, which smelled exceedingly appetizing.",
             "Tabağın içinde son derece iştah açıcı kokan, aromatik otlardan yapılmış duru bir çorba vardı.",
             "thin broth | Duru çorba / et suyu; 'appetizing' iştah açıcı."),
            ("The fox lapped up the savory soup with great ease, his broad tongue clearing the plate rapidly.",
             "Tilki geniş diliyle tabağı hızla temizleyerek leziz çorbayı büyük bir kolaylıkla yalayıp yuttu.",
             "lapped up | Yalayıp yutmak (sıvıyı diliyle içmek)."),
            ("The poor stork, having a long, slender beak, could only peck uselessly at the flat surface.",
             "Uzun ve ince bir gagaya sahip olan zavallı leylek ise düz yüzeye yalnızca nafile darbeler vurabildi.",
             "peck uselessly | Nafile gagalamak."),
            ("Not a single drop of the delicious soup entered her mouth despite all her patient efforts.",
             "Bütün sabırlı çabalarına rağmen lezzetli çorbanın tek bir damlası bile leyleğin ağzına girmedi.",
             "patient efforts | Sabırlı çabalar."),
            ("The fox pretended to be concerned, asking if she found the food unpalatable.",
             "Tilki yemeği lezzetsiz mi bulduğunu sorarak endişelenmiş gibi numara yaptı.",
             "unpalatable | Tatsız, lezzetsiz, yenmez."),
            ("'I am exceedingly sorry you do not enjoy my cooking,' chuckled the host deceitfully.",
             "Ev sahibi hilekarca kıkırdayarak, 'Yemeklerimi beğenmemenize son derece üzüldüm,' dedi.",
             "deceitfully | Hilekarca, aldatıcı bir tavırla."),
            ("The stork maintained her composure, politely thanking him for his kind entertainment.",
             "Leylek istifini bozmadı; nazik ağırlaması için tilkiye kibarca teşekkür etti.",
             "maintained composure | İstifini / sükunetini bozmamak."),
            ("Before departing, she requested the pleasure of the fox's company for dinner the following evening.",
             "Ayrılmadan önce, ertesi akşam tilkinin kendi evine akşam yemeğine teşrif etmesini rica etti.",
             "requested the pleasure | Şerefine nail olmayı rica etmek (davet nezaketi)."),
            ("The greedy fox gladly accepted, eager to enjoy a free meal at another's expense.",
             "Açgözlü tilki başkasının kesesinden bedava bir yemeğin tadını çıkarmaya can atarak memnuniyetle kabul etti.",
             "at another's expense | Başkasının hesabına / kesesinden."),
            ("The next day, when the fox arrived, he smelled the delicious aroma of roasted minced meat.",
             "Ertesi gün tilki vardığında, kızarmış kıyma etin enfes kokusunu duydu.",
             "minced meat | Kıyma et; 'aroma' hoş koku."),
            ("The stork served the meal in tall jars with very long, narrow necks and wide bases.",
             "Leylek yemeği, çok uzun ve dar boyunlu, tabanı geniş yüksek kavanozlarda servis etti.",
             "tall jars | Yüksek kavanozlar / vazolar."),
            ("The stork easily inserted her long beak into the jar, feasting upon the tender morsels.",
             "Leylek uzun gagasını kavanozun içine kolayca daldırdı ve yumuşacık lokmalarla ziyafet çekti.",
             "feasting upon | İle ziyafet çekmek."),
            ("The fox, with his short, broad snout, could not reach even the rim of the fragrant stew.",
             "Kısa ve geniş burnuyla tilki, mis kokulu yahninin kenarına bile ulaşamadı.",
             "broad snout | Geniş burun; 'fragrant stew' kokulu yahni."),
            ("He could do nothing but sniff the outside of the glass and lick the exterior in frustration.",
             "Büyük bir hayal kırıklığı içinde bardağın dışını koklamaktan ve dış yüzeyini yalamaktan başka hiçbir şey yapamadı.",
             "in frustration | Hayal kırıklığı içinde."),
            ("'I hope the meat is tender enough for your taste,' smiled the stork graciously.",
             "Leylek zarafetle tebessüm ederek, 'Umarım et ağız tadınıza yetecek kadar yumuşaktır,' dedi.",
             "graciously | Zarafetle, incelikle."),
            ("The crestfallen fox had to slink away hungrier than when he had arrived.",
             "Boynu bükük tilki, geldiğinden çok daha aç bir vaziyette sinsice sıvışıp gitmek zorunda kaldı.",
             "slink away | Sessizce sıvışıp gitmek."),
            ("One should never play tricks on others unless one is prepared to receive the same in return.",
             "Kişi aynısının karşılık olarak kendisine yapılmasını göze alamıyorsa, başkalarına asla oyun oynamamalıdır.",
             "play tricks on | Birine oyun oynamak / numara çekmek.")
        ],
        "vocab_focus": [
            ("mischievous", "muzip, yaramaz"),
            ("shallow", "sığ, derin olmayan"),
            ("broth", "et/ot suyu, duru çorba"),
            ("unpalatable", "tatsız, yenmez"),
            ("maintained composure", "soğukkanlılığını korudu"),
            ("narrow necks", "dar boyunlar"),
            ("fragrant stew", "mis kokulu yahni"),
            ("slink away", "sessizce sıvışıp gitmek")
        ]
    }
]

# Write rest of fables 4 to 15
fables_4_to_15 = [
    # 4. The Grasshopper and the Owl
    {
        "page_no": 4,
        "title": "The Grasshopper and the Owl",
        "tr_title": "Ağustos Böceği ile Baykuş",
        "sentences": [
            ("An elderly owl lived in the hollow trunk of an ancient oak tree in a shady forest.",
             "Yaşlı bir baykuş, gölgeli bir ormandaki kadim bir meşe ağacının kovuk gövdesinde yaşardı.",
             "hollow trunk | Kovuk gövde; 'ancient oak' kadim meşe."),
            ("She was accustomed to hunt by night and sleep undisturbed throughout the bright daylight hours.",
             "Geceleri avlanmaya ve aydınlık gündüz saatleri boyunca rahatsız edilmeden uyumaya alışkındı.",
             "undisturbed | Rahatsız edilmeden; 'accustomed to' alışkın."),
            ("One hot summer noon, a noisy grasshopper perched on a nearby bough and began chirping loudly.",
             "Sıcak bir yaz öğlesinde gürültücü bir ağustos böceği yakındaki bir dala tünedi ve avazı çıktığı kadar ötmeye başladı.",
             "bough | Ağaç dalı; 'chirping' cıvıldamak/ötmek."),
            ("His grating, repetitive rasp echoed incessantly through the quiet glade.",
             "Onun kulak tırmalayan, tekdüze vızıltısı sessiz orman açıklığında durmaksızın yankılandı.",
             "grating rasp | Kulak tırmalayan cırıltı; 'incessantly' durmaksızın."),
            ("The owl poked her head out of the hollow and politely asked the musician to desist.",
             "Baykuş kafasını kovuktan dışarı uzattı ve müzisyenden kibarca bu gürültüye son vermesini rica etti.",
             "desist | Vazgeçmek, durmak; 'poked head out' kafasını uzatmak."),
            ("'I am very tired, neighbor,' she said, 'and your singing prevents me from resting.'",
             "'Çok yorgunum komşu,' dedi, 've senin şarkın dinlenmeme mani oluyor.'",
             "prevents from resting | Dinlenmeye engel olmak."),
            ("The insolent grasshopper only laughed and chirped even louder to annoy her.",
             "Küstah ağustos böceği ise yalnızca güldü ve baykuşu sinirlendirmek için daha da yüksek sesle öttü.",
             "insolent | Küstah, saygısız."),
            ("'The daylight belongs to me as much as to you!' shouted the insect boastfully.",
             "Böcek kibirle, 'Gündüz ışığı senin olduğu kadar benimdir de!' diye bağırdı.",
             "boastfully | Kibirle, övünerek."),
            ("Knowing that her eyes could not see well in bright sunlight, the owl refrained from attacking.",
             "Parlak güneş ışığında gözlerinin iyi göremediğini bilen baykuş saldırmaktan kaçındı.",
             "refrained from | Bir şeyden kaçınmak / kendini tutmak."),
            ("She realized that cunning would succeed far better than useless pleading.",
             "Kurnazlığın faydasız yalvarmalardan çok daha iyi sonuç vereceğini anladı.",
             "useless pleading | Faydasız yalvarışlar."),
            ("She retreated slightly into the dark hollow and called out in a flattering tone.",
             "Karanlık kovuğun içine hafifçe çekildi ve pohpohlayıcı bir ses tonuyla seslendi.",
             "flattering tone | Pohpohlayıcı / tatlı dil."),
            ("'Since your music keeps me awake, I might as well enjoy your extraordinary talent,' she purred.",
             "Tatlı bir sesle, 'Madem müziğin beni uyanık tutuyor, bari o olağanüstü yeteneğinin tadını çıkarayım,' dedi.",
             "might as well | Bari ... yapayım (kalıbı)."),
            ("'I have just received a flask of delicious nectar sent to me from the gardens of Olympus.'",
             "'Bana tam da Olimpos'un bahçelerinden gönderilmiş enfes bir nektar şişesi ulaştı.'",
             "flask of nectar | Nektar şişesi."),
            ("'If you come inside, you may drink freely to lubricate your wondrous vocal chords.'",
             "'İçeri gelirsen, o harikulade ses tellerini yağlamak için kana kana içebilirsin.'",
             "lubricate | Yağlamak, yumuşatmak; 'vocal chords' ses telleri."),
            ("The vain grasshopper was completely seduced by the prospect of wine and flattery.",
             "Kibirli ağustos böceği, şarap ve övgü ihtimali karşısında büsbütün büyülendi.",
             "seduced by | İle aklı çelinmek / büyülenmek."),
            ("Without suspecting any peril, he hopped boldly into the darkness of the tree hollow.",
             "Hiçbir tehlikeden şüphelenmeyerek cesur adımlarla ağaç kovuğunun karanlığına sıçradı.",
             "hopped boldly | Cesurca zıplamak."),
            ("The instant he crossed the threshold, the sharp-eyed owl seized him in her deadly talons.",
             "Eşiği aştığı tam o anda, keskin gözlü baykuş onu ölümcül pençeleriyle kıskıvrak yakaladı.",
             "deadly talons | Ölümcül pençeler; 'threshold' eşik."),
            ("She devoured the foolish singer in one gulp and settled down to enjoy her peaceful slumber.",
             "Ahmak şarkıcıyı tek bir lokmada yutup bitirdi ve huzurlu uykusunun tadını çıkarmak üzere yerine kuruldu.",
             "in one gulp | Bir dikişte / tek lokmada."),
            ("Silence returned to the forest, broken only by the gentle rustle of leaves.",
             "Ormana yalnızca yaprakların hafif hışırtısıyla bölünen derin bir sessizlik geri döndü.",
             "rustle of leaves | Yaprak hışırtısı."),
            ("Flattery is a perilous trap that leads the foolish directly into the jaws of destruction.",
             "Dalkavukluk, ahmakları dosdoğru felaketin pençesine sürükleyen son derece tehlikeli bir tuzaktır.",
             "jaws of destruction | Yıkımın / felaketin pençesi.")
        ],
        "vocab_focus": [
            ("undisturbed", "rahatsız edilmeden"),
            ("grating rasp", "kulak tırmalayan cırıltı"),
            ("insolent", "küstah, saygısız"),
            ("refrained from", "kaçındı, kendini tuttu"),
            ("flattering", "pohpohlayıcı, dalkavukça"),
            ("lubricate", "yağlamak, yumuşatmak"),
            ("seduced", "aklı çelindi, büyülendi"),
            ("talons", "yırtıcı kuş pençeleri")
        ]
    },

    # 5. The Monkey and the Dolphin
    {
        "page_no": 5,
        "title": "The Monkey and the Dolphin",
        "tr_title": "Maymun ile Yunus",
        "sentences": [
            ("It was an ancient custom among Greek sailors to take pet monkeys with them on sea voyages.",
             "Yunan denizciler arasında deniz yolculuklarına evcil maymunları da yanlarında götürmek eski bir gelenekti.",
             "ancient custom | Kadim gelenek; 'sea voyages' deniz seferleri."),
            ("One sunny morning, a merchant ship set sail for Athens with a lively ape on board.",
             "Güneşli bir sabah, bir ticaret gemisi güvertesinde neşeli bir maymunla birlikte Atina'ya doğru yelken açtı.",
             "set sail | Yelken açmak; 'on board' güvertede."),
            ("Suddenly, a violent gale erupted near the rocky headland of Sunium, shattering the wooden hull.",
             "Ansızın Sunium'un kayalık burnu yakınlarında patlak veren şiddetli bir fırtına ahşap tekneyi parçaladı.",
             "shattering the hull | Tekne gövdesini parçalamak; 'headland' burun."),
            ("All hands were plunged into the churning sea, struggling desperately against the mountainous waves.",
             "Bütün mürettebat köpüren denize savruldu ve dağ gibi dalgalara karşı can havliyle mücadele etti.",
             "all hands | Bütün mürettebat; 'churning sea' köpüren deniz."),
            ("A friendly dolphin, renowned for rescuing drowning humans, swam swiftly through the tempest.",
             "Boğulan insanları kurtarmasıyla nam salmış dost canlısı bir yunus fırtınanın içinde hızla yüzdü.",
             "drowning humans | Boğulan insanlar; 'tempest' fırtına."),
            ("Seeing the monkey struggling in the foam, the dolphin mistook him for a shipwrecked man.",
             "Köpüklerin arasında çırpınan maymunu gören yunus, onu kazazede bir insan zannetti.",
             "mistook for | Bir şeyi başkası sanmak; 'shipwrecked' kazazede."),
            ("He glided beneath the exhausted animal and carried him safely upon his sleek, curved back.",
             "Bitkin düşen hayvanın altına doğru süzüldü ve onu parlak, kavisli sırtında güvenle taşıdı.",
             "glided beneath | Altına doğru süzülmek; 'sleek' pürüzsüz, parlak."),
            ("As they neared the tranquil shores of Piraeus, the chief harbor of Athens, the dolphin spoke.",
             "Atina'nın ana limanı olan Pire'nin sakin kıyılarına yaklaştıklarında yunus söze başladı.",
             "chief harbor | Ana liman; 'tranquil shores' sakin kıyılar."),
            ("'Are you an Athenian citizen?' inquired the noble cetacean in a friendly tone.",
             "Asil deniz memelisi dostane bir ses tonuyla, 'Siz Atina vatandaşı mısınız?' diye sordu.",
             "cetacean | Balina/yunus cinsi deniz memelisi; 'citizen' vatandaş."),
            ("'Yes, indeed,' replied the monkey boastfully, 'and I belong to one of the most illustrious families.'",
             "Maymun kibirle, 'Evet, elbette,' diye yanıt verdi, 'üstelik en şanlı ailelerden birine mensubum.'",
             "illustrious families | Şanlı, seçkin aileler."),
            ("'Then no doubt you are well acquainted with the great Piraeus?' asked the dolphin.",
             "Yunus, 'O halde hiç şüphesiz büyük Pire ile çok yakından tanışıyorsunuzdur?' diye sordu.",
             "well acquainted with | Bir şeyi/birini çok yakından tanımak."),
            ("Thinking that Piraeus must be an eminent statesman, the ignorant monkey nodded vigorously.",
             "Pire'nin seçkin bir devlet adamı olması gerektiğini düşünen cahil maymun hararetle başını salladı.",
             "eminent statesman | Seçkin devlet adamı; 'nodded vigorously' hararetle baş sallamak."),
            ("'Oh, very well acquainted indeed!' bragged the impudent ape with supreme confidence.",
             "Yüzsüz maymun üstün bir özgüvenle, 'Ah, hem de son derece yakından tanışırım!' diye böbürlendi.",
             "impudent ape | Yüzsüz / terbiyesiz maymun; 'bragged' böbürlendi."),
            ("'He is an intimate friend of mine, and we dine together at his palace frequently.'",
             "'Kendisi benim çok samimi bir dostumdur ve sarayında sık sık birlikte akşam yemeği yeriz.'",
             "intimate friend | Samimi / canciğer dost."),
            ("The dolphin was shocked and disgusted by such shameless falsehood and preposterous vanity.",
             "Yunus böylesine utanmazca bir yalana ve akıl almaz bir kendini beğenmişliğe şaşıp tiksindi.",
             "shameless falsehood | Utanmazca yalan; 'preposterous vanity' akıl almaz kibir."),
            ("Realizing that the creature upon his back was a foolish impostor, he plunged beneath the water.",
             "Sırtındaki mahlukun ahmak bir sahtekar olduğunu anlayan yunus dosdoğru suyun altına daldı.",
             "foolish impostor | Ahmak sahtekar; 'plunged beneath' derine dalmak."),
            ("The boastful monkey tumbled headlong into the deep, churning brine with a frantic shriek.",
             "Övüngen maymun çılgınca bir çığlıkla kafa üstü derin ve köpüklü tuzlu suya yuvarlandı.",
             "tumbled headlong | Kafa üstü yuvarlanmak; 'brine' tuzlu su/deniz."),
            ("The dolphin swam away toward open sea, leaving the liar to suffer his well-deserved fate.",
             "Yunus açık denize doğru yüzüp uzaklaşarak yalancıyı hak ettiği akıbetiyle baş başa bıraktı.",
             "well-deserved fate | Hak edilmiş akıbet / son."),
            ("The wretched monkey drowned in the waves, a victim of his own ridiculous pretension.",
             "Sefil maymun, kendi gülünç gösteriş merakının kurbanı olarak dalgaların arasında boğuldu.",
             "ridiculous pretension | Gülünç gösteriş / caka satma."),
            ("Those who pretend to possess knowledge they lack only expose their folly and invite disaster.",
             "Sahip olmadıkları bilgiye sahipmiş gibi davrananlar, yalnızca kendi ahmaklıklarını ifşa eder ve felakete davetiye çıkarırlar.",
             "expose their folly | Kendi ahmaklığını ifşa etmek.")
        ],
        "vocab_focus": [
            ("custom", "gelenek, adet"),
            ("shattering", "parçalayan, tuzla buz eden"),
            ("shipwrecked", "gemisi batmış, kazazede"),
            ("illustrious", "şanlı, meşhur, seçkin"),
            ("well acquainted", "yakından tanıyan"),
            ("impudent", "yüzsüz, arsız"),
            ("impostor", "sahtekar, dolandırıcı"),
            ("pretension", "gösteriş, caka satma")
        ]
    },

    # 6. The Ass in the Lion's Skin
    {
        "page_no": 6,
        "title": "The Ass in the Lion's Skin",
        "tr_title": "Aslan Postundaki Eşek",
        "sentences": [
            ("A dull donkey was grazing on a solitary hillside when he discovered a discarded hunter's prize.",
             "Ahmak bir eşek ıssız bir yamaçta otlarken, avcıların geride bıraktığı bir ganimet keşfetti.",
             "dull donkey | Ahmak eşek; 'discarded' atılmış, terk edilmiş."),
            ("It was the complete skin of a formidable lion, left to dry in the blazing sun.",
             "Kavurucu güneşin altında kurumaya bırakılmış heybetli bir aslanın eksiksiz postuydu bu.",
             "blazing sun | Kavurucu güneş; 'formidable lion' heybetli aslan."),
            ("The foolish animal wrapped the shaggy hide around his body, pulling the head over his ears.",
             "Ahmak hayvan tüylü postu gövdesine sardı ve aslanın başını kendi kulaklarının üzerine çekti.",
             "shaggy hide | Kaba tüylü post / deri."),
            ("Gazing at his reflection in a quiet pool, he was delighted by his terrifying new aspect.",
             "Durgun bir havuzdaki aksine bakarak bu yeni ve korkutucu görünüşünden son derece memnun oldu.",
             "terrifying aspect | Korkutucu görünüm / çehre."),
            ("'Now all the beasts of the forest shall tremble before my sovereign might,' he brayed softly.",
             "Usulca anırarak, 'Artık ormandaki bütün hayvanlar benim hükümdar gücümün önünde titreyecek,' dedi.",
             "sovereign might | Hükümdar gücü / kudreti."),
            ("He strode boldly into the green meadows where herds of cows and flocks of sheep were feeding.",
             "İnek sürülerinin ve koyunların otladığı yeşil çayırlara doğru cesur adımlarla yürüdü.",
             "strode boldly | Cesur adımlarla yürümek."),
            ("At the sight of the apparent monarch of beasts, cattle and sheep fled in wild panic.",
             "Görünüşteki hayvanlar hükümdarını gören sığırlar ve koyunlar çılgın bir panikle kaçıştılar.",
             "apparent monarch | Zahiri / görünürdeki kral; 'fled in panic' panikle kaçtı."),
            ("Even the fierce sheepdog ran whining to his master's cottage with his tail between his legs.",
             "Vahşi çoban köpeği bile kuyruğunu bacaklarının arasına kıstırarak inleye inleye efendisinin kulübesine kaçtı.",
             "tail between legs | Kuyruğu bacaklarının arasında."),
            ("Puffed up with boundless pride, the donkey believed himself an authentic terror to the world.",
             "Sınırsız bir gururla göğsü kabaran eşek, kendisini dünyaya dehşet salan hakiki bir canavar sandı.",
             "puffed up | Kibirle şişinmiş / böbürlenmiş."),
            ("He strutted through the village lanes, expecting all mankind to bow down in reverence.",
             "Bütün insanlığın hürmetle önünde eğilmesini bekleyerek köy sokaklarında çalım satarak yürüdü.",
             "strutted | Çalım satarak / kasılarak yürümek; 'reverence' hürmet."),
            ("Presently, he encountered a sly fox who stood calmly watching him from behind a stone wall.",
             "Az sonra, bir taş duvarın arkasından kendisini sakince izleyen kurnaz bir tilkiyle karşılaştı.",
             "encountered | Karşılaşmak; 'presently' az sonra."),
            ("Determined to frighten the fox as thoroughly as the others, the donkey attempted a mighty roar.",
             "Tilkiti de diğerleri kadar derinden korkutmaya kararlı olan eşek heybetli bir kükreme denemesi yaptı.",
             "mighty roar | Heybetli kükreme."),
            ("Alas, instead of a royal roar, an absurd, discordant bray burst from his gaping jaws.",
             "Heyhat, kraliyet kükremesi yerine, açık çenesinden saçma ve kulak tırmalayıcı bir anırma koptu.",
             "discordant bray | Ahenksiz / kulak tırmalayan anırma; 'gaping jaws' açık çene."),
            ("'Hee-haw! Hee-haw!' he shrieked, making the woodland echo with his unmistakable donkey voice.",
             "Ormanı o şaşmaz eşek sesiyle çınlatarak, 'Aiii-vaa! Aiii-vaa!' diye çığlık attı.",
             "unmistakable | Şüphe götürmez, apaçık."),
            ("At that moment, the long tips of his gray ears poked out through the lion's mane.",
             "Tam o anda, gri kulaklarının uzun uçları aslan yelesinin arasından dışarı fırlayıverdi.",
             "lion's mane | Aslan yelesi; 'poked out' dışarı fırlamak."),
            ("The fox burst into a fit of uncontrolled laughter, pointing his paw at the disguised beast.",
             "Tilki kılık değiştirmiş hayvana patisini doğrultarak katıla katıla kahkaha krizine girdi.",
             "fit of laughter | Kahkaha krizi / nöbeti."),
            ("'Ah, my friend,' chuckled the fox, 'you might have frightened me too, if you had kept your mouth shut.'",
             "Tilki kıkırdayarak, 'Ah dostum,' dedi, 'ağzını kapalı tutsaydın belki beni de korkutabilirdin.'",
             "kept mouth shut | Ağzını kapalı tutmak."),
            ("Hearing the commotion, the villager came running with a stout cudgel in his hand.",
             "Gürültüyü işiten köylü, elinde sağlam bir sopayla koşarak çıkageldi.",
             "stout cudgel | Kalın, sağlam sopa; 'commotion' kargaşa, gürültü."),
            ("He stripped off the lion's skin and administered a sound thrashing to the foolish imposter.",
             "Aslan postunu çekip çıkardı ve ahmak sahtekara sağlam bir dayak çekti.",
             "sound thrashing | Sağlam bir dayak / kötek; 'stripped off' soyup çıkardı."),
            ("Fine clothes may disguise a fool for a brief hour, but his speech will inevitably reveal his true nature.",
             "Süslü elbiseler bir ahmakı kısa bir süreliğine gizleyebilir; fakat konuşması kaçınılmaz olarak onun hakiki tabiatını ortaya koyacaktır.",
             "inevitably reveal | Kaçınılmaz şekilde ifşa etmek.")
        ],
        "vocab_focus": [
            ("shaggy hide", "kaba tüylü post"),
            ("terrifying aspect", "korkunç görünüm"),
            ("fled in panic", "panikle kaçtı"),
            ("puffed up", "şişinmiş, kibirle dolmuş"),
            ("strutted", "kasım kasım kasılarak yürüdü"),
            ("discordant", "uyumsuz, ahenksiz"),
            ("commotion", "kargaşa, velvele"),
            ("sound thrashing", "sağlam bir dayak")
        ]
    },

    # 7. The Stag and His Reflection
    {
        "page_no": 7,
        "title": "The Stag and His Reflection",
        "tr_title": "Geyik ve Boynuzları",
        "sentences": [
            ("A magnificent stag came to drink at a clear forest spring on a quiet summer morning.",
             "Muhteşem bir geyik, sakin bir yaz sabahında berrak bir orman pınarında su içmeye geldi.",
             "magnificent stag | Muhteşem geyik; 'spring' pınar, kaynak."),
            ("Having quenched his thirst, he paused beside the pool and gazed at his reflection in the glassy water.",
             "Susuzluğunu giderdikten sonra havuzun kenarında duraksadı ve cam gibi suda kendi aksini seyretti.",
             "glassy water | Cam gibi berrak su; 'quenched' giderdi."),
            ("He admired the grandeur of his branching antlers, which rose above his head like royal crowns.",
             "Başının üstünde kraliyet taçları gibi yükselen çatallı boynuzlarının azametine hayran kaldı.",
             "branching antlers | Dallı budaklı boynuzlar; 'grandeur' azamet."),
            ("He marvelled at their majestic spread, their elegant symmetry, and their towering grace.",
             "Onların heybetli yayılışına, zarif simetrisine ve göklere uzanan zarafetine hayretle baktı.",
             "majestic spread | Heybetli yayılış / açıklık."),
            ("However, when his eyes travelled downward to his legs, his heart sank with profound disappointment.",
             "Lakin gözleri aşağıya, bacaklarına doğru kaydığında yüreği derin bir hayal kırıklığıyla burkuldu.",
             "heart sank | Yüreği burkulmak / suya düşmek."),
            ("'What pitiful, spindly shanks!' he lamented bitterly, surveying his slender limbs.",
             "Narin bacaklarını süzerek acı acı, 'Ne kadar da acınası, çöp gibi bacaklar!' diye hayıflandı.",
             "spindly shanks | Çöp gibi / cılız bacaklar; 'lamented' hayıflandı."),
            ("'They are so thin and unsightly that they utterly spoil the dignity of my noble appearance.'",
             "'Öylesine zayıf ve çirkinler ki asil görünüşümün vakarını büsbütün bozuyorlar.'",
             "unsightly | Çirkin, göze hoş görünmeyen; 'dignity' vakar, asalet."),
            ("'Why could not nature have bestowed upon me sturdy limbs worthy of my magnificent crown?'",
             "'Tabiat bana neden o muhteşem tacıma layık sağlam bacaklar bahşetmedi sanki?'",
             "bestowed upon | Bahşetmek; 'worthy of' layık."),
            ("While he was thus bewailing his misfortune, the distant baying of hounds shattered the silence.",
             "O böyle talihsizliğine yanıp dövünürken, uzaktan gelen av köpeği havlamaları sessizliği paramparça etti.",
             "baying of hounds | Av köpeklerinin uluması / havlaması; 'bewailing' dövünmek."),
            ("A party of hunters had entered the grove, blowing sharp horns and releasing a pack of dogs.",
             "Bir grup avcı keskin borazanlar çalarak ve bir köpek sürüsünü salarak koruluğa girmişti.",
             "pack of dogs | Köpek sürüsü / takımı."),
            ("Filled with terror, the stag bounded away across the meadow with astonishing velocity.",
             "Dehşetle dolan geyik, şaşırtıcı bir hızla çayır boyunca sıçrayarak kaçtı.",
             "astonishing velocity | Şaşırtıcı sürat / hız."),
            ("His slender, despised legs carried him over the open plain like the swiftest wind.",
             "O hor gördüğü narin bacakları, onu en hızlı rüzgar gibi açık ova üzerinden taşıyıp götürdü.",
             "despised legs | Hor görülmüş / küçümsenmiş bacaklar."),
            ("He easily outdistanced the panting pursuers, leaving the barking pack far behind.",
             "Nefes nefese kalmış takipçilerini fersah fersah geride bırakarak kolayca arayı açtı.",
             "outdistanced | Geride bırakmak, arayı açmak; 'panting' nefes nefese."),
            ("As long as the race continued on the open ground, his safety was completely assured.",
             "Yarış açık arazide devam ettiği müddetçe onun emniyeti tamamen garanti altındaydı.",
             "assured | Garanti altında, kesin."),
            ("However, the path led into a dense thicket of tangled oak trees and interwoven briars.",
             "Fakat patika, birbirine girmiş meşe ağaçları ve sık dikenli çalılıklardan oluşan yoğun bir fundalığa girdi.",
             "dense thicket | Yoğun fundalık; 'briars' yaban gülü/dikenlik."),
            ("As he plunged headlong into the brushwood, his wide, branching antlers became hopelessly entangled.",
             "Çalı çırpının içine kafa üstü daldığı anda, geniş dallı budaklı boynuzları çaresizce dallara dolandı.",
             "hopelessly entangled | Çaresizce birbirine dolanmış / takılmış."),
            ("He struggled desperately to free his head, but every frantic tug bound him tighter to the boughs.",
             "Başını kurtarmak için can havliyle çabaladı; fakat her çılgınca asılış onu dallara daha da sıkı bağladı.",
             "frantic tug | Çılgınca asılış / çekiş."),
            ("In moments, the howling hounds caught up with their captive prey, surrounding him on every side.",
             "Birkaç saniye içinde uluyan av köpekleri tutsak avlarına yetiştiler ve dört bir yanını sardılar.",
             "caught up with | Yetişmek, yakalamak."),
            ("As the cruel hunters drew near with their spears, the dying stag groaned with his final breath.",
             "Zalim avcılar mızraklarıyla yaklaşırken, can çekişen geyik son nefesiyle inledi.",
             "dying stag groaned | Can çekişen geyik inledi; 'spears' mızraklar."),
            ("We often despise the humble things that save us, while prizing the ornaments that lead to our ruin.",
             "Bizi kurtaran mütevazı şeyleri sıklıkla hor görürüz; oysa felaketimize yol açan süslere paha biçeriz.",
             "prizing ornaments | Süsleri değerli saymak / baş tacı etmek.")
        ],
        "vocab_focus": [
            ("branching antlers", "dallı budaklı boynuzlar"),
            ("spindly shanks", "çöp gibi cılız bacaklar"),
            ("bewailing", "ağlayıp dövünmek"),
            ("velocity", "sürat, hız"),
            ("outdistanced", "geride bıraktı, arayı açtı"),
            ("dense thicket", "sık fundalık/çalık"),
            ("entangled", "dolanmış, takılmış"),
            ("prizing", "yüksek değer vermek")
        ]
    },

    # 8. The Frog and the Ox
    {
        "page_no": 8,
        "title": "The Frog and the Ox",
        "tr_title": "Öküz ile Kurbağa",
        "sentences": [
            ("In a lush, damp meadow beside a tranquil pond lived a family of green frogs.",
             "Sakin bir göletin kenarındaki yemyeşil, nemli bir çayırda bir yeşil kurbağa ailesi yaşardı.",
             "lush meadow | Yemyeşil, verimli çayır; 'tranquil pond' sakin gölet."),
            ("An enormous ox came lumbering down to the water to graze upon the tender clover.",
             "Kocaman bir öküz, taze yoncayı otlamak için ağır adımlarla suya doğru indi.",
             "lumbering | Ağır ve hantal adımlarla yürümek; 'clover' yonca."),
            ("A tiny young frog had never seen such a colossal beast in all his brief life.",
             "Minik bir yavru kurbağa, kısa ömründe böylesine devasa bir mahluku hiç görmemişti.",
             "brief life | Kısa ömür; 'colossal beast' devasa canavar."),
            ("Terrified by the creature's immense bulk, the youngster hopped frantically to his mother's lily pad.",
             "Yaratığın muazzam cüssesinden ödü kopan yavru, telaşla annesinin nilüfer yaprağına sıçradı.",
             "immense bulk | Muazzam cüsse / gövde; 'lily pad' nilüfer yaprağı."),
            ("'O Mother!' he gasped, panting with excitement, 'I have just beheld the most monstrous mountain of flesh!'",
             "Heyecandan soluk soluğa kalarak, 'Ah anne!' diye soludu, 'az önce etten oluşmuş en korkunç dağı gördüm!'",
             "mountain of flesh | Etten dağ; 'beheld' gördü."),
            ("'He has four sturdy legs, a tail like a rope, and two sharp horns upon his broad head.'",
             "'Dört sağlam bacağı, ip gibi bir kuyruğu ve geniş başında iki sivri boynuzu var.'",
             "sturdy legs | Sağlam bacaklar."),
            ("The old mother frog puffed herself up with professional pride, for she considered herself important.",
             "Yaşlı anne kurbağa kendini mühim gördüğü için mesleki bir gururla göğsünü şişirdi.",
             "puffed herself up | Kendini şişirmek / kabarmak."),
            ("'Was this monster larger than I am?' she inquired, drawing in a substantial gulp of air.",
             "İçine koca bir yudum hava çekerek, 'Bu canavar benden daha mı büyüktü?' diye sordu.",
             "substantial gulp | Dolgun / büyük yudum."),
            ("'Oh, much bigger, Mother! Vastly bigger!' cried the little frog, waving his webbed feet.",
             "Küçük kurbağa perdeli ayaklarını sallayarak, 'Ah, çok daha büyüktü anne! Katbekat büyüktü!' diye haykırdı.",
             "vastly bigger | Katbekat daha büyük."),
            ("Annoyed that any creature should surpass her grandeur, the mother inhaled deeply and swelled her body.",
             "Herhangi bir yaratığın kendi heybetini aşmasından rahatsız olan anne, derin bir nefes alıp bedenini şişirdi.",
             "swelled her body | Bedenini şişirdi; 'grandeur' heybet."),
            ("'Was he as big as this?' she asked, standing on tiptoe with her rubbery skin stretched tight.",
             "Lastik gibi derisi gerilerek parmak ucunda durup, 'Şunun kadar büyük müydü?' diye sordu.",
             "stretched tight | Sımsıkı gerilmiş; 'on tiptoe' parmak ucunda."),
            ("'Much bigger, Mother!' repeated the youth, 'you cannot conceive how truly huge he was.'",
             "Yavru, 'Çok daha büyüktü anne!' diye tekrarladı, 'onun ne kadar hakikaten devasa olduğunu tahayyül bile edemezsin.'",
             "cannot conceive | Tahayyül bile edememek."),
            ("Determined not to be outdone by an alien monster, the ambitious frog drew in more air.",
             "Yabancı bir canavar tarafından gölgede bırakılmamaya kararlı olan hırslı kurbağa daha fazla hava çekti.",
             "not to be outdone | Altta kalmamak / yenik düşmemek."),
            ("She strained and puffed until her mottled green sides looked like an inflated leather ball.",
             "Alacalı yeşil böğrü şişirilmiş bir meşin topa benzeyene dek zorlandı ve şiştikçe şişti.",
             "mottled green | Alacalı yeşil; 'inflated' şişirilmiş."),
            ("'Now look at me!' she croaked hoarsely, 'surely he was not grander than this?'",
             "Boğuk bir sesle vıraklayarak, 'Şimdi bana bak!' dedi, 'herhalde bundan daha heybetli değildi ya?'",
             "croaked hoarsely | Boğuk boğuk vıraklamak."),
            ("'If you were to swell until you burst, Mother,' said the son, 'you could not match his hoof.'",
             "Oğlu, 'Patlayana kadar şişsen bile anne,' dedi, 'onun tırnağına bile yetişemezsin.'",
             "match his hoof | Tırnağına bile yetişememek / denk olamamak."),
            ("Furious at this disparagement, the stubborn amphibian resolved to make one final, supreme effort.",
             "Bu küçümsemeye öfkelenen inatçı ikiyaşamlı, son ve yüce bir gayret göstermeye karar verdi.",
             "disparagement | Küçümseme, hafife alma; 'amphibian' ikiyaşamlı (kurbağa)."),
            ("She closed her eyes, clamped her mouth shut, and breathed in with frantic, desperate ambition.",
             "Gözlerini yumdu, ağzını sımsıkı kapadı ve çılgınca, çaresiz bir hırsla nefesini içine çekti.",
             "clamped mouth shut | Ağzını sımsıkı kapamak."),
            ("Pop! With a sudden, explosive snap, her fragile skin ruptured and she perished on the spot.",
             "Çaat! Ani ve patlayıcı bir sesle narin derisi yırtıldı ve oracıkta can verdi.",
             "ruptured | Yırtıldı, patladı; 'perished' can verdi, yok oldu."),
            ("Attempting to emulate those endowed with vastly superior stature inevitably invites complete self-destruction.",
             "Kendinden fersah fersah üstün bir cüsseye sahip olanlara özenmeye kalkışmak, kaçınılmaz olarak tam bir yıkıma davetiye çıkarır.",
             "emulate | Özenmek, taklit etmeye çalışmak; 'self-destruction' kendi kendini yok etme.")
        ],
        "vocab_focus": [
            ("lumbering", "ağır ve hantal yürüyüş"),
            ("puffed up", "şişindi, kabardı"),
            ("substantial gulp", "büyük bir nefes/yudum"),
            ("stretched tight", "sımsıkı gerilmiş"),
            ("inflated", "şişirilmiş, hava basılmış"),
            ("disparagement", "küçümseme, yerme"),
            ("ruptured", "patladı, yırtıldı"),
            ("emulate", "özenmek, taklit etmeye çabalamak")
        ]
    }
]

fables_9_to_15 = [
    # 9. The Lion in Love
    {
        "page_no": 9,
        "title": "The Lion in Love",
        "tr_title": "Aşık Olan Aslan",
        "sentences": [
            ("A fearsome lion, terror of the savanna, fell deeply in love with a beautiful woodcutter's daughter.",
             "Savanın dehşeti olan korkutucu bir aslan, güzel bir oduncunun kızına sırılsıklam aşık oldu.",
             "fearsome | Korkutucu, dehşet verici; 'savanna' savan, bozkır."),
            ("He abandoned his wild hunting habits and spent his days languishing near the forester's cottage.",
             "Vahşi avcılık alışkanlıklarını terk etti ve günlerini ormancının kulübesinin yakınında eriyip biterek geçirdi.",
             "languishing | Eriyip bitmek, aşk acısıyla süzülmek."),
            ("Unable to endure the pangs of passion any longer, he strode boldly to the woodman's door.",
             "Tutkunun ızdıraplarına daha fazla dayanamayarak oduncunun kapısına cesur adımlarla gitti.",
             "pangs of passion | Tutkunun sancıları / ızdırapları."),
            ("He demanded the fair maiden's hand in marriage, promising eternal peace between man and beast.",
             "İnsan ile hayvan arasında ebedi bir barış vadederek güzel bakirenin evlilik için elini istedi.",
             "fair maiden | Güzel genç kız / bakire; 'eternal peace' ebedi barış."),
            ("The woodcutter was petrified with terror at the preposterous proposition.",
             "Oduncu bu akıl almaz teklif karşısında dehşetten kaskatı kesildi.",
             "petrified with terror | Dehşetten taş kesilmek; 'proposition' teklif."),
            ("He shuddered at the terrible thought of giving his beloved daughter to so ferocious a carnivore.",
             "Sevgili kızını böylesine yırtıcı bir etobura verme düşüncesiyle tir tir titredi.",
             "ferocious carnivore | Vahşi etobur hayvan."),
            ("Yet he dared not utter a blunt refusal, lest the enraged monarch tear him limb from limb.",
             "Yine de öfkelenen hükümdarın kendisini parça pinçik etmesinden korkarak dobra bir ret cevabı vermeye cesaret edemedi.",
             "blunt refusal | Kestirip atılan / dobra ret cevabı."),
            ("After consulting his clever wits, the shrewd father devised an ingenious stratagem.",
             "Kıvrak zekasına danıştıktan sonra, kurnaz baba dahiyane bir harp hilesi tasarladı.",
             "shrewd | Kurnaz, açıkgöz; 'stratagem' taktik, harp hilesi."),
            ("'We are deeply honoured by your majestic proposal, O King of the forest,' said the woodman politely.",
             "Oduncu nezaketle, 'Ey ormanın Kralı, asil evlilik teklifinizle derin bir şeref duyduk,' dedi.",
             "majestic proposal | Asil / muhteşem evlilik teklifi."),
            ("'However, my tender daughter is of a singularly timid and delicate disposition.'",
             "'Fakat benim narin kızım eşsiz derecede ürkek ve hassas bir yaradılışa sahiptir.'",
             "delicate disposition | Narin, hassas mizaç."),
            ("'She is terrified of your formidable claws and trembles whenever she glimpses your razor-sharp fangs.'",
             "'Korkunç pençelerinizden ödü kopuyor ve o jilet gibi keskin sivri dişlerinizi her gördüğünde tir tir titriyor.'",
             "razor-sharp fangs | Jilet gibi keskin sivri dişler."),
            ("'If you genuinely desire her hand, you must consent to have your claws trimmed and teeth extracted.'",
             "'Eğer hakikaten onun elini istiyorsanız, pençelerinizi kestirmeye ve dişlerinizi çektirmeye rıza göstermelisiniz.'",
             "consent to | Bir şeye rıza göstermek / razı olmak."),
            ("The besotted lion was so blind with love that he readily consented to the bizarre sacrifice.",
             "Aşktan gözü dönen sevdalı aslan, bu tuhaf fedakarlığa dünden razı oldu.",
             "besotted | Aşktan gözü dönmüş, aklı başından gitmiş."),
            ("He permitted the woodman to shear off his deadly claws right down to the quick.",
             "Oduncunun o ölümcül pençelerini ta köküne kadar kesip atmasına izin verdi.",
             "shear off | Kırkıp kesmek; 'down to the quick' can damarına / köküne kadar."),
            ("Next, he patiently allowed every single formidable tooth to be drawn from his jaws.",
             "Ardından her bir heybetli dişin çenesinden teker teker sökülmesine sabırla müsaade etti.",
             "drawn from jaws | Çeneden sökülüp çekilmek."),
            ("Disarmed and defenseless, the toothless monarch returned to the cottage to claim his promised bride.",
             "Silahsız ve savunmasız kalan dişsiz hükümdar, vadolunan gelinini istemek için kulübeye geri döndü.",
             "disarmed and defenseless | Silahsız ve savunmasız."),
            ("Seeing that the terrifying beast could no longer bite or scratch, the woodman laughed mockingly.",
             "Korkutucu canavarın artık ne ısırabildiğini ne de tırmalayabildiğini gören oduncu alaycı bir kahkaha attı.",
             "laughed mockingly | Alaycı kahkaha atmak."),
            ("He seized a heavy hickory club from behind the door and beat the helpless beast unmercifully.",
             "Kapının arkasından ağır bir ceviz sopası kaptı ve çaresiz canavara acımasızca dayak attı.",
             "hickory club | Sert ceviz sopası; 'unmercifully' merhametsizce."),
            ("The battered lion was driven out into the wilderness, mourning his folly and stripped of his crown.",
             "Dayağı yiyen aslan ahmaklığına yanarak ve tacından soyulmuş halde yaban ellere sürüldü.",
             "battered lion | Hırpalanmış, dayak yemiş aslan."),
            ("He who surrenders his natural defenses out of infatuation quickly falls helpless before his adversaries.",
             "Aşkın kör tutkusu uğruna doğal savunmalarını teslim eden kişi, hasımları karşısında kısa sürede çaresiz kalır.",
             "infatuation | Kör kütük tutku, kara sevda; 'adversaries' hasımlar.")
        ],
        "vocab_focus": [
            ("fearsome", "korkunç, dehşetli"),
            ("languishing", "aşk acısıyla eriyip biten"),
            ("petrified", "taş kesilmiş, donakalmış"),
            ("stratagem", "harp hilesi, ustaca taktik"),
            ("disposition", "mizaç, yaradılış"),
            ("besotted", "aşktan aklı başından gitmiş"),
            ("shear off", "kesip kırkmak"),
            ("infatuation", "kör kütük tutku, meftunluk")
        ]
    },

    # 10. The Two Pots
    {
        "page_no": 10,
        "title": "The Two Pots",
        "tr_title": "İki Çömlek",
        "sentences": [
            ("Two domestic pots were left standing side by side upon the bank of a swollen river.",
             "Taşmış bir nehrin kıyısında iki ev çömleği yan yana bırakılmış vaziyette duruyordu.",
             "domestic pots | Ev çömlekleri / kapları; 'swollen river' taşmış nehir."),
            ("One was fashioned from sturdy, glittering brass, while the other was molded from common, brittle earthenware.",
             "Biri sağlam, pırıl pırıl pirinçten yapılmıştı; diğeri ise sıradan, kırılgan kilden yoğrulmuştu.",
             "brittle earthenware | Kırılgan kilden çömlek; 'brass' pirinç/tunç metal."),
            ("A sudden flash flood tore through the valley, sweeping both vessels out into the raging torrent.",
             "Vadiden kopan ani bir sel her iki kabı da coşkun akıntının içine sürükledi.",
             "flash flood | Ani sel baskını; 'raging torrent' coşkun akıntı."),
            ("They bobbed helplessly together upon the swirling eddies, carried swiftly toward the sea.",
             "Girdaplanan burgaçların üzerinde çaresizce birlikte dalgalandılar ve hızla denize doğru sürüklendiler.",
             "swirling eddies | Girdaplanan su burgaçları; 'bobbed' su üstünde batıp çıkmak."),
            ("Seeing his companion trembling in the foam, the Brass Pot called out with hearty cordiality.",
             "Yoldaşının köpüklerin içinde titrediğini gören Pirinç Çömlek candan bir samimiyetle seslendi.",
             "hearty cordiality | Candan samimiyet / dostluk."),
            ("'Keep close to my side, friend Clay,' he shouted above the roar of the foaming waters.",
             "Köpüklü suların kükremesi üzerinden, 'Benim yanıma yakın dur dostum Kil!' diye bağırdı.",
             "keep close | Yakın durmak / ayrılmamak."),
            ("'I am massive and durable; I shall gladly shield you against the collision of submerged boulders.'",
             "'Ben heybetli ve dayanıklıyım; seni su altındaki kayaların çarpışmasına karşı seve seve korurum.'",
             "durable | Dayanıklı; 'shield' kalkan olmak, korumak."),
            ("The fragile Earthen Pot steered himself away as vigorously as the currents permitted.",
             "Kırılgan Toprak Çömlek, akıntıların elverdiği ölçüde tüm gücüyle kendini ondan uzaklaştırdı.",
             "fragile | Kırılgan, narin; 'steered away' uzaklaşmak."),
            ("'I am infinitely grateful for your generous offer,' replied the pot of clay in alarm.",
             "Kil çömlek telaş içinde, 'Cömert teklifiniz için sonsuz derecede minnettarım,' diye yanıt verdi.",
             "in alarm | Telaş / panik içinde."),
            ("'However, that very proximity which you propose is the single greatest peril I face.'",
             "'Fakat teklif ettiğiniz o yakınlığın ta kendisi, karşı karşıya olduğum en büyük tek tehlikedir.'",
             "proximity | Yakınlık; 'greatest peril' en büyük tehlike."),
            ("'Whether I strike against you, or you crash against me, the catastrophe will be entirely mine.'",
             "'İster ben size çarpayım ister siz bana çarpın; felaket tamamen benim başıma gelecektir.'",
             "catastrophe | Felaket, yıkım; 'crash against' çarpmak."),
            ("'Your metallic toughness will emerge without a scratch, while my fragile clay will shatter into dust.'",
             "'Sizin madeni sertliğiniz tek bir çizik bile almadan çıkacak; oysa benim narin kili un ufak olacaktır.'",
             "shatter into dust | Toz duman olup parçalanmak."),
            ("So saying, the sensible earthen vessel kept his distance, paddling with cautious agility.",
             "Böyle söyleyen aklı başında toprak kap, ihtiyatlı bir çeviklikle mesafe koyup uzak durdu.",
             "kept his distance | Mesafesini korumak; 'cautious' tedbirli."),
            ("He gently navigated around floating logs and rocks, yielding patiently to the river's whims.",
             "Yüzen kütüklerin ve kayaların etrafından usulca manevra yaptı ve nehrin kaprislerine sabırla boyun eğdi.",
             "navigated around | Etrafından manevra yapmak; 'whims' kaprisler."),
            ("The Brass Pot, proud of his unyielding strength, drifted recklessly down the center of the rapids.",
             "Eğilmez gücüyle gururlanan Pirinç Çömlek ise azgın suların tam ortasından pervasızca sürüklendi.",
             "rapids | Azgın çağlayanlar / akıntılar; 'recklessly' pervasızca."),
            ("Whenever a rocky outcrop appeared, he charged into it headlong, relying upon his tough metal.",
             "Ne zaman kayalık bir çıkıntı belirse sert metaline güvenerek dosdoğru üzerine daldı.",
             "rocky outcrop | Kayalık çıkıntı."),
            ("The fragile pot of clay eventually drifted into a gentle inlet and grounded safely upon the sand.",
             "Kırılgan kilden çömlek nihayetinde sakin bir koya sürüklendi ve kumsalın üzerine güvenle oturdu.",
             "gentle inlet | Sakin koy / haliç; 'grounded' karaya oturdu."),
            ("He survived the flood completely intact because he had prudently recognized his own vulnerability.",
             "Kendi incinebilirliğini basiretle tanıdığı için selden tek parça halinde, sapasağlam kurtuldu.",
             "prudently | Basiretle, sağduyuyla; 'vulnerability' kırılganlık, incinebilirlik."),
            ("The unequal fellowship between the strong and the weak always exposes the weaker to fatal peril.",
             "Güçlü ile zayıf arasındaki eşit olmayan dostluk, daima zayıf olanı ölümcül bir tehlikeye maruz bırakır.",
             "unequal fellowship | Eşit olmayan dostluk / yoldaşlık."),
            ("Choose companions of your own condition, for intimate association with the mighty is fraught with danger.",
             "Kendi denginiz olan arkadaşlar seçin; zira kudretlilerle aşırı samimiyet tehlikelerle doludur.",
             "fraught with danger | Tehlikelerle dolu.")
        ],
        "vocab_focus": [
            ("brittle", "kırılgan, gevrek"),
            ("raging torrent", "coşkun azgın akıntı"),
            ("hearty cordiality", "içten samimiyet"),
            ("proximity", "yakınlık"),
            ("catastrophe", "büyük felaket, yıkım"),
            ("cautious agility", "tedbirli çeviklik"),
            ("vulnerability", "kırılganlık, zafiyet"),
            ("fraught with danger", "tehlikelerle dolu")
        ]
    },

    # 11. The Bear and the Two Travellers
    {
        "page_no": 11,
        "title": "The Bear and Two Travellers",
        "tr_title": "Ayı ile İki Yolcu",
        "sentences": [
            ("Two close companions were journeying together through a dense and dangerous forest.",
             "İki yakın yoldaş, sık ve tehlikeli bir ormanın içinden birlikte yolculuk ediyorlardı.",
             "close companions | Yakın yoldaşlar / dostlar."),
            ("Before entering the wild woodland, they swore a solemn oath of mutual fidelity.",
             "Yabani koruluğa girmeden evvel karşılıklı sadakat üzerine kutsal bir yemin ettiler.",
             "solemn oath | Kutsal / ağır yemin; 'mutual fidelity' karşılıklı sadakat."),
            ("They pledged that whatever peril might befall them, they would stand side by side to the end.",
             "Başlarına ne tür bir tehlike gelirse gelsin sonuna kadar omuz omuza duracaklarına söz verdiler.",
             "pledged | Söz vermek, taahhüt etmek; 'stand side by side' omuz omuza durmak."),
            ("They had scarcely traversed half a mile when a colossal grizzly bear crashed through the brushwood.",
             "Henüz yarım mil bile gitmemişlerdi ki devasa bir bozayı çalı çırpıyı kırarak karşılarına fırladı.",
             "grizzly bear | Bozayı; 'brushwood' çalı çırpı."),
            ("The monster stood on its hind legs, growling with terrifying fury and baring its yellow teeth.",
             "Canavar arka ayakları üzerine dikildi; korkunç bir öfkeyle hırlayıp sarı dişlerini gösterdi.",
             "hind legs | Arka ayaklar; 'terrifying fury' dehşet verici öfke."),
            ("One of the travellers, who was remarkably nimble, forgot his solemn vow in an instant.",
             "Oldukça çevik olan yolculardan biri, o kutsal yeminini bir göz açıp kapayıncaya dek unutuverdi.",
             "nimble | Çevik, atik; 'solemn vow' kutsal yemin."),
            ("He dropped his bundle and scrambled up into the high branches of a convenient beech tree.",
             "Çıkınını yere attı ve elverişli bir kayın ağacının yüksek dallarına tırmanıverdi.",
             "scrambled up | Hızla tırmanmak; 'convenient' elverişli."),
            ("He concealed himself amidst the thick foliage, without bestowing a single thought on his friend.",
             "Arkadaşına tek bir düşünce bile ayırmaksızın sık yaprakların arasına gizlendi.",
             "thick foliage | Sık yaprak örtüsü; 'without bestowing a thought' zerre kadar düşünmeden."),
            ("The other man, finding himself abandoned and unable to climb, was paralyzed with fear.",
             "Terk edildiğini gören ve tırmanmaktan aciz olan diğer adam ise korkudan felç olmuş gibiydi.",
             "paralyzed with fear | Korkudan donakalmış / felç olmuş."),
            ("Realizing that he had no chance against the beast in single combat, he relied upon his wits.",
             "Teke tek dövüşte canavara karşı hiçbir şansı olmadığını anlayan adam pratik zekasına başvurdu.",
             "single combat | Teke tek dövüş."),
            ("He remembered having heard that a bear will never touch or molest a lifeless corpse.",
             "Bir ayının cansız bir cesede asla dokunmadığını ve saldırmadığını duyduğunu hatırladı.",
             "lifeless corpse | Cansız ceset; 'molest' rahatsız etmek, saldırmak."),
            ("He threw himself flat upon his face in the dust, holding his breath with supreme resolution.",
             "Üstün bir kararlılıkla nefesini tutarak yüzüstü tozların içine boylu boyunca uzandı.",
             "flat upon his face | Yüzüstü boylu boyunca; 'holding breath' nefes tutmak."),
            ("He closed his eyes and made his limbs as rigid and cold as if life had completely fled.",
             "Gözlerini yumdu ve kollarını bacaklarını sanki canı büsbütün çekilmiş gibi kaskatı ve soğuk kıldı.",
             "rigid and cold | Kaskatı ve soğuk."),
            ("The huge bear lumbered up to the prostrate figure, sniffing curious snorts around his head.",
             "Koca ayı yüzüstü yatan bedene doğru ağır adımlarla geldi ve meraklı homurtularla kafasının etrafını kokladı.",
             "prostrate figure | Yüzüstü yatan beden; 'sniffing snorts' koklamak."),
            ("The beast nudged the man's neck with its wet, cold muzzle and smelled his motionless lips.",
             "Canavar ıslak, soğuk burnuyla adamın boynunu dürttü ve hareketsiz dudaklarını kokladı.",
             "nudged | Hafifçe dürtmek; 'motionless' hareketsiz."),
            ("The man did not flinch or shudder, maintaining his deathly stillness despite his terror.",
             "Adam dehşetine rağmen ölümcül sessizliğini koruyarak ne irkildi ne de titredi.",
             "did not flinch | Zerrece irkilmedi / geri çekilmedi."),
            ("Mistaking him for a dead carcass, the bear turned away and ambled slowly into the forest.",
             "Onu ölü bir leş zanneden ayı arkasını döndü ve aheste adımlarla ormanın içine doğru uzaklaştı.",
             "carcass | Leş, ceset; 'ambled' aheste yürümek."),
            ("When the beast was safely out of sight, the selfish comrade slid down from the branches.",
             "Canavar tamamen gözden kaybolduğunda, bencil yoldaş dallardan aşağı süzülüverdi.",
             "selfish comrade | Bencil yoldaş; 'slid down' aşağı kaymak."),
            ("He approached with a nervous chuckle, asking playfully what the bear had whispered in his ear.",
             "Ayının onun kulağına ne fısıldadığını şakayla sorarak sinirli bir kıkırdamayla yaklaştı.",
             "nervous chuckle | Sinirli kıkırdama; 'whispered' fısıldadı."),
            ("'He gave me very sound counsel,' replied the friend; 'never travel with a comrade who deserts you in peril.'",
             "Arkadaşı, 'Bana çok sağlam bir öğüt verdi,' dedi; 'tehlike anında seni terk eden bir yoldaşla asla yola çıkma.'",
             "sound counsel | Sağlam öğüt; 'deserts you' seni terk eden.")
        ],
        "vocab_focus": [
            ("mutual fidelity", "karşılıklı sadakat"),
            ("scrambled up", "hızla tırmandı"),
            ("foliage", "yaprak örtüsü"),
            ("lifeless corpse", "cansız ceset"),
            ("prostrate", "yüzüstü yere uzanmış"),
            ("flinch", "irkilmek, geri çekilmek"),
            ("carcass", "leş, hayvan ölüsü"),
            ("sound counsel", "sağlam/akıllıca öğüt")
        ]
    },

    # 12. The Fox and the Mask
    {
        "page_no": 12,
        "title": "The Fox and the Mask",
        "tr_title": "Tilki ile Tiyatro Maskesi",
        "sentences": [
            ("A curious fox had slipped into the workshop of a celebrated theatrical sculptor in the city.",
             "Meraklı bir tilki, şehirde meşhur bir tiyatro heykeltıraşının atölyesine gizlice süzüldü.",
             "theatrical sculptor | Tiyatro heykeltıraşı; 'curious' meraklı."),
            ("The craftsman had departed for the noon repast, leaving his tools and creations unguarded.",
             "Usta, aletlerini ve eserlerini sahipsiz bırakarak öğle yemeği için atölyeden ayrılmıştı.",
             "repast | Yemek, ziyafet; 'unguarded' sahipsiz, korunmasız."),
            ("The sly beast explored every corner of the studio, sniffing curiously at chisels, paints, and marble.",
             "Kurnaz hayvan stüdyonun her köşesini keşfetti; keskileri, boyaları ve mermerleri merakla kokladı.",
             "chisels | Keskiler, oyma aletleri; 'explored' keşfetti."),
            ("Suddenly, he caught sight of an extraordinary object resting upon a polished wooden pedestal.",
             "Ansızın cilalı ahşap bir kaidenin üzerinde duran fevkalade bir nesneye gözü ilişti.",
             "pedestal | Kaide, ayaklık; 'caught sight of' gözü ilişmek."),
            ("It was an exquisite tragic mask, carved from the finest alabaster to represent an ancient hero.",
             "Kadim bir kahramanı temsil etmek üzere en seçkin kaymaktaşından oyulmuş enfes bir trajedi maskesiydi bu.",
             "alabaster | Kaymaktaşı, ak mermer; 'exquisite' enfes, nadide."),
            ("The facial features were sculpted with unparalleled artistry and classical perfection.",
             "Yüz hatları emsalsiz bir sanatçılık ve klasik mükemmellikle yontulmuştu.",
             "unparalleled artistry | Emsalsiz sanatçılık; 'sculpted' yontulmuş."),
            ("The high, noble forehead suggested profound wisdom and intellectual grandeur.",
             "Yüksek ve asil alın, derin bir bilgeliği ve entelektüel heybeti çağrıştırıyordu.",
             "intellectual grandeur | Entelektüel heybet; 'suggested' çağrıştırdı."),
            ("The deep-set, expressive eyes seemed ready to flash with righteous passion or mournful tears.",
             "Çukura kaçmış, manalı gözler haklı bir tutkuyla veya kederli gözyaşlarıyla parıldamaya hazır görünüyordu.",
             "mournful tears | Kederli gözyaşları; 'deep-set' çukura kaçmış."),
            ("The beautifully contoured lips appeared poised on the verge of uttering sublime poetry.",
             "Güzelce şekillendirilmiş dudaklar, ulvi bir şiiri dile getirme eşiğinde gibi duruyordu.",
             "sublime poetry | Ulvi şiir; 'poised on the verge' eşiğinde durmak."),
            ("The fox approached cautiously, wondering whether he stood before a sleeping god or an imperial prince.",
             "Tilki uyuyan bir tanrının mı yoksa bir imparatorluk prensinin mi önünde durduğunu merak ederek temkinle yaklaştı.",
             "cautiously | Temkinle, ihtiyatla; 'imperial' imparatorluk."),
            ("He stretched out his velvet paw and nudged the still visage with hesitant curiosity.",
             "Kadife patisini uzattı ve tereddütlü bir merakla hareketsiz yüze hafifçe dokundu.",
             "visage | Çehre, yüz; 'hesitant curiosity' tereddütlü merak."),
            ("The object tipped over slightly, proving remarkably light and hollow to his touch.",
             "Nesne hafifçe yana yattı ve dokunuşuna karşı son derece hafif ve içinin boş olduğunu gösterdi.",
             "tipped over | Yana yatmak; 'hollow' içi boş."),
            ("The fox turned it over with his claws and inspected the cavernous reverse side.",
             "Tilki pençeleriyle onu ters yüz etti ve mağarayı andıran kovuk arka tarafını inceledi.",
             "cavernous reverse side | Mağara gibi kovuk arka yüz."),
            ("To his utter astonishment, there was nothing inside but empty space and smooth plaster.",
             "Büyük bir şaşkınlıkla gördü ki içinde boşluk ve düz alçıdan başka hiçbir şey yoktu.",
             "smooth plaster | Düz alçı; 'utter astonishment' tam bir şaşkınlık."),
            ("There was no warm flesh, no beating heart, and not a single particle of gray brain matter.",
             "Ne sıcak bir et ne atan bir kalp ne de tek bir zerre gri beyin maddesi vardı.",
             "brain matter | Beyin dokusu / maddesi."),
            ("The fox stepped back, tilted his head, and chuckled with philosophical contempt.",
             "Tilki bir adım geri çekildi, başını yana eğdi ve felsefi bir küçümsemeyle kıkırdadı.",
             "philosophical contempt | Felsefi küçümseme."),
            ("'What a magnificent, majestic head!' remarked the cunning fox with a deep sigh.",
             "Kurnaz tilki derin bir iç çekişle, 'Ne kadar muhteşem, ne kadar heybetli bir kafa!' dedi.",
             "majestic head | Heybetli kafa."),
            ("'And yet how profoundly tragic it is that it has not a single grain of brains inside!'",
             "'Ve yine de içinde tek bir zerre bile beyin olmaması ne kadar da derin bir trajedi!'",
             "grain of brains | Bir zerre beyin."),
            ("He turned his back upon the hollow marvel and trotted out into the sunny courtyard.",
             "İçi boş harikaya sırtını döndü ve güneşli avluya doğru tırıs adımlarla çıktı gitti.",
             "hollow marvel | İçi boş harika."),
            ("A handsome exterior is utterly worthless when it conceals an empty, shallow mind.",
             "İçi boş ve sığ bir zihni gizlediğinde, göz alıcı bir dış görünüş büsbütün değersizdir.",
             "handsome exterior | Yakışıklı / göz alıcı dış görünüş; 'shallow mind' sığ zihin.")
        ],
        "vocab_focus": [
            ("sculptor", "heykeltıraş"),
            ("repast", "öğün, yemek"),
            ("pedestal", "kaide, heykel ayağı"),
            ("alabaster", "kaymaktaşı, ak mermer"),
            ("visage", "çehre, yüz"),
            ("hollow", "kovuk, içi boş"),
            ("contempt", "küçümseme, hor görme"),
            ("shallow", "sığ, yüzeysel")
        ]
    },

    # 13. The Peacock and the Crane
    {
        "page_no": 13,
        "title": "The Peacock and the Crane",
        "tr_title": "Tavus Kuşu ile Turna",
        "sentences": [
            ("A conceited peacock was strutting proudly across a royal lawn, fanning his glorious tail feathers.",
             "Kibirli bir tavus kuşu şanlı kuyruk tüylerini yelpaze gibi açarak kraliyet çimenliğinde gururla çalım satıyordu.",
             "conceited | Kibirli, kendini beğenmiş; 'fanning' yelpaze gibi açmak."),
            ("His iridescent plumage shimmered in the sunlight with rich emerald greens and deep sapphire blues.",
             "Yanardöner tüyleri zengin zümrüt yeşilleri ve derin safir mavileriyle güneş ışığında parıldıyordu.",
             "iridescent plumage | Yanardöner tüyler; 'sapphire' safir."),
            ("Every feather was adorned with a magnificent velvety eye that sparkled like a celestial jewel.",
             "Her bir tüy, göksel bir mücevher gibi parıldayan kadifemsi muhteşem bir göz deseniyle süslenmişti.",
             "celestial jewel | Göksel mücevher; 'velvety eye' kadife göz motifi."),
            ("Presently, a graceful crane alighted quietly upon the grass near the palace fountain.",
             "Az sonra zarif bir turna saray fıskiyesinin yanındaki çimenliğe sessizce kondu.",
             "alighted quietly | Sessizce konmak; 'fountain' fıskiye."),
            ("The crane's plumage was uniformly composed of sober, ash-colored gray feathers.",
             "Turnanın tüyleri baştan aşağı sade, kül rengi gri tüylerden oluşuyordu.",
             "sober | Ağırbaşlı, sade; 'ash-colored' kül rengi."),
            ("The peacock regarded the newcomer with undisguised contempt and arrogant pity.",
             "Tavus kuşu bu yeni gelene gizlenemez bir küçümseme ve kibirli bir acımayla baktı.",
             "undisguised contempt | Gizlenemez / apaçık küçümseme."),
            ("He spread his enormous multicolored train to its utmost width, casting a shadow over the lawn.",
             "Çimenliğin üzerine bir gölge düşürerek o devasa çok renkli kuyruğunu son genişliğine kadar açtı.",
             "multicolored train | Çok renkli kuyruk sırması; 'utmost width' azami genişlik."),
            ("'Look at my royal purple and dazzling gold!' cried the peacock in an insulting tone.",
             "Tavus kuşu aşağılayıcı bir ses tonuyla, 'Şu kraliyet erguvanıma ve göz kamaştırıcı altınıma bakın!' diye haykırdı.",
             "insulting tone | Aşağılayıcı ses tonu."),
            ("'I am clothed like an emperor in robes of celestial splendor and unparalleled beauty.'",
             "'Ben göksel bir ihtişamın ve eşsiz güzelliğin kaftanları içinde bir imparator gibi giyinmişim.'",
             "celestial splendor | Göksel ihtişam; 'robes' kaftanlar, cübbeler."),
            ("'Whereas you wear nothing but dull, miserable gray, like a common workhouse beggar.'",
             "'Oysa siz sıradan bir düşkünler yurdu dilencisi gibi kasvetli, sefil bir griden başka hiçbir şey giymiyorsunuz.'",
             "workhouse beggar | Düşkünler yurdu dilencisi; 'dull' mat, sıkıcı."),
            ("The crane looked patiently at the displaying fop, without the slightest hint of envy or shame.",
             "Turna gösteriş yapan bu züppeye en ufak bir haset veya utanç emaresi göstermeksizin sabırla baktı.",
             "displaying fop | Gösteriş meraklısı züppe; 'slightest hint' en ufak ima/belirti."),
            ("'I do not deny that your feathers are far more colorful than mine,' replied the crane calmly.",
             "Turna sakince, 'Tüylerinizin benimkilerden çok daha renkli olduğunu inkar etmiyorum,' dedi.",
             "do not deny | İnkar etmemek; 'calmly' sakince."),
            ("'You certainly glitter like a king in a miniature garden enclosure.'",
             "'Ufacık bir bahçe parmaklığının içinde hakikaten bir kral gibi parıldıyorsunuz.'",
             "garden enclosure | Bahçe çiti / parmaklığı."),
            ("'However, I notice that with all your dazzling finery, you can barely lift yourself off the ground.'",
             "'Fakat fark ediyorum ki bütün o göz alıcı süslerinize rağmen kendinizi yerden zar zor kaldırabiliyorsunuz.'",
             "dazzling finery | Göz kamaştırıcı süs püs; 'barely lift' zar zor kaldırmak."),
            ("'You must strut in the dirt among the barnyard fowls, confined forever to this earthly prison.'",
             "'Sonsuza dek bu dünyevi hapishaneye mahkum olarak çiftlik kümes hayvanları arasında pislikte çalım satmak zorundasınız.'",
             "confined | Mahkum edilmiş, hapsedilmiş; 'barnyard fowls' kümes hayvanları."),
            ("'I, on the other hand, spread these sober gray wings and soar high into the boundless heavens.'",
             "'Ben ise diğer yandan bu sade gri kanatlarımı açar ve uçsuz bucaksız göklerin doruklarına yükselirim.'",
             "boundless heavens | Sınırsız / uçsuz bucaksız gökler."),
            ("'I fly among the clouds, singing freely while gazing down upon the stars and mountains.'",
             "'Bulutların arasında uçar, dağlara ve yıldızlara tepeden bakarak özgürce şarkı söylerim.'",
             "singing freely | Özgürce şarkı söylemek."),
            ("With these words, the crane unfolded her long, powerful wings and sprang lightly into the breeze.",
             "Bu sözlerle birlikte turna uzun, güçlü kanatlarını açtı ve esintinin içine hafifçe sıçradı.",
             "unfolded wings | Kanatlarını açtı / gerdi."),
            ("She rose majestically higher and higher, disappearing into the azure blue of the open sky.",
             "Heybetle yükseldikçe yükseldi ve açık göğün masmavi enginliğinde gözden kayboldu.",
             "azure blue | Gök mavisi, turkuaz enginlik."),
            ("Utility and true freedom are infinitely more valuable than vulgar ostentation and decorative vanity.",
             "Faydalılık ve hakiki özgürlük, kaba bir gösterişçilik ve süslü bir kibirden sonsuz derecede daha değerlidir.",
             "vulgar ostentation | Bayağı gösteriş merakı; 'decorative vanity' süs kibri.")
        ],
        "vocab_focus": [
            ("conceited", "kibirli, kendini beğenmiş"),
            ("iridescent", "yanardöner, sedefli"),
            ("sober", "sade, ağırbaşlı"),
            ("undisguised", "gizlenemez, aşikar"),
            ("fop", "züppe, gösteriş meraklısı"),
            ("finery", "süslü giysi, debdebe"),
            ("confined", "kapatılmış, hapsedilmiş"),
            ("azure", "gök mavisi, masmavi")
        ]
    },

    # 14. Mercury and the Woodman
    {
        "page_no": 14,
        "title": "Mercury and the Woodman",
        "tr_title": "Merkür ve Oduncu (Altın Balta)",
        "sentences": [
            ("An honest woodcutter was felling timber on the steep bank of a swift mountain river.",
             "Dürüst bir oduncu, hızlı bir dağ nehrinin sarp kıyısında kereste kesiyordu.",
             "felling timber | Kereste kesmek / ağaç devirmek; 'honest' dürüst."),
            ("As he swung his trusty axe with all his might, the heavy iron head flew off the wooden shaft.",
             "Güvenilir baltasını bütün gücüyle savururken, ağır demir başlık ahşap saptan fırlayıp çıktı.",
             "wooden shaft | Ahşap sap; 'trusty axe' güvenilir balta."),
            ("Splash! The essential tool plunged directly into the deep, swirling torrent and sank instantly from sight.",
             "Şılapp! Bu vazgeçilmez alet doğrudan derin, girdaplı akıntıya daldı ve anında gözden kayboldu.",
             "essential tool | Vazgeçilmez alet; 'swirling torrent' girdaplı akıntı."),
            ("Having no means to purchase another and unable to earn bread for his family, the poor man wept bitterly.",
             "Bir yenisini alacak imkanı olmadığından ve ailesine ekmek kazanamayacağından zavallı adam acı acı ağladı.",
             "no means to purchase | Satın alacak imkanı olmamak; 'wept bitterly' acı acı ağladı."),
            ("Moved by his genuine distress, the god Mercury suddenly appeared amidst a flash of celestial light.",
             "Onun bu hakiki kederinden duygulanan tanrı Merkür, ilahi bir ışık parıltısının ortasında aniden belirdi.",
             "celestial light | İlahi / göksel ışık; 'genuine distress' hakiki dert."),
            ("Hearing the cause of his profound grief, the benevolent deity dived into the rushing waters.",
             "Onun derin kederinin sebebini işiten merhametli tanrı, coşkun suların içine daldı.",
             "benevolent deity | Merhametli / hayırhah tanrı; 'rushing waters' coşkun sular."),
            ("A moment later, he emerged holding aloft a magnificent axe wrought of pure, gleaming gold.",
             "Bir an sonra, saf parıldayan altından işlenmiş muhteşem bir baltayı havaya kaldırarak yüzeye çıktı.",
             "wrought of gold | Altından işlenmiş; 'holding aloft' havaya kaldırmak."),
            ("'Is this the instrument you lost?' inquired Mercury with an encouraging smile.",
             "Merkür cesaret verici bir tebessümle, 'Kaybettiğiniz alet bu mudur?' diye sordu.",
             "encouraging smile | Cesaret verici tebessüm; 'instrument' alet."),
            ("The honest woodman shook his head without hesitation, declaring that it was not his.",
             "Dürüst oduncu hiç tereddüt etmeden başını salladı ve onun kendisine ait olmadığını ilan etti.",
             "without hesitation | Tereddüt etmeden."),
            ("Mercury dived a second time and brought up an exquisite axe crafted entirely of polished silver.",
             "Merkür ikinci kez daldı ve tamamen cilalı gümüşten yapılmış enfes bir balta çıkardı.",
             "crafted of silver | Gümüşten işlenmiş / yapılmış."),
            ("Again, the humble peasant refused the precious prize, stating that his axe was of common iron.",
             "Mütevazı köylü bu kıymetli ödülü bir kez daha reddetti ve kendi baltasının alelade demirden olduğunu belirtti.",
             "precious prize | Kıymetli ödül; 'common iron' alelade demir."),
            ("Mercury dived a third time and returned with the laborer's identical old iron implement.",
             "Merkür üçüncü kez daldı ve işçinin o eski demir aletinin aynısıyla geri döndü.",
             "identical implement | Birebir aynı alet."),
            ("'That is indeed mine!' cried the delighted woodcutter, receiving his old tool with overflowing gratitude.",
             "Memnun kalan oduncu taşan bir minnettarlıkla eski aletini alarak, 'İşte bu gerçekten benimki!' diye haykırdı.",
             "overflowing gratitude | Taşan / coşkulu minnettarlık."),
            ("Pleased with his admirable integrity, Mercury bestowed upon him both the gold and silver axes as a reward.",
             "Onun bu takdire şayan dürüstlüğünden memnun kalan Merkür, ödül olarak hem altın hem gümüş baltayı ona bağışladı.",
             "admirable integrity | Takdire şayan dürüstlük / doğruluk."),
            ("When the woodman returned to his village with his treasures, the miraculous story spread rapidly.",
             "Oduncu hazineleriyle köyüne döndüğünde bu mucizevi hikaye hızla yayıldı.",
             "miraculous story | Mucizevi hikaye."),
            ("An envious neighbor resolved to secure an identical fortune by fraudulent deceit.",
             "Haset bir komşu, hileli bir aldatmacayla aynı serveti elde etmeye karar verdi.",
             "fraudulent deceit | Hileli aldatmaca / sahtekarlık; 'envious' haset."),
            ("He ran to the river, hurled his iron axe intentionally into the deep water, and began weeping loudly.",
             "Nehre koştu, demir baltasını kasten derin sulara fırlattı ve avaz avaz ağlamaya başladı.",
             "hurled intentionally | Kasten fırlatmak."),
            ("Mercury appeared as before and dived, bringing forth the same dazzling golden axe.",
             "Merkür daha önceki gibi belirdi ve dalış yaparak aynı göz kamaştırıcı altın baltayı çıkardı.",
             "dazzling golden axe | Göz kamaştırıcı altın balta."),
            ("'That is mine! That is mine!' shrieked the greedy liar, stretching out his grasping hands.",
             "Açgözlü yalancı tamahkar ellerini uzatarak, 'O benimki! O benimki!' diye çığlık attı.",
             "grasping hands | Açgözlü / kapmaya çalışan eller."),
            ("Disgusted by such brazen greed, Mercury plunged back into the depths, taking the gold and leaving the liar with nothing.",
             "Böylesine yüzsüz bir hırstan iğrenen Merkür, altını da alıp yalancıyı hiçbir şeysiz bırakarak derinliklere geri daldı.",
             "brazen greed | Yüzsüz / hayasız açgözlülük.")
        ],
        "vocab_focus": [
            ("felling timber", "kereste kesmek"),
            ("wrought of gold", "altından dövülüp işlenmiş"),
            ("encouraging", "cesaret verici, yüreklendirici"),
            ("integrity", "dürüstlük, doğruluk"),
            ("bestowed upon", "bahşetti, hediye etti"),
            ("fraudulent", "hileli, sahtekarca"),
            ("hurled", "var gücüyle fırlattı"),
            ("brazen greed", "yüzsüz/arsız açgözlülük")
        ]
    },

    # 15. The Fisherman and the Little Fish
    {
        "page_no": 15,
        "title": "The Fisherman and the Little Fish",
        "tr_title": "Balıkçı ile Küçük Balık",
        "sentences": [
            ("A poor, patient fisherman sat on the rocky bank of a tranquil river throughout a long afternoon.",
             "Yoksul ve sabırlı bir balıkçı, uzun bir öğleden sonra boyunca sakin bir nehrin kayalık kıyısında oturdu.",
             "patient fisherman | Sabırlı balıkçı; 'tranquil river' sakin nehir."),
            ("He had cast his woven net into the deep waters many times, but had captured nothing all day.",
             "Örme ağını derin sulara defalarca atmıştı ama bütün gün hiçbir şey yakalayamamıştı.",
             "woven net | Örme ağ; 'captured nothing' hiçbir şey yakalayamadı."),
            ("Just as the evening sun was sinking behind the hills, he felt a faint tug upon his line.",
             "Akşam güneşi tepelerin ardında batmak üzereyken oltasında hafif bir çekiş hissetti.",
             "faint tug | Hafif bir çekiş / asılma."),
            ("He hauled up his hook with eager anticipation, hoping for a substantial carp or a heavy pike.",
             "Büyük bir sazan veya ağır bir turnabalığı umarak hevesli bir beklentiyle kancasını yukarı çekti.",
             "hauled up | Yukarı çekmek; 'carp' sazan balığı; 'pike' turnabalığı."),
            ("Alas, dangling from the barb was only a solitary, tiny fish no longer than a man's thumb.",
             "Heyhat, kancanın ucunda sallanan tek şey bir adamın başparmağından daha uzun olmayan minicik, yalnız bir balıktı.",
             "dangling from barb | Kancanın ucunda sallanan; 'thumb' başparmak."),
            ("The disappointed angler took the wriggling creature in his hand, preparing to deposit it into his basket.",
             "Hayal kırıklığına uğrayan olta balıkçısı, sepetine koymaya hazırlanarak çırpınan yaratığı eline aldı.",
             "wriggling creature | Çırpınan / kıvranan yaratık; 'angler' olta balıkçısı."),
            ("To his utter astonishment, the miniature captive opened its tiny mouth and pleaded piteously.",
             "Büyük bir hayretle gördü ki minyatür esir minik ağzını açtı ve acıklı bir dille yalvarmaya başladı.",
             "pleaded piteously | Acıklı acıklı yalvarmak; 'miniature captive' minyatür tutsak."),
            ("'O generous angler, I beseech you to spare my life and throw me back into the water!'",
             "'Ey cömert balıkçı, hayatımı bağışlamanız ve beni suya geri atmanız için size yalvarırım!'",
             "beseech you | Size yalvarırım, istirham ederim; 'spare my life' canımı bağışla."),
            ("'I am so exceedingly small that I would not make half a mouthful for your evening supper.'",
             "'Öylesine son derece küçüğüm ki akşam yemeğiniz için yarım lokma bile etmem.'",
             "half a mouthful | Yarım lokma; 'evening supper' akşam yemeği."),
            ("'What possible satisfaction or sustenance could such a pitiful specimen afford your family?'",
             "'Böylesi acınası bir numune ailenize nasıl bir doyum veya besin sağlayabilir ki?'",
             "sustenance | Besin, gıda, azık; 'pitiful specimen' acınası numune."),
            ("'Permit me to grow in the river until next summer, feeding on water-snails and succulent weeds.'",
             "'Gelecek yaza kadar su salyangozları ve etli su otlarıyla beslenerek nehirde büyümeme müsaade edin.'",
             "succulent weeds | Etli su otları; 'permit me' bana izin verin."),
            ("'When I have become plump, heavy, and full-grown, you may capture me again.'",
             "'Tombul, ağır ve tamamen yetişkin bir balık olduğumda beni tekrar yakalayabilirsiniz.'",
             "full-grown | Tamamen büyümüş, yetişkin; 'plump' semiz, tombul."),
            ("'Then I shall fetch a magnificent sum of money for you at the town fish market.'",
             "'O zaman kasaba balık pazarında sizin için muazzam bir para miktarı getireceğim.'",
             "magnificent sum | Muazzam para tutarı."),
            ("The wise old fisherman listened calmly, shook his grizzled head, and smiled knowingly.",
             "Bilge yaşlı balıkçı sakince dinledi, kırlaşmış başını salladı ve bilmiş bilmiş tebessüm etti.",
             "grizzled head | Kırlaşmış / ak saçlı baş; 'knowingly' bilmişçe."),
            ("'I should indeed be a colossal simpleton,' remarked the fisherman, 'to heed your enticing speech.'",
             "Balıkçı, 'Senin o cezbedici nutkuna kulak asacak olsaydım, hakikaten devasa bir ahmak olurdum,' dedi.",
             "colossal simpleton | Devasa ahmak / safdil; 'enticing' cezbedici."),
            ("'If I surrendered a small certainty already in my hand for the vague hope of a future banquet, I would be a fool.'",
             "'Halihazırda elimde olan küçük bir kesinliği gelecekteki bir ziyafetin belirsiz umudu için teslim etseydim ahmak olurdum.'",
             "small certainty | Küçük kesinlik / garanti; 'vague hope' belirsiz umut."),
            ("'A tiny perch in the basket is infinitely superior to a mighty salmon swimming loose in the river.'",
             "'Sepetteki minicik bir tatlı su levreği, nehirde başıboş yüzen devasa bir somondan katbekat üstündür.'",
             "perch | Tatlı su levreği; 'salmon' somon balığı."),
            ("'You may be a modest prize, but you are a real one, and you shall fry in my skillet tonight.'",
             "'Mütevazı bir ödül olabilirsin ama gerçek bir ödülsün ve bu gece tavamda cızırdayacaksın.'",
             "fry in skillet | Tavada kızarmak; 'modest prize' mütevazı ödül."),
            ("With that, he dropped the tiny fish securely into his wicker creel and reeled in his empty tackle.",
             "Bununla birlikte minik balığı hasır sepetine güvenle bıraktı ve boş oltasını makarasına sardı.",
             "wicker creel | Hasır balıkçı sepeti; 'tackle' olta takımı."),
            ("A small advantage in hand is always more valuable than a magnificent promise in the uncertain future.",
             "Eldeki küçük bir kazanç, belirsiz gelecekteki muazzam bir vaatten daima daha kıymetlidir.",
             "in the uncertain future | Belirsiz gelecekte.")
        ],
        "vocab_focus": [
            ("faint tug", "hafif bir çekiş/dokunuş"),
            ("hauled up", "yukarı çekti"),
            ("wriggling", "çırpınan, kıvranan"),
            ("beseech", "yalvarmak, istirham etmek"),
            ("sustenance", "besin, gıda"),
            ("simpleton", "safdil, bön kimse"),
            ("certainty", "kesinlik, garanti"),
            ("wicker creel", "hasır balık sepeti")
        ]
    }
]

import os

output_file = os.path.join(os.path.dirname(__file__), "book_07_data.py")
all_pages = fables + fables_4_to_15 + fables_9_to_15

with open(output_file, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""\n')
    f.write("Book 7: Aesop's Classic Fables (Part 2): Moral of the Town\n")
    f.write("Level 1 Graded Reader — 15 Pages x 20 Sentences = 300 Sentences.\n")
    f.write('"""\n\n')
    f.write('BOOK_TITLE = "Aesop\'s Classic Fables (Part 2): Moral of the Town (15 Sayfa / 300 Cümle / Graded Reader)"\n')
    f.write('AUTHOR = "Aesop (Ezop)"\n\n')
    f.write("PAGES_DATA = [\n")
    
    current_sentence_id = 1
    for page in all_pages:
        f.write("    {\n")
        f.write(f'        "page_no": {page["page_no"]},\n')
        f.write(f'        "title": "{page["title"]}",\n')
        f.write(f'        "tr_title": "{page["tr_title"]}",\n')
        f.write('        "sentences": [\n')
        for s in page["sentences"]:
            text = s[0].replace('"', '\\"')
            tr = s[1].replace('"', '\\"')
            notes = s[2].replace('"', '\\"')
            f.write("            {\n")
            f.write(f'                "id": {current_sentence_id},\n')
            f.write(f'                "text": "{text}",\n')
            f.write(f'                "translation": "{tr}",\n')
            f.write(f'                "notes": "{notes}"\n')
            f.write("            },\n")
            current_sentence_id += 1
        f.write("        ],\n")
        f.write('        "vocab_focus": [\n')
        for v in page["vocab_focus"]:
            v_en = v[0].replace('"', '\\"')
            v_tr = v[1].replace('"', '\\"')
            f.write(f'            ("{v_en}", "{v_tr}"),\n')
        f.write("        ]\n")
        f.write("    },\n")
    f.write("]\n")

print(f"Generated tools/book_07_data.py successfully with {current_sentence_id - 1} sentences across {len(all_pages)} pages!")
