# -*- coding: utf-8 -*-
"""
Core English -> Turkish vocabulary (most frequent words), written for DictaLearn.
Used by build_dictionary.py with the highest priority so common words get their
general meaning rather than a story-specific one.
"""

CORE = {
    # Function words
    "a": "bir", "an": "bir", "the": "belirli tanımlık (o, şu)", "and": "ve", "or": "veya", "but": "ama, fakat",
    "if": "eğer", "because": "çünkü", "so": "bu yüzden; öyle", "than": "-den daha", "then": "sonra; o zaman",
    "that": "o, şu; ki", "this": "bu", "these": "bunlar", "those": "şunlar", "there": "orada; (there is) var",
    "here": "burada", "where": "nerede", "when": "ne zaman; -dığında", "why": "neden", "how": "nasıl",
    "what": "ne", "which": "hangi; ki", "who": "kim; ki", "whom": "kimi", "whose": "kimin",
    "i": "ben", "you": "sen, siz", "he": "o (erkek)", "she": "o (kadın)", "it": "o (cansız/hayvan)",
    "we": "biz", "they": "onlar", "me": "beni, bana", "him": "onu, ona (erkek)", "her": "onu, ona; onun (kadın)",
    "us": "bizi, bize", "them": "onları, onlara", "my": "benim", "your": "senin, sizin", "his": "onun (erkek)",
    "its": "onun (cansız)", "our": "bizim", "their": "onların", "mine": "benimki", "yours": "seninki",
    "myself": "kendim", "himself": "kendisi (erkek)", "herself": "kendisi (kadın)", "itself": "kendisi",
    "themselves": "kendileri", "ourselves": "kendimiz", "yourself": "kendin",
    "in": "içinde, -de", "on": "üzerinde, -de", "at": "-de, -da", "to": "-e, -a; için", "from": "-den, -dan",
    "of": "-in, -ın", "with": "ile", "without": "-sız, olmadan", "for": "için", "by": "tarafından; yanında",
    "about": "hakkında; yaklaşık", "into": "içine", "onto": "üstüne", "out": "dışarı", "up": "yukarı",
    "down": "aşağı", "over": "üzerinden; bitmiş", "under": "altında", "above": "üstünde, yukarısında",
    "below": "aşağısında", "between": "arasında", "among": "arasında (çok şey)", "through": "içinden, boyunca",
    "across": "karşısına, boyunca", "around": "etrafında", "behind": "arkasında", "before": "önce; önünde",
    "after": "sonra", "during": "sırasında", "until": "-e kadar", "since": "-den beri; çünkü",
    "near": "yakınında", "far": "uzak", "inside": "içeride", "outside": "dışarıda", "along": "boyunca",
    "against": "karşı", "toward": "-e doğru", "towards": "-e doğru", "upon": "üzerine", "within": "içinde",
    "not": "değil", "no": "hayır; hiç", "yes": "evet", "very": "çok", "too": "de, da; fazla",
    "also": "ayrıca, de", "only": "sadece", "just": "sadece; az önce", "even": "bile", "still": "hâlâ",
    "already": "zaten, çoktan", "yet": "henüz; yine de", "again": "tekrar", "never": "asla, hiç",
    "always": "her zaman", "often": "sık sık", "sometimes": "bazen", "usually": "genellikle",
    "soon": "yakında", "now": "şimdi", "today": "bugün", "tomorrow": "yarın", "yesterday": "dün",
    "tonight": "bu gece", "ago": "önce", "once": "bir kez; bir zamanlar", "ever": "hiç, şimdiye dek",
    "all": "hepsi, bütün", "every": "her", "each": "her bir", "some": "biraz, bazı", "any": "herhangi; hiç",
    "many": "çok (sayılabilir)", "much": "çok (sayılamaz)", "more": "daha fazla", "most": "en çok",
    "few": "az, birkaç", "little": "küçük; az", "less": "daha az", "other": "diğer", "another": "başka bir",
    "same": "aynı", "such": "böyle, öyle", "both": "her ikisi", "either": "ikisinden biri", "neither": "hiçbiri",
    "nothing": "hiçbir şey", "something": "bir şey", "everything": "her şey", "anything": "herhangi bir şey",
    "nobody": "hiç kimse", "somebody": "biri", "someone": "biri", "everyone": "herkes", "anyone": "herhangi biri",
    "own": "kendi", "else": "başka", "quite": "oldukça", "rather": "oldukça; tercihen", "almost": "neredeyse",
    "perhaps": "belki", "maybe": "belki", "really": "gerçekten", "suddenly": "aniden", "slowly": "yavaşça",
    "quickly": "hızla", "together": "birlikte", "away": "uzağa", "back": "geri; sırt", "off": "kapalı; -den uzak",
    "well": "iyi; peki; kuyu", "as": "olarak; gibi; -iken", "like": "gibi; sevmek", "while": "-iken; süre",
    "though": "rağmen; yine de", "although": "-e rağmen", "however": "ancak", "therefore": "bu nedenle",
    # Be / have / do / modals
    "be": "olmak", "am": "-im (olmak)", "is": "-dir (olmak)", "are": "-dirler (olmak)", "was": "idi (olmak)",
    "were": "idiler (olmak)", "been": "olmuş", "being": "olan; varlık", "have": "sahip olmak; -miş olmak",
    "has": "sahip; -miş", "had": "sahipti; -mişti", "do": "yapmak", "does": "yapar", "did": "yaptı",
    "done": "yapılmış", "can": "-ebilmek", "could": "-ebilirdi", "will": "-ecek; irade", "would": "-erdi",
    "shall": "-ecek (resmî)", "should": "-meli", "may": "-ebilir", "might": "-ebilirdi", "must": "-meli, zorunda",
    # Common verbs
    "go": "gitmek", "went": "gitti", "gone": "gitmiş", "come": "gelmek", "came": "geldi",
    "get": "almak; olmak; varmak", "got": "aldı; oldu", "make": "yapmak", "made": "yaptı; yapılmış",
    "take": "almak; götürmek", "took": "aldı", "taken": "alınmış", "give": "vermek", "gave": "verdi",
    "given": "verilmiş", "see": "görmek", "saw": "gördü", "seen": "görülmüş", "look": "bakmak; görünmek",
    "watch": "izlemek; saat", "hear": "duymak", "heard": "duydu", "listen": "dinlemek", "say": "söylemek",
    "said": "söyledi", "tell": "anlatmak, söylemek", "told": "anlattı", "speak": "konuşmak", "spoke": "konuştu",
    "talk": "konuşmak", "ask": "sormak; istemek", "answer": "cevap; cevaplamak", "call": "çağırmak; aramak",
    "know": "bilmek", "knew": "bildi", "known": "bilinen", "think": "düşünmek", "thought": "düşündü; düşünce",
    "believe": "inanmak", "feel": "hissetmek", "felt": "hissetti", "want": "istemek", "wish": "dilemek; dilek",
    "hope": "umut; ummak", "love": "sevgi; sevmek", "hate": "nefret etmek", "need": "ihtiyaç duymak",
    "find": "bulmak", "found": "buldu; kurmak", "lose": "kaybetmek", "lost": "kaybetti; kayıp",
    "keep": "tutmak, saklamak", "kept": "tuttu", "leave": "ayrılmak; bırakmak", "left": "ayrıldı; sol",
    "stay": "kalmak", "live": "yaşamak", "die": "ölmek", "dead": "ölü", "begin": "başlamak", "began": "başladı",
    "start": "başlamak", "stop": "durmak, durdurmak", "end": "son; bitirmek", "finish": "bitirmek",
    "open": "açmak; açık", "close": "kapatmak; yakın", "turn": "dönmek; sıra", "move": "hareket etmek",
    "run": "koşmak", "ran": "koştu", "walk": "yürümek", "fly": "uçmak", "flew": "uçtu", "fall": "düşmek; sonbahar",
    "fell": "düştü", "sit": "oturmak", "sat": "oturdu", "stand": "ayakta durmak", "stood": "durdu (ayakta)",
    "lie": "uzanmak; yalan", "lay": "uzandı; koymak", "sleep": "uyumak", "wake": "uyanmak", "eat": "yemek",
    "ate": "yedi", "drink": "içmek", "cry": "ağlamak; bağırmak", "laugh": "gülmek", "smile": "gülümsemek",
    "play": "oynamak; çalmak", "work": "çalışmak; iş", "help": "yardım; yardım etmek", "try": "denemek",
    "use": "kullanmak", "show": "göstermek", "bring": "getirmek", "brought": "getirdi", "carry": "taşımak",
    "hold": "tutmak", "held": "tuttu", "put": "koymak", "set": "koymak; ayarlamak", "send": "göndermek",
    "sent": "gönderdi", "pay": "ödemek", "buy": "satın almak", "sell": "satmak", "build": "inşa etmek",
    "break": "kırmak", "broke": "kırdı", "cut": "kesmek", "write": "yazmak", "wrote": "yazdı", "read": "okumak",
    "learn": "öğrenmek", "teach": "öğretmek", "understand": "anlamak", "remember": "hatırlamak",
    "forget": "unutmak", "become": "olmak, haline gelmek", "became": "oldu", "seem": "görünmek",
    "happen": "olmak, meydana gelmek", "wait": "beklemek", "follow": "takip etmek", "meet": "tanışmak, buluşmak",
    "met": "tanıştı", "win": "kazanmak", "fight": "savaşmak; kavga", "kill": "öldürmek", "save": "kurtarmak",
    "pull": "çekmek", "push": "itmek", "throw": "atmak", "catch": "yakalamak", "climb": "tırmanmak",
    "jump": "zıplamak", "swim": "yüzmek", "sing": "şarkı söylemek", "dance": "dans etmek", "pack": "toplamak, paketlemek",
    "reply": "yanıtlamak", "shout": "bağırmak", "whisper": "fısıldamak", "notice": "fark etmek",
    "decide": "karar vermek", "allow": "izin vermek", "agree": "kabul etmek", "arrive": "varmak",
    "return": "geri dönmek", "reach": "ulaşmak", "pass": "geçmek", "grow": "büyümek", "change": "değişmek; değişim",
    # Nouns
    "man": "adam", "men": "adamlar", "woman": "kadın", "women": "kadınlar", "child": "çocuk", "children": "çocuklar",
    "boy": "oğlan", "girl": "kız", "people": "insanlar", "person": "kişi", "friend": "arkadaş", "family": "aile",
    "father": "baba", "mother": "anne", "son": "oğul", "daughter": "kız evlat", "brother": "erkek kardeş",
    "sister": "kız kardeş", "king": "kral", "queen": "kraliçe", "prince": "prens", "princess": "prenses",
    "lord": "lord, efendi", "lady": "hanımefendi", "sir": "efendim", "master": "efendi, usta", "servant": "hizmetkâr",
    "doctor": "doktor", "teacher": "öğretmen", "soldier": "asker", "captain": "kaptan", "god": "tanrı",
    "time": "zaman", "day": "gün", "night": "gece", "morning": "sabah", "evening": "akşam", "week": "hafta",
    "month": "ay", "year": "yıl", "hour": "saat", "minute": "dakika", "moment": "an", "life": "hayat",
    "world": "dünya", "home": "ev", "house": "ev", "room": "oda", "door": "kapı", "window": "pencere",
    "wall": "duvar", "floor": "zemin; kat", "table": "masa", "chair": "sandalye", "bed": "yatak",
    "city": "şehir", "town": "kasaba", "village": "köy", "street": "sokak", "road": "yol", "way": "yol; şekil",
    "place": "yer", "country": "ülke", "land": "kara, toprak", "sea": "deniz", "ocean": "okyanus",
    "river": "nehir", "lake": "göl", "island": "ada", "mountain": "dağ", "hill": "tepe", "forest": "orman",
    "wood": "tahta; koru", "tree": "ağaç", "flower": "çiçek", "garden": "bahçe", "grass": "çimen",
    "rose": "gül", "leaf": "yaprak", "sky": "gökyüzü", "sun": "güneş", "moon": "ay", "star": "yıldız",
    "cloud": "bulut", "rain": "yağmur", "snow": "kar", "wind": "rüzgâr", "fire": "ateş", "water": "su",
    "air": "hava", "earth": "dünya; toprak", "stone": "taş", "gold": "altın", "silver": "gümüş",
    "statue": "heykel", "heart": "kalp", "head": "baş", "face": "yüz", "eye": "göz", "eyes": "gözler",
    "ear": "kulak", "mouth": "ağız", "hand": "el", "arm": "kol", "foot": "ayak", "feet": "ayaklar",
    "leg": "bacak", "body": "vücut", "hair": "saç", "voice": "ses", "word": "kelime", "name": "isim",
    "story": "hikâye", "book": "kitap", "letter": "mektup; harf", "money": "para", "food": "yiyecek",
    "bread": "ekmek", "dog": "köpek", "cat": "kedi", "horse": "at", "bird": "kuş", "fish": "balık",
    "wolf": "kurt", "animal": "hayvan", "ship": "gemi", "boat": "tekne", "car": "araba", "train": "tren",
    "thing": "şey", "part": "parça", "side": "taraf", "end ": "son", "war": "savaş", "peace": "barış",
    "power": "güç", "idea": "fikir", "question": "soru", "reason": "sebep", "truth": "gerçek",
    "fear": "korku", "joy": "neşe", "sorrow": "keder", "dream": "rüya; hayal", "secret": "sır",
    "problem": "sorun", "mind": "zihin; akıl", "soul": "ruh", "light": "ışık; hafif", "dark": "karanlık",
    "color": "renk", "colour": "renk", "sound": "ses", "music": "müzik", "school": "okul", "church": "kilise",
    "castle": "kale, şato", "palace": "saray", "tower": "kule", "bridge": "köprü", "journey": "yolculuk",
    # Adjectives
    "good": "iyi", "bad": "kötü", "big": "büyük", "small": "küçük", "large": "büyük, geniş", "great": "büyük; harika",
    "long": "uzun", "short": "kısa", "tall": "uzun boylu, yüksek", "high": "yüksek", "low": "alçak",
    "old": "yaşlı; eski", "young": "genç", "new": "yeni", "first": "ilk", "last": "son", "next": "sonraki",
    "happy": "mutlu", "sad": "üzgün", "angry": "kızgın", "afraid": "korkmuş", "brave": "cesur", "kind": "nazik; tür",
    "beautiful": "güzel", "pretty": "hoş, güzel", "ugly": "çirkin", "rich": "zengin", "poor": "fakir; zavallı",
    "strong": "güçlü", "weak": "zayıf", "hot": "sıcak", "cold": "soğuk", "warm": "ılık, sıcak", "cool": "serin",
    "hard": "zor; sert", "easy": "kolay", "soft": "yumuşak", "fast": "hızlı", "slow": "yavaş",
    "full": "dolu", "empty": "boş", "true": "doğru, gerçek", "false": "yanlış", "right": "doğru; sağ",
    "wrong": "yanlış", "clean": "temiz", "dirty": "kirli", "quiet": "sessiz", "loud": "gürültülü",
    "white": "beyaz", "black": "siyah", "red": "kırmızı", "blue": "mavi", "green": "yeşil", "yellow": "sarı",
    "brown": "kahverengi", "grey": "gri", "gray": "gri", "golden": "altın renkli", "wise": "bilge",
    "foolish": "aptalca", "clever": "zeki", "strange": "tuhaf", "famous": "ünlü", "important": "önemli",
    "sure": "emin", "ready": "hazır", "alone": "yalnız", "free": "özgür; bedava", "busy": "meşgul",
    "tired": "yorgun", "hungry": "aç", "sick": "hasta", "whole": "bütün", "deep": "derin", "wide": "geniş",
    "real": "gerçek", "certain": "kesin; belirli", "possible": "mümkün", "dear": "sevgili, değerli",
    # Numbers
    "one": "bir", "two": "iki", "three": "üç", "four": "dört", "five": "beş", "six": "altı", "seven": "yedi",
    "eight": "sekiz", "nine": "dokuz", "ten": "on", "hundred": "yüz", "thousand": "bin", "second": "ikinci; saniye",
    "third": "üçüncü", "half": "yarım",
}
