# -*- coding: utf-8 -*-
"""
Generator script to build tools/book_06_data.py
Aesop's Classic Fables (Part 1): Wisdom of the Forest
15 Pages x 20 Sentences = 300 Sentences.
"""

pages_content = [
    # PAGE 1: The Tortoise and the Hare
    {
        "page_no": 1,
        "title": "The Tortoise and the Hare",
        "tr_title": "Kaplumbağa ile Tavşan",
        "sentences": [
            ("Once upon a time, a boastful hare lived in a peaceful green valley.",
             "Bir zamanlar, huzurlu ve yeşil bir vadide övünmeyi çok seven bir tavşan yaşarmış.",
             "boastful | 'Övüngen, kendini beğenen' sıfatıdır."),
            ("He never stopped bragging about how fast he could run across the open fields.",
             "Açık tarlalarda ne kadar hızlı koşabildiği hakkında böbürlenmeyi asla bırakmazdı.",
             "bragging about | 'Bir şeyle böbürlenmek, hava atmak' kalıbıdır."),
            ("One sunny morning, he caught sight of a patient tortoise crawling slowly along the road.",
             "Güneşli bir sabah, yol boyunca ağır ağır sürünen sabırlı bir kaplumbağayı gözüne kestirdi.",
             "caught sight of | 'Gözü ilişmek, aniden fark etmek' deyimidir."),
            ("The hare laughed loudly and mocked the tortoise for his remarkably slow pace.",
             "Tavşan kahkahalarla güldü ve olağanüstü yavaş temposu yüzünden kaplumbağayla alay etti.",
             "mocked | 'Alay etmek, dalga geçmek' fiilidir."),
            ("'Do you ever get anywhere before sunset?' asked the hare with a sharp chuckle.",
             "Tavşan sivri bir kıkırdamayla, 'Güneş batmadan herhangi bir yere varabildiğin oluyor mu hiç?' diye sordu.",
             "sharp chuckle | Sivri, alaycı kıkırdama."),
            ("'Yes, indeed,' answered the tortoise calmly, 'and I get there sooner than you think.'",
             "Kaplumbağa sakince, 'Evet, elbette,' diye yanıtladı, 've oraya düşündüğünden daha erken varırım.'",
             "sooner than you think | 'Düşündüğünden daha erken' zarf yapısıdır."),
            ("'In fact, I am quite willing to prove it by racing against you right now.'",
             "'Hatta hemen şu an seninle yarışarak bunu kanıtlamaya dünden hazırım.'",
             "quite willing to | 'Bir şeyi yapmaya son derece istekli/hazır olmak' kalıbıdır."),
            ("The hare thought this challenge was the finest joke he had heard all year.",
             "Tavşan bu meydan okumanın bütün yıl duyduğu en komik şaka olduğunu düşündü.",
             "challenge | Meydan okuma, iddia."),
            ("A wise old fox agreed to act as the official umpire and marked out the course.",
             "Bilge yaşlı bir tilki resmi hakemlik yapmayı kabul etti ve yarış parkurunu belirledi.",
             "umpire | Hakem, gözlemci; 'marked out' çizip belirlemek."),
            ("The starting signal was given, and the two runners began the famous contest.",
             "Başlangıç işareti verildi ve iki yarışmacı meşhur mücadeleye başladılar.",
             "contest | Yarışma, müsabaka, çekişme."),
            ("The hare bounded forward like an arrow, disappearing over the hill in an instant.",
             "Tavşan bir ok gibi ileriye fırladı ve bir göz açıp kapayıncaya dek tepenin ardında kayboldu.",
             "bounded forward | İleriye doğru sıçrayarak fırlamak."),
            ("Meanwhile, the tortoise kept plodding along at his steady, unhurried pace.",
             "Bu esnada kaplumbağa, düzenli ve telaşsız temposuyla ağır adımlarla ilerlemeye devam etti.",
             "plodding along | Ağır ve kararlı adımlarla ilerlemek."),
            ("Halfway to the finish line, the hare looked back and saw no sign of his rival.",
             "Bitiş çizgisinin yarısına geldiğinde tavşan arkasına baktı ve rakibinden hiçbir iz göremedi.",
             "no sign of | 'Hiçbir iz/belirti olmaması' kalıbıdır."),
            ("'I have plenty of time,' whispered the hare, feeling warm and drowsy under the midday sun.",
             "Öğle güneşinin altında ılık ve mayışmış hisseden tavşan, 'Bolca vaktim var,' diye fısıldadı.",
             "drowsy | Uykulu, mahmur, mayışmış."),
            ("He stretched himself out beneath a shady oak tree and soon fell fast asleep.",
             "Gölgeli bir meşe ağacının altına boylu boyunca uzandı ve kısa sürede derin bir uykuya daldı.",
             "stretched out | Boylu boyunca uzanmak."),
            ("Step by step, the determined tortoise continued his journey without pausing for a single moment.",
             "Kararlı kaplumbağa tek bir an bile duraksamadan adım adım yolculuğuna devam etti.",
             "without pausing | Duraksamadan, mola vermeden."),
            ("He silently passed the sleeping hare and steadily approached the wooden goal-post.",
             "Uyuyan tavşanın yanından sessizce geçti ve ahşap hedef direğine istikrarlı biçimde yaklaştı.",
             "goal-post | Hedef direği, kale direği."),
            ("When the hare finally woke up with a start, he saw the tortoise just crossing the line.",
             "Tavşan nihayet irkilerek uyandığında, kaplumbağanın çizgiyi tam o anda geçmekte olduğunu gördü.",
             "woke up with a start | İrkilerek / sıçrayarak uyanmak deyimidir."),
            ("He dashed forward with frantic speed, but his late effort was completely useless.",
             "Çılgınca bir hızla öne atıldı ama bu geç kalmış gayreti büsbütün nafileydi.",
             "frantic speed | Çılgınca / telaşlı bir sürat."),
            ("All the forest animals cheered, reminding everyone that slow and steady wins the race.",
             "Tüm orman hayvanları tezahürat yaparak yavaş ve istikrarlı olanın yarışı kazandığını herkese hatırlattı.",
             "slow and steady | 'Ağır ama istikrarlı' klasik deyimidir.")
        ],
        "vocab_focus": [
            ("boastful", "övüngen, kibirli"),
            ("mocked", "alay etti, küçümsedi"),
            ("slow pace", "yavaş tempo"),
            ("umpire", "hakem, tarafsız gözlemci"),
            ("plodding along", "ağır ve kararlı yürümek"),
            ("drowsy", "mayışmış, uykulu"),
            ("with a start", "irkilerek, sıçrayarak"),
            ("slow and steady", "ağır ve kararlı olan")
        ]
    },

    # PAGE 2: The Boy Who Cried Wolf
    {
        "page_no": 2,
        "title": "The Boy Who Cried Wolf",
        "tr_title": "Yalancı Çoban",
        "sentences": [
            ("A young shepherd boy was assigned to watch the village sheep on a solitary hillside.",
             "Genç bir çoban çocuğu, ıssız bir yamaçta köyün koyunlarını gözetlemekle görevlendirilmişti.",
             "assigned to | Bir göreve atanmak / görevlendirilmek."),
            ("He found his daily duties exceedingly dull, sitting alone from sunrise until twilight.",
             "Gündoğumundan alacakaranlığa dek yapayalnız oturarak günlük vazifelerini son derece sıkıcı buluyordu.",
             "exceedingly dull | Son derece sıkıcı / tekdüze."),
            ("To relieve his intense boredom, he devised a mischievous scheme to amuse himself.",
             "Bu yoğun can sıkıntısını gidermek için kendi kendini eğlendirecek muzip bir plan tasarladı.",
             "relieve boredom | Can sıkıntısını gidermek."),
            ("He ran toward the edge of the hill and shouted at the top of his voice.",
             "Tepenin kenarına doğru koştu ve avazı çıktığı kadar bağırmaya başladı.",
             "at the top of his voice | Avazı çıktığı kadar."),
            ("'Wolf! Wolf! A fierce wolf is attacking the peaceful flock!'",
             "'Kurt! Kurt! Vahşi bir kurt masum sürüye saldırıyor!'",
             "fierce | Vahşi, azgın; 'flock' koyun sürüsüdür."),
            ("The diligent villagers dropped their heavy scythes and rushed up the slope to help him.",
             "Gayretli köylüler ağır tırpanlarını yere attılar ve ona yardım etmek için yamaca koştular.",
             "scythes | Tırpanlar; 'rushed up' yukarı koştular."),
            ("When they arrived out of breath, they found no dangerous wolf anywhere in sight.",
             "Nefes nefese oraya vardıklarında görünürde hiçbir tehlikeli kurt bulamadılar.",
             "out of breath | Nefes nefese kalmış."),
            ("Instead, they saw the shepherd boy laughing heartily at the success of his foolish prank.",
             "Bunun yerine, ahmakça şakasının başarısına katıla katıla gülen çoban çocuğunu gördüler.",
             "laughing heartily | Katıla katıla / candan gülmek."),
            ("The elders scolded him severely for disturbing the peace of the honest community.",
             "Büyükler, dürüst cemaatin huzurunu kaçırdığı için onu sert bir dille azarladılar.",
             "scolded severely | Sertçe azarlamak."),
            ("A few days later, feeling lonely once again, the boy repeated the deceptive trick.",
             "Birkaç gün sonra kendini yeniden yalnız hisseden çocuk, bu aldatıcı numarayı tekrarladı.",
             "deceptive trick | Aldatıcı numara / hile."),
            ("Once more, the alarmed villagers climbed the steep hill to rescue the innocent sheep.",
             "Endişelenen köylüler masum koyunları kurtarmak için sarp tepeye bir kez daha tırmandılar.",
             "alarmed | Telaşlanmış, paniğe kapılmış."),
            ("Again, they found only the mocking boy chuckling behind a tall stone boulder.",
             "Yine karşılarında yalnızca kocaman bir kayanın arkasında kıkırdayan o alaycı çocuğu buldular.",
             "boulder | İri kaya parçası."),
            ("The villagers returned home feeling deeply resentful and vowed never to be deceived again.",
             "Köylüler kendilerini derinden kırılmış hissederek eve döndüler ve bir daha aldanmayacaklarına yemin ettiler.",
             "resentful | Kırgın, içerlemiş; 'vowed' yemin etti."),
            ("One gloomy evening, a real grey wolf crept stealthily out from the dense forest.",
             "Karanlık ve kasvetli bir akşam, gerçek gri bir kurt sık ormandan sinsi adımlarla çıkageldi.",
             "crept stealthily | Sinsice / gizlice sokulmak."),
            ("The ferocious beast sprang upon the helpless flock, baring its sharp white teeth.",
             "Yırtıcı canavar sivri beyaz dişlerini göstererek çaresiz sürünün üzerine atıldı.",
             "ferocious beast | Yırtıcı, vahşi canavar."),
            ("Terrified beyond measure, the shepherd boy screamed for assistance with genuine desperation.",
             "Tarifsiz bir dehşete kapılan çoban çocuğu, hakiki bir çaresizlikle yardım için feryat etti.",
             "beyond measure | Haddinden fazla, ölçüsüz derecede."),
            ("'Wolf! Wolf! I swear by heaven that a real monster is devouring our sheep!'",
             "'Kurt! Kurt! Gökyüzüne yemin ederim ki gerçek bir canavar koyunlarımızı parçalıyor!'",
             "devouring | Açgözlülükle yiyip yutmak, parçalamak."),
            ("Hearing his cries, the villagers shrugged their shoulders, assuming it was merely another falsehood.",
             "Feryatlarını işiten köylüler, bunun yalnızca bir başka yalan olduğunu varsayarak omuz silktiler.",
             "shrugged shoulders | Omuz silkmek; 'falsehood' yalan."),
            ("Nobody went to his aid, and the hungry predator scattered and destroyed the entire flock.",
             "Hiç kimse onun yardımına gitmedi ve aç yırtıcı hayvan bütün sürüyü dağıtıp telef etti.",
             "predator | Yırtıcı hayvan, avcı."),
            ("Liars will never be believed, even when they utter the absolute truth in moments of peril.",
             "Yalancılara, en büyük tehlike anlarında mutlak hakikati dile getirseler bile asla inanılmaz.",
             "moments of peril | Tehlike anları / felaket anı.")
        ],
        "vocab_focus": [
            ("solitary", "yalnız, tenha"),
            ("relieve boredom", "can sıkıntısını gidermek"),
            ("scythes", "tırpanlar"),
            ("prank", "şaka, muziplik"),
            ("deceptive", "aldatıcı, yanıltıcı"),
            ("crept stealthily", "sinsice sokuldu"),
            ("ferocious", "yırtıcı, vahşi"),
            ("moments of peril", "tehlike ve kriz anları")
        ]
    },

    # PAGE 3: The Lion and the Mouse
    {
        "page_no": 3,
        "title": "The Lion and the Mouse",
        "tr_title": "Aslan ile Fare",
        "sentences": [
            ("A mighty lion was sleeping peacefully beneath the pleasant shade of a leafy tree.",
             "Kudretli bir aslan, yapraklı bir ağacın tatlı gölgesi altında huzur içinde uyuyordu.",
             "mighty | Kudretli, güçlü, azametli."),
            ("A timid little field mouse, scurrying through the tall grass, accidentally ran across the lion's nose.",
             "Uzun otların arasında aceleyle koşturan ürkek küçük bir tarla faresi, kazara aslanın burnunun üzerinden geçti.",
             "scurrying | Telaşla hızlı adımlarla koşmak."),
            ("Startled from his deep slumber, the great beast awoke with a formidable roar.",
             "Derin uykusundan irkilen büyük canavar, heybetli bir kükremeyle uyandı.",
             "slumber | Uyku, uyuklama hali; 'formidable' heybetli, korku uyandıran."),
            ("He placed his enormous, heavy paw upon the tiny creature, intending to crush it instantly.",
             "Minik yaratığı bir anda ezmek niyetiyle kocaman, ağır pençesini üzerine koydu.",
             "intending to | '... niyetinde olmak, hedeflemek' kalıbıdır."),
            ("'Spare me, O King!' squeaked the terrified mouse in a tiny, trembling voice.",
             "Ödü patlayan fare titrek, minicik bir sesle 'Beni bağışla ey Kralım!' diye ciyakladı.",
             "squeaked | Ciyaklamak, tiz ses çıkarmak; 'spare me' canımı bağışla."),
            ("'Forgive my clumsy carelessness, and I promise I shall never forget your boundless mercy.'",
             "'Sakarlığımı affet; sonsuz merhametini asla unutmayacağıma söz veriyorum.'",
             "boundless mercy | Sınırsız / uçsuz bucaksız merhamet."),
            ("'Who knows but that I may be able to repay your kindness on some future occasion?'",
             "'Kimbilir, belki gelecekteki bir günde bu iyiliğinin karşılığını ben de ödeyebilirim?'",
             "repay your kindness | İyiliğinin karşılığını ödemek."),
            ("The lion was so amused by the preposterous idea of a mouse helping a lion that he laughed aloud.",
             "Bir farenin bir aslana yardım etmesi gibi akıl almaz bir fikir aslana öyle komik geldi ki kahkahayla güldü.",
             "preposterous | Akıl almaz, saçma, mantıksız."),
            ("Being generous in spirit, he lifted his heavy paw and permitted the grateful captive to escape.",
             "Ruhu cömert olduğu için ağır pençesini kaldırdı ve minnettar esirin kaçmasına izin verdi.",
             "grateful captive | Minnettar esir / tutsak."),
            ("A short time afterward, the lion was roaming through the forest in search of prey.",
             "Kısa bir süre sonra aslan, av arayışıyla ormanda dolaşıyordu.",
             "roaming | Dolaşmak, gezinmek."),
            ("He stepped into a concealed hunter's trap made of strong, interwoven hemp cords.",
             "Güçlü ve birbirine örülmüş kenevir halatlardan yapılmış gizli bir avcı tuzağına bastı.",
             "concealed trap | Gizlenmiş tuzak; 'hemp cords' kenevir ipler."),
            ("The heavy net tightened swiftly around him, binding his limbs so tightly that he could not move.",
             "Ağır ağ onun etrafında hızla sıkılaştı ve kollarını bacaklarını hareket edemeyeceği kadar sıktı.",
             "tightened swiftly | Hızla sıkılaştı / daraldı."),
            ("His thunderous roars of fury and distress echoed through the woodland for miles around.",
             "Öfke ve çaresizlik dolu gök gürültüsü gibi kükremeleri millerce uzaktaki korulukta yankılandı.",
             "thunderous roars | Gök gürültüsünü andıran kükremeler."),
            ("Recognizing the voice of his majestic benefactor, the little mouse hurried to the scene.",
             "Heybetli velinimetinin sesini tanıyan küçük fare derhal olay yerine koştu.",
             "benefactor | İyiliksever, velinimet."),
            ("He found the mighty King of Beasts writhing helplessly within the intricate knots of the net.",
             "Kudretli Hayvanlar Kralı'nı ağın karmaşık düğümleri içinde çaresizce kıvranırken buldu.",
             "writhing helplessly | Çaresizce kıvranmak."),
            ("'Do not despair, noble friend,' murmured the mouse, 'I shall set you free without delay.'",
             "Fare, 'Umutsuzluğa kapılma asil dostum,' diye fısıldadı, 'seni gecikmeden özgür kılacağım.'",
             "do not despair | Umutsuzluğa kapılma / yeise düşme."),
            ("He immediately set to work with his sharp little incisors, gnawing relentlessly at the thickest rope.",
             "Keskin minik ön dişleriyle hemen işe koyuldu ve en kalın ipi durup dinlenmeksizin kemirdi.",
             "incisors | Ön kesici dişler; 'gnawing relentlessly' acımasızca / durmaksızın kemirmek."),
            ("Strand by strand, the tough fibers parted beneath his patient and persistent labor.",
             "Onun sabırlı ve kararlı emeği sayesinde sert lifler tel tel birbirinden ayrıldı.",
             "strand by strand | Tel tel, lif lif."),
            ("Soon a great opening was made, and the grateful monarch slipped safely out of the trap.",
             "Kısa sürede büyük bir delik açıldı ve minnettar hükümdar tuzaktan güvenle sıyrılıp çıktı.",
             "monarch | Hükümdar, kral."),
            ("No act of kindness, no matter how small, is ever wasted in this wide world.",
             "Bu koca dünyada, ne kadar küçük olursa olsun hiçbir iyilik asla boşa gitmez.",
             "is ever wasted | Asla boşa harcanmaz / ziyan olmaz.")
        ],
        "vocab_focus": [
            ("slumber", "derin uyku"),
            ("preposterous", "akıl almaz, mantıksız"),
            ("captive", "esir, tutsak"),
            ("concealed", "gizlenmiş, saklanmış"),
            ("thunderous", "gök gürültüsü gibi heybetli"),
            ("benefactor", "iyiliksever, velinimet"),
            ("gnawing", "kemirmek"),
            ("persistent", "ısrarcı, sebatkâr")
        ]
    },

    # PAGE 4: The Ant and the Grasshopper
    {
        "page_no": 4,
        "title": "The Ant and the Grasshopper",
        "tr_title": "Karınca ile Ağustos Böceği",
        "sentences": [
            ("Throughout the glorious summer days, a merry grasshopper sang and danced in the meadow.",
             "Muhteşem yaz günleri boyunca, neşeli bir ağustos böceği çayırda şarkı söyledi ve dans etti.",
             "glorious | Görkemli, parlak, şahane."),
            ("He basked in the golden sunshine, carefree and oblivious to any thought of the approaching winter.",
             "Altın güneşin altında keyifle ısındı; yaklaşan kışa dair hiçbir düşünceyi umursamayan kaygısız bir haldeydi.",
             "basked | Güneşlenmek, tadını çıkarmak; 'oblivious to' bir şeyden bihaber olmak."),
            ("Near his sunny perch, a colony of hardworking ants toiled diligently from dawn to dusk.",
             "Onun güneşli tüneğinin yakınında, çalışkan bir karınca kolonisi şafaktan gün batımına kadar gayretle ter döküyordu.",
             "toiled diligently | Gayretle çalışmak / didinmek."),
            ("They carried heavy grains of wheat and barley into their underground storerooms with tireless perseverance.",
             "Yorulmak bilmez bir azimle ağır buğday ve arpa tanelerini yer altı kilerlerine taşıyorlardı.",
             "tireless perseverance | Yorulmaz azim / sebat."),
            ("The grasshopper laughed heartily at their unceasing sweat and mockingly invited them to join his music.",
             "Ağustos böceği onların dinmeyen terine katıla katıla güldü ve alaycı bir tavırla onları müziğine katılmaya çağırdı.",
             "unceasing sweat | Dinmeyen, aralıksız alın teri."),
            ("'Why exhaust yourselves with such heavy burdens when summer offers delightful leisure?' he asked.",
             "'Yaz böylesine enfes bir dinlence sunarken neden kendinizi böylesi ağır yüklerle tüketiyorsunuz?' diye sordu.",
             "exhaust yourselves | Kendini tüketmek / tüketip bitirmek."),
            ("A sensible ant paused momentarily, wiping the perspiration from her brow.",
             "Aklı başında bir karınca alnındaki teri silerek bir anlığına duraksadı.",
             "perspiration | Ter; 'sensible' aklı başında, mantıklı."),
            ("'We are laying up food for the harsh winter months,' she answered calmly.",
             "Sükunetle, 'Çetin kış ayları için yiyecek depoluyoruz,' diye cevap verdi.",
             "laying up food | Yiyecek biriktirmek / stoklamak."),
            ("'And I strongly counsel you to do the same before the biting frosts arrive.'",
             "'Ve dondurucu kırağılar gelmeden evvel sana da hararetle aynısını yapmanı tavsiye ederim.'",
             "biting frosts | İliklere işleyen / dondurucu kırağılar."),
            ("The grasshopper scoffed at her earnest advice, declaring that winter was still far away.",
             "Ağustos böceği kışın daha çok uzakta olduğunu ilan ederek karıncanın içten tavsiyesini küçümsedi.",
             "scoffed at | Bir şeyi alaya almak, burun kıvırmak."),
            ("When the golden autumn faded, icy gales swept across the barren landscape.",
             "Altın sonbahar solup gittiğinde, buz gibi sert rüzgarlar kıraç arazide esip geçti.",
             "barren landscape | Kıraç / çorak manzara; 'gales' fırtınalar."),
            ("Deep drifts of snow buried every blade of grass, and the streams froze into solid glass.",
             "Derin kar yığınları her bir ot yaprağını gömdü ve dereler donup sert birer cama dönüştü.",
             "drifts of snow | Kar yığınları / tepecikleri."),
            ("Shivering with piercing cold and faint from agonizing hunger, the wretched grasshopper had nothing to eat.",
             "İçine işleyen soğuktan titreyen ve kahredici açlıktan bitkin düşen sefil ağustos böceğinin yiyecek hiçbir şeyi kalmamıştı.",
             "shivering with cold | Soğuktan titremek; 'agonizing hunger' kahredici açlık."),
            ("In utter desperation, he dragged himself to the underground habitation of the frugal ants.",
             "Büsbütün bir çaresizlik içinde, tutumlu karıncaların yer altı meskenine doğru kendini güçlükle sürükledi.",
             "frugal | Tutumlu, idareli; 'habitation' mesken, barınak."),
            ("He knocked humbly at the sturdy entrance, begging for a few pitiful crumbs of corn.",
             "Birkaç acınası mısır kırıntısı için yalvararak sağlam kapıyı mahcup bir tavırla çaldı.",
             "pitiful crumbs | Acınası kırıntılar; 'humbly' mahcupça."),
            ("The ants opened their door slightly, warm and comfortably fed from their abundant stores.",
             "Bereketli erzak depolarından karınları doymuş, sıcacık ve rahat haldeki karıncalar kapılarını araladılar.",
             "abundant stores | Bol, bereketli erzak depoları."),
            ("'What did you do all summer while we were harvesting the crop?' asked the leader.",
             "Liderleri, 'Biz mahsulü hasat ederken sen bütün yaz ne yaptın?' diye sordu.",
             "harvesting the crop | Mahsulü hasat etmek."),
            ("'Alas!' wept the grasshopper, 'I had no time to store food, for I was busy singing night and day.'",
             "Ağustos böceği ağlayarak, 'Ah!' dedi, 'yiyecek depolamaya hiç vaktim olmadı; çünkü gece gündüz şarkı söylemekle meşguldüm.'",
             "busy singing | Şarkı söylemekle meşgul."),
            ("'If you were foolish enough to sing all summer,' replied the ant firmly, 'you may dance all winter.'",
             "Karınca kararlı bir dille, 'Bütün yaz şarkı söyleyecek kadar ahmaktıysan,' dedi, 'bütün kış da dans edebilirsin.'",
             "foolish enough to | '... yapacak kadar ahmak' kalıbıdır."),
            ("It is best to prepare today for the inevitable hardships and necessities of tomorrow.",
             "Yarının kaçınılmaz zorlukları ve zaruri ihtiyaçları için bugünden hazırlanmak en doğrusudur.",
             "inevitable hardships | Kaçınılmaz zorluklar.")
        ],
        "vocab_focus": [
            ("basked", "güneşin tadını çıkardı"),
            ("oblivious", "bihaber, kayıtsız"),
            ("toiled", "ağır işlerde didindi"),
            ("perseverance", "azim, sebat"),
            ("biting frosts", "dondurucu kırağılar"),
            ("frugal", "tutumlu, idareli"),
            ("abundant", "bol, bereketli"),
            ("inevitable", "kaçınılmaz")
        ]
    },

    # PAGE 5: The Fox and the Grapes
    {
        "page_no": 5,
        "title": "The Fox and the Grapes",
        "tr_title": "Tilki ile Üzümler",
        "sentences": [
            ("A sly fox was slinking silently through a flourishing country vineyard on a sultry summer afternoon.",
             "Kurnaz bir tilki, boğucu sıcak bir yaz ikindisinde bereketli bir köy bağının içinde sessizce süzülüyordu.",
             "slinking | Sinsice süzülmek, sessizce yürümek; 'sultry' boğucu sıcak."),
            ("He was parched with unbearable thirst and his stomach rumbled with acute hunger.",
             "Dayanılmaz bir susuzluktan dili damağı kurumuştu ve karnı şiddetli bir açlıkla gurulduyordu.",
             "parched | Dili damağı kurumuş; 'acute hunger' şiddetli açlık."),
            ("Suddenly, his amber eyes caught sight of magnificent bunches of purple grapes hanging high overhead.",
             "Ansızın kehribar rengi gözleri, tepede asılı duran muhteşem mor üzüm salkımlarına ilişti.",
             "bunches of grapes | Üzüm salkımları."),
            ("They were fully ripe, glistening lusciously in the filtered sunlight like polished amethysts.",
             "Tamamen olgunlaşmışlardı; süzülen güneş ışığında cilalı ametist taşları gibi iştah açıcı şekilde parıldıyorlardı.",
             "glistening lusciously | İştah kabartıcı şekilde parıldamak."),
            ("The sweet juice seemed ready to burst through their thin, tender skins at the slightest touch.",
             "Tatlı şıra, en ufak bir dokunuşta incecik, narin kabuklarından dışarı fışkırmaya hazır görünüyordu.",
             "burst through | Yarıp dışarı fırlamak."),
            ("'Just the very thing to quench my thirst!' exclaimed the fox, licking his dry lips in anticipation.",
             "Beklentiyle kuru dudaklarını yalayan tilki, 'Susuzluğumu gidermek için tam da aradığım şey!' diye haykırdı.",
             "quench thirst | Susuzluğu gidermek / dindirmek."),
            ("He took a few steps backward to gain sufficient momentum for a powerful upward leap.",
             "Güçlü bir yukarı sıçrayış için yeterli ivmeyi kazanmak maksadıyla birkaç adım geriye çekildi.",
             "gain momentum | İvme / hız kazanmak."),
            ("With all his strength, he sprang high into the air, snapping his jaws hungrily.",
             "Bütün gücüyle havaya sıçradı ve açgözlülükle çenesini şaklattı.",
             "snapping his jaws | Çenesini / dişlerini şaklatmak."),
            ("Alas, he missed the dangling cluster by a mere couple of inches and tumbled back down.",
             "Heyhat, sarkan salkımı yalnızca birkaç parmak farkla kaçırdı ve tepeüstü yere yuvarlandı.",
             "dangling cluster | Sarkan salkım; 'by a mere couple of inches' sadece birkaç parmak farkla."),
            ("Undaunted by his first failure, he retreated further into the lane to take a longer run.",
             "İlk başarısızlığından yılmayarak daha uzun bir koşu mesafesi almak için patikada biraz daha geriye çekildi.",
             "undaunted | Yılmamış, cesareti kırılmamış."),
            ("Again he leaped with desperate agility, stretching his pointed muzzle toward the fruit.",
             "Sivri burnunu meyveye doğru uzatarak can havliyle bir çeviklikle bir kez daha sıçradı.",
             "desperate agility | Çaresizlikten doğan çeviklik."),
            ("Once more his paws grasped empty air, and he landed heavily upon the stony soil.",
             "Pençeleri bir kez daha boş havayı kavradı ve taşlı toprağın üzerine sertçe indi.",
             "grasped empty air | Boş havayı yakalamak."),
            ("Time after time he repeated the exhausting endeavor, refusing to abandon the tantalizing prize.",
             "Karşı konulmaz ödülü terk etmeyi reddederek bu yorucu teşebbüsü defalarca tekrarladı.",
             "tantalizing prize | İştah kabartan / cazip ödül."),
            ("His breath came in ragged gasps, and his sleek red coat was coated in thick dust.",
             "Nefesi kesik kesik çıkıyordu ve parlak kızıl kürkü kalın bir toz tabakasıyla kaplanmıştı.",
             "ragged gasps | Kesik kesik solumalar; 'sleek' parlak, düzgün."),
            ("Finally, realizing that the grapes hung far beyond his utmost physical reach, he ceased his efforts.",
             "Nihayet üzümlerin kendi azami fiziksel erişiminin çok ötesinde asılı durduğunu fark ederek çabalarına son verdi.",
             "utmost reach | Ulaşılabilecek en son nokta / azami erişim."),
            ("He smoothed his ruffled fur and curled his bushy tail with an elaborate show of indifference.",
             "Kabarmış kürkünü düzeltti ve incelikli bir umursamazlık gösterisiyle gür kuyruğunu kıvırdı.",
             "show of indifference | Umursamazlık gösterisi."),
            ("Looking up disdainfully at the luscious fruit, he wrinkled his nose in apparent disgust.",
             "İştah kabartıcı meyveye küçümsemeyle yukarı doğru bakarak bariz bir tiksintiyle burnunu kıvırdı.",
             "wrinkled his nose | Burnunu kıvırmak / buruşturmak."),
            ("'What a fool I am to weary myself for such worthless green trash!' he muttered loudly.",
             "'Böylesi değersiz yeşil süprüntüler uğruna kendimi yoracak kadar ne ahmakmışım!' diye seslice söylendi.",
             "weary myself | Kendimi yormak / tüketmek."),
            ("'They are completely sour and unripe; only foolish birds would bother to taste them.'",
             "'Tamamen ekşi ve hamlar; ancak aptal kuşlar onları tatmaya tenezzül eder.'",
             "sour and unripe | Ekşi ve ham / olgunlaşmamış."),
            ("It is easy to despise and belittle what one cannot attain through one's own shortcomings.",
             "İnsanın kendi kusur ve yetersizlikleri yüzünden elde edemediği şeyleri hor görüp küçümsemesi pek kolaydır.",
             "despise and belittle | Hor görmek ve küçümsemek.")
        ],
        "vocab_focus": [
            ("sultry", "boğucu sıcak, bunaltıcı"),
            ("parched", "susuzluktan kurumuş"),
            ("quench", "dindirmek, gidermek"),
            ("undaunted", "yılmamış, cesur"),
            ("tantalizing", "iştah kabartan, cezbedici"),
            ("show of indifference", "umursamazlık gösterisi"),
            ("wrinkled his nose", "burnunu kıvırdı"),
            ("belittle", "küçümsemek, hafife almak")
        ]
    },

    # PAGE 6: The Town Mouse and the Country Mouse
    {
        "page_no": 6,
        "title": "Town Mouse and Country Mouse",
        "tr_title": "Şehir Faresi ile Köy Faresi",
        "sentences": [
            ("A modest country mouse lived quietly in a hollow tree root beside a peaceful wheatfield.",
             "Mütevazı bir kır faresi, huzurlu bir buğday tarlasının yanındaki kovuk bir ağaç kökünde sakince yaşardı.",
             "hollow tree root | Kovuk ağaç kökü; 'modest' mütevazı."),
            ("One afternoon, his wealthy cousin from the grand metropolis arrived for a friendly visit.",
             "Bir öğleden sonra, büyük metropolden varlıklı kuzeni dostane bir ziyaret için çıkageldi.",
             "metropolis | Büyükşehir, metropol; 'wealthy' varlıklı."),
            ("The hospitable country mouse gladly offered the best fare his humble pantry could provide.",
             "Misafirperver kır faresi, mütevazı kilerinin sunabileceği en leziz azığı sevinçle ikram etti.",
             "hospitable | Misafirperver; 'fare' yiyecek, azık."),
            ("He served dried acorns, tender barley stalks, and freshly gathered wild berries.",
             "Kurutulmuş meşe palamutları, taze arpa sapları ve yeni toplanmış yabani böğürtlenler sundu.",
             "acorns | Meşe palamutları; 'barley stalks' arpa sapları."),
            ("The town mouse nibbled daintily at the coarse food, wrinkling his whiskers in obvious disdain.",
             "Şehir faresi bu kaba yiyecekleri belli bir küçümsemeyle bıyıklarını oynatarak nazikçe kemirdi.",
             "nibbled daintily | Kibarca, ucuyla kemirmek; 'disdain' küçümseme."),
            ("'How can you endure such primitive existence in this dreary wilderness?' asked the cousin.",
             "'Bu kasvetli yaban ellerde böylesine ilkel bir varoluşa nasıl katlanabiliyorsun?' diye sordu kuzen.",
             "dreary wilderness | Kasvetli yaban hayatı / ıssızlık."),
            ("'Come with me to the royal city, where luxury, abundance, and endless pleasures await us.'",
             "'Benimle o şanlı şehre gel; orada lüks, bolluk ve sonsuz zevkler bizi bekliyor.'",
             "luxury and abundance | Lüks ve bolluk."),
            ("Persuaded by these glittering promises, the country mouse set off with his cousin that night.",
             "Bu parıltılı vaatlerle ikna olan kır faresi, o gece kuzeniyle birlikte yola koyuldu.",
             "persuaded by | İkna edilmiş; 'set off' yola çıkmak."),
            ("They reached a stately mansion with tall marble columns and magnificent carpets.",
             "Yüksek mermer sütunları ve muhteşem halıları olan görkemli bir köşke vardılar.",
             "stately mansion | Görkemli malikane / konak."),
            ("On the dining table lay the sumptuous remnants of a magnificent feast for the nobility.",
             "Yemek masasının üzerinde, soylular için verilmiş muazzam bir ziyafetin nefis artıkları duruyordu.",
             "sumptuous remnants | Paha biçilmez / nefis artıklar."),
            ("There were delicate French cheeses, rich pastry pastries, and crystal dishes filled with candied fruits.",
             "Nefis Fransız peynirleri, zengin hamur tatlıları ve şekerlemeli meyvelerle dolu kristal tabaklar vardı.",
             "candied fruits | Şekerlemeli / kristalize meyveler."),
            ("The country mouse believed he had entered an earthly paradise of unimaginable delights.",
             "Kır faresi akıl almaz zevklerle dolu bir yeryüzü cennetine adım attığına inandı.",
             "earthly paradise | Yeryüzü cenneti."),
            ("Just as they were tasting some sweet fig cake, the heavy doors burst open violently.",
             "Tam tatlı bir incirli keki tadıyorlardı ki ağır kapılar şiddetle ardına kadar açıldı.",
             "burst open | Hızla ve gürültüyle açılmak."),
            ("Two ferocious mastiffs bounded into the room, barking loudly and baring their enormous fangs.",
             "Odaya iki yırtıcı çoban köpeği daldı; avaz avaz havlayarak koca dişlerini gösterdiler.",
             "mastiffs | İri bekçi/çoban köpekleri; 'fangs' sivri dişler."),
            ("The terrified mice scrambled across the slippery floor in desperate search of a hiding place.",
             "Dehşete düşen fareler kaygan zemin üzerinde can havliyle bir sığınak arayarak kaçıştılar.",
             "scrambled | Can havliyle koşuşmak."),
            ("They squeezed into a tiny, narrow crack in the wainscot, barely escaping the snapping jaws.",
             "Köpeklerin kapanan çenelerinden kıl payı kurtularak ahşap kaplamadaki küçücük, dar bir yarığa sıkıştılar.",
             "wainscot | Ahşap duvar kaplaması; 'barely escaping' kıl payı kurtularak."),
            ("Trembling with sheer fright, they crouched in darkness, scarcely daring to draw breath.",
             "Katıksız bir korkuyla titreyerek nefes almaya bile neredeyse cesaret edemeden karanlıkta sindiler.",
             "crouched | Sinmek, çömelmek."),
            ("When the barking beasts finally departed, the country mouse crept out toward the exit.",
             "Havlayan canavarlar nihayet ayrıldığında, kır faresi çıkışa doğru sinsice süründü.",
             "crept out | Dışarı doğru sessizce süzülmek."),
            ("'Farewell, dear cousin,' he whispered, 'enjoy your lavish dainties amidst terrifying perils.'",
             "Fısıldayarak, 'Elveda sevgili kuzen,' dedi, 'korkunç tehlikelerin ortasında o lüks lezzetlerinin tadını çıkar.'",
             "lavish dainties | Lüks ikramlar / lezzetler."),
            ("A humble crust of bread eaten in peace is far better than a banquet shadowed by fear.",
             "Huzur içinde yenen mütevazı bir ekmek kabuğu, korkunun gölgesindeki bir ziyafetten çok daha evladır.",
             "shadowed by fear | Korkuyla gölgelenmiş.")
        ],
        "vocab_focus": [
            ("hospitable", "misafirperver, cömert"),
            ("nibbled daintily", "kibarca kemirdi"),
            ("stately mansion", "görkemli malikane"),
            ("sumptuous", "paha biçilmez, nefis"),
            ("mastiffs", "iri bekçi köpekleri"),
            ("wainscot", "ahşap duvar kaplaması"),
            ("crouched", "korkuyla sindi"),
            ("lavish dainties", "lüks ikramlar/lezzetler")
        ]
    },

    # PAGE 7: The Crow and the Pitcher
    {
        "page_no": 7,
        "title": "The Crow and the Pitcher",
        "tr_title": "Karga ile Su Testisi",
        "sentences": [
            ("During a severe drought when rivers ran dry, a thirsty crow flew across the parched plains.",
             "Nehirlerin kuruduğu şiddetli bir kuraklık esnasında, susamış bir karga kavrulmuş ovalar üzerinde uçuyordu.",
             "severe drought | Şiddetli kuraklık; 'parched plains' kavrulmuş ovalar."),
            ("He had not found a single drop of moisture for many hours, and his strength was rapidly failing.",
             "Saatlerdir tek bir damla bile nem bulamamıştı ve takati hızla tükeniyordu.",
             "failing | Tükenmek, zayıflamak."),
            ("As he hovered over an abandoned farmhouse garden, he spied a tall earthenware pitcher.",
             "Terk edilmiş bir çiftlik bahçesinin üzerinde süzülürken uzun toprak bir testi fark etti.",
             "earthenware pitcher | Toprak/kilden yapılmış su testisi."),
            ("With a flutter of hopeful wings, he alighted upon the narrow rim to inspect its contents.",
             "Umut dolu kanat çırpışlarıyla, içindekileri kontrol etmek için dar kenarın üzerine kondu.",
             "narrow rim | Dar kenar/ağız; 'inspect' incelemek."),
            ("Peering down into the deep vessel, he saw a small quantity of clear water at the bottom.",
             "Derin kabın içine doğru baktığında, dibinde az miktarda berrak su olduğunu gördü.",
             "peering down | Aşağıya dikkatle bakmak; 'vessel' kap, çanak."),
            ("Eagerly, he thrust his black beak inside, straining with all his might to reach the liquid.",
             "Bütün gücüyle sıvıya ulaşmaya çabalayarak siyah gagasını hevesle içeri daldırdı.",
             "straining | Gayretle çabalamak, zorlamak."),
            ("Alas, the neck of the pitcher was too narrow and the water level was far too low.",
             "Heyhat, testinin boynu çok dardı ve su seviyesi fazlasıyla alçaktaydı.",
             "narrow neck | Dar boyun."),
            ("No matter how hard he stretched his neck, his beak remained an inch above the surface.",
             "Boynunu ne kadar uzatırsa uzatsın, gagası su yüzeyinin bir parmak yukarısında kaldı.",
             "an inch above | Bir parmak/inç yukarısında."),
            ("He tried to overturn the heavy pitcher with his claws, but it stood heavy and immovable.",
             "Ağır testiyi pençeleriyle devirmeye çalıştı ama testi ağır ve yerinden oynamaz halde durdu.",
             "immovable | Kımıldamaz, yerinden oynamaz."),
            ("He next attempted to crack the sturdy clay walls with his sharp bill, but without success.",
             "Ardından keskin gagasıyla sağlam kil duvarları kırmaya teşebbüs etti, fakat nafile.",
             "sturdy clay | Sağlam kil/toprak."),
            ("Exhausted and despairing, the crow paused to collect his thoughts rather than panic.",
             "Tükenmiş ve umutsuzluğa düşmüş karga, paniğe kapılmak yerine düşüncelerini toparlamak için duraksadı.",
             "collect his thoughts | Düşüncelerini toparlamak."),
            ("Looking around the courtyard, his sharp gaze fell upon a heap of small, smooth pebbles.",
             "Avlunun etrafına bakarken keskin bakışları, küçük ve pürüzsüz çakıl taşlarından oluşan bir yığına ilişti.",
             "smooth pebbles | Pürüzsüz çakıl taşları."),
            ("A brilliant idea flashed through his clever mind like lightning in a dark sky.",
             "Karanlık gökteki bir şimşek gibi zekice bir fikir akıllı zihninde bir anda çaktı.",
             "flashed through his mind | Zihninde aniden belirmek."),
            ("He flew down, picked up a single pebble in his beak, and dropped it into the pitcher.",
             "Aşağıya uçtu, gagasına tek bir çakıl taşı aldı ve onu testinin içine bıraktı.",
             "picked up | Yerden almak, kaldırmak."),
            ("Plink! The small stone sank to the bottom, raising the water level by a tiny fraction.",
             "Tıpp! Küçük taş dibe battı ve su seviyesini ufacık bir miktar yükseltti.",
             "tiny fraction | Minicik bir pay / kesir."),
            ("Undeterred by the slow progress, the bird flew back and forth with tireless patience.",
             "Yavaş ilerlemeden yılmayan kuş, yorulmaz bir sabırla ileri geri uçtu durdu.",
             "undeterred | Yılmamış, vazgeçmemiş."),
            ("Pebble after pebble tumbled into the jar, gradually displacing the precious liquid upward.",
             "Çakıl taşı ardına çakıl taşı kabın içine yuvarlandı ve kıymetli sıvıyı yavaş yavaş yukarı doğru itti.",
             "displacing | Yerini değiştirmek / suyunu yükseltmek."),
            ("Finally, after dropping fifty stones, the cool water rose right up to the very brim.",
             "Nihayet elli taş attıktan sonra serin su tam da testinin ağzına kadar yükseldi.",
             "to the very brim | Ağzına / kenarına kadar."),
            ("The wise crow quenched his agonizing thirst thoroughly and saved his own life.",
             "Bilge karga o kahredici susuzluğunu doyasıya giderdi ve kendi hayatını kurtardı.",
             "quenched thirst | Susuzluğunu giderdi."),
            ("Ingenuity and patient perseverance will always overcome obstacles where mere brute force fails.",
             "Salt kaba kuvvetin yetersiz kaldığı yerde, pratik zeka ve sabırlı sebat daima engelleri aşacaktır.",
             "ingenuity | Hüner, yaratıcı zeka; 'perseverance' sebat.")
        ],
        "vocab_focus": [
            ("severe drought", "şiddetli kuraklık"),
            ("earthenware", "toprak/kilden yapılmış"),
            ("peering down", "aşağı dikkatle bakmak"),
            ("immovable", "kımıldatılamaz, sabit"),
            ("smooth pebbles", "pürüzsüz çakıllar"),
            ("undeterred", "yılmamış, azimli"),
            ("displacing", "yerini alarak yükseltmek"),
            ("ingenuity", "yaratıcı zeka, pratik akıl")
        ]
    },

    # PAGE 8: The North Wind and the Sun
    {
        "page_no": 8,
        "title": "The North Wind and the Sun",
        "tr_title": "Kuzey Rüzgarı ile Güneş",
        "sentences": [
            ("A heated dispute arose high in the heavens between the North Wind and the gentle Sun.",
             "Göklerin yükseklerinde Kuzey Rüzgarı ile nazik Güneş arasında hararetli bir münakaşa patlak verdi.",
             "heated dispute | Hararetli münakaşa / tartışma."),
            ("Each claimed to possess greater power and supremacy over the creatures of the earth below.",
             "Her ikisi de aşağıdaki dünya yaratıkları üzerinde daha büyük güce ve hakimiyete sahip olduğunu iddia ediyordu.",
             "supremacy | Üstünlük, hakimiyet."),
            ("'I can uproot giant forest trees and shatter stone buildings!' boomed the North Wind arrogantly.",
             "Kuzey Rüzgarı kibirle, 'Ben devasa orman ağaçlarını kökünden sökebilir ve taş binaları parçalayabilirim!' diye gürledi.",
             "uproot | Kökünden sökmek; 'boomed' gürledi."),
            ("'True strength does not rely on violence,' replied the Sun with a calm, benevolent smile.",
             "Güneş sakin ve şefkatli bir tebessümle, 'Hakiki kuvvet şiddete dayanmaz,' diye yanıt verdi.",
             "benevolent smile | Şefkatli, iyilik dolu tebessüm."),
            ("As they argued back and forth, they saw a solitary traveller walking along the highway.",
             "Onlar karşılıklı tartışırken, anayol boyunca yürüyen yalnız bir yolcu gördüler.",
             "solitary traveller | Yalnız yolcu."),
            ("He was wrapped securely in a thick, woollen cloak to protect himself from the chilly air.",
             "Kendisini ayazdan korumak için kalın yünlü bir paltoya sıkıca sarınmıştı.",
             "woollen cloak | Yünlü palto / pelerin."),
            ("'Let us settle our dispute by a practical test,' proposed the Sun serenely.",
             "Güneş sükunetle, 'Gelin uyuşmazlığımızı pratik bir sınavla çözelim,' diye teklif etti.",
             "settle dispute | Uyuşmazlığı / anlaşmazlığı çözmek."),
            ("'Whichever of us can cause that man to take off his cloak shall be acknowledged as the stronger.'",
             "'Şu adama paltosunu çıkarmayı hangimiz başarabilirse, o daha güçlü olarak kabul edilsin.'",
             "acknowledged as | Olarak kabul edilmek / tanınmak."),
            ("The North Wind agreed eagerly, demanding the privilege of making the first attempt.",
             "Kuzey Rüzgarı ilk denemeyi yapma ayrıcalığını talep ederek hevesle kabul etti.",
             "privilege | Ayrıcalık, imtiyaz."),
            ("He drew in a colossal breath and blew a furious, howling gale against the unsuspecting traveller.",
             "Devasa bir nefes çekti ve hiçbir şeyden habersiz yolcuya doğru öfkeli, uğultulu bir fırtına üfledi.",
             "howling gale | Uğultulu fırtına / bora."),
            ("The icy blast tore furiously at the heavy garment, howling through the leafless trees.",
             "Buz gibi fırtına yapraksız ağaçlarda uğuldayarak ağır giysiyi öfkeyle çekiştirdi.",
             "tore furiously | Öfkeyle çekiştirmek."),
            ("Dust swirled violently into the air, and freezing raindrops slashed against the man's face.",
             "Havada tozlar şiddetle girdaplandı ve dondurucu yağmur damlaları adamın yüzünü kamçıladı.",
             "slashed against | Kamçılamak, çarpmak."),
            ("Yet the harder the angry wind blew, the tighter the traveller wrapped his cloak around his shivering body.",
             "Fakat öfkeli rüzgar ne kadar sert eserse, yolcu titreyen bedenine paltosunu o kadar sıkı sardı.",
             "the harder ... the tighter | Ne kadar sert... o kadar sıkı (orantı yapısı)."),
            ("He drew the sturdy collar high around his ears and buttoned every clasp securely.",
             "Sağlam yakayı kulaklarının etrafına kadar çekti ve her bir kopçayı sıkıca ilikledi.",
             "buttoned every clasp | Her kopçayı / düğmeyi iliklemek."),
            ("Exhausted and furious at his failure, the North Wind finally gave up the hopeless contest.",
             "Başarısızlığı karşısında tükenen ve öfkeden köpüren Kuzey Rüzgarı nihayet bu umutsuz mücadeleden vazgeçti.",
             "gave up | Vazgeçmek, pes etmek."),
            ("Then the gentle Sun emerged from behind the dark storm clouds, shining with mild warmth.",
             "Ardından nazik Güneş kara fırtına bulutlarının ardından belirdi ve tatlı bir ılıkla parıldamaya başladı.",
             "mild warmth | Tatlı, ılıman sıcaklık."),
            ("The tempest ceased completely, and sweet rays of golden light illuminated the pleasant countryside.",
             "Fırtına tamamen dindi ve altın ışığın tatlı huzmeleri güzel kırsalı aydınlattı.",
             "tempest ceased | Fırtına dindi."),
            ("The grateful traveller soon began to feel comfortably warm after the bitter storm.",
             "Minnettar yolcu, o dondurucu fırtınanın ardından çok geçmeden kendini rahatlatıcı bir sıcaklıkta hissetti.",
             "comfortably warm | Rahatlatıcı derecede ılık."),
            ("Finding the heat increasing with every step, he gladly unbuttoned his cloak and threw it over his arm.",
             "Her adımda ısının arttığını görünce memnuniyetle paltosunu açtı ve onu kolunun üzerine attı.",
             "unbuttoned | Düğmelerini çözdü."),
            ("Persuasion and gentle warmth accomplish far more than harsh bluster and raw violence ever can.",
             "Tatlı dille ikna ve nazik sıcaklık, kaba gürültü ve çıplak şiddetin başarabileceğinden çok daha fazlasını başarır.",
             "bluster | Kaba tehdit, boş gürültü; 'persuasion' ikna.")
        ],
        "vocab_focus": [
            ("heated dispute", "hararetli tartışma"),
            ("uproot", "kökünden sökmek"),
            ("benevolent", "hayırhah, şefkatli"),
            ("howling gale", "uğultulu şiddetli fırtına"),
            ("slashed", "kamçıladı, savruldu"),
            ("tempest", "şiddetli fırtına"),
            ("unbuttoned", "düğmelerini çözdü"),
            ("persuasion", "ikna etme, tatlı dil")
        ]
    },

    # PAGE 9: The Dog and His Reflection
    {
        "page_no": 9,
        "title": "The Dog and His Reflection",
        "tr_title": "Köpek ve Sudaki Gölgesi",
        "sentences": [
            ("A hungry hound was trotting happily homeward through the village on a bright spring morning.",
             "Aç bir av köpeği, pırıl pırıl bir bahar sabahında köyün içinden keyifle evine doğru koşturuyordu.",
             "trotting | Tırıs gitmek, hafif koşmak; 'hound' av köpeği."),
            ("In his strong jaws he carried a magnificent, juicy piece of meat given to him by a generous butcher.",
             "Güçlü çenesinde, cömert bir kasap tarafından kendisine verilmiş muhteşem, sulu bir et parçası taşıyordu.",
             "juicy piece of meat | Sulu et parçası."),
            ("He held his head high with immense satisfaction, eager to devour his delicious prize in private.",
             "Lezzetli ödülünü tenha bir yerde yiyip bitirmek için can atarak başını muazzam bir tatminle dik tutuyordu.",
             "in private | Baş başa, tenha bir yerde."),
            ("On his journey, he came to a narrow wooden footbridge spanning a crystal-clear brook.",
             "Yolculuğu sırasında berrak bir dereyi aşan dar, ahşap bir yaya köprüsüne geldi.",
             "footbridge | Yaya köprüsü; 'spanning' üzerinden geçen."),
            ("The surface of the stream was as smooth and transparent as a polished silver mirror.",
             "Suyun yüzeyi cilalı bir gümüş ayna kadar pürüzsüz ve şeffaftı.",
             "transparent | Saydam, şeffaf."),
            ("As the dog stepped onto the bridge, he accidentally glanced down into the quiet water below.",
             "Köpek köprüye adım attığında kazara aşağıdaki sakin suya doğru bir göz attı.",
             "glanced down | Aşağıya göz atmak."),
            ("To his utter astonishment, he saw another dog looking back up at him from the depths.",
             "Büyük bir şaşkınlıkla, derinliklerden kendisine yukarı doğru bakan bir başka köpek gördü.",
             "utter astonishment | Katıksız hayret / şaşkınlık."),
            ("The mysterious stranger also held a large piece of succulent meat clamped firmly between his teeth.",
             "Bu gizemli yabancı da dişleri arasına sıkıca kenetlenmiş iri ve sulu bir et parçası tutuyordu.",
             "clamped firmly | Sıkıca kenetlenmiş / tutulmuş."),
            ("Foolishly, the greedy hound did not realize that he was merely observing his own reflection.",
             "Açgözlü köpek ahmakça, yalnızca kendi aksini seyretmekte olduğunu fark edemedi.",
             "reflection | Yansıma, akis; 'greedy' açgözlü."),
            ("In his envious mind, the meat in the other dog's mouth appeared twice as large as his own.",
             "Onun kıskanç zihninde, diğer köpeğin ağzındaki et kendi etinden iki kat daha büyük görünüyordu.",
             "envious mind | Kıskanç, haset zihin."),
            ("'Why should that creature possess a finer feast than mine?' he thought with sudden covetousness.",
             "Ani bir tamahkarlıkla, 'Neden şu mahluk benimkinden daha enfes bir ziyafete sahip olsun ki?' diye düşündü.",
             "covetousness | Açgözlülük, tamahkarlık."),
            ("Overcome by uncontrollable greed, he resolved to seize the larger portion for himself immediately.",
             "Dizginlenemez bir hırsın etkisine kapılarak o daha büyük payı derhal kendine kapmaya karar verdi.",
             "seize | Ele geçirmek, zorla kapmak."),
            ("He growled menacingly, baring his sharp white teeth at the watery apparition below.",
             "Aşağıdaki sulu hayalete keskin beyaz dişlerini göstererek tehditkar bir şekilde hırladı.",
             "menacingly | Tehditkar biçimde; 'apparition' hayalet, görüntü."),
            ("The image in the stream mimicked his angry snarl with equal ferocity.",
             "Sudaki görüntü onun öfkeli hırıltısını aynı vahşilikle taklit etti.",
             "mimicked | Taklit etti; 'ferocity' vahşilik."),
            ("Without pausing to consider the consequences, he snapped violently at the shadow dog.",
             "Sonuçları düşünmek için tek bir an bile duraksamadan, gölge köpeğe doğru şiddetle dişlerini geçirdi.",
             "snapped violently | Şiddetle diş atmak / ısırmak."),
            ("The instant his jaws parted, his own precious piece of meat slipped from his grip.",
             "Çenesi açıldığı anda, kendi kıymetli et parçası ağzından kayıp düştü.",
             "slipped from his grip | Tutuşundan / ağzından kayıp düşmek."),
            ("Splash! It plummeted directly into the deep pool and sank to the muddy bottom forever.",
             "Şılapp! Doğrudan derin havuza çakıldı ve sonsuza dek çamurlu dibe battı.",
             "plummeted | Hızla aşağı düşmek / çakılmak."),
            ("The splashing ripples distorted the surface, and the phantom dog vanished instantly from sight.",
             "Sıçrayan dalgacıklar yüzeyi bozdu ve hayali köpek anında gözden kayboldu.",
             "phantom dog | Hayali / gölge köpek; 'distorted' biçimini bozdu."),
            ("The crestfallen animal was left with nothing but his own bitter remorse and an empty belly.",
             "Boynu bükük hayvan, kendi acı pişmanlığı ve boş bir karından başka hiçbir şeyle kalakaldı.",
             "crestfallen | Boynu bükük, hayal kırıklığına uğramış; 'remorse' pişmanlık."),
            ("He who covets what belongs to another risks forfeiting all the blessings he already possesses.",
             "Başkasının elindekine göz diken kişi, halihazırda sahip olduğu bütün nimetleri kaybetmeyi göze alır.",
             "forfeiting | Kaybetmek, elinden kaçırmak; 'covets' göz dikmek.")
        ],
        "vocab_focus": [
            ("trotting", "hafif koşar adım yürümek"),
            ("footbridge", "yaya köprüsü"),
            ("clamped", "sıkıca kenetlenmiş"),
            ("covetousness", "açgözlülük, tamahkarlık"),
            ("menacingly", "tehditkarca"),
            ("plummeted", "dikine çakıldı/düştü"),
            ("crestfallen", "boynu bükük, perişan"),
            ("forfeiting", "hakkını kaybetmek, feda etmek")
        ]
    },

    # PAGE 10: The Goose that Laid the Golden Eggs
    {
        "page_no": 10,
        "title": "The Golden Egg",
        "tr_title": "Altın Yumurtlayan Kaz",
        "sentences": [
            ("A poor country cottager and his wife lived in a modest hut beside a sparkling meadow.",
             "Yoksul bir köylü ile karısı, pırıl pırıl bir çayırın kenarındaki mütevazı bir kulübede yaşarlardı.",
             "cottager | Kulübede yaşayan köylü."),
            ("They possessed very little worldly wealth, owning only a small vegetable garden and a solitary goose.",
             "Küçük bir sebze bahçesi ve tek bir kazdan başka bir şeye sahip olmayarak dünyevi zenginlikten pek nasiplenmemişlerdi.",
             "solitary goose | Tek başına bir kaz."),
            ("One fortunate morning, the cottager went out to the coop to gather the daily eggs.",
             "Uğurlu bir sabah köylü, günlük yumurtaları toplamak için kümese çıktı.",
             "coop | Kümes; 'fortunate' uğurlu, talihli."),
            ("To his utter astonishment, he found a yellow egg that felt remarkably heavy in his palm.",
             "Büyük bir hayret içinde, avucunda olağanüstü ağır hissettiren sarı bir yumurta buldu.",
             "in his palm | Avucunun içinde."),
            ("Suspecting that a prank had been played upon him, he examined the object under the bright sunlight.",
             "Kendisine bir muziplik yapıldığından şüphelenerek nesneyi parlak güneş ışığı altında inceledi.",
             "suspecting | Şüphelenerek."),
            ("He rubbed the smooth surface against a whetstone and discovered that it was composed of pure gold.",
             "Pürüzsüz yüzeyi bir bileği taşına sürttü ve onun som altından oluştuğunu keşfetti.",
             "whetstone | Bileği taşı; 'composed of' den oluşmuş."),
            ("He hurried indoors with wild excitement to show the glittering treasure to his astonished wife.",
             "Parıldayan hazineyi şaşkın karısına göstermek için çılgın bir heyecanla içeri koştu.",
             "glittering treasure | Parıldayan hazine."),
            ("Every succeeding morning brought the identical miracle, for the bird produced another golden egg daily.",
             "Sonraki her sabah aynı mucizeyi getirdi; zira kuş her gün bir başka altın yumurta üretiyordu.",
             "succeeding morning | Birbirini takip eden sabahlar."),
            ("The cottager carried the precious eggs to the town market, selling them for exorbitant sums of money.",
             "Köylü kıymetli yumurtaları kasaba pazarına taşıdı ve onları fahiş fiyatlara sattı.",
             "exorbitant sums | Fahiş / çok yüksek miktarlar."),
            ("Within a few short months, the once destitute peasants had accumulated immense riches.",
             "Birkaç kısa ay içinde, bir zamanların yoksul köylüleri muazzam bir servet biriktirmişti.",
             "destitute | Muhtaç, sefil; 'accumulated' biriktirmişti."),
            ("They purchased luxurious garments, expanded their estate, and lived in unprecedented splendour.",
             "Lüks giysiler satın aldılar, mülklerini genişlettiler ve eşi benzeri görülmemiş bir debdebe içinde yaşadılar.",
             "unprecedented splendour | Görülmemiş ihtişam."),
            ("However, as their wealth multiplied, an insatiable avarice began to poison their simple minds.",
             "Lakin zenginlikleri katlandıkça, doymak bilmez bir hırs ve açgözlülük sade zihinlerini zehirlemeye başladı.",
             "insatiable avarice | Doymak bilmez açgözlülük / ihtiras."),
            ("They grew impatient with receiving merely one single golden egg every twenty-four hours.",
             "Her yirmi dört saatte yalnızca tek bir altın yumurta almaktan ötürü sabırsızlandılar.",
             "grew impatient | Sabırsızlanmak."),
            ("'Surely the interior of this marvelous fowl must be stuffed entirely with solid gold!' said the husband.",
             "Koca, 'Hiç şüphesiz bu harikulade kuşun içi tamamen som altınla tıka basa dolu olmalı!' dedi.",
             "marvelous fowl | Harikulade kümes hayvanı / kuş."),
            ("'If we slay the bird at once,' agreed the wife, 'we can seize the entire fortune in an instant.'",
             "Karısı, 'Kuşu hemen şimdi kesersek,' diyerek onayladı, 'bütün serveti bir anda ele geçirebiliriz.'",
             "slay | Katletmek, kesmek."),
            ("Blind to reason and devoured by ruthless greed, they fetched a sharp butcher's knife.",
             "Akıldan yoksun kalarak ve acımasız hırsın pençesinde kıvranarak keskin bir kasap bıçağı getirdiler.",
             "ruthless greed | Acımasız açgözlülük."),
            ("They cruelly slaughtered the miraculous goose and cut its body open without hesitation.",
             "Mucizevi kazı gaddarca kestiler ve hiç tereddüt etmeden gövdesini yardılar.",
             "without hesitation | Tereddüt etmeden; 'slaughtered' kestiler."),
            ("To their horror and dismay, they found its internal anatomy identical to that of any common goose.",
             "Dehşet ve hüsranla, iç anatomisinin herhangi bir sıradan kazınkiyle tamamen aynı olduğunu gördüler.",
             "dismay | Hüsran, büyük hayal kırıklığı."),
            ("There was no store of hidden treasure within, and the source of their daily wealth was gone forever.",
             "İçinde hiçbir gizli hazine deposu yoktu ve günlük zenginliklerinin kaynağı sonsuza dek yok olup gitmişti.",
             "store of treasure | Hazine deposu."),
            ("Those who grasp greedily after sudden riches often destroy the steady stream of their existing fortune.",
             "Ani zenginliklerin peşinde açgözlülükle koşanlar, genellikle ellerindeki mevcut servetin istikrarlı akışını da yok ederler.",
             "steady stream | İstikrarlı akış; 'grasp greedily' açgözlülükle sarılmak.")
        ],
        "vocab_focus": [
            ("cottager", "kulübede yaşayan köylü"),
            ("whetstone", "bileği taşı"),
            ("exorbitant", "fahiş, haddinden fazla"),
            ("destitute", "yoksul, muhtaç"),
            ("insatiable avarice", "doymak bilmez açgözlülük"),
            ("slay", "kesmek, katletmek"),
            ("slaughtered", "gaddarca kesti"),
            ("dismay", "hüsran, derin üzüntü")
        ]
    },

    # PAGE 11: The Milkmaid and Her Pail
    {
        "page_no": 11,
        "title": "The Milkmaid and Her Pail",
        "tr_title": "Sütçü Kız ve Kovası",
        "sentences": [
            ("Patty, the cheerful milkmaid, was carrying a heavy pail of foaming milk balanced upon her head.",
             "Neşeli sütçü kız Patty, kafasında dengede duran köpüklü süt dolu ağır bir kovayı taşıyordu.",
             "foaming milk | Köpüklü süt; 'balanced' dengelenmiş."),
            ("She walked gracefully down the meadow path, heading toward the busy market in the village.",
             "Köydeki kalabalık pazara doğru ilerleyerek çayır patikasında zarifçe yürüyordu.",
             "heading toward | '... doğru yol almak / yönelmek' kalıbıdır."),
            ("As she strolled along, her active imagination began weaving elaborate daydreams of future prosperity.",
             "Yol boyunca ilerlerken, canlı hayal gücü gelecekteki refaha dair incelikli gündüz düşleri örmeye başladı.",
             "elaborate daydreams | İncelikli gündüz düşleri / hayaller."),
            ("'The cream from this rich milk will fetch a very handsome price from the dairy merchant,' she thought.",
             "'Bu yağlı sütün kaymağı mandıracıdan son derece dolgun bir fiyat getirecektir,' diye düşündü.",
             "fetch a handsome price | İyi / dolgun bir fiyat getirmek."),
            ("'With the coins I earn, I shall immediately purchase at least three hundred choice eggs from farmer Brown.'",
             "'Kazanacağım paralarla çiftçi Brown'dan derhal en az üç yüz adet seçme yumurta satın alacağım.'",
             "choice eggs | Seçme, kaliteli yumurtalar."),
            ("'Allowing for those that may prove addled, I am certain to hatch more than two hundred and fifty chicks.'",
             "'Cılk çıkabilecek olanları hesaba katsam bile, en az iki yüz elli civciv çıkaracağımdan eminim.'",
             "addled | Cılk çıkmış, bozulmuş; 'hatch' kuluçkadan çıkmak."),
            ("'I shall tend the tiny fledglings with extraordinary care, feeding them on the finest grain.'",
             "'Minik palazlara olağanüstü bir özenle bakacağım; onları en kaliteli tahılla besleyeceğim.'",
             "fledglings | Palazlar, yavru kuşlar."),
            ("'By Christmas time, when poultry is in the highest demand, they will be fat, plump fowls ready for market.'",
             "'Kümes hayvanlarına talebin en yüksek olduğu Noel vaktinde, onlar pazar için hazır, semiz ve tombul kuşlar olacak.'",
             "in highest demand | En yüksek talepte; 'plump' tombul."),
            ("'Selling my chickens at the peak of the season will bring me a substantial purse of shining silver.'",
             "'Tavuklarımı mevsimin doruk noktasında satmak bana parıldayan gümüşlerle dolu yüklü bir kese kazandıracak.'",
             "substantial purse | Yüklü, dolgun kese."),
            ("'With that money, I shall buy myself a new gown of vivid party-green silk.'",
             "'O parayla kendime göz alıcı parti yeşili ipekten yeni bir balo elbisesi alacağım.'",
             "vivid silk | Göz alıcı, canlı ipek."),
            ("'I shall also purchase matching satin ribbons to weave delightfully through my dark hair.'",
             "'Koyu saçlarımın arasına neşeyle örmek için elbisenin rengine uygun saten kurdeleler de alacağım.'",
             "matching ribbons | Uyumlu kurdeleler."),
            ("'Thus attired, I shall attend the grand May Day festival in the village square.'",
             "'Böyle kuşanıp donanmış olarak, köy meydanındaki büyük 1 Mayıs festivaline katılacağım.'",
             "thus attired | Bu şekilde kuşanmış / giyinmiş halde."),
            ("'Every young lad in the parish will eagerly crave the honour of dancing with me.'",
             "'Bütün nahiyedeki her genç delikanlı benimle dans etme şerefine erişmek için can atacak.'",
             "crave the honour | Şerefine nail olmayı arzulamak."),
            ("'Polly Shaw will turn pale green with sheer envy at my magnificent appearance.'",
             "'Polly Shaw benim muazzam görünüşüm karşısında saf bir hasetten sapsarı kesilecek.'",
             "sheer envy | Katıksız haset / kıskançlık."),
            ("'Young farmer Thomas will step forward, begging humbly for my hand for the festive reel.'",
             "'Genç çiftçi Thomas öne çıkıp şenlik dansı için elimi tutmak maksadıyla mahcupça yalvaracak.'",
             "festive reel | Şenlik dansı / horonu."),
            ("'But I shall simply toss my head haughtily and tell him that I have far better suitors.'",
             "'Fakat ben yalnızca başımı kibirle geriye atacağım ve ona çok daha iyi taliplerim olduğunu söyleyeceğim.'",
             "toss my head | Başını gururla geriye atmak; 'suitors' talipler."),
            ("Carried away by the vivid drama of her thoughts, she actually tossed her head in reality.",
             "Düşüncelerinin canlı dramasına kendini kaptıran kız, hakikaten başını geriye doğru savuruverdi.",
             "carried away | Kendini kaptırmak."),
            ("Instantly, the heavy pail slipped from its perch and crashed down upon the dusty roadway.",
             "Kova anında durduğu yerden kaydı ve tozlu yolun üzerine gürültüyle çakıldı.",
             "crashed down | Gürültüyle yere inmek."),
            ("The white milk gushed across the stony gravel, soaking into the soil until not a drop remained.",
             "Beyaz süt taşlı çakılların üzerine fışkırdı ve tek bir damlası bile kalmayana dek toprağa süzüldü.",
             "gushed across | Üzerine fışkırmak, saçılmak."),
            ("Do not count your chickens before they are hatched, lest pride and premature triumph end in ruin.",
             "Tavuklarınızı yumurtadan çıkmadan önce saymayın; yoksa gurur ve erken zafer sevinci hüsranla biter.",
             "count chickens before hatched | 'Doğmamış çocuğa don biçmek' atasözünün İngilizce karşılığıdır.")
        ],
        "vocab_focus": [
            ("foaming", "köpüren, köpüklü"),
            ("elaborate", "incelikli, ayrıntılı"),
            ("addled", "cılk çıkmış, bozulmuş"),
            ("fledglings", "yavru kuşlar, palazlar"),
            ("substantial purse", "dolgun para kesesi"),
            ("thus attired", "böyle kuşanmış vaziyette"),
            ("crave", "şiddetle arzulamak"),
            ("toss head", "başını kibirle geriye atmak")
        ]
    },

    # PAGE 12: The Wolf in Sheep's Clothing
    {
        "page_no": 12,
        "title": "Wolf in Sheep's Clothing",
        "tr_title": "Koyun Postundaki Kurt",
        "sentences": [
            ("A cunning wolf had long prowled around a prosperous sheepfold, seeking an opportunity to seize a meal.",
             "Kurnaz bir kurt, bir ziyafet kapmak için fırsat kollayarak bereketli bir ağılın etrafında uzun süre kol gezmişti.",
             "prowled | Sinsice kol gezmek; 'sheepfold' koyun ağılı."),
            ("The vigilant shepherd and his alert hound kept watch night and day, making direct assault impossible.",
             "Uyanık çoban ve tetikteki av köpeği gece gündüz nöbet tutuyor, doğrudan saldırıyı imkansız kılıyordu.",
             "vigilant | Uyanık, tetikte; 'assault' saldırı."),
            ("Every attempt the predator made had been repelled with stinging stones and ferocious barking.",
             "Yırtıcının yaptığı her girişim acımasız taşlar ve vahşi havlamalarla püskürtülmüştü.",
             "repelled | Püskürtülmüş, geri püskürtülmüş."),
            ("Realizing that force alone was inadequate, the treacherous beast resorted to treacherous deception.",
             "Kaba kuvvetin tek başına yetersiz kaldığını anlayan hain canavar, sinsi bir hileye başvurdu.",
             "treacherous deception | Haince hile / aldatmaca."),
            ("Near the edge of the meadow, he discovered the complete fleece of a sheep that had been flayed.",
             "Çayırın kenarına yakın bir yerde, yüzülmüş bir koyunun eksiksiz postunu buldu.",
             "fleece | Koyun yapağısı, postu; 'flayed' derisi yüzülmüş."),
            ("He carefully drew the woollen hide over his gaunt body, fastening it securely across his back.",
             "Yünlü postu zayıf bedeninin üzerine dikkatle çekti ve sırtından sıkıca tutturdu.",
             "gaunt body | Zayıf, bir deri bir kemik beden."),
            ("He concealed his pointed snout beneath the soft wool and practiced walking with a gentle, sheepish gait.",
             "Sivri burnunu yumuşak yünün altına gizledi ve koyunsu, uysal bir yürüyüşle adım atma talimi yaptı.",
             "sheepish gait | Koyun gibi uysal yürüyüş; 'snout' burun."),
            ("Thus disguised, he slipped unnoticed into the pasture where the flock was grazing quietly.",
             "Böylece kılık değiştirerek, sürünün sakince otladığı otlağa hiç fark edilmeden süzüldü.",
             "pasture | Otlak, mera; 'disguised' kılık değiştirmiş."),
            ("The unsuspecting lambs mistook him for one of their own kin and grazed peacefully beside him.",
             "Hiçbir şeyden şüphelenmeyen kuzular onu kendi soylarından biri sandılar ve yanında huzurla otladılar.",
             "unsuspecting lambs | Masum / şüphelenmeyen kuzular; 'kin' akraba, soy."),
            ("Even the vigilant shepherd was completely deceived by the remarkably convincing masquerade.",
             "Uyanık çoban bile bu fevkalade ikna edici maskeli baloya tamamen aldandı.",
             "masquerade | Maskeleme, aldatıcı kılık."),
            ("When evening shadows lengthened, the shepherd led the entire flock into the secure enclosure.",
             "Akşam gölgeleri uzadığında çoban, bütün sürüyü korunaklı ağılın içine yönlendirdi.",
             "secure enclosure | Güvenli çit / ağıl."),
            ("He locked the heavy wooden gate and retired peacefully to his cottage for a night of untroubled rest.",
             "Ağır ahşap kapıyı kilitledi ve deliksiz bir gece uykusu için kulübesine huzurla çekildi.",
             "untroubled rest | Dertsiz, dingin dinlenme."),
            ("Inside the fold, the treacherous wolf gloated silently over the feast awaiting him at midnight.",
             "Ağılın içinde hain kurt, gece yarısında kendisini bekleyen ziyafetin hayaliyle sessizce kıs kıs güldü.",
             "gloated silently | Sessizce kıs kıs gülmek / zevkten dört köşe olmak."),
            ("'What a splendid triumph of intellect over muscle!' thought the wicked predator.",
             "Kötü niyetli yırtıcı, 'Zekanın kas gücüne karşı ne muhteşem bir zaferi!' diye düşündü.",
             "intellect over muscle | Zekanın kas gücüne üstünlüğü."),
            ("However, later that night, the master of the house arrived to inspect the farm.",
             "Fakat o gecenin ilerleyen saatlerinde, çiftliğin efendisi çiftliği teftiş etmek için çıkageldi.",
             "inspect the farm | Çiftliği denetlemek / teftiş etmek."),
            ("Wanting meat to prepare a substantial meal for his guests, he entered the sheepfold in the pitch-dark.",
             "Misafirlerine doyurucu bir yemek hazırlamak için et isteyerek zifiri karanlıkta ağıla girdi.",
             "pitch-dark | Zifiri karanlık; 'substantial meal' doyurucu yemek."),
            ("He reached out with a stout hook and seized the first animal that came within his grasp.",
             "Sağlam bir çengelle uzandı ve elinin erdiği ilk hayvanı yakaladı.",
             "stout hook | Sağlam kanca / çengel."),
            ("It was the wolf, still clad in the soft woollen fleece of the innocent sheep.",
             "Yakalanan, masum koyunun yumuşak yünlü postuna bürünmüş haldeki kurdun ta kendisiydi.",
             "clad in | Bürünmüş, giyinmiş."),
            ("Before the beast could utter a single snarl, the knife descended and killed him on the spot.",
             "Canavar tek bir hırıltı bile çıkaramadan bıçak indi ve onu oracıkta öldürdü.",
             "on the spot | Oracıkta, o anda."),
            ("Those who practice wicked deception frequently fall victims to the very snares they set for others.",
             "Kötücül hilelere başvuranlar, sıklıkla başkaları için kurdukları tuzakların kurbanı olurlar.",
             "snares | Tuzaklar, kapanlar.")
        ],
        "vocab_focus": [
            ("prowled", "sinsice kol gezdi"),
            ("vigilant", "uyanık, tetikte"),
            ("treacherous", "haince, sinsi"),
            ("fleece", "koyun yapağısı, post"),
            ("sheepish gait", "uysal koyun yürüyüşü"),
            ("masquerade", "maskeli aldatmaca"),
            ("gloated", "kötü niyetle sevindi"),
            ("snares", "tuzaklar, kapanlar")
        ]
    },

    # PAGE 13: The Oak and the Reeds
    {
        "page_no": 13,
        "title": "The Oak and the Reeds",
        "tr_title": "Meşe Ağacı ile Sazlıklar",
        "sentences": [
            ("A gigantic oak tree stood proudly on the bank of a swift, winding mountain stream.",
             "Hızlı ve kıvrımlı bir dağ deresinin kıyısında devasa bir meşe ağacı gururla yükseliyordu.",
             "gigantic | Devasa, muazzam; 'swift' hızlı, süratli."),
            ("Its immense trunk had withstood the changing seasons and ferocious tempests for over a hundred years.",
             "Kocaman gövdesi, yüz yılı aşkın bir süredir değişen mevsimlere ve vahşi fırtınalara göğüs germişti.",
             "withstood | Göğüs germek, direnmek; 'trunk' ağaç gövdesi."),
            ("Along the edge of the water below grew a cluster of slender, flexible green reeds.",
             "Aşağıda suyun kıyısı boyunca ince, esnek yeşil sazlıklardan oluşan bir küme bitmişti.",
             "slender and flexible | İnce ve esnek; 'reeds' sazlıklar."),
            ("The proud oak looked down with boundless condescension upon these frail water plants.",
             "Mağrur meşe, bu cılız su bitkilerine sınırsız bir tepeden bakışla yukarıdan baktı.",
             "frail | Narin, kırılgan, cılız."),
            ("'How exceedingly pitiful is your humble lot in life!' rumbled the majestic tree.",
             "Görkemli ağaç gürleyerek, 'Hayattaki mütevazı nasibiniz ne kadar da acınası!' dedi.",
             "pitiful lot | Acınası kader / pay."),
            ("'The slightest breath of air that scarce ruffles the water causes you to bow your heads.'",
             "'Su yüzeyini neredeyse hiç kırıştırmayan en hafif bir esinti bile başlarınızı öne eğmenize sebep oluyor.'",
             "scarce ruffles | Zar zor dalgalandırmak; 'bow heads' baş eğmek."),
            ("'Whereas I stand towering and immovable, defying the fiercest gales that rage across the heavens.'",
             "'Oysa ben göklerde kükreyen en azgın fırtınalara meydan okuyarak heybetli ve sarsılmaz biçimde ayakta duruyorum.'",
             "defying gales | Fırtınalara meydan okumak."),
            ("The reeds rustled gently in the afternoon breeze, whispering their modest reply.",
             "Sazlıklar ikindi esintisinde nazikçe hışırdayarak alçakgönüllü cevaplarını fısıldadılar.",
             "rustled gently | Nazikçe hışırdamak."),
            ("'Do not lament our humble nature, noble giant,' murmured their leader softly.",
             "Önderleri usulca, 'Bizim mütevazı tabiatımız için yas tutmayın asil dev,' diye fısıldadı.",
             "lament | Yas tutmak, hayıflanmak."),
            ("'The wind may bend us low, but it rarely breaks our supple stems.'",
             "'Rüzgar bizi yere kadar eğebilir ama esnek gövdelerimizi nadiren kırar.'",
             "supple stems | Bükülgen, esnek gövdeler/saplar."),
            ("'You resist the blast with stiff obstinacy, and that very stubbornness may prove your undoing.'",
             "'Siz ise fırtınaya katı bir inatla direniyorsunuz; tam da bu inatçılık sizin felaketiniz olabilir.'",
             "stiff obstinacy | Katı inatçılık; 'undoing' felaket, yıkım."),
            ("The mighty oak laughed contemptuously at what he regarded as a cowardly apology for weakness.",
             "Kudretli meşe, zayıflığın korkakça bir mazereti olarak gördüğü bu söze küçümsemeyle güldü.",
             "cowardly apology | Korkakça mazeret / savunma."),
            ("Suddenly, without warning, a terrifying hurricane roared out of the northern sky.",
             "Ansızın hiçbir uyarı olmaksızın, kuzey göğünden korkunç bir kasırga kükreyerek koptu.",
             "hurricane roared | Kasırga kükredi."),
            ("It lashed the forest with unprecedented fury, tearing branches and howling through the valley.",
             "Dalları koparıp vadide uğuldayarak eşi görülmemiş bir öfkeyle ormanı kamçıladı.",
             "lashed the forest | Ormanı kamçıladı."),
            ("The flexible reeds bowed flat against the water, allowing the furious blast to sweep harmlessly over them.",
             "Esnek sazlıklar suyun üzerine dümdüz eğilerek öfkeli fırtınanın üzerlerinden zararsızca geçmesine izin verdiler.",
             "bowed flat | Dümdüz eğilmek."),
            ("The colossal oak, on the other hand, braced its rigid limbs and fought the storm with furious pride.",
             "Devasa meşe ise diğer yandan kaskatı kollarını gerdi ve fırtınayla azgın bir gururla savaştı.",
             "rigid limbs | Kaskatı dallar / uzuvlar."),
            ("The hurricane redoubled its force, striking the unyielding trunk with devastating momentum.",
             "Kasırga gücünü ikiye katladı ve boyun eğmez gövdeye yıkıcı bir ivmeyle çarptı.",
             "unyielding trunk | Boyun eğmez, eğilmez gövde; 'redoubled' iki katına çıkardı."),
            ("With a deafening crash that shook the earth for miles, the mighty tree was torn up by its roots.",
             "Toprağı millerce sarsan sağır edici bir gürültüyle kudretli ağaç köklerinden söküldü.",
             "torn up by roots | Kökünden sökülüp atılmak."),
            ("When the tempest passed, the humble reeds stood upright once more, unharmed beneath the morning sun.",
             "Fırtına dindiğinde, mütevazı sazlıklar sabah güneşinin altında zarar görmeden yeniden dimdik ayaktaydılar.",
             "stood upright | Yeniden dimdik durmak."),
            ("Better to yield gracefully to inevitable necessity than to be shattered through rigid, stubborn pride.",
             "Katı ve inatçı bir gurur yüzünden paramparça olmaktansa, kaçınılmaz zorunluluğa zarafetle boyun eğmek çok daha iyidir.",
             "yield gracefully | Zarafetle boyun eğmek / esnemek.")
        ],
        "vocab_focus": [
            ("withstood", "göğüs gerdi, dayandı"),
            ("supple", "esnek, bükülgen"),
            ("stiff obstinacy", "katı inatçılık"),
            ("undoing", "felaket, yıkım"),
            ("hurricane", "kasırga"),
            ("lashed", "kamçıladı, savurdu"),
            ("unyielding", "boyun eğmez, eğilmez"),
            ("yield gracefully", "zarafetle boyun eğmek/esnemek")
        ]
    },

    # PAGE 14: Belling the Cat
    {
        "page_no": 14,
        "title": "Belling the Cat",
        "tr_title": "Kediye Çan Takmak",
        "sentences": [
            ("For many months, a community of mice had been terrorized by an extraordinarily cunning house cat.",
             "Aylardır bir fare cemaati, olağanüstü kurnaz bir ev kedisi tarafından terörize ediliyordu.",
             "terrorized | Dehşete düşürülmüş, korku salınmış."),
            ("The feline predator moved with such silent stealth that nobody ever heard her velvety footsteps approaching.",
             "Bu kedi avcı öyle sessiz bir gizlilikle hareket ediyordu ki hiç kimse kadife ayak seslerinin yaklaştığını duymazdı.",
             "silent stealth | Sessiz gizlilik; 'velvety footsteps' kadife ayak sesleri."),
            ("She sprang from dark shadows without warning, seizing helpless victims day after day.",
             "Hiçbir uyarı olmaksızın karanlık gölgelerden fırlıyor, günbegün çaresiz kurbanları yakalıyordu.",
             "seizing victims | Kurbanları yakalamak."),
            ("The terrified mice scarcely dared to venture out of their holes, even to forage for essential food.",
             "Dehşete düşen fareler, temel yiyecekleri aramak için bile deliklerinden dışarı çıkmaya neredeyse cesaret edemiyorlardı.",
             "forage for food | Yiyecek aramak."),
            ("Realizing that their very survival was at stake, they summoned a general council to debate the crisis.",
             "Bizzat hayatta kalışlarının pamuk ipliğine bağlı olduğunu fark ederek krizi müzakere etmek üzere genel bir konsey topladılar.",
             "at stake | Tehlikede, pamuk ipliğinde; 'summoned council' kurul toplamak."),
            ("They assembled in the safety of a dark cellar while the dreaded cat was asleep on the hearth.",
             "Korkulan kedi ocakta uyurken onlar karanlık bir mahzenin emniyetinde bir araya geldiler.",
             "dreaded cat | Korkulan kedi; 'hearth' ocak başı."),
            ("Various schemes were proposed by the elder mice, but each was rejected as impractical or dangerous.",
             "Yaşlı fareler tarafından çeşitli planlar öne sürüldü; fakat her biri ya kullanışsız ya da tehlikeli bulunarak reddedildi.",
             "schemes proposed | Önerilen planlar; 'impractical' uygulanamaz."),
            ("At last, a young mouse of lively wit and confident demeanor rose to address the assembly.",
             "Nihayet, kıvrak bir zekaya ve özgüvenli bir duruşa sahip genç bir fare topluluğa hitap etmek için ayağa kalktı.",
             "lively wit | Kıvrak zeka; 'confident demeanor' kendinden emin tavır."),
            ("'I have devised a remarkably simple plan,' he announced proudly, puffing out his little chest.",
             "Küçük göğsünü kabartarak gururla, 'Son derece basit bir plan tasarladım,' diye duyurdu.",
             "puffing out chest | Göğsünü kabartmak."),
            ("'Our peril arises solely from the sly and unpredictable approach of our enemy.'",
             "'Tehlikemiz yalnızca düşmanımızın sinsi ve önceden kestirilemez yaklaşmasından kaynaklanıyor.'",
             "unpredictable approach | Kestirilemez yaklaşım."),
            ("'If we had adequate warning of her whereabouts, we could easily retreat to safety in time.'",
             "'Onun nerede olduğuna dair yeterli bir uyarımız olsaydı, zamanında emniyete kolayca çekilebilirdik.'",
             "whereabouts | Bulunduğu yer; 'adequate warning' yeterli uyarı."),
            ("'I propose that we procure a small brass bell and attach it to a ribbon around her neck.'",
             "'Küçük pirinç bir çan temin edip onu bir kurdeleyle kedinin boynuna bağlamamızı teklif ediyorum.'",
             "brass bell | Pirinç çan; 'procure' temin etmek."),
            ("'Whenever she moves, the bell will tinkle merrily, signalling her approach and saving our lives.'",
             "'Kedi her hareket ettiğinde çan neşeyle çıngırdayacak, onun gelişini haber verip hayatlarımızı kurtaracaktır.'",
             "tinkle merrily | Neşeyle çıngırdamak."),
            ("The entire council erupted in ecstatic applause, hailing the young speaker as a brilliant savior.",
             "Bütün meclis coşkulu alkışlarla inledi; genç konuşmacıyı dahi bir kurtarıcı olarak alkışladılar.",
             "erupted in applause | Alkışlarla inlemek / patlamak."),
            ("They congratulated one another on having discovered such a masterly and permanent solution.",
             "Böylesine ustaca ve kalıcı bir çözüm keşfettikleri için birbirlerini tebrik ettiler.",
             "masterly solution | Ustaca çözüm."),
            ("In the midst of the general jubilation, an elderly, experienced mouse slowly rose to his feet.",
             "Bu genel sevinç gösterisinin ortasında, yaşlı ve tecrübeli bir fare yavaşça ayağa kalktı.",
             "jubilation | Büyük sevinç, bayram havası."),
            ("He looked thoughtfully around the gathering, waiting until complete silence was restored.",
             "Topluluğun etrafına düşünceli bir şekilde baktı ve tam bir sessizlik sağlanana kadar bekledi.",
             "silence restored | Sessizliğin yeniden sağlanması."),
            ("'The young gentleman's plan is undoubtedly ingenious and admirable,' observed the veteran calmly.",
             "Kıdemli fare sakince, 'Genç beyefendinin planı hiç şüphesiz dahiyane ve takdire şayan,' dedi.",
             "veteran | Kıdemli, tecrübeli kişi; 'ingenious' dahiyane."),
            ("'However, before we celebrate our victory, allow me to ask one very simple question.'",
             "'Fakat zaferimizi kutlamadan önce, çok basit tek bir soru sormama müsaade edin.'",
             "celebrate victory | Zaferi kutlamak."),
            ("'Which one among us is going to volunteer to bell the cat?'",
             "'Aramızdan kim kediye çan takmaya gönüllü olacak?'",
             "bell the cat | 'Kediye çan takmak' tehlikeli bir işe kalkışmak deyimidir.")
        ],
        "vocab_focus": [
            ("terrorized", "korku salınmış, sindirilmiş"),
            ("silent stealth", "sessiz ve sinsi gizlilik"),
            ("at stake", "tehlikede, pamuk ipliğinde"),
            ("impractical", "uygulanması zor, gayripratik"),
            ("procure", "temin etmek, tedarik etmek"),
            ("tinkle", "çıngırdamak"),
            ("jubilation", "büyük sevinç, coşku"),
            ("bell the cat", "kediye çan takmak (tehlikeyi göze almak)")
        ]
    },

    # PAGE 15: The Bundle of Sticks
    {
        "page_no": 15,
        "title": "The Bundle of Sticks",
        "tr_title": "Demet Halindeki Çubuklar (Birlikten Doğan Güç)",
        "sentences": [
            ("An aged father had several sons who were continually quarrelling and bickering amongst themselves.",
             "Yaşlı bir babanın, kendi aralarında sürekli kavga eden ve çekişip duran birkaç oğlu vardı.",
             "continually quarrelling | Sürekli kavga eden; 'bickering' didişme."),
            ("Despite his earnest entreaties and loving advice, they refused to live together in brotherly harmony.",
             "Babanın içten yalvarışlarına ve sevgi dolu öğütlerine rağmen kardeşçe bir ahenk içinde yaşamayı reddediyorlardı.",
             "earnest entreaties | İçten yalvarışlar / ricalar."),
            ("Their mutual jealousy and bitter discord brought immense sorrow to the old patriarch's heart.",
             "Onların karşılıklı kıskançlığı ve acı uyuşmazlığı, ihtiyar aile reisinin yüreğine muazzam bir keder getiriyordu.",
             "patriarch | Aile reisi, ata; 'mutual jealousy' karşılıklı kıskançlık."),
            ("He knew that as long as they remained disunited, their enemies would easily conquer and ruin them.",
             "Aralarında birlik olmadığı müddetçe, düşmanlarının onları kolayca yenip mahvedeceğini çok iyi biliyordu.",
             "disunited | Bölünmüş, birliği olmayan."),
            ("One morning, feeling his physical strength waning, he summoned all his sons to his bedside.",
             "Bir sabah fiziksel gücünün tükendiğini hissederek bütün oğullarını başucuna çağırdı.",
             "strength waning | Gücün zayıflaması / tükenmesi; 'summoned' çağırdı."),
            ("He commanded his youngest servant to bring in a tight bundle of sturdy wooden sticks.",
             "En genç hizmetkârına sağlam tahta çubuklardan oluşan sıkı bir demet getirmesini emretti.",
             "bundle of sticks | Çubuk / sopa demeti."),
            ("The sticks were bound securely together with several coils of tough leather cord.",
             "Çubuklar, sert deri iple birkaç tur sarılarak birbirine sımsıkı bağlanmıştı.",
             "bound securely | Sımsıkı bağlanmış; 'coils' kangallar, turlar."),
            ("The father handed the bundle to his eldest son and issued a straightforward command.",
             "Baba demeti en büyük oğluna uzattı ve apaçık bir emir verdi.",
             "issued a command | Emir vermek / buyurmak."),
            ("'Take this bundle in your two hands and break it in pieces before my eyes.'",
             "'Bu demeti iki eline al ve gözlerimin önünde parçalara ayır.'",
             "break in pieces | Parçalara ayırmak / kırmak."),
            ("The eldest son strained with all his muscular strength, his face turning red with the exertion.",
             "Büyük oğul bütün kas gücüyle asıldı; bu yoğun çabadan yüzü kıpkırmızı kesildi.",
             "strained | Zorlandı, gayret etti; 'exertion' yoğun efor / çaba."),
            ("He braced the bundle across his knee and pulled with desperate fury, but could not bend it in the least.",
             "Demeti dizine dayadı ve çaresiz bir öfkeyle çekti; fakat onu zerre kadar bile bükemedi.",
             "braced across knee | Dizine dayamak."),
            ("One by one, the other brothers took their turns, each confident that his superior strength would prevail.",
             "Diğer kardeşler, her biri kendi üstün gücünün galip geleceğinden emin olarak sırayla denediler.",
             "superior strength | Üstün güç; 'prevail' galip gelmek."),
            ("Yet, despite their groans and fierce struggles, the sturdy bundle remained completely unbroken.",
             "Yine de inlemelerine ve şiddetli mücadelelerine rağmen, sağlam demet bütünüyle kırılmadan kaldı.",
             "unbroken | Kırılmamış, bozulmamış."),
            ("'We cannot break it, father,' they admitted shamefacedly, handing the bundle back.",
             "Demeti geri uzatarak mahcupça, 'Bunu kıramıyoruz baba,' diye itiraf ettiler.",
             "shamefacedly | Mahcupça, yüzü kızararak."),
            ("The father smiled gently, untied the leather cord, and distributed a single stick to each son.",
             "Baba tatlı bir tebessümle deri ipi çözdü ve her bir oğluna tek bir çubuk dağıttı.",
             "untied | Çözdü; 'distributed' dağıttı."),
            ("'Now, my sons,' said the venerable man, 'try to break the sticks individually.'",
             "Saygıdeğer adam, 'Şimdi evlatlarım,' dedi, 'çubukları teker teker kırmayı deneyin.'",
             "venerable man | Saygıdeğer, muhterem adam."),
            ("Snap! Snap! Snap! Each son snapped his solitary stick in twain with the greatest of ease.",
             "Çat! Çat! Çat! Her bir oğul, elindeki tek çubuğu büyük bir kolaylıkla ortadan ikiye kırıverdi.",
             "in twain | İkiye, ortadan ikiye."),
            ("'Behold the lesson,' concluded the father with solemn gravity and profound tenderness.",
             "Baba vakar dolu bir ciddiyet ve derin bir şefkatle, 'İşte bu ibrete iyi bakın,' diyerek sözlerini tamamladı.",
             "solemn gravity | Vakur bir ciddiyet; 'tenderness' şefkat."),
            ("'As long as you stand united in brotherly love, no adversary in the world will have power to injure you.'",
             "'Kardeşlik sevgisiyle bir arada durduğunuz müddetçe, dünyadaki hiçbir hasım sizi incitmeye muktedir olamayacaktır.'",
             "stand united | Birlik içinde durmak; 'adversary' düşman, hasım."),
            ("'United we stand and conquer, but divided by petty quarrels we surely fall.'",
             "'Birlik olursak dimdik durur ve fethederiz; fakat küçük sürtüşmelerle bölünürsek muhakkak yıkılırız.'",
             "united we stand, divided we fall | 'Birlikten kuvvet doğar, ayrılanı kurt kapar' klasik atasözüdür.")
        ],
        "vocab_focus": [
            ("bickering", "didişme, ufak tefek çekişme"),
            ("entreaties", "içten ricalar, yalvarışlar"),
            ("waning", "azalan, sönmeye yüz tutan"),
            ("bundle", "demet, bağ"),
            ("exertion", "yoğun efor, çaba harcama"),
            ("in twain", "ortadan ikiye"),
            ("adversary", "hasım, düşman"),
            ("united we stand", "birlikten güç doğar")
        ]
    }
]

import os

output_file = os.path.join(os.path.dirname(__file__), "book_06_data.py")
with open(output_file, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""\n')
    f.write("Book 6: Aesop's Classic Fables (Part 1): Wisdom of the Forest\n")
    f.write("Level 1 Graded Reader — 15 Pages x 20 Sentences = 300 Sentences.\n")
    f.write('"""\n\n')
    f.write('BOOK_TITLE = "Aesop\'s Classic Fables (Part 1): Wisdom of the Forest (15 Sayfa / 300 Cümle / Graded Reader)"\n')
    f.write('AUTHOR = "Aesop (Ezop)"\n\n')
    f.write("PAGES_DATA = [\n")
    
    current_sentence_id = 1
    for page in pages_content:
        f.write("    {\n")
        f.write(f'        "page_no": {page["page_no"]},\n')
        f.write(f'        "title": "{page["title"]}",\n')
        f.write(f'        "tr_title": "{page["tr_title"]}",\n')
        f.write('        "sentences": [\n')
        for s in page["sentences"]:
            text = s[0].replace('"', '\\"')
            tr = s[1].replace('"', '\\"')
            notes = s[2].replace('"', '\\"')
            f.write("            {\n")
            f.write(f'                "id": {current_sentence_id},\n')
            f.write(f'                "text": "{text}",\n')
            f.write(f'                "translation": "{tr}",\n')
            f.write(f'                "notes": "{notes}"\n')
            f.write("            },\n")
            current_sentence_id += 1
        f.write("        ],\n")
        f.write('        "vocab_focus": [\n')
        for v in page["vocab_focus"]:
            v_en = v[0].replace('"', '\\"')
            v_tr = v[1].replace('"', '\\"')
            f.write(f'            ("{v_en}", "{v_tr}"),\n')
        f.write("        ]\n")
        f.write("    },\n")
    f.write("]\n")

print(f"Generated tools/book_06_data.py successfully with {current_sentence_id - 1} sentences across {len(pages_content)} pages!")
