# -*- coding: utf-8 -*-
"""
Generator script to build tools/book_08_data.py
The Little Prince: Chapters of the Stars (Antoine de Saint-Exupéry)
15 Pages x 20 Sentences = 300 Sentences.
"""

pages_content = [
    # PAGE 1: Chapter 1: The Boa Constrictor and the Hat
    {
        "page_no": 1,
        "title": "The Boa Constrictor and the Hat",
        "tr_title": "Boğa Yılanı ve Şapka Resmi",
        "sentences": [
            ("Once, when I was six years old, I saw a magnificent picture in a book about the primeval forest.",
             "Bir keresinde, altı yaşındayken, balta girmemiş ormanlar hakkındaki bir kitapta muhteşem bir resim gördüm.",
             "primeval forest | Balta girmemiş / el değmemiş bakir orman."),
            ("The book was called 'True Stories from Nature,' and it made a profound impression upon my imagination.",
             "Kitabın adı 'Doğadan Gerçek Hikayeler' idi ve hayal gücümün üzerinde derin bir tesir bıraktı.",
             "profound impression | Derin tesir / etki."),
            ("The picture represented an enormous boa constrictor in the act of swallowing an entire wild beast.",
             "Resim, bütün bir yaban hayvanını yutmakta olan devasa bir boğa yılanını tasvir ediyordu.",
             "in the act of | '... eylemi esnasında, tam yaparken' yapısıdır."),
            ("The book explained that boa constrictors swallow their prey whole, without chewing it at all.",
             "Kitap, boğa yılanlarının avlarını hiç çiğnemeden, bütünüyle tek lokmada yuttuklarını açıklıyordu.",
             "swallow whole | Bütün olarak tek lokmada yutmak."),
            ("After that, they are unable to move for six long months while they peacefully digest their meal.",
             "Bundan sonra, yemeklerini huzur içinde sindirirken altı uzun ay boyunca kımıldayamazlar.",
             "digest | Sindirmek, hazmetmek; 'peacefully' huzurla."),
            ("I pondered deeply over the extraordinary adventures of the jungle and its mysterious creatures.",
             "Balta girmemiş ormanın olağanüstü maceraları ve gizemli yaratıkları üzerine derin derin kafa yordum.",
             "pondered deeply | Derin derin kafa yormak / düşünmek."),
            ("After some work with a colored pencil, I succeeded in drawing my very first picture.",
             "Renkli bir kurşun kalemle biraz uğraştıktan sonra, ilk resmimi başarıyla çizmeyi başardım.",
             "succeeded in drawing | Çizmeyi başarmak."),
            ("My Drawing Number One showed an elephant inside a boa constrictor from the outside.",
             "Bir Numaralı Resmim, bir fili yutmuş boğa yılanını dışarıdan gösteriyordu.",
             "Drawing Number One | Bir Numaralı Çizim."),
            ("I proudly showed my masterpiece to the grown-ups and asked if my drawing frightened them.",
             "Şaheserimi gururla büyüklere gösterdim ve çizimimin onları korkutup korkutmadığını sordum.",
             "grown-ups | Yetişkinler, büyükler; 'masterpiece' şaheser."),
            ("They looked at it casually and answered, 'Why should anyone be frightened by an ordinary hat?'",
             "Ona gelişi güzel baktılar ve 'İnsan sıradan bir şapkadan neden korksun ki?' diye yanıtladılar.",
             "casually | Gelişigüzel, kayıtsızca; 'ordinary' sıradan."),
            ("My drawing was not a picture of a hat at all, but a boa constrictor digesting an elephant.",
             "Benim çizimim kesinlikle bir şapka resmi değildi; aksine bir fili sindirmekte olan bir boğa yılanıydı.",
             "not at all | Kesinlikle değil."),
            ("Since the grown-ups were always unable to understand things by themselves, I drew another picture.",
             "Büyükler hiçbir şeyi kendi başlarına anlamaktan daima aciz oldukları için bir başka resim daha çizdim.",
             "by themselves | Kendi başlarına; 'unable to' den aciz."),
            ("I made Drawing Number Two, which clearly portrayed the inside of the snake so adults could see.",
             "Yetişkinler görebilsin diye yılanın içini apaçık tasvir eden İki Numaralı Çizim'i yaptım.",
             "portrayed | Tasvir etti, resmetti."),
            ("They always require explanations, for clear and simple concepts seem completely invisible to them.",
             "Onlar daima açıklamalar talep ederler; zira berrak ve sade kavramlar onlara tamamen görünmez gelir.",
             "require explanations | Açıklama talep etmek / gerektirmek."),
            ("This time, the grown-ups advised me to lay aside my drawings of open or closed boa constrictors.",
             "Bu sefer büyükler, açık veya kapalı boğa yılanı çizimlerimi bir kenara bırakmamı tavsiye ettiler.",
             "lay aside | Bir kenara bırakmak; 'advised' tavsiye etti."),
            ("They told me to devote myself instead to geography, history, arithmetic, and strict grammar.",
             "Bunun yerine kendimi coğrafyaya, tarihe, aritmetiğe ve katı dilbilgisine adamamı söylediler.",
             "devote myself to | Kendini bir şeye adamak."),
            ("That is how, at the tender age of six, I abandoned a magnificent career as a painter.",
             "İşte böylece, henüz altı yaşımın o körpe çağında ressamlık gibi muhteşem bir kariyeri terk ettim.",
             "tender age | Körpe / küçük yaş; 'abandoned' terk etti."),
            ("I had been completely discouraged by the failure of my first two artistic masterpieces.",
             "İlk iki sanatsal şaheserimin başarısızlığı yüzünden hevesim büsbütün kırılmıştı.",
             "discouraged | Hevesi kırılmış, cesareti sönmüş."),
            ("Grown-ups never understand anything on their own, and it is exhausting for children to explain everything.",
             "Büyükler hiçbir şeyi kendi başlarına asla anlayamazlar ve her şeyi onlara açıklamak çocuklar için çok yorucudur.",
             "exhausting | Yorucu, tüketici; 'on their own' kendi kendilerine."),
            ("So I chose another profession and learned to pilot airplanes across the great blue sky.",
             "Bu yüzden başka bir meslek seçtim ve masmavi gökyüzünde uçak kullanmayı öğrendim.",
             "profession | Meslek; 'pilot airplanes' uçak pilotluğu yapmak.")
        ],
        "vocab_focus": [
            ("primeval", "balta girmemiş, ilkel"),
            ("profound", "derin, köklü"),
            ("pondered", "derin derin düşündü"),
            ("grown-ups", "yetişkinler, büyükler"),
            ("casually", "kayıtsızca, gelişigüzel"),
            ("portrayed", "tasvir etti, resmetti"),
            ("discouraged", "hevesi kırılmış"),
            ("exhausting", "son derece yorucu")
        ]
    },

    # PAGE 2: Chapter 2: The Sahara Desert and 'Draw Me a Sheep'
    {
        "page_no": 2,
        "title": "The Sahara and the Sheep",
        "tr_title": "Sahra Çölü ve 'Bana Bir Koyun Çiz'",
        "sentences": [
            ("I lived my life alone, without anyone with whom I could speak intimately, until a breakdown in the desert.",
             "Çöldeki bir arızaya kadar, samimiyetle konuşabileceğim hiç kimsem olmadan hayatımı yapayalnız yaşadım.",
             "speak intimately | Samimiyetle / içtenlikle konuşmak; 'breakdown' arıza."),
            ("Six years ago, something broke inside the engine of my plane above the vast Sahara Desert.",
             "Altı yıl önce, uçsuz bucaksız Sahra Çölü'nün üzerinde uçağımın motorunun içinde bir şeyler kırıldı.",
             "vast Sahara | Uçsuz bucaksız Sahra; 'engine' motor."),
            ("As I had neither a mechanic nor any passengers with me, I prepared to attempt the difficult repair alone.",
             "Yanımda ne bir makinist ne de herhangi bir yolcu bulunduğundan, bu zor onarımı tek başıma denemeye koyuldum.",
             "attempt repair | Onarımı denemek / kalkışmak."),
            ("It was a matter of life or death, for I had scarcely enough drinking water for eight short days.",
             "Bu bir ölüm kalım meselesiydi; zira ancak sekiz kısa güne yetecek kadar içme suyum kalmıştı.",
             "matter of life or death | Ölüm kalım meselesi; 'scarcely' zar zor."),
            ("On my first night, I fell asleep on the golden sand, a thousand miles from any inhabited country.",
             "İlk gecemde, yerleşimin olduğu herhangi bir diyardan bin mil uzakta, altın kumların üzerinde uyuyakaldım.",
             "inhabited country | Yerleşimin / insanların olduğu ülke."),
            ("I was far more isolated than a shipwrecked sailor clinging to a wooden raft in the midst of the ocean.",
             "Okyanusun ortasında tahta bir sala tutunmuş kazazede bir denizciden çok daha fazla yalıtılmış durumdaydım.",
             "isolated | Yalıtılmış, dünyadan kopuk; 'clinging to' tutunarak."),
            ("Imagine my utter amazement when, at sunrise, an extraordinary little voice awakened me softly.",
             "Gündoğumunda fevkalade minik bir ses beni usulca uyandırdığında duyduğum tam hayreti tahayyül edin.",
             "utter amazement | Tam bir hayret / şaşkınlık; 'awakened' uyandırdı."),
            ("The voice said gently, 'Please... draw me a sheep!'",
             "Ses nazikçe şöyle diyordu: 'Lütfen... bana bir koyun çizer misin!'",
             "draw me a sheep | Bana bir koyun çiz."),
            ("I leaped to my feet as if I had been struck by a bolt of blinding lightning.",
             "Kör edici bir şimşek çarpmış gibi birden ayağa fırladım.",
             "leaped to my feet | Birden ayağa fırlamak / sıçramak."),
            ("I rubbed my tired eyes vigorously and looked intently around the barren expanse of sand.",
             "Yorgun gözlerimi kuvvetle ovuşturdum ve kıraç kum enginliğine dikkatle baktım.",
             "rubbed eyes | Gözleri ovuşturmak; 'barren expanse' kıraç enginlik."),
            ("And I saw a most extraordinary little boy, who was examining me with great solemnity.",
             "Ve beni büyük bir ciddiyetle incelemekte olan, son derece olağanüstü küçük bir çocuk gördüm.",
             "solemnity | Ciddiyet, vekar; 'examining' incelemek."),
            ("He was neither lost, nor fainting from fatigue, nor dying of thirst or terrifying hunger.",
             "Ne kaybolmuştu ne yorgunluktan bayılacak gibiydi ne de susuzluktan ya da korkunç açlıktan ölüyordu.",
             "fainting from fatigue | Yorgunluktan bayılacak gibi olmak."),
            ("He showed not the slightest trace of fear, standing composed in the midst of nowhere.",
             "Hiçliğin ortasında vakarla durarak en ufak bir korku izi bile göstermiyordu.",
             "slightest trace | En ufak bir iz; 'composed' sakin, vakar dolu."),
            ("When at last I was able to speak, I asked him, 'What are you doing here in the desert?'",
             "Nihayet konuşabildiğimde ona, 'Burada, çölde ne yapıyorsun?' diye sordum.",
             "able to speak | Konuşabilmek."),
            ("He repeated very softly and seriously, 'Please... draw me a sheep...'",
             "Çok yumuşak ve ciddi bir sesle tekrarladı: 'Lütfen... bana bir koyun çiz...'",
             "repeated softly | Yumuşakça tekrarlamak."),
            ("When a mystery is too overwhelming, one simply does not dare to disobey.",
             "Bir gizem fazlasıyla ezici ve büyüleyici olduğunda, insan karşı gelmeye asla cesaret edemez.",
             "overwhelming | Ezici, karşı konulmaz; 'disobey' itaatsizlik etmek."),
            ("Absurd as it seemed a thousand miles from any habitation, I took out a sheet of paper and a pen.",
             "İnsan yerleşiminden bin mil uzakta ne kadar saçma görünse de cebimden bir yaprak kağıt ve bir dolmakalem çıkardım.",
             "sheet of paper | Bir yaprak kağıt; 'habitation' yerleşim yeri."),
            ("Then I remembered that my studies had been concentrated on geography, history, and arithmetic.",
             "Derken derslerimin coğrafya, tarih ve aritmetik üzerinde yoğunlaşmış olduğunu hatırladım.",
             "concentrated on | Üzerinde yoğunlaşmış olmak."),
            ("I told the little fellow, somewhat crossly, that I did not know how to draw.",
             "Küçük delikanlıya biraz aksi bir edayla resim yapmayı bilmediğimi söyledim.",
             "crossly | Aksi bir tavırla; 'little fellow' küçük delikanlı/çocuk."),
            ("He answered simply, 'That does not matter at all. Draw me a sheep.'",
             "O ise sade bir dille, 'Bunun hiçbir önemi yok. Bana bir koyun çiz,' diye yanıtladı.",
             "does not matter at all | Hiç ama hiçbir önemi olmamak.")
        ],
        "vocab_focus": [
            ("isolated", "yalıtılmış, dünyadan kopuk"),
            ("utter amazement", "tam bir şaşkınlık"),
            ("leaped to feet", "birden ayağa fırladı"),
            ("barren expanse", "kıraç/ıssız enginlik"),
            ("fatigue", "aşırı yorgunluk, bitkinlik"),
            ("composed", "sakin, soğukkanlı"),
            ("disobey", "itaatsizlik etmek, karşı gelmek"),
            ("crossly", "aksi aksi, huysuzca")
        ]
    },

    # PAGE 3: Chapter 3: Where Do You Come From?
    {
        "page_no": 3,
        "title": "Where Do You Come From?",
        "tr_title": "Nereden Geliyorsun?",
        "sentences": [
            ("Since I had never drawn a sheep before, I made for him my Drawing Number One.",
             "Daha önce hiç koyun çizmediğim için ona Bir Numaralı Çizimimi yaptım.",
             "made for him | Onun için yaptım."),
            ("To my utter astonishment, the little prince exclaimed, 'No! No! I do not want an elephant inside a boa!'",
             "Büyük bir hayretle gördüm ki küçük prens, 'Hayır! Hayır! Ben boğa yılanının içinde bir fil istemiyorum!' diye haykırdı.",
             "utter astonishment | Tam bir hayret."),
            ("'A boa constrictor is very dangerous, and an elephant is far too cumbersome for my tiny home.'",
             "'Bir boğa yılanı çok tehlikelidir ve bir fil de minik evim için fazlasıyla hantaldır.'",
             "cumbersome | Hantal, külfetli, çok yer kaplayan."),
            ("'Where I live, everything is so small that there is no room for such monsters.'",
             "'Benim yaşadığım yerde her şey o kadar küçüktür ki böylesi canavarlara yer yoktur.'",
             "no room for | '... için yer olmaması' kalıbıdır."),
            ("I was amazed that he understood my drawing immediately, so I attempted to draw a real sheep.",
             "Çizimimi anında anlamasına hayret ederek gerçek bir koyun çizmeyi denedim.",
             "attempted to draw | Çizmeyi denemek."),
            ("He looked at it carefully, then shook his head: 'No, this one is already very sickly; draw another.'",
             "Ona dikkatle baktı, sonra başını salladı: 'Hayır, bu zaten çok hastalıklı; bir başkasını çiz.'",
             "sickly | Hastalıklı, çelimsiz."),
            ("I drew again, but he remarked gently, 'You see yourself that this is not a sheep, but a ram with horns.'",
             "Tekrar çizdim ama nazikçe, 'Kendin de görüyorsun ki bu bir koyun değil, boynuzları olan bir koç,' dedi.",
             "ram with horns | Boynuzlu koç."),
            ("My next drawing was rejected just as swiftly: 'This one is far too old; I want a sheep that will live long.'",
             "Bir sonraki çizimim de aynı hızla reddedildi: 'Bu çok yaşlı; ben uzun yaşayacak bir koyun istiyorum.'",
             "rejected swiftly | Hızla reddedilmek."),
            ("By this time, my patience had run out, as I was in a hurry to dismantle my engine.",
             "O ana kadar sabrım tükenmişti; çünkü motorumu sökmek için acele ediyordum.",
             "patience had run out | Sabrı tükenmek; 'dismantle' sökmek."),
            ("So I hastily scribbled a simple box with three small air holes on the side.",
             "Böylece aceleyle yan tarafında üç küçük hava deliği olan sade bir kutu karaladım.",
             "hastily scribbled | Aceleyle karalamak / çiziktirmek."),
            ("I handed it over and said, 'This is only the box; the sheep you asked for is inside.'",
             "Onu uzattım ve 'Bu yalnızca bir kutudur; istediğin koyun da içindedir,' dedim.",
             "handed over | Uzatmak, teslim etmek."),
            ("I was utterly astounded to see the face of my young judge light up with brilliant joy.",
             "Genç yargıcımın yüzünün parlak bir sevinçle aydınlandığını görünce büsbütün donakaldım.",
             "light up with joy | Sevinçle aydınlanmak; 'astounded' donakalmış."),
            ("'That is exactly the way I wanted it!' he exclaimed with genuine delight.",
             "Hakiki bir sevinçle, 'Tam da istediğim gibi olmuş!' diye haykırdı.",
             "genuine delight | Hakiki sevinç / mutluluk."),
            ("'Do you suppose that this sheep will require a great deal of fresh green grass?'",
             "'Sence bu koyun çok fazla taze yeşil ota ihtiyaç duyar mı?'",
             "require a great deal | Çok fazla şeye ihtiyaç duymak."),
            ("'Why do you ask?' I inquired, puzzled by his curious concern.",
             "Onun bu tuhaf endişesi karşısında şaşırarak, 'Neden soruyorsun?' dedim.",
             "puzzled by | İle aklı karışmış / şaşırmış."),
            ("'Because where I live, everything is so exceedingly small,' he murmured pensively.",
             "Düşünceli bir şekilde mırıldanarak, 'Çünkü benim yaşadığım yerde her şey son derece küçüktür,' dedi.",
             "pensively | Düşünceli şekilde; 'exceedingly small' son derece küçük."),
            ("'There will certainly be enough grass for him,' I smiled, 'for I have given you a very tiny sheep.'",
             "Tebessüm ederek, 'Onun için kesinlikle yeterince ot olacaktır,' dedim, 'çünkü sana ufacık bir koyun verdim.'",
             "tiny sheep | Ufacık koyun."),
            ("He bent his head over the drawing and whispered, 'Not so tiny as all that... Look! He has gone to sleep!'",
             "Başını çizimin üzerine eğdi ve fısıldadı: 'O kadar da küçük değil... Bak! Uyuyuvermiş!'",
             "gone to sleep | Uyuya kalmak."),
            ("And that is how I made the acquaintance of the extraordinary Little Prince.",
             "Ve işte o fevkalade Küçük Prens ile bu şekilde tanışmış oldum.",
             "made the acquaintance | İle tanışmak / tanışıklık kurmak."),
            ("It took me a long time to understand where he came from, for he asked questions without answering mine.",
             "Nereden geldiğini anlamak uzun zamanımı aldı; zira benimkileri cevaplamadan sürekli kendisi soru soruyordu.",
             "took a long time | Uzun zaman almak.")
        ],
        "vocab_focus": [
            ("cumbersome", "hantal, zahmetli, külfetli"),
            ("sickly", "hastalıklı, çelimsiz"),
            ("ram", "koç"),
            ("dismantle", "sökmek, parçalarına ayırmak"),
            ("hastily scribbled", "aceleyle karaladı"),
            ("astounded", "şaşakalmış, donakalmış"),
            ("pensively", "düşünceli bir tavırla"),
            ("made the acquaintance", "tanışıklık kurdu")
        ]
    },

    # PAGE 4: Chapter 4: Asteroid B-612 and the Turkish Astronomer
    {
        "page_no": 4,
        "title": "Asteroid B-612",
        "tr_title": "Asteroit B-612 ve Türk Gökbilimci",
        "sentences": [
            ("I learned that the planet from which the Little Prince had journeyed was scarcely larger than a house.",
             "Küçük Prens'in yolculuk ettiği gezegenin bir evden zar zor daha büyük olduğunu öğrendim.",
             "scarcely larger | Zar zor / ancak daha büyük."),
            ("This did not surprise me excessively, for I knew that besides the great planets, there are hundreds of asteroids.",
             "Bu beni aşırı derecede şaşırtmadı; zira büyük gezegenlerin yanında yüzlerce asteroit olduğunu biliyordum.",
             "excessively | Aşırı derecede; 'asteroids' göktaşları/asteroitler."),
            ("Some of them are so diminutive that one can hardly observe them even through a powerful telescope.",
             "Bazıları öylesine küçüktür ki güçlü bir teleskopla bile onları neredeyse hiç gözlemleyemezsiniz.",
             "diminutive | Küçücük, minicik; 'observe' gözlemlemek."),
            ("When an astronomer discovers one of these tiny spheres, he does not give it a name, but a number.",
             "Bir gökbilimci bu minik kürelerden birini keşfettiğinde ona bir isim değil, bir numara verir.",
             "astronomer | Gökbilimci, astronom; 'spheres' küreler."),
            ("He simply designates it as Asteroid 325, or Asteroid 4391, for official cataloging.",
             "Resmi kataloglama için onu yalnızca Asteroit 325 veya Asteroit 4391 olarak adlandırır.",
             "designates | Belirlemek, adlandırmak."),
            ("I have serious reason to believe that the planet from which the little prince came was Asteroid B-612.",
             "Küçük prensin geldiği gezegenin Asteroit B-612 olduğuna inanmak için çok ciddi sebeplerim var.",
             "serious reason | Ciddi gerekçe / sebep."),
            ("This asteroid had been sighted only once through a telescope by a Turkish astronomer in 1909.",
             "Bu asteroit 1909 yılında bir Türk gökbilimci tarafından teleskopla yalnızca bir kez görülmüştü.",
             "sighted | Görülmüş, fark edilmiş."),
            ("The astronomer presented his magnificent discovery to the International Astronomical Congress with great demonstration.",
             "Gökbilimci bu muazzam keşfini Uluslararası Astronomi Kongresi'ne büyük bir ispat gösterisiyle sundu.",
             "demonstration | İspat, gösteri; 'presented' sundu."),
            ("However, nobody would believe what he reported, simply on account of the traditional costume he wore.",
             "Fakat giydiği geleneksel kıyafet yüzünden hiç kimse onun bildirdiklerine inanmak istemedi.",
             "on account of | '... yüzünden, ötürü' bağlacıdır; 'costume' kıyafet."),
            ("Grown-ups are like that; they judge truth by superficial appearances rather than authentic reality.",
             "Büyükler böyledir işte; hakikati gerçeklik yerine yüzeysel görünüşlere göre yargılarlar.",
             "superficial appearances | Yüzeysel görünüşler."),
            ("Fortunately for the reputation of Asteroid B-612, a Turkish ruler compelled his subjects to dress like Europeans.",
             "Asteroit B-612'nin itibarı adına ne mutlu ki bir Türk lider tebaasına Avrupalılar gibi giyinmeyi zorunlu kıldı.",
             "compelled | Zorunlu kılmak; 'reputation' itibar; 'subjects' tebaa."),
            ("So, in 1920, the elegant astronomer presented his report again, dressed in a fashionable European suit.",
             "Böylece 1920'de o zarif gökbilimci, şık bir Avrupa takım elbisesi giymiş olarak raporunu tekrar sundu.",
             "fashionable suit | Şık takım elbise."),
            ("This time, everybody accepted his scientific report without the slightest hesitation or doubt.",
             "Bu sefer herkes onun bilimsel raporunu en ufak bir tereddüt ya da şüphe duymaksızın kabul etti.",
             "slightest hesitation | En ufak bir tereddüt."),
            ("If I tell you these details about Asteroid B-612 and recount its exact number, it is on account of the grown-ups.",
             "Eğer size Asteroit B-612 hakkındaki bu detayları anlatıyor ve tam numarasını aktarıyorsam, bu büyüklerin yüzündendir.",
             "recount | Aktarmak, nakletmek."),
            ("Adults adore figures and statistics; they are obsessed with numbers and measurements.",
             "Yetişkinler rakamlara ve istatistiklere bayılırlar; sayılar ve ölçümlerle kafayı bozmuşlardır.",
             "obsessed with | İle takıntılı olmak; 'figures' rakamlar."),
            ("When you tell them about a new friend, they never ask the essential questions: 'What does his voice sound like?'",
             "Onlara yeni bir arkadaştan bahsettiğinizde asla asıl önemli soruları sormazlar: 'Sesi nasıldır?'",
             "essential questions | Asıl önemli / zaruri sorular."),
            ("Instead, they demand, 'How old is he? How many brothers has he? How much does his father earn?'",
             "Bunun yerine, 'Kaç yaşındadır? Kaç kardeşi vardır? Babası ne kadar para kazanır?' diye diretirler.",
             "demand | Talep etmek, üstelemek."),
            ("Only from these quantitative digits do they believe that they know and understand a human soul.",
             "Ancak bu niceliksel basamaklardan yola çıkarak bir insan ruhunu tanıdıklarına ve anladıklarına inanırlar.",
             "quantitative digits | Niceliksel / sayısal basamaklar."),
            ("To children, however, friendship is woven of warmth, gentle laughter, and the fragrance of dreams.",
             "Çocuklar için ise dostluk; sıcaklıktan, tatlı kahkahalardan ve hayallerin kokusundan örülmüştür.",
             "woven of | Den örülmüş."),
            ("It is truly a sad thing to forget a beloved friend, for not everyone has the good fortune to possess one.",
             "Sevgili bir dostu unutmak hakikaten hüzünlü bir şeydir; zira bir dosta sahip olma şansı herkese nasip olmaz.",
             "good fortune | İyi talih, şans.")
        ],
        "vocab_focus": [
            ("diminutive", "küçücük, minyatür"),
            ("designates", "adlandırır, tayin eder"),
            ("superficial", "yüzeysel, sığ"),
            ("compelled", "zorladı, mecbur kıldı"),
            ("recount", "anlatmak, nakletmek"),
            ("obsessed with", "ile takıntılı"),
            ("quantitative", "niceliksel, sayısal"),
            ("woven of", "...-den örülmüş")
        ]
    }
]

# Write pages 5 to 15
pages_5_to_15 = [
    # PAGE 5: Chapter 5: The Dreaded Baobab Trees
    {
        "page_no": 5,
        "title": "The Dreaded Baobabs",
        "tr_title": "Tehlikeli Baobab Ağaçları",
        "sentences": [
            ("Each day I learned something new about the Little Prince's planet, his departure, and his journey.",
             "Her gün Küçük Prens'in gezegeni, ayrılışı ve yolculuğu hakkında yeni bir şeyler öğreniyordum.",
             "departure | Ayrılış, yola çıkış; 'journey' yolculuk."),
            ("It came quite slowly and haphazardly, through casual thoughts that slipped into our conversation.",
             "Bu bilgiler, sohbetimize karışan gelişigüzel düşünceler aracılığıyla oldukça yavaş ve rastlantısal olarak geldi.",
             "haphazardly | Gelişigüzel, rastgele; 'casual' sıradan."),
            ("It was on the third day that I learned the grim truth about the catastrophic baobabs.",
             "Felaket getiren baobaplar hakkındaki o ürkütücü hakikati öğrendiğim gün üçüncü gündü.",
             "grim truth | Ürkütücü / karanlık hakikat; 'catastrophic' felaket getiren."),
            ("The Little Prince asked me abruptly, 'It is true, is it not, that sheep eat little bushes?'",
             "Küçük Prens bana birdenbire, 'Koyunların küçük çalıları yedikleri doğrudur, değil mi?' diye sordu.",
             "abruptly | Birdenbire, aniden; 'bushes' çalılar."),
            ("'Yes, that is true,' I answered without looking up from my work on the engine.",
             "Motordaki işimden başımı kaldırmaksızın, 'Evet, bu doğrudur,' diye yanıtladım.",
             "looking up from | Den başını kaldırmak."),
            ("'Ah, I am glad!' he cried, clearly relieved by my affirmative confirmation.",
             "Olumlu teyidimle bariz biçimde rahatlayarak, 'Ah, çok sevindim!' diye bağırdı.",
             "affirmative confirmation | Olumlu teyit / onay."),
            ("I did not understand why it was so important that sheep should consume little bushes.",
             "Koyunların küçük çalıları tüketmesinin neden bu denli önemli olduğunu anlayamamıştım.",
             "consume | Tüketmek, yemek; 'important' mühim."),
            ("He added, 'Then they eat baobab trees too, do they not?'",
             "Şunu ekledi: 'Öyleyse baobap ağaçlarını da yerler, değil mi?'",
             "baobab trees | Baobap ağaçları."),
            ("I pointed out to him that baobabs are not little bushes, but trees as tall as cathedrals.",
             "Ona baobapların küçük çalılar olmadığını, katedraller kadar yüksek ağaçlar olduğunu belirttim.",
             "tall as cathedrals | Katedraller kadar yüksek."),
            ("'Even if you brought a whole herd of elephants, they could not eat a single baobab tree.'",
             "'Bütün bir fil sürüsünü getirsen bile tek bir baobap ağacını yiyip bitiremezler.'",
             "herd of elephants | Fil sürüsü."),
            ("The idea of a herd of elephants made the Little Prince laugh merrily.",
             "Fil sürüsü fikri Küçük Prens'i neşeyle güldürdü.",
             "made laugh merrily | Neşeyle güldürmek."),
            ("'We would have to put them on top of one another!' he chuckled with sparkling eyes.",
             "Işıldayan gözlerle kıkırdayarak, 'Onları üst üste koymamız gerekirdi!' dedi.",
             "on top of one another | Üst üste."),
            ("Then he observed sagely, 'Before they grow so large, baobabs start out by being very small.'",
             "Sonra bilgece bir tespitte bulundu: 'O kadar büyümeden evvel baobaplar da işe çok küçük olarak başlarlar.'",
             "observed sagely | Bilgece gözlemde bulunmak / tespit etmek."),
            ("'That is strictly correct,' I agreed, 'but why do you want your sheep to eat the little baobabs?'",
             "'Bu tamamen doğru,' diyerek onayladım, 'fakat koyununun küçük baobapları yemesini neden istiyorsun?'",
             "strictly correct | Tamamen / harfiyen doğru."),
            ("He answered, 'Oh, come, come!' as if he were speaking of something entirely obvious.",
             "Sanki apaçık bir şeyden bahsediyormuş gibi, 'Hadi ama, bunu bilmeyecek ne var!' diye cevap verdi.",
             "entirely obvious | Tamamen apaçık / bariz."),
            ("It required an enormous mental effort for me to comprehend this problem by myself.",
             "Bu meseleyi kendi başıma kavramak benim için muazzam bir zihinsel çaba gerektirdi.",
             "comprehend | Anlamak, kavramak; 'mental effort' zihinsel çaba."),
            ("On the Little Prince's planet, as on all planets, there were good plants and bad weeds.",
             "Küçük Prens'in gezegeninde de bütün gezegenlerde olduğu gibi hem faydalı bitkiler hem zararlı yabani otlar vardı.",
             "good plants and weeds | Faydalı bitkiler ve yabani otlar."),
            ("The soil of his tiny world was infested with the microscopic seeds of terrible baobab trees.",
             "Onun ufacık dünyasının toprağı, korkunç baobap ağaçlarının mikroskobik tohumlarıyla dolup taşmıştı.",
             "infested with | İle sarılmış / istilaya uğramış."),
            ("If a baobab is not uprooted as soon as it sprouts, it will spread roots through the whole asteroid.",
             "Bir baobap filizlenir filizlenmez kökünden sökülmezse bütün asteroide kök salar ve onu parçalar.",
             "uprooted | Kökünden sökülmüş; 'sprouts' filizlenir."),
            ("It is a question of daily discipline: every morning, one must faithfully weed out the baobabs.",
             "Bu bir günlük disiplin meselesidir: her sabah insan baobapları sadakatle ayıklamak zorundadır.",
             "daily discipline | Günlük disiplin; 'weed out' ayıklamak.")
        ],
        "vocab_focus": [
            ("haphazardly", "gelişigüzel, rastgele"),
            ("grim truth", "karanlık/korkunç hakikat"),
            ("affirmative", "olumlu, tasdik edici"),
            ("cathedrals", "katedraller, ulu mabetler"),
            ("sagely", "bilgece, basiretle"),
            ("comprehend", "kavramak, idrak etmek"),
            ("infested", "istila edilmiş, sarılmış"),
            ("weed out", "ayıklamak, temizlemek")
        ]
    },

    # PAGE 6: Chapter 6: Forty-Four Sunsets
    {
        "page_no": 6,
        "title": "Forty-Four Sunsets",
        "tr_title": "Kırk Dört Günbatımı",
        "sentences": [
            ("Oh, Little Prince, bit by bit I came to understand the secrets of your sad, quiet life!",
             "Ah Küçük Prens, senin o hüzünlü, sessiz hayatının sırlarını azar azar anlamaya başladım!",
             "bit by bit | Azar azar, yavaş yavaş."),
            ("For a long time, your only recreation had been the gentle melancholy of sunsets.",
             "Uzun bir süre boyunca senin yegane eğlencen günbatımlarının o tatlı hüznü olmuştu.",
             "recreation | Eğlence, dinlence; 'melancholy' hüzün."),
            ("I learned this new detail on the morning of the fourth day, when you said to me softly:",
             "Bu yeni detayı dördüncü günün sabahında, bana usulca şöyle dediğinde öğrendim:",
             "learned detail | Detayı öğrendi."),
            ("'I am very fond of sunsets; come, let us go and watch a sunset right now.'",
             "'Günbatımlarını çok severim; gel, hemen şimdi gidip bir günbatımı seyredelim.'",
             "fond of sunsets | Günbatımlarına düşkün / seven."),
            ("'But we must wait,' I said, puzzled by his unexpected request.",
             "Beklenmedik isteği karşısında şaşırarak, 'Fakat beklememiz gerekir,' dedim.",
             "puzzled by | İle şaşırmış; 'unexpected request' beklenmedik istek."),
            ("'Wait? For what?' the Little Prince asked with genuine bewilderment in his eyes.",
             "Küçük Prens gözlerinde hakiki bir şaşkınlıkla, 'Beklemek mi? Neyi bekleyeceğiz?' diye sordu.",
             "genuine bewilderment | Hakiki şaşkınlık / afallama."),
            ("'Wait for the sun to go down, of course; we must wait for evening to arrive.'",
             "'Güneşin batmasını elbette; akşamın gelmesini beklemeliyiz.'",
             "wait for evening | Akşamı beklemek."),
            ("At first, he seemed intensely surprised, and then he laughed merrily at himself.",
             "İlk başta son derece şaşırmış göründü, ardından kendi haline neşeyle güldü.",
             "intensely surprised | Son derece şaşırmış."),
            ("'I am always imagining that I am at home on my own planet!' he explained with a smile.",
             "Gülümseyerek, 'Kendimi daima kendi gezegenimde, evimde sanıyorum!' diye açıkladı.",
             "imagining | Hayal etmek / sanmak."),
            ("Everybody knows that when it is noon in the United States, the sun is setting over France.",
             "Amerika Birleşik Devletleri'nde öğle vaktiyken Fransa'da güneşin batmakta olduğunu herkes bilir.",
             "sun is setting | Güneş batıyor."),
            ("If you could travel to France in one minute, you could watch the sunset immediately.",
             "Fransa'ya bir dakikada gidebilseydiniz günbatımını hemen o an izleyebilirdiniz.",
             "travel in one minute | Bir dakikada gitmek."),
            ("Unfortunately, France is far too distant for such instantaneous terrestrial voyages.",
             "Ne yazık ki Fransa böylesi anlık karasal yolculuklar için fazlasıyla uzaktır.",
             "instantaneous | Anlık, bir anda olan; 'terrestrial' karasal."),
            ("But on your tiny asteroid, all you had to do was move your chair a few steps.",
             "Fakat senin o ufacık asteroitinde tek yapman gereken sandalyeni birkaç adım ilerletmekti.",
             "move your chair | Sandalyeni hareket ettirmek."),
            ("You could watch the twilight falling whenever you had the slightest desire.",
             "Canın ne zaman isterse akşam alacakaranlığının çöküşünü dilediğince seyredebiliyordun.",
             "twilight falling | Alacakaranlığın çöküşü; 'slightest desire' en ufak arzu."),
            ("'One day,' you said to me, 'I saw the sunset forty-four times within twenty-four hours!'",
             "Bana, 'Bir keresinde,' dedin, 'yirmi dört saat içinde güneşin tam kırk dört kez battığını gördüm!'",
             "forty-four times | Kırk dört kez."),
            ("And a little later you added pensively, 'You know, when one is so terribly sad, one loves sunsets.'",
             "Ve biraz sonra düşünceli bir halde ekledin: 'Bilirsin ya, insan çok ama çok kederliyken günbatımlarını sever.'",
             "terribly sad | Çok / kahredici biçimde kederli."),
            ("'Were you so terribly sad, then, on the day of the forty-four sunsets?' I asked gently.",
             "Şefkatle, 'O kırk dört günbatımı gününde o kadar çok mu kederliydin peki?' diye sordum.",
             "asked gently | Şefkatle / nazikçe sormak."),
            ("The Little Prince made no answer, gazing quietly across the golden desert dunes.",
             "Küçük Prens altın çöl kumullarına doğru sakince bakarak hiçbir cevap vermedi.",
             "desert dunes | Çöl kumulları; 'made no answer' cevap vermedi."),
            ("His silence spoke more eloquently than words of the solitary grief that filled his heart.",
             "Onun bu sessizliği, yüreğini dolduran o kimsesiz kederi kelimelerden çok daha beliğ bir şekilde anlatıyordu.",
             "spoke eloquently | Beliğ / etkileyici biçimde anlatmak; 'solitary grief' kimsesiz keder."),
            ("A sunset shared with a companion brings solace to even the deepest and darkest sorrow.",
             "Bir dostla paylaşılan günbatımı, en derin ve en karanlık kedere bile teselli getirir.",
             "brings solace | Teselli getirmek / dindirmek.")
        ],
        "vocab_focus": [
            ("melancholy", "hüzün, kederli duygu"),
            ("bewilderment", "şaşkınlık, afallama"),
            ("instantaneous", "anlık, bir anda gerçekleşen"),
            ("terrestrial", "yeryüzüne ait, karasal"),
            ("twilight", "alacakaranlık"),
            ("pensively", "düşünceli bir edayla"),
            ("dunes", "kumullar, kum tepeleri"),
            ("solace", "teselli, avuntu")
        ]
    },

    # PAGE 7: Chapter 7: The Secret of the Thorns and Tears
    {
        "page_no": 7,
        "title": "Thorns and Secret Tears",
        "tr_title": "Dikenlerin Sırrı ve Gözyaşları",
        "sentences": [
            ("On the fifth day, thanks again to the sheep, another secret of the Little Prince's life was revealed.",
             "Beşinci gün, yine koyun sayesinde, Küçük Prens'in hayatının bir başka sırrı daha açığa çıktı.",
             "was revealed | Açığa çıktı / ifşa edildi."),
            ("He asked me abruptly, without preface, 'If a sheep eats bushes, does it eat flowers too?'",
             "Bana hiçbir girizgah yapmadan birdenbire, 'Bir koyun çalıları yiyorsa çiçekleri de yer mi?' diye sordu.",
             "without preface | Girizgah / ön söz olmadan; 'abruptly' aniden."),
            ("'A sheep eats whatever it finds in its path,' I answered, my mind absorbed in repairing my plane.",
             "Zihnim uçağımı tamir etmeye dalmış halde, 'Bir koyun yolunda ne bulursa onu yer,' diye yanıtladım.",
             "absorbed in | Bir şeye dalmış / gömülmüş olmak."),
            ("'Even flowers that possess sharp thorns?' inquired the Little Prince anxiously.",
             "Küçük Prens endişeyle, 'Sivri dikenleri olan çiçekleri bile mi?' diye sordu.",
             "sharp thorns | Sivri dikenler; 'anxiously' endişeyle."),
            ("'Yes, even flowers with sharp thorns,' I replied impatiently, struggling with a stubborn bolt.",
             "İnatçı bir cıvatayla mücadele ederken sabırsızlıkla, 'Evet, sivri dikenli çiçekleri bile,' diye karşılık verdim.",
             "stubborn bolt | İnatçı cıvata; 'impatiently' sabırsızlıkla."),
            ("'Then what purpose do thorns serve if they cannot protect the plant?' he persisted.",
             "Israr etti: 'O halde çiçeği koruyamıyorlarsa dikenler ne amaca hizmet eder?'",
             "what purpose serve | Hangi amaca hizmet etmek; 'persisted' üsteledi."),
            ("My engine was leaking fuel, my water was dwindling, and I feared the very worst.",
             "Motorum yakıt sızdırıyordu, suyum tükenmekteydi ve en kötüsünden korkuyordum.",
             "leaking fuel | Yakıt sızdıran; 'dwindling' azalan, tükenen."),
            ("'Thorns serve no purpose whatsoever; they are merely pure malice on the part of flowers!' I snapped.",
             "Terslenerek, 'Dikenler hiçbir işe yaramaz; yalnızca çiçeklerin katıksız bir kötülüğüdür!' diye çıkıştım.",
             "pure malice | Katıksız kötülük / hinlik; 'snapped' terslendi."),
            ("The Little Prince looked at me with immense shock and indignation in his golden eyes.",
             "Küçük Prens altın sarısı gözlerinde muazzam bir şok ve hiddetle bana baktı.",
             "indignation | Hiddet, haklı öfke; 'immense shock' büyük şok."),
            ("'I do not believe you!' he cried with trembling lips; 'flowers are weak and naive creatures!'",
             "Titreyen dudaklarıyla haykırdı: 'Sana inanmıyorum! Çiçekler zayıf ve saf yaratıklardır!'",
             "naive creatures | Saf / masum yaratıklar."),
            ("'They reassure themselves as best they can; they believe their thorns make them terrible!'",
             "'Ellerinden geldiğince kendilerini teselli ederler; dikenlerinin kendilerini korkunç kıldığına inanırlar!'",
             "reassure themselves | Kendilerini teselli etmek."),
            ("I made no reply, for I was muttering to myself that my hammer would loosen the bolt.",
             "Hiçbir cevap vermedim; zira çekiçimin bu cıvatayı gevşeteceğini kendi kendime mırıldanıyordum.",
             "loosen the bolt | Cıvatayı gevşetmek; 'hammer' çekiç."),
            ("'And you actually believe,' he resumed furiously, 'that flowers make thorns out of spite?'",
             "Öfkeyle devam etti: 'Ve sen sahiden çiçeklerin dikenleri kinlerinden dolayı yaptıklarına mı inanıyorsun?'",
             "out of spite | Kindarlık / gıcıklık olsun diye."),
            ("'No, no!' I shouted, losing my temper, 'I am busy here with matters of genuine consequence!'",
             "Tepem atarak haykırdım: 'Hayır, hayır! Ben burada hakiki ehemmiyete sahip ciddi meselelerle meşgulüm!'",
             "matters of consequence | Önemli / mühim meseleler; 'losing temper' öfkelenmek."),
            ("He stared at me, thunderstruck, watching me hold a greasy wrench over a black engine.",
             "Kara bir motorun üzerinde yağlı bir anahtar tutuşumu izleyerek yıldırım çarpmış gibi bana baktı.",
             "thunderstruck | Yıldırım çarpmışa dönmüş; 'wrench' İngiliz anahtarı."),
            ("'You speak just like the grown-ups!' he exclaimed with bitter tears welling in his eyes.",
             "Gözlerinde acı yaşlar birikerek haykırdı: 'Tıpkı büyükler gibi konuşuyorsun!'",
             "tears welling | Gözlerin yaşla dolması."),
            ("'You confuse everything... you mix up what is truly essential with what is utterly meaningless!'",
             "'Her şeyi birbirine karıştırıyorsun... neyin hakikaten önemli olduğuyla neyin anlamsız olduğunu karıştırıyorsun!'",
             "confuse everything | Her şeyi birbirine karıştırmak."),
            ("'If someone loves a flower of which only one specimen exists in millions of stars, that is enough!'",
             "'Biri milyonlarca yıldız arasında sadece tek bir örneği bulunan bir çiçeği seviyorsa, bu ona yeter!'",
             "specimen exists | Örneği bulunmak."),
            ("He could speak no more, and suddenly burst into sobbing tears under the starry desert sky.",
             "Daha fazla konuşamadı ve yıldızlı çöl göğünün altında ansızın hıçkırıklara boğuldu.",
             "burst into tears | Gözyaşlarına boğulmak."),
            ("It is such a secret, mysterious place, the land of tears, where love and sorrow meet.",
             "Aşk ile kederin buluştuğu o gözyaşı diyarı, öylesine gizemli, öylesine sır dolu bir yerdir ki!",
             "land of tears | Gözyaşı diyarı / ülkesi.")
        ],
        "vocab_focus": [
            ("absorbed in", "bir şeye dalmış"),
            ("thorns", "dikenler"),
            ("dwindling", "tükenen, azalan"),
            ("pure malice", "katıksız kötülük/kin"),
            ("reassure", "güvence vermek, teselli etmek"),
            ("matters of consequence", "ciddi ve önemli meseleler"),
            ("thunderstruck", "yıldırım çarpmışa dönmüş"),
            ("land of tears", "gözyaşları diyarı")
        ]
    },

    # PAGE 8: Chapter 8: The Birth of the Unique Rose
    {
        "page_no": 8,
        "title": "The Birth of the Rose",
        "tr_title": "Eşsiz Gülün Doğuşu",
        "sentences": [
            ("I soon came to know this mysterious flower better, for she had sprouted on the prince's planet.",
             "Küçük prensin gezegeninde filizlendiği için bu gizemli çiçeği çok geçmeden daha yakından tanıdım.",
             "came to know | Tanımaya başlamak; 'sprouted' filizlendi."),
            ("There had always been simple flowers on his asteroid, which possessed only one single ring of petals.",
             "Asteroitinde her zaman, yalnızca tek bir taç yaprak halkasına sahip sade çiçekler var olmuştu.",
             "ring of petals | Taç yaprak halkası."),
            ("They took up no room, bothered no one, and faded away quietly into the evening breeze.",
             "Hiç yer kaplamaz, kimseyi rahatsız etmez ve akşam esintisinde sakince solup giderlerdi.",
             "faded away | Solup gitmek; 'took up no room' hiç yer kaplamazdı."),
            ("But this new sprout had grown from a seed brought from who knows where across the cosmos.",
             "Fakat bu yeni filiz, evrenin kimbilir neresinden getirilmiş bir tohumdan boy vermişti.",
             "across the cosmos | Evrenin dört bir yanından; 'sprout' filiz."),
            ("The Little Prince had watched the new stem very closely, fearing it might be a new variety of baobab.",
             "Küçük Prens yeni bir baobap türü olabileceğinden korkarak yeni sapı çok yakından gözlemlemişti.",
             "new variety | Yeni bir tür; 'stem' bitki sapı."),
            ("However, the shrub soon ceased growing and began to prepare a magnificent blossom.",
             "Bununla birlikte çalı kısa sürede uzamayı kesti ve muhteşem bir çiçek hazırlamaya başladı.",
             "magnificent blossom | Muhteşem çiçek; 'shrub' çalı."),
            ("The Little Prince sensed that a miraculous apparition would presently emerge from the green chamber.",
             "Küçük Prens yeşil odacığın içinden az sonra mucizevi bir güzelliğin belireceğini hissetmişti.",
             "miraculous apparition | Mucizevi hayalet / güzellik; 'presently' az sonra."),
            ("Yet the flower was never done with her coquettish preparations inside her secret green room.",
             "Yine de çiçek gizli yeşil odasının içinde o cilveli hazırlıklarını bir türlü bitirmek bilmiyordu.",
             "coquettish preparations | Cilveli / nazlı hazırlıklar."),
            ("She chose her vibrant colors with the greatest care and adjusted her petals one by one.",
             "Göz alıcı renklerini en büyük özenle seçti ve taç yapraklarını teker teker düzeltti.",
             "vibrant colors | Canlı / göz alıcı renkler; 'adjusted' düzeltti."),
            ("She did not wish to go out into the world all crumpled like the common field poppies.",
             "Sıradan tarla gelincikleri gibi buruş buruş bir halde dünyaya çıkmak istemiyordu.",
             "crumpled | Buruşuk, kırışık; 'field poppies' tarla gelincikleri."),
            ("She wished to appear only in the full radiance of her incomparable beauty and splendor.",
             "Yalnızca emsalsiz güzelliğinin ve ihtişamının tam parlaklığı içinde görünmek arzusundaydı.",
             "full radiance | Tam ışıltı / parlaklık; 'splendor' ihtişam."),
            ("Her mysterious toilet had lasted for days, until suddenly, one morning at sunrise, she revealed herself.",
             "Gizemli süslenmesi günlerce sürdü; ta ki bir sabah gündoğumunda aniden kendini gösterene kadar.",
             "mysterious toilet | Gizemli süslenme / giyinme; 'revealed herself' kendini gösterdi."),
            ("Yawning gracefully, she murmured, 'Ah, I am scarcely awake... I beg your pardon... my petals are still tousled.'",
             "Zarifçe esneyerek, 'Ah, henüz zar zor uyandım... kusuruma bakmayın... yapraklarım hala darmadağınık,' diye mırıldandı.",
             "tousled | Darmadağınık, taranmamış; 'scarcely awake' henüz uyanmış."),
            ("The Little Prince could not restrain his boundless admiration: 'How extraordinarily beautiful you are!'",
             "Küçük Prens sınırsız hayranlığını zaptedemedi: 'Ne kadar da olağanüstü güzelsiniz!'",
             "restrain admiration | Hayranlığını zaptetmek / dizginlemek."),
            ("'Am I not?' the flower responded softly, 'and I was born at the very same moment as the sun.'",
             "Çiçek usulca, 'Öyle değil miyim ama?' diye yanıtladı, 'üstelik tam da güneşle aynı anda doğdum.'",
             "responded softly | Usulca yanıtlamak."),
            ("The Little Prince noticed that she was not excessively modest, but she was exquisitely moving.",
             "Küçük Prens onun aşırı derecede mütevazı olmadığını fark etti; fakat nefis biçimde dokunaklıydı.",
             "exquisitely moving | Nefis derecede dokunaklı / etkileyici."),
            ("'I believe it is breakfast time,' she soon added; 'would you have the kindness to remember me?'",
             "Çok geçmeden, 'Sanırım kahvaltı vakti,' diye ekledi; 'bana ikramda bulunma nezaketini gösterir miydiniz?'",
             "breakfast time | Kahvaltı vakti; 'kindness' nezaket."),
            ("Abashed and contrite, the prince went to fetch a watering-can of fresh, cool water.",
             "Mahcup ve pişman olan prens, taze ve serin su dolu bir sulama kabı getirmeye gitti.",
             "abashed and contrite | Mahcup ve pişman; 'watering-can' sulama kabı."),
            ("He tended the demanding flower tenderly, serving her with devoted love and patience.",
             "O talepkar çiçeğe şefkatle baktı; ona adanmış bir aşk ve sabırla hizmet etti.",
             "tended tenderly | Şefkatle bakmak; 'demanding' talepkar."),
            ("Yet her vanity, touchy pride, and whimsical doubts soon tormented the young prince's innocent heart.",
             "Fakat çiçeğin kibri, alıngan gururu ve kaprisli şüpheleri çok geçmeden genç prensin masum yüreğine ızdırap verdi.",
             "whimsical doubts | Kaprisli şüpheler; 'tormented' ızdırap verdi.")
        ],
        "vocab_focus": [
            ("ring of petals", "taç yaprak halkası"),
            ("sprout", "filiz, taze sürgün"),
            ("apparition", "beliriş, hayalet, harika"),
            ("coquettish", "cilveli, nazlı"),
            ("radiance", "ışıltı, parlaklık"),
            ("tousled", "darmadağınık, karışık"),
            ("abashed", "mahcup olmuş, utanmış"),
            ("tormented", "ızdırap çekti, eziyet gördü")
        ]
    },

    # PAGE 9: Chapter 9: The Departure from the Asteroid
    {
        "page_no": 9,
        "title": "The Departure",
        "tr_title": "Gezegenden Ayrılış",
        "sentences": [
            ("I believe that for his escape, the Little Prince took advantage of a migration of wild birds.",
             "Kaçışı için Küçük Prens'in göç eden bir yaban kuşu sürüsünden yararlandığına inanıyorum.",
             "took advantage of | Bir şeyden yararlanmak / fırsat bilmek; 'migration' göç."),
            ("On the morning of his departure, he put his entire planet in impeccable order.",
             "Ayrılışının sabahında, bütün gezegenini kusursuz bir intizama soktu.",
             "impeccable order | Kusursuz intizam / düzen; 'departure' ayrılış."),
            ("He carefully cleaned out his active volcanoes, using a small scraper to clear away soot.",
             "İsli kalıntıları temizlemek için küçük bir kazıyıcı kullanarak aktif volkanlarını dikkatle temizledi.",
             "active volcanoes | Aktif yanardağlar; 'soot' is, kurum."),
            ("He possessed two active volcanoes, which were exceedingly convenient for warming his morning breakfast.",
             "Sabah kahvaltısını ısıtmak için son derece elverişli olan iki aktif volkanı vardı.",
             "exceedingly convenient | Son derece elverişli / pratik."),
            ("He also had one extinct volcano, but as he wisely said, 'One never knows what may happen!'",
             "Ayrıca bir de sönmüş volkanı vardı; ama bilgece dediği gibi: 'İnsanın başına ne geleceği hiç bilinmez!'",
             "extinct volcano | Sönmüş yanardağ."),
            ("So he carefully cleaned out the extinct volcano too, making sure all vents were clear.",
             "Böylece bütün bacaların açık olduğundan emin olarak sönmüş volkanı da dikkatle temizledi.",
             "vents | Havalandırma bacaları / menfezler."),
            ("He also pulled up, with a touch of melancholy, the last remaining sprouts of baobabs.",
             "Ayrıca hafif bir hüzünle, geriye kalan son baobap filizlerini de kökünden söktü.",
             "touch of melancholy | Hafif bir hüzün; 'pulled up' kökünden söktü."),
            ("He believed that he would never want to return to his solitary kingdom again.",
             "O kimsesiz krallığına bir daha asla geri dönmek istemeyeceğine inanıyordu.",
             "solitary kingdom | Kimsesiz / tenha krallık."),
            ("All these familiar tasks seemed exceedingly precious to him on that final morning.",
             "Bütün bu alışıldık vazifeler o son sabahta ona son derece kıymetli göründü.",
             "familiar tasks | Alışıldık / tanıdık işler; 'precious' kıymetli."),
            ("When he watered the flower for the last time and prepared to cover her with her glass globe, he wept.",
             "Çiçeği son kez suladığında ve onu cam fanusuyla örtmeye hazırlandığında gözyaşlarına boğuldu.",
             "glass globe | Cam fanus / küre; 'wept' ağladı."),
            ("'Farewell,' he said to the rose softly, his voice trembling with hidden emotion.",
             "Sesi gizli bir duyguyla titreyerek güle usulca, 'Elveda,' dedi.",
             "farewell | Elveda, hoşça kal."),
            ("She did not answer him at once, but coughed gently to conceal her deep confusion.",
             "Çiçek ona hemen cevap vermedi; fakat derin şaşkınlığını gizlemek için usulca öksürdü.",
             "conceal confusion | Şaşkınlığını gizlemek."),
            ("'Farewell,' repeated the Little Prince, waiting patiently for her final words.",
             "Küçük Prens onun son sözlerini sabırla bekleyerek, 'Elveda,' diye tekrarladı.",
             "repeated patiently | Sabırla tekrarladı."),
            ("'I have been silly,' she said at last; 'I ask your pardon, and I hope you will be happy.'",
             "Nihayet, 'Ahmaklık ettim,' dedi çiçek; 'özür dilerim ve umarım mutlu olursun.'",
             "ask your pardon | Özür dilemek / affını istemek."),
            ("He was astonished by the absence of reproaches, standing motionless with the globe in his hands.",
             "Hiçbir sitem ve kınama olmamasına şaşıran prens, ellerinde fanusla hareketsizce kalakaldı.",
             "absence of reproaches | Sitemlerin / azarların yokluğu; 'motionless' hareketsiz."),
            ("'Of course I love you,' said the flower gently; 'it is my fault that you never knew it.'",
             "Çiçek nazikçe, 'Elbette seni seviyorum,' dedi; 'bunu hiç bilememiş olman benim hatamdır.'",
             "my fault | Benim hatam."),
            ("'That does not matter now; but you were just as foolish as I was; try to be happy.'",
             "'Bunun artık hiçbir önemi yok; fakat sen de benim kadar ahmaktın; mutlu olmaya çalış.'",
             "just as foolish | Tıpkı onun kadar ahmak."),
            ("'Leave the glass globe alone; I do not want it any more; the night breeze will do me good.'",
             "'Cam fanusu bir kenara bırak; onu artık istemiyorum; gece esintisi bana iyi gelecektir.'",
             "night breeze | Gece esintisi; 'do me good' iyi gelmek."),
            ("'I must endure the presence of two or three caterpillars if I wish to become acquainted with butterflies.'",
             "'Kelebeklerle tanışmak istiyorsam iki ya da üç tırtılın varlığına katlanmak zorundayım.'",
             "endure caterpillars | Tırtıllara katlanmak; 'butterflies' kelebekler."),
            ("She urged him to leave quickly, for she was a proud flower and did not want him to see her weeping.",
             "Çabucak ayrılması için üsteledi; zira mağrur bir çiçekti ve ağladığını görmesini hiç istemiyordu.",
             "proud flower | Mağrur çiçek; 'urged to leave' ayrılması için üsteledi.")
        ],
        "vocab_focus": [
            ("migration", "göç"),
            ("impeccable", "kusursuz, lekesiz"),
            ("scraper", "kazıyıcı alet"),
            ("vents", "havalandırma bacaları"),
            ("glass globe", "cam fanus"),
            ("absence", "yokluk, bulunmama"),
            ("reproaches", "sitemler, azarlar"),
            ("endure", "dayanmak, katlanmak")
        ]
    },

    # PAGE 10: Chapter 10: The King of the First Asteroid
    {
        "page_no": 10,
        "title": "The King of the Asteroid",
        "tr_title": "Birinci Gezegendeki Kral",
        "sentences": [
            ("The Little Prince found himself in the neighborhood of Asteroids 325, 326, 327, 328, 329, and 330.",
             "Küçük Prens kendini 325, 326, 327, 328, 329 ve 330 numaralı asteroitlerin civarında buldu.",
             "neighborhood | Civar, muhit, mahalle."),
            ("He began by visiting them in order to find something to do and to instruct himself.",
             "Yapacak bir şeyler bulmak ve kendini eğitmek amacıyla onları ziyaret ederek işe başladı.",
             "instruct himself | Kendini eğitmek / bilgi edinmek."),
            ("The first planet was inhabited by an absolute monarch clad in royal purple and ermine robes.",
             "İlk gezegende, erguvani krallık kaftanı ve kakım kürküne bürünmüş mutlak bir hükümdar yaşıyordu.",
             "absolute monarch | Mutlak hükümdar / monark; 'clad in' kuşanmış."),
            ("He was seated upon a throne which was at the same time very simple and extremely majestic.",
             "Aynı anda hem çok sade hem de son derece görkemli olan bir tahtın üzerine oturmuştu.",
             "majestic throne | Görkemli taht."),
            ("'Ah! Here is a subject!' exclaimed the King when he caught sight of the Little Prince.",
             "Kral Küçük Prens'i görür görmez, 'Ah! İşte bir tebaa!' diye haykırdı.",
             "subject | Tebaa, buyruk altındaki vatandaş."),
            ("The Little Prince asked himself, 'How can he recognize me when he has never seen me before?'",
             "Küçük Prens kendi kendine, 'Beni daha önce hiç görmemişken nasıl tanıyabiliyor?' diye sordu.",
             "recognize | Tanımak, teşhis etmek."),
            ("He did not know that for kings, the entire world is simplified: all men are merely subjects.",
             "Krallar için bütün dünyanın basitleştirilmiş olduğunu bilmiyordu: tüm insanlar yalnızca birer tebaadır.",
             "simplified | Basitleştirilmiş; 'merely' yalnızca."),
            ("'Approach, so that I may see you better!' commanded the King, proud of having someone to rule.",
             "Yönetecek birine sahip olmaktan gururlanan Kral, 'Yaklaş ki seni daha iyi görebileyim!' diye buyurdu.",
             "commanded | Buyurdu, emretti."),
            ("The Little Prince looked around for a place to sit, but the planet was covered by the magnificent ermine mantle.",
             "Küçük Prens oturacak bir yer aradı; fakat gezegen muhteşem kakım kürkü pelerinle tamamen kaplanmıştı.",
             "ermine mantle | Kakım kürkünden pelerin / harmani."),
            ("So he remained standing upright, and since he was thoroughly exhausted, he yawned.",
             "Böylece ayakta dimdik kaldı ve büsbütün bitkin düştüğü için esnedi.",
             "yawned | Esnedi; 'standing upright' ayakta dimdik durmak."),
            ("'It is contrary to etiquette to yawn in the presence of a king,' the monarch informed him sternly.",
             "Hükümdar sertçe, 'Bir kralın huzurunda esnemek adabımuaşerete aykırıdır,' diye bildirdi.",
             "contrary to etiquette | Görgü kurallarına aykırı; 'sternly' sertçe."),
            ("'I forbid you to yawn!' added the King, adjusting his golden crown with dignity.",
             "Kral vakarla altın tacını düzelterek, 'Esnemeni yasaklıyorum!' diye ekledi.",
             "forbid | Yasaklamak; 'adjusting crown' tacı düzeltmek."),
            ("'I cannot help it,' answered the Little Prince, confused; 'I have made a long journey and had no sleep.'",
             "Aklı karışan Küçük Prens, 'Elimde değil,' diye yanıtladı; 'uzun bir yolculuk yaptım ve hiç uyumadım.'",
             "cannot help it | Elde olmamak / engel olamamak."),
            ("'Then I command you to yawn!' the King decreed hastily; 'I have not seen anyone yawn for years.'",
             "Kral aceleyle, 'O halde esnemeni emrediyorum!' diye ferman buyurdu; 'yıllardır kimsenin esnediğini görmedim.'",
             "decreed | Hüküm verdi, ferman buyurdu."),
            ("The Little Prince blushed: 'I cannot yawn any more... that has frightened me,' he murmured.",
             "Küçük Prens kızardı: 'Artık esneyemiyorum... bu beni ürküttü,' diye mırıldandı.",
             "blushed | Yüzü kızardı; 'frightened' ürküttü."),
            ("The King tolerated no insubordination, for he was an absolute monarch, yet he was a reasonable man.",
             "Kral itaatsizliğe asla müsamaha göstermezdi, zira mutlak bir monarktı; yine de makul bir adamdı.",
             "tolerated no insubordination | İtaatsizliğe hiç tahammül etmemek; 'reasonable' makul."),
            ("'One must require from each person what each person can realistically perform,' he explained.",
             "'İnsanın her kişiden, o kişinin gerçekçi biçimde yapabileceği şeyi talep etmesi gerekir,' diye açıkladı.",
             "realistically perform | Gerçekçi biçimde yerine getirmek."),
            ("'Authority rests first of all upon reason; if you command your people to jump into the sea, they will revolt.'",
             "'Otorite her şeyden önce akla dayanır; halkına denize atlamasını emredersen isyan çıkarırlar.'",
             "rests upon reason | Akla dayanmak; 'revolt' isyan etmek."),
            ("'I have the right to demand obedience because my royal commands are always reasonable.'",
             "'İtaat talep etmeye hakkım vardır; çünkü kraliyet emirlerim daima makuldür.'",
             "demand obedience | İtaat talep etmek."),
            ("The Little Prince departed, thinking to himself that grown-ups are truly extraordinary creatures.",
             "Küçük Prens, büyüklerin hakikaten olağanüstü yaratıklar olduğunu kendi kendine düşünerek oradan ayrıldı.",
             "departed | Ayrıldı; 'extraordinary' olağanüstü.")
        ],
        "vocab_focus": [
            ("absolute monarch", "mutlak hükümdar"),
            ("subject", "tebaa, buyruk altındaki kişi"),
            ("simplified", "basitleştirilmiş"),
            ("etiquette", "görgü kuralları, adap"),
            ("decreed", "ferman buyurdu, hükmetti"),
            ("insubordination", "itaatsizlik, başkaldırı"),
            ("reasonable", "makul, akla yatkın"),
            ("obedience", "itaat, boyun eğme")
        ]
    }
]

pages_11_to_15 = [
    # PAGE 11: Chapter 11: The Conceited Man
    {
        "page_no": 11,
        "title": "The Conceited Man",
        "tr_title": "Kendini Beğenmiş Adam",
        "sentences": [
            ("The second planet was inhabited by a conceited man wearing an absurdly shaped hat.",
             "İkinci gezegende, saçma biçimli bir şapka takmış olan kendini beğenmiş bir adam yaşıyordu.",
             "conceited | Kendini beğenmiş, kibirli; 'absurdly' saçma biçimde."),
            ("'Ah! Ah! I am about to receive a visit from an admirer!' he cried from afar.",
             "Uzaktan, 'Aha! Bir hayranım tarafından ziyaret edilmek üzereyim!' diye haykırdı.",
             "admirer | Hayran, takdirkar."),
            ("For, to conceited men, all other human beings in the universe are mere admirers.",
             "Zira kendini beğenmiş adamlara göre evrendeki diğer tüm insanlar yalnızca birer hayrandır.",
             "mere admirers | Yalnızca birer hayran."),
            ("'Good morning,' said the Little Prince; 'that is a very curious hat you are wearing.'",
             "Küçük Prens, 'Günaydın,' dedi; 'taktığınız çok tuhaf bir şapka.'",
             "curious hat | Tuhaf / ilginç şapka."),
            ("'It is an instrument for tipping,' the conceited man replied with supreme self-importance.",
             "Kendini beğenmiş adam üstün bir caka ile, 'Selam vermek maksadıyla şapka çıkarmaya yarayan bir alettir,' dedi.",
             "tipping | Şapkayı eğerek selam verme; 'self-importance' kendini önemseme."),
            ("'It is for raising in salute when people acclaim me with thunderous applause.'",
             "'İnsanlar beni gök gürültülü alkışlarla karşıladıklarında selam vermek üzere yukarı kaldırmak içindir.'",
             "acclaim | Alkışlamak, tezahürat yapmak; 'thunderous' gök gürültüsü gibi."),
            ("'Unfortunately, nobody ever passes by this solitary way,' he added with a sigh.",
             "Bir iç çekişle, 'Ne yazık ki bu ıssız yoldan hiç kimse geçmez,' diye ekledi.",
             "solitary way | Issız / kimsesiz yol."),
            ("'Really?' said the Little Prince, not comprehending the man's bizarre obsession.",
             "Adamın tuhaf takıntısını anlayamayan Küçük Prens, 'Sahiden mi?' dedi.",
             "bizarre obsession | Tuhaf / acayip takıntı."),
            ("'Clap your hands one against the other,' the conceited man directed eagerly.",
             "Kendini beğenmiş adam hevesle buyurdu: 'Ellerini birbirine vur, alkışla.'",
             "clap hands | El çırpmak, alkışlamak."),
            ("The Little Prince clapped his hands, and the conceited man tipped his hat modestly in salute.",
             "Küçük Prens ellerini çırptı ve kendini beğenmiş adam şapkasını mütevazı bir edayla eğerek selam verdi.",
             "tipped hat in salute | Şapkasını eğerek selam vermek."),
            ("'This is much more amusing than the visit to the old King,' the Little Prince said to himself.",
             "Küçük Prens kendi kendine, 'Bu yaşlı Kral'ı ziyaretten çok daha eğlenceli,' dedi.",
             "amusing | Eğlenceli, keyifli."),
            ("And he began to clap his hands again, watching the man repeat his polite gesture.",
             "Ve adamın kibar jestini tekrar etmesini izleyerek ellerini yeniden çırpmaya başladı.",
             "polite gesture | Kibar jest / hareket."),
            ("After five minutes of exercise, the Little Prince grew exceedingly tired of the monotony of the game.",
             "Beş dakikalık bu egzersizden sonra Küçük Prens oyunun tekdüzeliğinden son derece sıkıldı.",
             "monotony | Tekdüzelik, monotonluk; 'exceedingly tired' son derece sıkılmış."),
            ("'And what must one do to make the hat fall off?' he inquired innocently.",
             "Masumca, 'Peki şapkanın yere düşmesini sağlamak için ne yapmak gerekir?' diye sordu.",
             "inquired innocently | Masumca sormak."),
            ("But the conceited man did not hear him, for conceited people never hear anything but praise.",
             "Fakat kendini beğenmiş adam onu duymadı; zira kendini beğenmişler övgüden başka hiçbir şeyi asla duymazlar.",
             "hear but praise | Övgüden başkasını duymamak."),
            ("'Do you truly admire me very greatly?' he demanded of the young traveller.",
             "Genç yolcuya üsteleyerek sordu: 'Bana sahiden çok büyük bir hayranlık duyuyor musun?'",
             "truly admire | Hakikaten hayranlık duymak."),
            ("'What does that mean — to admire?' asked the Little Prince in genuine perplexity.",
             "Küçük Prens hakiki bir kafa karışıklığıyla, 'Hayranlık duymak ne demektir?' diye sordu.",
             "genuine perplexity | Hakiki kafa karışıklığı."),
            ("'To admire means to acknowledge that I am the handsomest, richest, and most intelligent man on the planet.'",
             "'Hayran olmak; gezegendeki en yakışıklı, en zengin ve en zeki adam olduğumu kabul etmek demektir.'",
             "acknowledge | Kabul etmek, tasdik etmek."),
            ("'But you are the only man on your planet!' exclaimed the boy in surprise.",
             "Çocuk hayretle, 'Fakat gezegenindeki tek insan sensin!' diye haykırdı.",
             "only man | Tek insan."),
            ("'Do me this favor; admire me nevertheless!' whispered the vain man, and the prince departed in wonder.",
             "Kibirli adam, 'Bana bu iyiliği yap; yine de bana hayran ol!' diye fısıldadı ve prens hayretler içinde oradan ayrıldı.",
             "departed in wonder | Hayret içinde ayrılmak.")
        ],
        "vocab_focus": [
            ("conceited", "kendini beğenmiş"),
            ("admirer", "hayran, takdir eden"),
            ("self-importance", "kendini aşırı önemseme"),
            ("acclaim", "övgüyle alkışlamak"),
            ("gesture", "jest, hareket"),
            ("monotony", "tekdüzelik"),
            ("perplexity", "şaşkınlık, kafa karışıklığı"),
            ("acknowledge", "kabul etmek, onaylamak")
        ]
    },

    # PAGE 12: Chapter 12: The Businessman Counting Stars
    {
        "page_no": 12,
        "title": "The Businessman and the Stars",
        "tr_title": "Yıldızları Sayan İşadamı",
        "sentences": [
            ("The fourth planet belonged to a bustling businessman who was so absorbed that he did not even look up.",
             "Dördüncü gezegen, işine öyle dalmış olan telaşlı bir işadamına aitti ki başını yukarı bile kaldırmadı.",
             "bustling | Telaşlı, hareketli; 'absorbed' işine dalmış."),
            ("'Good morning,' said the Little Prince; 'your cigarette has gone out.'",
             "Küçük Prens, 'Günaydın,' dedi; 'sigaranız sönmüş.'",
             "cigarette gone out | Sigaranın sönmesi."),
            ("'Three and two make five; five and seven make twelve; twelve and three make fifteen,' muttered the man.",
             "Adam kendi kendine mırıldandı: 'Üç iki daha beş eder; beş yedi daha on iki eder; on iki üç daha on beş eder.'",
             "muttered | Kendi kendine mırıldandı."),
            ("'Fifteen and seven make twenty-two; twenty-two and six make twenty-eight; I have no time to relight it.'",
             "'On beş yedi daha yirmi iki; yirmi iki altı daha yirmi sekiz; onu yeniden yakacak hiç vaktim yok.'",
             "relight | Yeniden yakmak."),
            ("'Twenty-eight and three make thirty-one; phew! That makes five hundred and one million, six hundred and twenty-two thousand!'",
             "'Yirmi sekiz üç daha otuz bir; puf! Bu beş yüz bir milyon altı yüz yirmi iki bin eder!'",
             "phew | Yorulma nidası (puf/of)."),
            ("'Five hundred million what?' asked the Little Prince, curious as always.",
             "Her zamanki gibi meraklı olan Küçük Prens, 'Beş yüz milyon ne?' diye sordu.",
             "curious as always | Her zamanki gibi meraklı."),
            ("The businessman raised his head: 'During the fifty-four years I have inhabited this planet, I have been disturbed only three times.'",
             "İşadamı başını kaldırdı: 'Bu gezegende yaşadığım elli dört yıl boyunca yalnızca üç kez rahatsız edildim.'",
             "inhabited | Yaşadığı, mukim olduğu; 'disturbed' rahatsız edilmiş."),
            ("'I am a serious man; I do not amuse myself with nonsense; five hundred million of those little golden objects.'",
             "'Ben ciddi bir adamım; saçmalıklarla eğlenmem; o küçük altın sarısı nesnelerden beş yüz milyon tane.'",
             "amuse with nonsense | Saçmalıklarla eğlenmek."),
            ("'Do you mean flies?' asked the Little Prince.",
             "Küçük Prens, 'Sinekleri mi kastediyorsunuz?' diye sordu.",
             "flies | Sinekler."),
            ("'No, little glittering objects that make lazy people daydream in the evening.'",
             "'Hayır, akşamları tembel insanları hayallere daldıran o minik parıltılı nesneler.'",
             "glittering objects | Parıltılı nesneler; 'daydream' hayallere dalmak."),
            ("'Ah, you mean the stars!' said the prince.",
             "Prens, 'Ah, yıldızları kastediyorsunuz!' dedi.",
             "mean the stars | Yıldızları kastetmek."),
            ("'Yes, exactly, the stars,' confirmed the businessman; 'and what do you do with five hundred million stars?'",
             "İşadamı onayladı: 'Evet, tam olarak yıldızlar; peki sen beş yüz milyon yıldızla ne yaparsın?'",
             "confirmed | Onayladı, teyit etti."),
            ("'What do I do with them? I own them!' shouted the man with overwhelming financial pride.",
             "Adam ezici bir mali gururla, 'Onlarla ne mi yapıyorum? Onlara sahibim ben!' diye haykırdı.",
             "financial pride | Mali / parasal gurur; 'own them' onlara sahip olmak."),
            ("'And what good does it do you to own the stars?' inquired the puzzled boy.",
             "Şaşıran çocuk, 'Peki yıldızlara sahip olmak size ne fayda sağlar?' diye sordu.",
             "what good does it do | Ne fayda sağlar / neye yarar."),
            ("'It makes me rich; and if I am rich, I can buy more stars, if any more are ever discovered.'",
             "'Beni zengin yapar; zengin olursam, şayet daha fazlası keşfedilirse daha fazla yıldız satın alabilirim.'",
             "ever discovered | Hiç keşfedilirse."),
            ("'I myself,' said the Little Prince, 'own a flower which I water every day, and three volcanoes which I clean every week.'",
             "Küçük Prens, 'Ben kendim,' dedi, 'her gün suladığım bir çiçeğe ve her hafta temizlediğim üç yanardağa sahibim.'",
             "own a flower | Bir çiçeğe sahip olmak."),
            ("'It is of some use to my volcanoes, and it is of use to my flower, that I own them.'",
             "'Benim onlara sahip olmam yanardağlarım için bir faydadır ve çiçeğim için de bir faydadır.'",
             "of some use | Bir faydası olan / yararlı."),
            ("'But you are of no use whatever to the stars that you claim to possess.'",
             "'Fakat sizin sahip olduğunuzu iddia ettiğiniz yıldızlara zerre kadar hiçbir faydanız yok.'",
             "of no use whatever | Hiçbir surette faydası olmamak."),
            ("The businessman opened his mouth, but found nothing whatever to say in answer.",
             "İşadamı ağzını açtı ama cevap olarak söyleyecek hiçbir şey bulamadı.",
             "found nothing to say | Söyleyecek hiçbir şey bulamamak."),
            ("And the Little Prince went away on his travels, thinking that grown-ups are entirely extraordinary.",
             "Ve Küçük Prens büyüklerin tamamen olağanüstü acayip olduklarını düşünerek yolculuğuna devam etti.",
             "entirely extraordinary | Tamamen olağanüstü / tuhaf.")
        ],
        "vocab_focus": [
            ("bustling", "telaşlı, hareketli"),
            ("relight", "yeniden yakmak"),
            ("glittering", "parıldayan, ışıldayan"),
            ("financial", "mali, parasal"),
            ("puzzled", "şaşırmış, aklı karışmış"),
            ("of some use", "faydalı, işe yarar"),
            ("claim", "iddia etmek"),
            ("entirely", "tamamen, bütünüyle")
        ]
    },

    # PAGE 13: Chapter 13: The Lamplighter and his Duty
    {
        "page_no": 13,
        "title": "The Faithful Lamplighter",
        "tr_title": "Fenerci ve Sadık Görevi",
        "sentences": [
            ("The fifth planet was very strange; it was the smallest of all the asteroids the prince had visited.",
             "Beşinci gezegen çok tuhaftı; prensin ziyaret ettiği bütün asteroitlerin en küçüğüydü.",
             "smallest of all | Hepsinin en küçüğü."),
            ("There was just enough room on it for a single street lamp and a solitary lamplighter.",
             "Üzerinde yalnızca tek bir sokak lambası ve tek başına bir fenerci için yetecek kadar yer vardı.",
             "street lamp | Sokak lambası; 'solitary' yalnız, tek başına."),
            ("The Little Prince could not fathom what could be the use of a street lamp in the boundless sky.",
             "Küçük Prens uçsuz bucaksız gökyüzünde bir sokak lambasının ne işe yarayabileceğini bir türlü kavrayamadı.",
             "fathom | Anlamak, sırrına ermek, kavramak."),
            ("There were no houses on the planet, and no population to walk beneath its light.",
             "Gezegende ne evler vardı ne de ışığının altında yürüyecek bir ahali bulunuyordu.",
             "population | Nüfus, ahali."),
            ("However, he said to himself, 'It is very possible that this man is absurd, but he is less absurd than the others.'",
             "Bununla birlikte kendi kendine, 'Bu adamın saçma olması kuvvetle muhtemel; ama diğerlerinden daha az saçma,' dedi.",
             "less absurd | Daha az saçma."),
            ("'When he lights his street lamp, it is as if he brought one more star to life, or one more flower.'",
             "'Sokak lambasını yaktığında, sanki bir yıldızı daha veya bir çiçeği daha hayata döndürüyormuş gibi oluyor.'",
             "brought to life | Hayata döndürmek / canlandırmak."),
            ("'When he puts it out, he sends the flower or the star to sleep; it is a truly beautiful occupation.'",
             "'Onu söndürdüğünde ise çiçeği ya da yıldızı uykuya gönderiyor; bu hakikaten güzel bir meşgale.'",
             "beautiful occupation | Güzel bir meşgale / iş."),
            ("When he reached the planet, he greeted the lamplighter politely: 'Good morning. Why have you just put out your lamp?'",
             "Gezegene vardığında fenerciyi kibarca selamladı: 'Günaydın. Lambanızı neden az önce söndürdünüz?'",
             "put out lamp | Lambayı söndürmek."),
            ("'Those are the orders,' answered the lamplighter; 'good morning.'",
             "Fenerci, 'Emirler böyle,' diye yanıtladı; 'günaydın.'",
             "orders | Emirler, talimatlar."),
            ("'What are the orders?' asked the Little Prince.",
             "Küçük Prens, 'Emirler nedir?' diye sordu.",
             "What are the orders | Emirler nedir?"),
            ("'The orders are to put out my lamp; good evening,' and he immediately lit it again.",
             "'Emirler lambamı söndürmektir; iyi akşamlar,' ve onu derhal yeniden yaktı.",
             "lit it again | Onu yeniden yaktı."),
            ("'But why have you just lit it again?' asked the boy.",
             "Çocuk, 'Fakat neden az önce onu tekrar yaktınız?' diye sordu.",
             "why lit it again | Neden tekrar yaktın?"),
            ("'Those are the orders,' repeated the weary lamplighter, wiping his forehead with a red checkered handkerchief.",
             "Yorgun fenerci alnını kırmızı ekose bir mendille silerek, 'Emirler böyle,' diye tekrarladı.",
             "checkered handkerchief | Ekose mendil; 'weary' yorgun."),
            ("'I follow a terrible profession; once it was reasonable: I turned it off in the morning and on at night.'",
             "'Korkunç bir mesleği icra ediyorum; eskiden makuldü: sabahları söndürür, geceleri yakardım.'",
             "terrible profession | Korkunç meslek."),
            ("'Then the planet began to rotate faster and faster every year, but the orders have never been changed!'",
             "'Sonra gezegen her yıl daha hızlı ve daha hızlı dönmeye başladı; fakat emirler hiç değiştirilmedi!'",
             "rotate faster | Daha hızlı dönmek."),
            ("'Now it makes a complete revolution every minute, and I do not have a single second of rest!'",
             "'Artık her bir dakikada tam bir tur atıyor ve benim tek bir saniye bile dinlencem yok!'",
             "revolution | Devir, tam dönüş; 'rest' dinlenme."),
            ("'Every minute I have to light my lamp and put it out; each minute brings a whole new day!'",
             "'Her dakika lambamı yakmak ve söndürmek zorundayım; her dakika yepyeni bir gün getiriyor!'",
             "brings a new day | Yeni bir gün getirmek."),
            ("The Little Prince looked at him with tender affection; he loved this man who was so faithful to his orders.",
             "Küçük Prens ona derin bir şefkatle baktı; emirlerine böylesine sadık olan bu adamı çok sevmişti.",
             "tender affection | Derin şefkat / sevgi; 'faithful' sadık."),
            ("'Here is one man,' thought the prince, 'who would not be ridiculed by the King, the conceited man, or the businessman.'",
             "Prens, 'İşte,' diye düşündü, 'Kral, kendini beğenmiş adam veya işadamı tarafından alaya alınmayacak tek insan bu.'",
             "ridiculed | Alaya alınmış, dalga geçilmiş."),
            ("'Because he cares for something else besides himself; his labor has genuine meaning and devotion.'",
             "'Çünkü kendisinden başka bir şeyle ilgileniyor; onun emeği hakiki bir anlama ve adanmışlığa sahip.'",
             "labor | Emek, çalışma; 'devotion' adanmışlık.")
        ],
        "vocab_focus": [
            ("fathom", "kavramak, akıl erdirmek"),
            ("occupation", "meslek, meşgale"),
            ("orders", "emirler, talimatlar"),
            ("checkered", "ekose, kareli"),
            ("rotate", "kendi ekseninde dönmek"),
            ("revolution", "tam devir, dönüş"),
            ("faithful", "sadık, vefakar"),
            ("devotion", "adanmışlık, bağlılık")
        ]
    },

    # PAGE 14: Chapter 14: The Encounter with the Fox
    {
        "page_no": 14,
        "title": "The Fox and the Secret",
        "tr_title": "Tilki ile Karşılaşma ve Evcilleştirme",
        "sentences": [
            ("It was at this moment that the fox appeared beneath the apple tree on planet Earth.",
             "İşte tam bu anda Dünya gezegenindeki elma ağacının altında tilki çıkageldi.",
             "planet Earth | Dünya gezegeni; 'appeared' belirdi, ortaya çıktı."),
            ("'Good morning,' said the fox politely from the shadows of the fragrant orchard.",
             "Mis kokulu meyve bahçesinin gölgelerinden tilki nezaketle, 'Günaydın,' dedi.",
             "fragrant orchard | Mis kokulu meyve bahçesi."),
            ("'Good morning,' the Little Prince replied courteously, though when he turned around he saw nothing.",
             "Küçük Prens etrafına döndüğünde hiçbir şey görmemesine rağmen kibarca, 'Günaydın,' diye karşılık verdi.",
             "courteously | Nezaketle, saygıyla."),
            ("'I am right here,' said the voice, 'under the apple tree.'",
             "Ses, 'Tam buradayım,' dedi, 'elma ağacının altında.'",
             "under apple tree | Elma ağacının altında."),
            ("'Who are you?' asked the Little Prince; 'you are very pretty to look at.'",
             "Küçük Prens, 'Kimsin sen?' diye sordu; 'bakması çok güzel birisin.'",
             "pretty to look at | Bakması çok güzel."),
            ("'I am a fox,' the animal answered with a flick of his bushy golden tail.",
             "Hayvan gür altın sarısı kuyruğunu sallayarak, 'Ben bir tilkiyim,' diye yanıt verdi.",
             "bushy tail | Gür kuyruk; 'flick' hafifçe sallamak."),
            ("'Come and play with me,' proposed the Little Prince; 'I am so terribly sad.'",
             "Küçük Prens teklifte bulundu: 'Gel benimle oyna; öyle kahredici biçimde kederliyim ki.'",
             "terribly sad | Kahredici derecede kederli."),
            ("'I cannot play with you,' the fox said softly; 'I am not tamed.'",
             "Tilki usulca, 'Seninle oynayamam,' dedi; 'ben evcil değilim.'",
             "tamed | Evcilleştirilmiş, terbiye edilmiş."),
            ("'Ah! Please excuse me,' murmured the prince, but after a moment's thought he added: 'What does that mean — to tame?'",
             "Prens, 'Ah! Beni bağışla lütfen,' diye mırıldandı ama biraz düşündükten sonra ekledi: 'Evcilleştirmek ne demektir?'",
             "what does that mean | Ne demektir?"),
            ("'It is an act too often neglected,' said the fox; 'it means to establish ties.'",
             "Tilki, 'Fazlasıyla sık ihmal edilen bir eylemdir,' dedi; 'bağlar kurmak anlamına gelir.'",
             "establish ties | Bağlar kurmak; 'neglected' ihmal edilmiş."),
            ("'To establish ties?' repeated the boy, captivated by the concept.",
             "Kavrama hayran kalan çocuk, 'Bağlar kurmak mı?' diye tekrarladı.",
             "captivated | Büyülenmiş, hayran kalmış."),
            ("'Just that,' said the fox; 'to me, you are still nothing more than a little boy like a hundred thousand other little boys.'",
             "Tilki, 'Aynen öyle,' dedi; 'benim için sen henüz yüz bin başka küçük çocuk gibi bir çocuktan başka bir şey değilsin.'",
             "nothing more than | '... başka hiçbir şey olmamak' kalıbıdır."),
            ("'And I have no need of you; and you, on your part, have no need of me.'",
             "'Ve benim sana ihtiyacım yok; senin de kendi payına bana ihtiyacın yok.'",
             "no need of | İhtiyacı olmamak; 'on your part' senin açından."),
            ("'To you I am nothing more than a fox like a hundred thousand other wild foxes.'",
             "'Senin için ben yüz bin başka yaban tilkisi gibi bir tilkiden başka hiçbir şey değilim.'",
             "wild foxes | Yaban tilkileri."),
            ("'But if you tame me, then we shall have need of each other in this wide world.'",
             "'Fakat beni evcilleştirirsen, o vakit bu koca dünyada birbirimize ihtiyacımız olacak.'",
             "need of each other | Birbirine ihtiyaç duymak."),
            ("'To me, you will be unique in all the world; to you, I shall be unique in all the world.'",
             "'Benim için sen dünyada biricik olacaksın; senin için de ben dünyada eşsiz olacağım.'",
             "unique in all world | Bütün dünyada eşsiz / biricik."),
            ("'I am beginning to understand,' said the Little Prince; 'there is a flower... I think that she has tamed me.'",
             "Küçük Prens, 'Anlamaya başlıyorum,' dedi; 'bir çiçek var... sanırım o beni evcilleştirdi.'",
             "beginning to understand | Anlamaya başlamak."),
            ("'My life is monotonous,' the fox explained; 'I hunt chickens; men hunt me; all the chickens are alike, and all the men are alike.'",
             "Tilki açıkladı: 'Hayatım tekdüzedir; tavukları avlarım, insanlar da beni avlar; bütün tavuklar birbirine benzer ve bütün insanlar da birbirine benzer.'",
             "monotonous | Tekdüze, yeknesak; 'alike' birbirine benzer."),
            ("'If you tame me, my life will be as filled with sunshine; the golden wheat will remind me of your hair.'",
             "'Beni evcilleştirirsen hayatım güneş ışığıyla dolmuş gibi olacak; altın sarısı buğday bana senin saçlarını hatırlatacak.'",
             "filled with sunshine | Güneş ışığıyla dolu; 'golden wheat' altın buğday."),
            ("The fox gazed at the Little Prince for a long time: 'Please... tame me!' he whispered tenderly.",
             "Tilki uzun süre Küçük Prens'e baktı: 'Lütfen... evcilleştir beni!' diye şefkatle fısıldadı.",
             "whispered tenderly | Şefkatle fısıldamak.")
        ],
        "vocab_focus": [
            ("courteously", "kibarca, hürmetle"),
            ("tamed", "evcilleştirilmiş"),
            ("establish ties", "bağlar kurmak"),
            ("neglected", "ihmal edilmiş, unutulmuş"),
            ("captivated", "büyülenmiş, hayran kalmış"),
            ("unique", "eşsiz, biricik"),
            ("monotonous", "tekdüze, sıkıcı"),
            ("wheat", "buğday")
        ]
    },

    # PAGE 15: Chapter 15: What is Essential is Invisible to the Eye
    {
        "page_no": 15,
        "title": "What is Essential is Invisible",
        "tr_title": "Asıl Gerekli Olan Göze Görünmez",
        "sentences": [
            ("So the Little Prince tamed the fox, visiting him at the exact same hour every afternoon.",
             "Böylece Küçük Prens her ikindi tam aynı saatte ziyaret ederek tilkiyi evcilleştirdi.",
             "exact same hour | Tam aynı saat; 'tamed' evcilleştirdi."),
            ("And when the hour of his departure drew near, the fox murmured softly, 'Ah! I shall weep.'",
             "Ve ayrılık saati yaklaştığında tilki usulca, 'Ah! Ağlayacağım,' diye mırıldandı.",
             "departure drew near | Ayrılık vakti yaklaştı."),
            ("'It is your own fault,' said the Little Prince; 'I never wished you any sort of harm.'",
             "Küçük Prens, 'Bu senin kendi hatandır,' dedi; 'sana asla hiçbir tür zarar vermek istememiştim.'",
             "own fault | Kendi hatası; 'any sort of harm' hiçbir tür zarar."),
            ("'You wanted me to tame you, and now you suffer,' added the prince with heartfelt sorrow.",
             "Prens içten bir kederle ekledi: 'Seni evcilleştirmemi sen istedin ve şimdi acı çekiyorsun.'",
             "heartfelt sorrow | Yürekten gelen keder; 'suffer' acı çekmek."),
            ("'Yes, that is true,' answered the fox, looking at the golden fields of swaying wheat.",
             "Tilki sallanan altın buğday tarlalarına bakarak, 'Evet, bu doğru,' diye yanıt verdi.",
             "swaying wheat | Salınan buğday."),
            ("'Then you get no good from it at all!' exclaimed the prince in sorrowful bewilderment.",
             "Prens hüzünlü bir şaşkınlıkla, 'Öyleyse bunun sana zerre kadar hiçbir faydası olmadı!' diye haykırdı.",
             "no good at all | Hiçbir faydası olmamak; 'sorrowful' hüzünlü."),
            ("'I get some good,' said the fox firmly, 'because of the color of the wheat.'",
             "Tilki kararlı bir sesle, 'Bana faydası oldu,' dedi, 'buğdayın rengi sayesinde.'",
             "color of wheat | Buğdayın rengi."),
            ("Then he added, 'Go and look again at the roses; you will understand now that yours is unique in all the world.'",
             "Sonra ekledi: 'Git ve güllere tekrar bak; seninkinin bütün dünyada eşsiz olduğunu şimdi anlayacaksın.'",
             "unique in all world | Bütün dünyada eşsiz."),
            ("The Little Prince went to look at the garden of five thousand roses blooming together.",
             "Küçük Prens birlikte açmış olan beş bin güllük bahçeye bakmaya gitti.",
             "blooming together | Birlikte açmış / çiçek vermiş."),
            ("He said to them, 'You are not at all like my rose; as yet you are nothing to me.'",
             "Onlara, 'Benim gülüme kesinlikle hiç benzemiyorsunuz; henüz benim için hiçbir şeysiniz,' dedi.",
             "nothing to me | Benim için hiçbir şey."),
            ("'No one has tamed you, and you have tamed no one; you are beautiful, but you are empty.'",
             "'Sizi hiç kimse evcilleştirmedi ve siz de hiç kimseyi evcilleştirmediniz; güzelsiniz ama bomboşsunuz.'",
             "beautiful but empty | Güzel ama bomboş."),
            ("'An ordinary passer-by would think my rose was just like you, but she is far more important than all of you.'",
             "'Yoldan geçen sıradan biri benim gülümün tıpkı sizin gibi olduğunu sanırdı; fakat o hepinizden çok daha mühimdir.'",
             "passer-by | Yoldan geçen kimse; 'important' mühim."),
            ("'Because it is she that I have watered; it is she that I have put under the glass globe.'",
             "'Çünkü suladığım odur; cam fanusun altına koyduğum odur.'",
             "put under globe | Fanusun altına koymak."),
            ("'Because it is she that I have sheltered behind the screen; because it is she that is my rose.'",
             "'Çünkü rüzgarlığa karşı koruduğum odur; çünkü o benim gülümdür.'",
             "sheltered behind screen | Paravanın arkasında korumak."),
            ("And he returned to the fox to say his final farewell.",
             "Ve son vedasını söylemek için tilkinin yanına geri döndü.",
             "final farewell | Son veda."),
            ("'Goodbye,' said the Little Prince softly.",
             "Küçük Prens usulca, 'Hoşça kal,' dedi.",
             "goodbye | Hoşça kal, elveda."),
            ("'Goodbye,' said the fox; 'and now here is my secret, a very simple secret:'",
             "Tilki, 'Hoşça kal,' dedi; 've işte sırrım, son derece sade bir sır:'",
             "very simple secret | Son derece sade bir sır."),
            ("'It is only with the heart that one can see rightly; what is essential is invisible to the eye.'",
             "'İnsan ancak yüreğiyle doğruyu görebilir; asıl gerekli ve öz olan şey göze görünmez.'",
             "essential is invisible | Öz olan göze görünmez."),
            ("'It is the time you have wasted for your rose that makes your rose so important.'",
             "'Gülünü böylesine önemli kılan şey, onun uğruna harcadığın zamandır.'",
             "time wasted for rose | Gülün uğruna harcanan zaman."),
            ("'You become responsible, forever, for what you have tamed; you are responsible for your rose.'",
             "'Evcilleştirdiğin şeyden sonsuza dek sorumlu olursun; sen gülünden sorumlusun.'",
             "responsible forever | Sonsuza dek sorumlu.")
        ],
        "vocab_focus": [
            ("heartfelt", "içten, yürekten gelen"),
            ("sorrowful", "hüzün dolu, kederli"),
            ("passer-by", "yoldan gelip geçen"),
            ("sheltered", "korunaklı, himaye edilmiş"),
            ("farewell", "veda, elveda"),
            ("essential", "asıl gerekli olan, öz"),
            ("invisible", "görünmez, gizli"),
            ("responsible", "sorumlu, mesul")
        ]
    }
]

import os

all_pages = pages_content + pages_5_to_15 + pages_11_to_15
output_file = os.path.join(os.path.dirname(__file__), "book_08_data.py")

with open(output_file, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""\n')
    f.write("Book 8: The Little Prince: Chapters of the Stars (Antoine de Saint-Exupéry)\n")
    f.write("Level 1 Graded Reader — 15 Pages x 20 Sentences = 300 Sentences.\n")
    f.write('"""\n\n')
    f.write('BOOK_TITLE = "The Little Prince: Chapters of the Stars (15 Sayfa / 300 Cümle / Graded Reader)"\n')
    f.write('AUTHOR = "Antoine de Saint-Exupéry"\n\n')
    f.write("PAGES_DATA = [\n")
    
    current_sentence_id = 1
    for page in all_pages:
        f.write("    {\n")
        f.write(f'        "page_no": {page["page_no"]},\n')
        f.write(f'        "title": "{page["title"]}",\n')
        f.write(f'        "tr_title": "{page["tr_title"]}",\n')
        f.write('        "sentences": [\n')
        for s in page["sentences"]:
            text = s[0].replace('"', '\\"')
            tr = s[1].replace('"', '\\"')
            notes = s[2].replace('"', '\\"')
            f.write("            {\n")
            f.write(f'                "id": {current_sentence_id},\n')
            f.write(f'                "text": "{text}",\n')
            f.write(f'                "translation": "{tr}",\n')
            f.write(f'                "notes": "{notes}"\n')
            f.write("            },\n")
            current_sentence_id += 1
        f.write("        ],\n")
        f.write('        "vocab_focus": [\n')
        for v in page["vocab_focus"]:
            v_en = v[0].replace('"', '\\"')
            v_tr = v[1].replace('"', '\\"')
            f.write(f'            ("{v_en}", "{v_tr}"),\n')
        f.write("        ]\n")
        f.write("    },\n")
    f.write("]\n")

print(f"Generated tools/book_08_data.py successfully with {current_sentence_id - 1} sentences across {len(all_pages)} pages!")
