# -*- coding: utf-8 -*-
"""
Generator script to build tools/book_05_data.py
15 Pages x 20 Sentences = 300 Sentences.
Oscar Wilde's 'The Remarkable Rocket'.
"""

pages_content = [
    # PAGE 1: The Arrival of the Russian Princess & The Royal Wedding
    {
        "page_no": 1,
        "title": "The Royal Wedding",
        "tr_title": "Kraliyet Düğünü ve Prensesin Gelişi",
        "sentences": [
            ("The King's son was going to be married, so there were general rejoicings throughout the whole realm.",
             "Kralın oğlu evlenmek üzereydi, bu yüzden tüm krallıkta genel kutlamalar ve sevinç gösterileri vardı.",
             "general rejoicings | 'Genel sevinç/kutlamalar' anlamına gelen isim tamlamasıdır."),
            ("He had waited a whole year for his bride, and at last she had arrived at the palace gates.",
             "Gelini için tam bir yıl beklemişti ve nihayet prenses saray kapılarına varmıştı.",
             "at last | 'Nihayet, sonunda' anlamına gelen zaman zarfıdır."),
            ("She was a Russian Princess, and had driven all the way from Finland in a sledge drawn by six reindeer.",
             "Kendisi bir Rus prensesiydi ve Finlandiya'dan altı ren geyiğinin çektiği bir kızakla bütün yolu gelmişti.",
             "sledge | Kızak; 'drawn by' ise pasif niteleme yapısıdır (tarafından çekilen)."),
            ("The sledge was shaped like a great golden swan, and between the swan's wings lay the little Princess herself.",
             "Kızak devasa altın bir kuğu biçimindeydi ve kuğunun kanatları arasında bizzat küçük prenses yatıyordu.",
             "shaped like | '... biçiminde, şeklinde' kalıbıdır."),
            ("Her long ermine-cloak reached right down to her feet, keeping her warm against the northern winds.",
             "Uzun kakım kürkü pelerini ta ayaklarına kadar iniyor, onu kuzey rüzgarlarına karşı sıcak tutuyordu.",
             "ermine-cloak | Kakım kürkünden yapılmış pelerin; 'right down to' kalıbı mesafeyi vurgular."),
            ("On her head was a tiny cap of silver tissue, which glittered softly in the winter light.",
             "Başında, kış ışığında yumuşakça parıldayan gümüş dokumadan küçücük bir başlık vardı.",
             "silver tissue | Gümüş sırma kumaş / dokuma."),
            ("She was as pale as the Snow Palace in which she had always lived.",
             "Tüm ömrü boyunca yaşadığı Kar Sarayı kadar beyaz ve solgundu.",
             "as pale as | Eşitlik belirten benzetme kalıbı (kadar solgun)."),
            ("So pale was she that as she drove through the streets, all the townspeople wondered in amazement.",
             "O kadar solgundu ki sokaklardan geçerken bütün kent sakinleri hayret içinde kalakaldı.",
             "inversion | 'So pale was she that' devrik yapısı pekiştirme sağlar."),
            ("'She is like a white rose!' they cried enthusiastically, and they threw down fragrant flowers from the balconies.",
             "'O tıpkı beyaz bir gül gibi!' diye coşkuyla bağırdılar ve balkonlardan üzerine mis kokulu çiçekler attılar.",
             "fragrant | 'Güzel kokulu, hoş kokulu' sıfatıdır."),
            ("At the grand gate of the Castle, the Prince was waiting eagerly to receive his royal bride.",
             "Şatonun büyük kapısında Prens, kraliyet gelinini karşılamak için sabırsızlıkla bekliyordu.",
             "receive | 'Resmi olarak karşılamak, kabul etmek' anlamında kullanılmıştır."),
            ("He had dreamy violet eyes, and his wavy hair was like spun gold under the sun.",
             "Hülyalı menekşe rengi gözleri vardı ve dalgalı saçları güneşin altında eğrilmiş altın gibiydi.",
             "spun gold | Eğrilmiş altın iplik; 'dreamy' hülyalı demektir."),
            ("When he saw her radiant face, he sank upon one knee and kissed her gentle hand.",
             "Onun ışıltılı yüzünü görünce tek dizi üstüne çöktü ve narin elini öptü.",
             "sink upon one knee | Tek dizinin üzerine çökmek deyimidir."),
            ("'Your picture was beautiful,' he murmured softly, 'but you are far more beautiful than your picture.'",
             "'Portreniz çok güzeldi,' diye fısıldadı usulca, 'fakat siz resminizden çok daha güzelsiniz.'",
             "far more beautiful | 'Çok daha güzel' anlamında sıfat derecelendirmesidir."),
            ("The little Princess blushed sweetly at his courtly compliments and lowered her eyes.",
             "Küçük Prenses bu asilce iltifatlar karşısında tatlı tatlı kızardı ve gözlerini indirdi.",
             "blushed | Utanıp kızarmak; 'courtly' saraya yakışır, asil anlamındadır."),
            ("'She was like a white rose before,' said a young Page to his neighbour, 'but she is like a red rose now.'",
             "Genç bir uşak yanındakine, 'Daha önce beyaz bir gül gibiydi,' dedi, 'ama şimdi kırmızı bir gül gibi oldu.'",
             "Page | Saray uşağı, genç hizmetkâr."),
            ("The whole Court was delighted with her charming grace, and murmured their sincere approval.",
             "Tüm Saray halkı onun büyüleyici zarafetinden son derece memnun oldu ve içten takdirlerini mırıldandı.",
             "delighted with | 'Bir şeyden hoşnut kalmak, memnun olmak' fiilidir."),
            ("For the next three days everybody went about repeating, 'White rose, Red rose, Red rose, White rose.'",
             "Sonraki üç gün boyunca herkes sokaklarda 'Beyaz gül, Kırmızı gül, Kırmızı gül, Beyaz gül' diyerek dolaştı.",
             "went about repeating | Dolaşıp durarak tekrar etmek kalıbıdır."),
            ("The King gave orders that the young Page's salary should be doubled immediately as a reward.",
             "Kral, bu güzel benzetmenin ödülü olarak genç uşağın maaşının derhal iki katına çıkarılmasını emretti.",
             "salary | Maaş, aylık ücret; 'should be doubled' pasif emir kipine örnektir."),
            ("As he received no salary at all, this did not make much difference to his daily circumstances.",
             "Fakat uşak zaten hiç maaş almadığı için, bu emir onun günlük durumunda pek bir fark yaratmadı.",
             "no salary at all | 'Hiçbir maaş'; Wilde'ın meşhur hiciv cümlelerinden biridir."),
            ("Nevertheless, it was considered a great honour by the entire kingdom, and was duly gazetted.",
             "Yine de bu lütuf tüm krallıkça büyük bir onur sayıldı ve resmi gazetede usulünce ilan edildi.",
             "gazetted | Resmi bültende / gazetede yayımlanıp duyurulan.")
        ],
        "vocab_focus": [
            ("rejoicings", "kutlamalar, şenlikler"),
            ("sledge", "kar kızağı"),
            ("ermine-cloak", "kakım kürkünden pelerin"),
            ("as pale as", "kadar solgun/beyaz"),
            ("spun gold", "eğrilmiş altın"),
            ("blushed", "yüzü kızardı"),
            ("courtly", "saraya yakışır, asil"),
            ("gazetted", "resmi bültende yayımlanmış")
        ]
    },

    # PAGE 2: The Magnificent Banquet and the King's Page
    {
        "page_no": 2,
        "title": "The State Banquet",
        "tr_title": "Görkemli Ziyafet ve Flüt Çalan Kral",
        "sentences": [
            ("When the three days were over, the magnificent marriage was celebrated in the royal chapel.",
             "Üç gün sona erdiğinde, muhteşem evlilik töreni kraliyet şapelinde kutlandı.",
             "were over | 'Sona ermek, bitmek' phrasal verb yapısıdır."),
            ("It was a ceremony of exceptional splendour, attended by ambassadors from thirty foreign kingdoms.",
             "Otuz yabancı krallıktan elçilerin katıldığı, olağanüstü görkeme sahip bir törendi.",
             "splendour | İhtişam, parlaklık, görkem."),
            ("The bride and bridegroom walked hand in hand under a canopy of purple velvet embroidered with pearls.",
             "Gelin ve damat, incilerle işlenmiş erguvani kadifeden bir gölgelik altında el ele yürüdüler.",
             "canopy | Gölgelik, sayeban; 'embroidered with' ile işlenmiş demektir."),
            ("Then followed a splendid State Banquet, which lasted for five uninterrupted hours.",
             "Ardından tam beş saat kesintisiz süren görkemli bir Resmi Devlet Ziyafeti başladı.",
             "State Banquet | Resmi devlet ziyafeti; 'uninterrupted' kesintisiz."),
            ("The Prince and Princess sat at the top of the Great Hall and drank out of a cup of pure crystal.",
             "Prens ve Prenses Büyük Salon'un başköşesinde oturdular ve som kristalden bir kadehten içtiler.",
             "pure crystal | Saf, som kristal cam."),
            ("Only true lovers could drink out of this magical cup, for if false lips touched it, it grew grey and cloudy.",
             "Bu sihirli kadehten yalnızca gerçek aşıklar içebilirdi; zira sahte dudaklar dokunursa kadeh grileşir ve bulanıklaşırdı.",
             "cloudy | Bulanık, mat; 'for' burada 'çünkü / zira' bağlacıdır."),
            ("'It is quite clear that they love each other,' said the little Page, 'as clear as the crystal itself!'",
             "Küçük Uşak, 'Birbirlerini sevdikleri çok aşikar,' dedi, 'kristalin kendisi kadar berrak!'",
             "as clear as | 'Kadar berrak / apaçık' benzetmesidir."),
            ("And the King promptly doubled his salary a second time, much to the young courtier's theoretical satisfaction.",
             "Ve Kral gencin maaşını derhal ikinci kez iki katına çıkardı; bu da genç saraylının kağıt üstündeki doyumunu artırdı.",
             "promptly | Derhal, vakit kaybetmeden."),
            ("'What an honour!' cried all the courtiers in chorus, bowing respectfully toward the throne.",
             "Tüm saraylılar tahta doğru hürmetle eğilerek koro halinde, 'Ne büyük bir şeref!' diye haykırdılar.",
             "in chorus | Koro halinde, hep bir ağızdan."),
            ("After the banquet there was to be a grand Ball, and the palace musicians tuned their instruments.",
             "Ziyafetten sonra büyük bir Balo düzenlenecekti ve saray müzisyenleri enstrümanlarını akort ettiler.",
             "was to be | Gelecek zaman planlamasını anlatan kalıp (düzenlenecekti)."),
            ("The bride and bridegroom were to dance the Rose-dance together before all the assembled dignitaries.",
             "Gelin ve damat toplanmış tüm ileri gelenlerin önünde Gül Dansı'nı birlikte yapacaklardı.",
             "assembled dignitaries | Toplanmış devlet büyükleri / ileri gelenler."),
            ("The King had promised to play the flute himself during this special performance.",
             "Kral bu özel gösteri esnasında flütü bizzat kendisi çalacağına söz vermişti.",
             "play the flute | Flüt çalmak."),
            ("He played very badly, but no one had ever dared to tell him so, because he was the King.",
             "Çok kötü çalıyordu ama hiç kimse bunu ona söylemeye cesaret edememişti çünkü o Kral'dı.",
             "dared to | Cesaret etmek; cesaret gösterebilmek."),
            ("Indeed, he only knew two tunes, and was never quite certain which of the two he was playing at any moment.",
             "Doğrusu yalnızca iki ezgi biliyordu ve herhangi bir anda bu ikisinden hangisini çaldığından asla tam emin olamıyordu.",
             "tunes | Melodiler, ezgiler."),
            ("However, nobody minded in the least, for everyone applauded with enthusiasm whenever he finished a passage.",
             "Bununla birlikte kimse bunu zerrece dert etmiyordu; çünkü kral her bir bölümü bitirdiğinde herkes coşkuyla alkışlıyordu.",
             "in the least | 'Zerre kadar, hiç mi hiç' anlamında olumsuzluk pekiştiricisidir."),
            ("The Court applauded politely, calling his majesty's performance singularly delicate and full of passion.",
             "Saray ahalisi nezaketle alkış tutarak majestelerinin icrasını eşsiz derecede zarif ve duygu dolu olarak niteledi.",
             "singularly delicate | Eşsiz derecede zarif / nadide incelikte."),
            ("The last performance on the royal programme was a grand display of fireworks on the terrace.",
             "Kraliyet programındaki en son gösteri ise terasta yapılacak olan büyük havai fişek şöleniydi.",
             "display of fireworks | Havai fişek gösterisi."),
            ("They were to be let off exactly at midnight, when the stars would look down upon the palace.",
             "Yıldızların sarayı tepeden izleyeceği tam gece yarısında ateşleneceklerdi.",
             "let off | Havai fişek patlatmak, ateşlemek."),
            ("The little Princess had never seen a firework in her entire life, having lived secluded in the north.",
             "Kuzeyde gözlerden uzak yaşadığı için küçük Prenses hayatında hiç havai fişek görmemişti.",
             "secluded | Gözlerden ırak, münzevi, tenha."),
            ("So the King had ordered that the Royal Pyrotechnist should prepare the finest spectacle the world had ever seen.",
             "Bu yüzden Kral, Kraliyet Havai Fişek Ustası'nın dünyanın gördüğü en muazzam gösteriyi hazırlamasını emretmişti.",
             "Pyrotechnist | Havai fişek ustası, piroteknik uzmanı.")
        ],
        "vocab_focus": [
            ("splendour", "ihtişam, parlaklık"),
            ("canopy", "gölgelik, sayeban"),
            ("uninterrupted", "kesintisiz, durmaksızın"),
            ("in chorus", "hep bir ağızdan, koro halinde"),
            ("dignitaries", "ileri gelenler, rical"),
            ("in the least", "zerre kadar, asla"),
            ("singularly", "eşsiz şekilde, fevkalade"),
            ("let off", "ateşlemek, patlatmak")
        ]
    },

    # PAGE 3: The Pyrotechnic Display and the Conversation of the Fireworks
    {
        "page_no": 3,
        "title": "The Fireworks on the Terrace",
        "tr_title": "Terasta Bekleyen Fişeklerin Sohbeti",
        "sentences": [
            ("'What are fireworks like?' the Princess had asked the Prince one morning as they walked on the terrace.",
             "Terasta yürüdükleri bir sabah Prenses, Prens'e 'Havai fişekler neye benzer?' diye sormuştu.",
             "What are ... like? | '... neye benzer, nasıldır?' soru kalıbıdır."),
            ("'They are like the Aurora Borealis,' said the King, who always answered questions addressed to other people.",
             "Başkalarına yöneltilen sorulara her zaman atlayıp cevap veren Kral, 'Kuzey Işıkları gibidirler,' dedi.",
             "Aurora Borealis | Kuzey Işıkları (Kutup Şafağı)."),
            ("'Only they are much more natural,' the monarch added with an air of profound authority.",
             "Hükümdar derin bir otorite edasıyla, 'Yalnızca fişekler çok daha doğaldır,' diye ekledi.",
             "profound authority | Derin / sarsılmaz otorite."),
            ("'I prefer fireworks to stars myself, for you always know when they are going to appear in the sky.'",
             "'Ben şahsen havai fişekleri yıldızlara tercih ederim; zira gökyüzünde ne zaman belireceklerini her zaman bilirsiniz.'",
             "prefer ... to ... | Bir şeyi başka bir şeye tercih etmek kalıbıdır."),
            ("'Besides, they are as delightful as my own flute-playing, and far more unexpected in their effects.'",
             "'Üstelik kendi flüt icram kadar keyif vericidirler ve etkileri bakımından çok daha beklenmediktirler.'",
             "delightful | Keyifli, zevk veren; 'unexpected' beklenmedik."),
            ("So a great wooden scaffold had been set up at the far end of the royal garden.",
             "Böylece kraliyet bahçesinin en uç kısmına devasa ahşap bir iskele kurulmuştu.",
             "scaffold | İskele, ahşap platform."),
            ("And as soon as the Royal Pyrotechnist had put everything in its proper place, the fireworks began to talk.",
             "Ve Kraliyet Havai Fişekçisi her şeyi yerli yerine koyar koymaz, havai fişekler kendi aralarında konuşmaya başladılar.",
             "in its proper place | Uygun yerine, layık olduğu yere."),
            ("'The world is certainly very beautiful,' cried a little Squib in a shrill, excited voice.",
             "Küçük bir Torpil, tiz ve heyecanlı bir sesle 'Dünya kesinlikle çok güzel!' diye haykırdı.",
             "Squib | Torpil fişeği; 'shrill' tiz, keskin ses."),
            ("'Look at those yellow tulips across the lawn! If they were real crackers, they could not be lovelier.'",
             "'Çimenliğin karşısındaki şu sarı lalelere bakın! Gerçek birer patlangaç olsalardı bile daha sevimli olamazlardı.'",
             "crackers | Çatapat, patlangaç fişekleri."),
            ("'I am very glad that I have travelled,' continued the Squib, 'for travel improves the mind amazingly.'",
             "'Seyahat ettiğime çok memnunum,' diye devam etti Torpil, 'çünkü seyahat etmek zihni şaşırtıcı biçimde geliştirir.'",
             "improves the mind | Zihni geliştirmek, ufku açmak."),
            ("'Travel also gets rid of all one's prejudices, as any cultivated person knows.'",
             "'Ayrıca her kültürlü insanın bildiği gibi seyahat, kişinin tüm önyargılarını yok eder.'",
             "gets rid of | 'Bir şeyden kurtulmak, tasfiye etmek' fiilidir."),
            ("'The King's garden is not the world, you foolish little creature,' said a large Roman Candle haughtily.",
             "Kocaman bir Roma Kandili kibirle, 'Kralın bahçesi tüm dünya demek değildir, seni aptal küçük yaratık,' dedi.",
             "haughtily | Kibirle, üstten bakarak."),
            ("'The world is an enormous place, and it would take you three whole days to see it thoroughly.'",
             "'Dünya muazzam büyüklükte bir yerdir ve onu baştan başa görebilmek tam üç gününüzü alırdı.'",
             "thoroughly | Baştan başa, etraflıca, eksiksizce."),
            ("'Any place you happen to love is the world to you,' gentle-hearted Catherine Wheel remarked softly.",
             "İnce kalpli Fırıldak Fişek usulca, 'Sevmeye başladığınız her yer sizin için dünyadır,' dedi.",
             "Catherine Wheel | Fırıldak havai fişek (dönerek kıvılcım saçan daire fişek)."),
            ("She had been attached to an old deal box in her youth, and was proud of her affectionate heart.",
             "Gençliğinde eski bir çam kutuya raptedilmişti ve sevecen kalbiyle her zaman gurur duyardı.",
             "deal box | Çam tahtasından kutu; 'affectionate' şefkatli, sevecen."),
            ("'Romance is dead, quite dead,' murmured the Roman Candle in a solemn, tragic whisper.",
             "Roma Kandili vakur ve trajik bir fısıltıyla, 'Romantizm öldü, büsbütün öldü,' diye mırıldandı.",
             "solemn | Vakur, ciddiyet dolu."),
            ("'The moon has killed it by staying always cold and distant while we burn with intense fire.'",
             "'Biz yoğun ateşle yanarken, ay daima soğuk ve mesafeli kalarak onu katletti.'",
             "intense fire | Yoğun / şiddetli ateş."),
            ("'Romance is not dead at all,' retorted the Catherine Wheel briskly, spinning slightly in anticipation.",
             "Fırıldak Fişek beklentiyle hafifçe dönerek, 'Romantizm kesinlikle ölmedi,' diye anında karşı çıktı.",
             "retorted | Karşılık vermek, lafı yapıştırmak."),
            ("'It flourishes on moonlight and flourishes on sweet memories, even when one is tied to a post.'",
             "'Ay ışığında serpilir ve bir direğe bağlı olunduğunda bile tatlı hatıralarla can bulur.'",
             "flourishes | Gelişmek, serpilmek, çiçek açmak."),
            ("The other fireworks listened intently, preparing themselves for the magnificent midnight exhibition.",
             "Diğer fişekler dikkatle dinliyor ve kendilerini gece yarısındaki o muhteşem gösteriye hazırlıyorlardı.",
             "listened intently | Can kulağıyla / dikkatle dinlemek.")
        ],
        "vocab_focus": [
            ("Aurora Borealis", "kuzey ışıkları"),
            ("scaffold", "iskele, platform"),
            ("Squib", "küçük torpil fişeği"),
            ("prejudices", "önyargılar"),
            ("haughtily", "kibirle, tepeden bakarak"),
            ("Catherine Wheel", "dönen fırıldak fişek"),
            ("affectionate", "sevecen, şefkatli"),
            ("flourishes", "serpilir, yeşerir")
        ]
    },

    # PAGE 4: The Roman Candle and the Catherine Wheel
    {
        "page_no": 4,
        "title": "Debates Among the Fireworks",
        "tr_title": "Aşk ve Sanat Üzerine Münakaşa",
        "sentences": [
            ("'Look at the Prince and Princess!' continued the Catherine Wheel, gazing affectionately toward the palace.",
             "Fırıldak Fişek saraya doğru sevgiyle bakarak, 'Şu Prens ile Prenses'e bakın!' diye devam etti.",
             "gazing affectionately | Sevgiyle süzmek, şefkatle bakmak."),
            ("'They are so young and handsome, and their love is as fresh as morning dew.'",
             "'Çok genç ve yakışıklılar; aşkları da sabah çiği kadar taze.'",
             "morning dew | Sabah çiği."),
            ("'Humph!' grunted the Roman Candle, 'what does youth or beauty matter compared to true genius?'",
             "Roma Kandili homurdanarak, 'Hıh!' dedi, 'gerçek dehanın yanında gençliğin ya da güzelliğin ne önemi var?'",
             "compared to | '... ile karşılaştırıldığında' kalıbıdır."),
            ("'I am composed of pyrotechnic materials of the very highest order, imported from the Orient.'",
             "'Ben Şark'tan ithal edilmiş en üst mertebeden piroteknik malzemelerden imal edildim.'",
             "highest order | En yüksek rütbe / en üst kalite."),
            ("'My colours are dazzling red and electric blue, capable of illuminating the entire valley.'",
             "'Renklerim göz kamaştırıcı kırmızı ve elektrik mavisidir; tüm vadiyi aydınlatmaya muktedirdir.'",
             "illuminating | Aydınlatmak, ışık saçmak."),
            ("'That is all very well,' said a quiet Cracker, 'but you should not boast so loudly before the performance.'",
             "Sessiz bir Çatapat, 'Bunlar çok hoş,' dedi, 'fakat gösteriden önce bu kadar gürültülü övünmemelisiniz.'",
             "boast | Övünmek, böbürlenmek."),
            ("'Boasting is the sign of a vulgar spirit,' agreed a small Fire-balloon drifting gently in the breeze.",
             "Esintide hafifçe salınan küçük bir Ateş Balonu, 'Övünmek bayağı bir ruhun işaretidir,' diyerek onayladı.",
             "vulgar spirit | Bayağı / kaba ruh."),
            ("'A true gentleman simply does his duty, rises into the air, and bursts into brilliant stars.'",
             "'Gerçek bir centilmen sadece vazifesini yapar, havaya yükselir ve parlak yıldızlara dönüşerek patlar.'",
             "does his duty | Görevini yerine getirmek."),
            ("'Duty is an absurd invention of dull minds,' snapped the Roman Candle with visible irritation.",
             "Roma Kandili bariz bir asabiyetle, 'Vazife, sıkıcı zihinlerin uydurduğu saçma bir icattır,' diye çıkıştı.",
             "snapped | Çıkışmak, terslemek."),
            ("'Art is the only thing worth living and dying for in this wretched world of ours.'",
             "'Şu sefil dünyamızda uğrunda yaşamaya ve ölmeye değer yegane şey Sanat'tır.'",
             "wretched world | Sefil / zavallı dünya."),
            ("The Catherine Wheel sighed softly, remembering her youthful dreams on the old deal box.",
             "Fırıldak Fişek eski çam kutu üzerindeki gençlik düşlerini hatırlayarak usulca iç çekti.",
             "sighed softly | Derinden / usulca iç çekmek."),
            ("'I loved a cart-wheel once,' she murmured wistfully to anyone who cared to listen.",
             "Dinlemek isteyen herkese hüzünle, 'Ben bir keresinde bir öküz arabası tekerleğine aşık olmuştum,' diye mırıldandı.",
             "wistfully | Hüzünle, özlem duyarak; 'cart-wheel' araba tekerleğidir."),
            ("'He was of dignified appearance, and turned with great solemnity whenever the heavy cart moved.'",
             "'Ağırbaşlı bir duruşu vardı ve ağır yük arabası hareket ettikçe büyük bir vekarla dönerdi.'",
             "solemnity | Vakar, ciddiyet, resmiyet."),
            ("'I broke my heart for him, but he never noticed my brilliant sparks nor my devoted revolutions.'",
             "'Onun için kalbimi parçaladım; ama o ne parlak kıvılcımlarımı ne de sadık dönüşlerimi hiç fark etmedi.'",
             "revolutions | Dönüşler, turlar (kendi etrafında devir)."),
            ("'What a tragedy!' exclaimed a sensitive Bengal Light, turning pale green with sudden sympathy.",
             "Duygusal bir Bengal Meşalesi ani bir şefkatle açık yeşile dönerek, 'Ne büyük bir trajedi!' diye bağırdı.",
             "Bengal Light | Bengal ateşi / meşalesi."),
            ("'Tragedy is high art,' observed the Roman Candle, nodding sagely like a practiced philosopher.",
             "Roma Kandili tecrübeli bir filozof gibi bilgelikle başını sallayarak, 'Trajedi yüksek sanattır,' dedi.",
             "sagely | Bilgece, basiretle."),
            ("'The suffering of noble beings is always edifying to the common multitude.'",
             "'Asil varlıkların acı çekmesi sıradan halk yığınları için daima eğitici ve ibret vericidir.'",
             "edifying | Terbiye edici, ibret verici, eğitici."),
            ("Just then, a curious cough was heard from the highest shelf of the wooden framework.",
             "Tam o sırada ahşap iskelenin en yüksek rafından tuhaf bir öksürük sesi duyuldu.",
             "framework | İskele, çatı, yapı."),
            ("It was a clear, dry cough, uttered with a distinct intention of attracting universal attention.",
             "Evrensel ilgiyi üzerine çekmek amacıyla belirgin bir niyetle atılmış berrak, kuru bir öksürüktü bu.",
             "universal attention | Herkesin / tüm cemaatin ilgisi."),
            ("Every firework looked up immediately, wondering who possessed such an extraordinary cough.",
             "Her havai fişek böylesine olağanüstü bir öksürüğe kimin sahip olduğunu merak ederek hemen yukarı baktı.",
             "possessed | Sahip olmak, haiz olmak.")
        ],
        "vocab_focus": [
            ("morning dew", "sabah çiği"),
            ("highest order", "en üst rütbe/kalite"),
            ("boast", "böbürlenmek, övünmek"),
            ("vulgar spirit", "bayağı/kaba mizaç"),
            ("wistfully", "hüzünle, iç çekerek"),
            ("revolutions", "kendi ekseninde dönüşler"),
            ("edifying", "ibret verici, eğitici"),
            ("universal attention", "bütün dikkatleri toplama")
        ]
    },

    # PAGE 5: The Grand Entrance of the Remarkable Rocket
    {
        "page_no": 5,
        "title": "The Remarkable Rocket Speaks",
        "tr_title": "Harika Roketin Sahneye Çıkışı",
        "sentences": [
            ("The cough proceeded from a very tall, haughty Rocket tied to the end of a long wooden stick.",
             "Öksürük, uzun tahta bir sopanın ucuna bağlanmış son derece boylu poslu, kibirli bir Roket'ten geliyordu.",
             "proceeded from | '...-den ileri gelmek, çıkmak' kalıbıdır."),
            ("He always coughed before speaking, in order to make certain that everybody was listening to him.",
             "Herkesin kendisini dinlediğinden emin olmak için konuşmadan evvel daima öksürürdü.",
             "in order to | '... amacıyla, mek için' amaç bildiren bağlaçtır."),
            ("'Ahem! Ahem!' he repeated with immense dignity, surveying the company below with condescension.",
             "'Öhö! Öhö!' diye muazzam bir vakurla tekrarladı ve aşağıdaki topluluğu tepeden bakışlarla süzdü.",
             "condescension | Lütfeder gibi tepeden bakma, kibir."),
            ("Nobody answered, so he cleared his throat once more and struck a commanding attitude.",
             "Kimse cevap vermeyince boğazını bir kez daha temizledi ve buyurgan bir duruş takındı.",
             "commanding attitude | Buyurgan, heybetli tavır."),
            ("'The King's son is very fortunate,' he began gravely, 'in being married on the very day on which I am to be let off.'",
             "Ağırbaşlılıkla, 'Kralın oğlu,' diye söze başladı, 'benim ateşleneceğim günde evlendiği için çok talihli.'",
             "gravely | Ciddiyetle, ağırbaşlılıkla."),
            ("'Dear me!' said the Catherine Wheel, 'I thought it was the other way round, and that you were let off in his honour.'",
             "Fırıldak Fişek, 'Aman yarabbim!' dedi, 'ben tam tersi olduğunu, sizin onun şerefine ateşlendiğinizi sanıyordum.'",
             "the other way round | 'Tam tersine, aksine' deyimidir."),
            ("'It may be so with you,' answered the Rocket haughtily, 'indeed, I have no doubt that it is so.'",
             "Roket kibirle, 'Sizin durumunuzda öyle olabilir,' diye yanıtladı, 'doğrusu öyle olduğuna zerrece şüphem yok.'",
             "have no doubt | Şüphesi olmamak."),
            ("'With a person of your common origin, one expects nothing more than humble subordination.'",
             "'Sizin gibi sıradan kökenden gelen bir şahıstan mütevazı bir itaatten fazlası beklenemez zaten.'",
             "subordination | Tabi olma, boyun eğme, astlık."),
            ("'But with me it is totally different; I am an extraordinary personage of remarkable pedigree.'",
             "'Fakat benim durumum tamamen farklıdır; ben fevkalade bir soya sahip olağanüstü bir şahsiyetim.'",
             "pedigree | Soy kütüğü, asil şecere."),
            ("'My mother was the most celebrated Catherine Wheel of her day, and was renowned for her graceful dancing.'",
             "'Annem devrinin en meşhur Fırıldak Fişeğiydi ve zarif danslarıyla nam salmıştı.'",
             "renowned for | 'İle ünlenmiş, şöhret bulmuş' sıfatıdır."),
            ("'When she made her great public debut at the French Court, she spun round six times before going out.'",
             "'Fransız Sarayı'nda ilk büyük sahnesine çıktığında, sönmeden önce tam altı defa fırıl fırıl dönmüştü.'",
             "public debut | Sahneye ilk çıkış, ilk gösteri."),
            ("'And each time she turned, she threw off fifty-four magnificent stars of brilliant rose-colour.'",
             "'Ve her dönüşünde etrafa gül pembesi renginde elli dört muhteşem yıldız saçmıştı.'",
             "threw off | Etrafa saçmak, fırlatmak."),
            ("'She was three feet and a half in diameter, and made of the very finest pyrotechnic paste.'",
             "'Çapı üç buçuk ayaktı ve piyasadaki en kaliteli havai fişek hamurundan imal edilmişti.'",
             "diameter | Çap; 'pyrotechnic paste' fişek barut hamuru."),
            ("'My father was a Rocket of prestigious French extraction, directly descended from royal lineage.'",
             "'Babam ise doğrudan kraliyet soyundan gelen, muteber Fransız kökenli bir Roketti.'",
             "prestigious extraction | Saygın / itibarlı köken."),
            ("'He flew so high into the heavens that the spectators feared he would never come down again.'",
             "'Göklerin o kadar yükseğine uçmuştu ki seyirciler bir daha asla geri inemeyeceğinden korkmuşlardı.'",
             "heavens | Gökyüzü, felekler."),
            ("'He did come down, of course, because he was of a kindly and accommodating disposition.'",
             "'Tabii ki indi, çünkü kendisi son derece nazik ve halden anlayan bir tabiata sahipti.'",
             "accommodating disposition | Uysal, uzlaşmacı ve anlayışlı mizaç."),
            ("'And he made a most brilliant descent in a shower of golden sparks that astonished the entire capital.'",
             "'Ve bütün başkenti hayretler içinde bırakan altın kıvılcım yağmuru eşliğinde en parlak inişini gerçekleştirdi.'",
             "shower of golden sparks | Altın kıvılcım sağanağı."),
            ("'The newspapers wrote about him in terms of the highest admiration and patriotic gratitude.'",
             "'Gazeteler onun hakkında en yüksek hayranlık ve vatansever şükran ifadeleriyle dolu yazılar yazdılar.'",
             "admiration | Hayranlık, takdir."),
            ("'Indeed, the Court gazette officially called his performance a triumph of French pyrotechnic art.'",
             "'Doğrusu saray gazetesi onun gösterisini Fransız piroteknik sanatının bir zaferi olarak resmen niteledi.'",
             "triumph | Zafer, büyük başarı."),
            ("'I am made from his direct materials, so you can easily imagine my unparalleled superiority.'",
             "'Ben onun doğrudan malzemelerinden üretildim, dolayısıyla emsalsiz üstünlüğümü kolayca tahayyül edebilirsiniz.'",
             "unparalleled superiority | Emsalsiz, eşsiz üstünlük.")
        ],
        "vocab_focus": [
            ("proceeded from", "...-den ileri geldi"),
            ("condescension", "tepeden bakma, lütfetme kibri"),
            ("subordination", "tabi olma, itaat etme"),
            ("pedigree", "soy kütüğü, asil şecere"),
            ("renowned for", "ile nam salmış"),
            ("public debut", "ilk sahneye çıkış"),
            ("accommodating", "anlayışlı, uzlaşmacı mizaç"),
            ("unparalleled", "emsalsiz, dengi olmayan")
        ]
    },

    # PAGE 6: The Rocket's Boasting of his Noble Pedigree
    {
        "page_no": 6,
        "title": "Pedigree and Pretentions",
        "tr_title": "Roketin Kibirli Soyağacı ve İddiaları",
        "sentences": [
            ("'Well, I hope you will fly high tonight,' said a small Roman Candle, feeling somewhat intimidated.",
             "Küçük bir Roma Kandili kendini biraz gözü korkmuş hissederek, 'Umarım bu gece yükseklere uçarsınız,' dedi.",
             "intimidated | Gözü korkmuş, yılmış."),
            ("'Fly high?' echoed the Rocket with sovereign contempt, raising his pointed head even higher.",
             "Roket sivri kafasını daha da yukarı kaldırarak hükümdarvari bir küçümsemeyle, 'Yükseklere uçmak mı?' diye yankılandı.",
             "sovereign contempt | Hükümdarca / mutlak bir küçümseme."),
            ("'I intend to fly so high that the Prince and Princess will forget each other in sheer wonder.'",
             "'O kadar yükseklere uçmaya niyetliyim ki Prens ile Prenses saf bir hayranlık içinde birbirlerini unutacaklar.'",
             "sheer wonder | Saf / katıksız hayret ve hayranlık."),
            ("'The entire Court will hold its breath, and all the stars will hide behind the clouds in shame.'",
             "'Tüm saray nefesini tutacak ve bütün yıldızlar utançlarından bulutların ardına saklanacak.'",
             "hold its breath | Nefesini tutmak."),
            ("'As for the King, he will probably order a statue of pure gold to commemorate my glorious ascension.'",
             "'Kral'a gelince, şanlı yükselişimin anısına muhtemelen som altından bir heykel dikilmesini emredecektir.'",
             "commemorate | Anmak, hatırasını yaşatmak."),
            ("'You talk a great deal about yourself,' remarked the Catherine Wheel quietly, 'and praise yourself incessantly.'",
             "Fırıldak Fişek sakince, 'Kendinizden çok fazla bahsediyorsunuz,' dedi, 've durmaksızın kendinizi övüyorsunuz.'",
             "incessantly | Durmaksızın, aralıksız."),
            ("'Of course I do!' exclaimed the Rocket indignantly, puffing out his paper chest.",
             "Roket kağıttan göğsünü kabartarak öfkeyle, 'Elbette överim!' diye haykırdı.",
             "indignantly | Kızgınlıkla, hiddetle."),
            ("'Whom else should I talk about? There is nobody else present who possesses the slightest interest.'",
             "'Başka kimden bahsedecekmişim? Burada en ufak bir merak uyandıracak başka hiç kimse yok ki!'",
             "slightest interest | En ufak bir ilgi / merak."),
            ("'I always talk about myself, because I find myself infinitely fascinating and intellectually superior.'",
             "'Daima kendimden bahsederim; çünkü kendimi sonsuz derecede büyüleyici ve entelektüel olarak üstün buluyorum.'",
             "infinitely fascinating | Sonsuz derecede büyüleyici."),
            ("'Self-confidence is the absolute foundation of all great careers in modern society.'",
             "'Özgüven, modern toplumdaki tüm büyük kariyerlerin mutlak temel taşıdır.'",
             "absolute foundation | Mutlak temel."),
            ("'If one does not blow one's own trumpet, who is there to blow it for one?'",
             "'İnsan kendi borazanını kendisi çalmazsa, onun yerine çalacak kim var ki?'",
             "blow one's own trumpet | Kendi borusunu öttürmek, kendini övmek deyimidir."),
            ("'That sounds exceedingly selfish,' muttered a modest Bengal Light from the corner.",
             "Köşeden mütevazı bir Bengal Ateşi, 'Bu kulağa son derece bencilce geliyor,' diye söylendi.",
             "exceedingly selfish | Son derece bencilce."),
            ("'Selfishness?' cried the Rocket, turning upon the speaker with fierce indignation.",
             "Roket şiddetli bir hiddetle konuşana doğru dönerek, 'Bencillik mi?' diye kükredi.",
             "indignation | Haklı öfke, içerleme, hiddet."),
            ("'It is not selfishness at all; it is simply self-respect, which is the finest virtue in the universe.'",
             "'Bu kesinlikle bencillik değildir; evrendeki en yüce erdem olan özsaygının ta kendisidir.'",
             "self-respect | Özsaygı, haysiyet."),
            ("'A really well-bred rocket never listens to other people; he does all the talking himself.'",
             "'Gerçekten iyi yetişmiş bir roket diğer insanları asla dinlemez; konuşmanın tamamını bizzat kendisi yapar.'",
             "well-bred | İyi yetişmiş, asil terbiyeli."),
            ("'Listening to others is merely an admission of weakness and lack of original ideas.'",
             "'Başkalarını dinlemek, yalnızca bir zayıflığın ve özgün fikir eksikliğinin itirafıdır.'",
             "admission of weakness | Zayıflık itirafı."),
            ("'I always say what I think, and I never allow anyone to contradict me under any circumstances.'",
             "'Ben daima düşündüğümü söylerim ve hiçbir koşul altında kimsenin bana itiraz etmesine izin vermem.'",
             "contradict | Aksini iddia etmek, itiraz etmek."),
            ("The Catherine Wheel sighed again, feeling that the conversation was becoming rather tedious.",
             "Fırıldak Fişek sohbetin epeyce sıkıcı bir hal almaya başladığını hissederek yine iç çekti.",
             "tedious | Bıktırıcı, sıkıcı, yeknesak."),
            ("The Roman Candle turned red with anger, wishing he could burn the haughty Rocket on the spot.",
             "Roma Kandili öfkeden kıpkırmızı kesildi ve o küstah Roket'i oracıkta yakabilmeyi diledi.",
             "on the spot | Oracıkta, hemen o anda."),
            ("Yet the Rocket stood upright on his stick, convinced that everyone admired his incomparable eloquence.",
             "Yine de Roket sopası üzerinde dimdik duruyor ve herkesin emsalsiz hitabetine hayran kaldığına inanıyordu.",
             "incomparable eloquence | Kıyaslanamaz / benzersiz belagat ve güzel konuşma.")
        ],
        "vocab_focus": [
            ("sovereign contempt", "hükümdarca küçümseme"),
            ("commemorate", "anmak, hatırasını yaşatmak"),
            ("incessantly", "durmaksızın, biteviye"),
            ("blow one's trumpet", "kendini övmek"),
            ("indignation", "hiddet, içerleme"),
            ("self-respect", "özsaygı, haysiyet"),
            ("contradict", "çelişmek, aksini iddia etmek"),
            ("eloquence", "belagat, etkileyici hitabet")
        ]
    },

    # PAGE 7: The Argument About Sensitivity and Emotion
    {
        "page_no": 7,
        "title": "The Debate on Sensitivity",
        "tr_title": "Hassasiyet ve Duygu Üzerine Münakaşa",
        "sentences": [
            ("'I like you,' said the little Squib to the Catherine Wheel, 'because you have such a sympathetic nature.'",
             "Küçük Torpil Fırıldak Fişek'e, 'Senden hoşlanıyorum,' dedi, 'çünkü çok cana yakın ve sevecen bir tabiatın var.'",
             "sympathetic nature | Cana yakın / anlayışlı mizaç."),
            ("'Sympathy is very well,' observed the Rocket coldly, 'provided it is directed toward superior persons like myself.'",
             "Roket soğuk bir tavırla, 'Benim gibi üstün şahsiyetlere yöneltildiği müddetçe sempati gayet hoştur,' dedi.",
             "provided | '... şartıyla, me kaydıyla' koşul bağlacıdır."),
            ("'I am extraordinarily sensitive myself; in fact, I am the most sensitive object in existence.'",
             "'Ben şahsen fevkalade hassas biriyim; doğrusu, var olan en duyarlı varlık benim.'",
             "sensitive | Hassas, alıngan, duygusal."),
            ("'If anyone speaks harshly to me, my delicate paper casing trembles from head to foot.'",
             "'Biri bana sert bir şekilde konuşursa, narin kağıt gövdem baştan aşağı titrer.'",
             "paper casing | Kağıttan muhafaza / dış kılıf."),
            ("'What a dreadful calamity it would be if anything were to happen to the Prince and Princess tonight!'",
             "'Bu gece Prens ile Prenses'in başına bir şey gelseydi ne korkunç bir felaket olurdu!'",
             "dreadful calamity | Korkunç felaket / afet."),
            ("'Why should anything happen to them?' asked the Catherine Wheel in surprise, stopping her slow turning.",
             "Fırıldak Fişek yavaş dönüşünü durdurarak hayretle, 'Neden başlarına bir şey gelsin ki?' diye sordu.",
             "in surprise | Şaşkınlıkla."),
            ("'They are surrounded by guards, surrounded by courtiers, and surrounded by true love.'",
             "'Etrafı muhafızlarla çevrili, saraylılarla çevrili ve gerçek aşkla kuşatılmış durumdalar.'",
             "surrounded by | İle çevrili / kuşatılmış."),
            ("'Ah, you lack imagination!' cried the Rocket dramatically, clutching his wooden stick with emotion.",
             "Roket duygulanarak tahta sopasına sarılıp dramatik biçimde, 'Ah, sizde hayal gücü eksik!' diye haykırdı.",
             "lack imagination | Hayal gücünden yoksun olmak."),
            ("'Suppose the Prince fell into the river while dancing on the terrace and was tragically drowned!'",
             "'Farz edin ki Prens terasta dans ederken nehre düştü ve feci şekilde boğuldu!'",
             "suppose | Farz et ki, varsayalım ki."),
            ("'Suppose the Princess wept until her violet eyes were completely blinded by salty sorrow!'",
             "'Farz edin ki Prenses tuzlu kederinden menekşe rengi gözleri büsbütün kör olana dek ağladı!'",
             "salty sorrow | Tuzlu keder / acı gözyaşları."),
            ("'Suppose the King lost his kingdom through overwhelming grief and had to play the flute on the highway!'",
             "'Farz edin ki Kral kahredici yas yüzünden krallığını kaybetti ve anayollarda dilenip flüt çalmak zorunda kaldı!'",
             "overwhelming grief | Kahredici / ezici keder."),
            ("'Good heavens!' cried the Bengal Light, 'what an awful catastrophe to contemplate!'",
             "Bengal Meşalesi, 'Aman Tanrım!' diye bağırdı, 'düşünmesi bile ne korkunç bir kıyamet!'",
             "contemplate | Zihninde tasavvur etmek, derin derin düşünmek."),
            ("'It is positively heart-breaking,' sobbed the Rocket, overcome by the vivid horror of his own invention.",
             "Kendi uydurduğu dehşetin canlılığı karşısında ezilen Roket hıçkırarak, 'Bu kesinlikle yürek parçalayıcı,' dedi.",
             "heart-breaking | Yürek parçalayıcı."),
            ("'When I think of the King losing his crown and playing for pennies, I feel I must weep.'",
             "'Kralın tacını kaybedip kuruşlar için flüt çaldığını düşündükçe ağlamam gerektiğini hissediyorum.'",
             "weep | Gözyaşı dökmek, ağlamak."),
            ("'And indeed, I cannot help weeping, for I possess the delicate sensibility of an authentic genius.'",
             "'Ve hakikaten ağlamaktan kendimi alamıyorum; çünkü ben hakiki bir dehanın o narin duyarlılığına sahibim.'",
             "cannot help weeping | Ağlamaktan kendini alamamak."),
            ("With these words, large tears began to roll down his paper sides like heavy raindrops.",
             "Bu sözlerle birlikte, ağır yağmur damlaları gibi iri gözyaşları kağıt gövdesinden aşağı süzülmeye başladı.",
             "roll down | Yuvarlanıp aşağı inmek."),
            ("'Don't cry!' pleaded the Catherine Wheel, 'you will make yourself damp before the display begins.'",
             "Fırıldak Fişek, 'Ağlama!' diye yalvardı, 'gösteri başlamadan önce kendini nemlendirip ıslatacaksın.'",
             "make yourself damp | Kendini nemlendirmek / ıslatmak."),
            ("'A damp rocket is of no use to anybody, for wet gunpowder will never take fire.'",
             "'Nemli bir roket hiç kimsenin işine yaramaz; zira ıslak barut asla ateş almaz.'",
             "gunpowder | Barut; 'take fire' tutuşmak, ateş almak."),
            ("'Leave me alone!' sobbed the Rocket, 'my tears are the sacred proof of my boundless compassion.'",
             "Roket hıçkırıklarla, 'Beni yalnız bırakın!' dedi, 'gözyaşlarım benim sonsuz merhametimin kutsal kanıtıdır.'",
             "boundless compassion | Sınırsız merhamet / şefkat."),
            ("And he continued to weep abundantly, soaking his fuse and dampening his glorious gunpowder.",
             "Ve fitilini ıslatıp o şanlı barutunu nemlendirerek oluk oluk ağlamaya devam etti.",
             "soaking his fuse | Fitilini sırılsıklam ederek.")
        ],
        "vocab_focus": [
            ("sympathetic", "cana yakın, sevecen"),
            ("calamity", "büyük felaket, afet"),
            ("suppose", "farz et ki, varsayalım"),
            ("overwhelming", "ezici, karşı konulmaz"),
            ("contemplate", "üzerinde derinlemesine düşünmek"),
            ("sensibility", "duyarlılık, hassasiyet"),
            ("gunpowder", "barut"),
            ("compassion", "merhamet, şefkat")
        ]
    },

    # PAGE 8: The Tears of the Rocket and Getting Damp
    {
        "page_no": 8,
        "title": "The Tears of the Rocket",
        "tr_title": "Roketin Kibirli Gözyaşları ve Islanması",
        "sentences": [
            ("'If you soak yourself so thoroughly, you will never be able to go off!' warned the Roman Candle.",
             "Roma Kandili, 'Kendini böyle sırılsıklam edersen asla patlayamazsın!' diye uyardı.",
             "go off | Patlamak, infilak etmek (havai fişek/bomba)."),
            ("'I know what I am doing,' replied the Rocket between his sniffs and theatrical groans.",
             "Roket burnunu çekişleri ve teatral inlemeleri arasında, 'Ben ne yaptığımı çok iyi biliyorum,' diye yanıt verdi.",
             "theatrical groans | Tiyatrovari inlemeler."),
            ("'A genius is never understood by ordinary mortals; his grief is too sublime for their vulgar minds.'",
             "'Bir deha sıradan fanilerce asla anlaşılamaz; onun kederi onların kaba zihinleri için fazla yücedir.'",
             "sublime | Yüce, ulvi."),
            ("'The Prince and Princess are at this very moment eating iced pudding and drinking golden wine.'",
             "Fırıldak Fişek, 'Prens ile Prenses şu anda buzlu puding yiyip altın sarısı şarap içiyorlar,' dedi.",
             "iced pudding | Buzlu puding / tatlı."),
            ("'They are perfectly happy and have not the least desire to drown in any river whatsoever.'",
             "'Gayet mutlular ve hiçbir nehirde boğulmak gibi bir arzuları zerre kadar yok.'",
             "whatsoever | 'Hiçbir surette, asla' pekiştiricisidir."),
            ("'That shows their callous lack of imagination,' sniffed the Rocket, shedding another shower of tears.",
             "Roket bir sağanak gözyaşı daha dökerek burnunu çekti: 'Bu onların hayal gücünden yoksun taş kalpliliğini gösterir.'",
             "callous | Duygusuz, katı yürekli, taş kalpli."),
            ("'A truly refined nature anticipates sorrow and weeps before the tragedy actually occurs.'",
             "'Gerçekten incelmiş bir tabiat kederi önceden sezer ve trajedi fiilen gerçekleşmeden evvel ağlar.'",
             "anticipates | Önceden sezmek, beklemek."),
            ("'Well, I am sure the King would not thank you for spoiling his midnight pyrotechnics,' said the Squib.",
             "Torpil, 'Doğrusu Kral'ın gece yarısı fişeklerini berbat ettiğin için sana teşekkür etmeyeceğinden eminim,' dedi.",
             "spoiling | Berbat etmek, bozmak."),
            ("'The King is an amateur,' remarked the Rocket disdainfully, 'and knows nothing of genuine art.'",
             "Roket küçümseyerek, 'Kral bir amatördür,' dedi, 've hakiki sanattan zerre kadar anlamaz.'",
             "disdainfully | Küçümseyerek, hakir görerek."),
            ("'He plays the flute out of tune, and yet expects the stars to dance to his clumsy piping.'",
             "'Flütü detone çalar, yine de yıldızların kendi hantal üflemesine göre dans etmesini bekler.'",
             "out of tune | Detone, akortsuz."),
            ("'I, on the other hand, am a finished master of harmony, splendour, and cosmic spectacle.'",
             "'Ben ise diğer yandan ahengin, ihtişamın ve kozmik gösterinin kusursuz bir üstadıyım.'",
             "finished master | Tam / mükemmel bir usta."),
            ("By this time, the tears had completely saturated the Rocket's touch-paper and outer wrappings.",
             "Bu süre zarfında gözyaşları Roket'in fitil kağıdını ve dış sargılarını tamamen sırılsıklam etmişti.",
             "saturated | Sırılsıklam olmuş, doymuş."),
            ("The black powder inside turned into a heavy, sluggish paste of wet charcoal and sulphur.",
             "İçindeki kara barut, ıslak kömür ve kükürtten oluşan ağır, peltemsi bir hamura dönüştü.",
             "sluggish paste | Ağır, yapışkan hamur."),
            ("Still, he remained immensely pleased with himself, smiling loftily down upon the other fireworks.",
             "Yine de kendinden son derece memnun kaldı ve diğer fişeklere tepeden mağrur bir tebessümle baktı.",
             "loftily | Mağrurca, yukarılardan bakarak."),
            ("'Look how silent they all are,' he thought; 'they are completely struck dumb by my superior intellect.'",
             "'Bakın hepsi nasıl da sus pus oldu,' diye düşündü; 'üstün zekam karşısında dilleri büsbütün tutuldu.'",
             "struck dumb | Dili tutulmuş, şaşkınlıktan donakalmış."),
            ("The moon rose higher in the clear night sky, shedding silver brilliance over the royal gardens.",
             "Ay berrak gece göğünde daha da yükselerek kraliyet bahçelerinin üzerine gümüş parlaklığını döktü.",
             "silver brilliance | Gümüş ışıltı / parlaklık."),
            ("The clocks in the palace towers began to chime, warning everyone that midnight was rapidly approaching.",
             "Saray kulelerindeki saatler çalmaya başlayarak gece yarısının hızla yaklaştığını herkese haber verdi.",
             "chime | Çan çalmak."),
            ("A distant sound of trumpets and kettle-drums announced that the royal banquet was finally concluded.",
             "Uzaktan gelen borazan ve davul sesleri kraliyet ziyafetinin nihayet sona erdiğini duyurdu.",
             "concluded | Sona erdirilmek, tamamlanmak."),
            ("The grand glass doors opened, and the wedding procession stepped out onto the marble terrace.",
             "Büyük cam kapılar açıldı ve düğün alayı mermer terasın üzerine adım attı.",
             "procession | Tören alayı, kortej."),
            ("The Royal Pyrotechnist stepped forward with his glowing torch, ready to commence the spectacle.",
             "Kraliyet Havai Fişekçisi gösteriyi başlatmaya hazır halde elinde parıldayan meşalesiyle öne çıktı.",
             "commence | Başlamak, başlatmak.")
        ],
        "vocab_focus": [
            ("go off", "patlamak, ateş almak"),
            ("sublime", "yüce, ulvi"),
            ("callous", "taş kalpli, duygusuz"),
            ("disdainfully", "küçümseyerek, hakir görerek"),
            ("out of tune", "detone, akortsuz"),
            ("saturated", "sırılsıklam olmuş"),
            ("struck dumb", "dili tutulmuş"),
            ("procession", "kortej, tören alayı")
        ]
    },

    # PAGE 9: The Grand Evening Fireworks Show Begins
    {
        "page_no": 9,
        "title": "The Grand Midnight Display",
        "tr_title": "Görkemli Akşam Gösterisinin Başlaması",
        "sentences": [
            ("Exactly as the clock struck twelve, the Royal Pyrotechnist applied the torch to the first fuse.",
             "Saat tam on ikiyi vurduğunda, Kraliyet Havai Fişekçisi meşaleyi ilk fitile değdirdi.",
             "applied the torch | Meşaleyi değdirmek / ateşe vermek."),
            ("Whizz! Whizz! went the Catherine Wheel, spinning round and round with marvellous rapidity.",
             "Vııız! Vııız! diyerek Fırıldak Fişek harikulade bir süratle fırıl fırıl dönmeye başladı.",
             "rapidity | Hızlılık, sürat."),
            ("She threw out glittering showers of gold and silver sparks that lit up the whole terrace.",
             "Tüm terası aydınlatan altın ve gümüş pırıltılı kıvılcım sağanakları saçtı etrafa.",
             "glittering showers | Parıldayan sağanaklar."),
            ("Boom! went the Roman Candles, shooting great balls of fiery crimson and emerald into the darkness.",
             "Güüm! diye patladı Roma Kandilleri; karanlığın içine kızıl ve zümrüt renginde alev topları fırlatarak.",
             "fiery crimson | Alev kırmızısı."),
            ("The little Squibs danced across the lawn like frantic fireflies, bursting with merry crackles.",
             "Küçük Torpiller neşeli çıtırtılarla patlayarak çimenlik boyunca telaşlı ateşböcekleri gibi dans ettiler.",
             "merry crackles | Neşeli çatırtılar / patırtılar."),
            ("Then the Fire-balloons rose gracefully into the air, drifting towards the mountains like miniature moons.",
             "Ardından Ateş Balonları havaya zarifçe yükselerek minyatür aylar gibi dağlara doğru süzüldüler.",
             "miniature moons | Minyatür / küçük aylar."),
            ("The whole sky became a swirling kaleidoscope of dazzling lights and glorious colours.",
             "Bütün gökyüzü göz kamaştırıcı ışıklar ve muhteşem renklerden oluşan dönen bir çiçek dürbününe dönüştü.",
             "kaleidoscope | Kaleydoskop, çiçek dürbünü."),
            ("The crowd cheered with excitement, clapping their hands and shouting bravo with all their might.",
             "Kalabalık var güçleriyle el çırparak ve 'bravo!' diye bağırarak heyecanla tezahüratta bulundu.",
             "with all their might | Var güçleriyle."),
            ("The little Princess clapped her hands in delight, declaring that it was the prettiest thing in the world.",
             "Küçük Prenses sevinçle ellerini çırparak bunun dünyadaki en tatlı şey olduğunu ilan etti.",
             "in delight | Sevinçle, neşeyle."),
            ("The Prince embraced her warmly, his violet eyes glowing in the radiant light of the fireworks.",
             "Prens, menekşe rengi gözleri havai fişeklerin parlak ışığında parıldayarak ona sımsıkı sarıldı.",
             "embraced | Kucakladı, sarıldı."),
            ("Even the King was pleased, though he remarked that the display could not compare with his flute-playing.",
             "Kral bile memnun kalmıştı, gerçi gösterinin kendi flüt çalışıyla kıyaslanamayacağını yine de belirtti.",
             "could not compare with | İle kıyaslanamazdı."),
            ("Every single firework did its duty magnificently, exhausting its brilliant life in a blaze of glory.",
             "Her bir havai fişek vazifesini muazzam biçimde yaptı ve parlak ömrünü bir ihtişam alevi içinde tüketti.",
             "blaze of glory | Şan ve şeref alevi."),
            ("The Catherine Wheel spun until her last spark vanished into a sweet whisper of smoke.",
             "Fırıldak Fişek son kıvılcımı tatlı bir duman fısıltısına karışıp yok olana dek döndü.",
             "vanished | Gözden kayboldu, yok oldu."),
            ("The Roman Candles burned to the very end, scattering stars across the royal fountains.",
             "Roma Kandilleri en sonuna kadar yandı ve kraliyet fıskiyelerinin üzerine yıldızlar serpiştirdi.",
             "scattering | Saçmak, serpiştirmek."),
            ("Only the Remarkable Rocket remained untouched on his tall stick, looking gloomy and thoroughly wet.",
             "Yalnızca Harika Roket yüksek sopası üzerinde hüzünlü ve sırılsıklam halde dokunulmadan öylece kaldı.",
             "remained untouched | Dokunulmadan kalmak."),
            ("Finally, the Pyrotechnist noticed him and touched his burning match to the Rocket's long fuse.",
             "Nihayet Havai Fişekçi onu fark etti ve yanan kibritini Roket'in uzun fitiline değdirdi.",
             "burning match | Yanan kibrit."),
            ("The match hissed against the damp paper, but the fuse merely sputtered and would not catch fire.",
             "Kibrit nemli kağıda değince cızıldadı; fakat fitil sadece cılız cızbız sesleri çıkardı ve bir türlü tutuşmadı.",
             "sputtered | Cızbız etmek, tükürür gibi ses çıkarmak."),
            ("'Aha!' whispered the Rocket proudly, 'they are keeping me for some extraordinary state occasion!'",
             "Roket gururla fısıldadı: 'Aha! Beni fevkalade bir devlet töreni için saklıyorlar!'",
             "state occasion | Resmi devlet töreni."),
            ("'They know that my magnificence would completely overshadow the rest of the company.'",
             "'Benim haşmetimin topluluğun geri kalanını tamamen gölgede bırakacağını çok iyi biliyorlar.'",
             "overshadow | Gölgede bırakmak."),
            ("So he stood waiting on his stick, expecting to be brought back into the palace with royal honours.",
             "Böylece saraya kraliyet şerefleriyle geri taşınmayı umarak sopasının üzerinde bekleyip durdu.",
             "with royal honours | Kraliyet nişanlarıyla / şerefiyle.")
        ],
        "vocab_focus": [
            ("rapidity", "hızlılık, çeviklik"),
            ("fiery crimson", "alev kırmızısı"),
            ("kaleidoscope", "kaleydoskop, çiçek dürbünü"),
            ("blaze of glory", "şan ve şeref alevi"),
            ("scattering", "saçmak, serpmek"),
            ("sputtered", "cızırdayıp söndü"),
            ("state occasion", "resmi devlet töreni"),
            ("overshadow", "gölgede bırakmak")
        ]
    },

    # PAGE 10: The Fizzle and Being Thrown Into the Mud
    {
        "page_no": 10,
        "title": "Thrown into the Mud",
        "tr_title": "Yanmayan Roket ve Çamura Fırlatılış",
        "sentences": [
            ("The next morning, the palace servants came out to clear away the rubbish from the terrace.",
             "Ertesi sabah saray hizmetkarları terastaki süprüntüleri temizlemek için dışarı çıktılar.",
             "clear away | Ortadan kaldırmak, temizlemek."),
            ("'Here is a bad rocket,' said one workman, picking up the Rocket by his stick.",
             "İşçilerden biri Roket'i sopasından tutarak, 'İşte bozuk bir roket,' dedi.",
             "picking up | Yukarı kaldırmak, yerden almak."),
            ("'What a dreadful failure! It never went off at all, but only got soaked with dew.'",
             "'Ne korkunç bir fiyasko! Hiç ateş almamış, sadece çiy ile sırılsıklam olmuş.'",
             "dreadful failure | Korkunç fiyasko / başarısızlık."),
            ("'Bad rocket? Failure?' muttered the Rocket to himself with indignant indignation.",
             "Roket içerlemiş bir hiddetle kendi kendine 'Bozuk roket mi? Fiyasko mu?' diye söylendi.",
             "muttered to himself | Kendi kendine söylenmek."),
            ("'He said grand rocket, of course; these common people always confuse grand and bad.'",
             "'Elbette harika roket demiştir; bu avam halk 'harika' ile 'bozuk' kelimelerini daima karıştırır.'",
             "confuse | Karıştırmak, ayırt edememek."),
            ("The workman swung his arm back and threw the damp Rocket over the garden wall into the ditch.",
             "İşçi kolunu geriye doğru savurdu ve nemli Roket'i bahçe duvarının üzerinden hendeğe fırlattı.",
             "ditch | Hendek, su kanalı."),
            ("Splash! went the Rocket, landing headfirst in a deep, muddy pool among the tall rushes.",
             "Şılapp! diye Roket, uzun sazlıkların arasındaki derin, çamurlu bir birikintiye kafa üstü çakıldı.",
             "landing headfirst | Kafa üstü yere/suya inmek."),
            ("'This is very comfortable,' remarked the Rocket, sinking gently into the black ooze.",
             "Siyah balçığın içine usulca batan Roket, 'Burası son derece rahat,' dedi.",
             "ooze | Balçık, çamur."),
            ("'No doubt this is some fashionable watering-place sent to restore my delicate nerves.'",
             "'Hiç şüphesiz burası, narin sinirlerimi yatıştırmak için gönderildiğim gözde bir kaplıcadır.'",
             "watering-place | Kaplıca, ılıca, dinlenme yeri."),
            ("'A genius requires rest after experiencing such profound and overwhelming emotions.'",
             "'Böylesine derin ve kahredici duygular tecrübe ettikten sonra bir deha mutlaka dinlenmeye ihtiyaç duyar.'",
             "requires rest | Dinlenme gerektirir."),
            ("He lay quietly in the mud, imagining that the Court was mourning his sudden departure.",
             "Sarayın onun bu ani ayrılışı için yas tuttuğunu hayal ederek çamurun içinde sessizce yattı.",
             "mourning | Yas tutmak, kederlenmek."),
            ("'The Prince will probably refuse to eat until I am recovered from this tranquil retreat.'",
             "'Prens muhtemelen ben bu huzurlu inzivadan geri dönene dek yemek yemeyi reddedecektir.'",
             "tranquil retreat | Huzurlu inziva yeri."),
            ("Just then, a little frog with bright jewel eyes popped his head out of the green water.",
             "Tam o sırada, mücevher gibi parlak gözleri olan küçük bir kurbağa kafasını yeşil sudan dışarı çıkardı.",
             "popped his head out | Kafasını aniden dışarı uzatmak."),
            ("'Croak, croak, croak!' said the Frog, staring curiously at the long wooden stick.",
             "Kurbağa uzun tahta sopaya merakla bakarak, 'Vrak, vrak, vrak!' dedi.",
             "staring curiously | Merakla dik dik bakmak."),
            ("'A newcomer, I observe! Well, there is nothing like mud for improving the complexion.'",
             "'Yeni gelen bir misafir görüyorum! Doğrusu, cilt güzelliği için çamur gibisi yoktur.'",
             "complexion | Cilt rengi, ten güzelliği."),
            ("'Give me good, wholesome dampness and plenty of weeds, and I am entirely contented.'",
             "'Bana iyi, şifalı bir nem ve bolca su yosunu verin, ben büsbütün tatmin olurum.'",
             "wholesome dampness | Yararlı, sıhhatli nemlilik."),
            ("'Are you fond of rainy weather?' the Frog inquired politely, paddling closer with his webbed feet.",
             "Kurbağa perdeli ayaklarıyla daha da yakına yüzerek nezaketle, 'Yağmurlu havayı sever misiniz?' diye sordu.",
             "webbed feet | Perdeli ayaklar; 'fond of' bir şeyi sevmek."),
            ("The Rocket made no reply, feeling deeply offended that a common reptile should address him.",
             "Sıradan bir sürüngenin kendisine hitap etmesinden derin biçimde gocunan Roket hiç cevap vermedi.",
             "deeply offended | Derinden kırılmış / gocunmuş."),
            ("'You seem to have lost your tongue,' observed the Frog pleasantly, blinking in the morning sun.",
             "Kurbağa sabah güneşinde gözlerini kırpıştırarak tatlı bir dille, 'Dilinizi yutmuş gibisiniz,' dedi.",
             "lost your tongue | Dilini yutmak."),
            ("'Never mind, I can easily do all the talking for both of us, as I possess a natural talent for conversation.'",
             "'Zararı yok; sohbete karşı doğal bir yeteneğim olduğu için ikimizin yerine de ben kolayca konuşabilirim.'",
             "talent for conversation | Konuşma / sohbet kabiliyeti.")
        ],
        "vocab_focus": [
            ("clear away", "temizlemek, ortadan kaldırmak"),
            ("dreadful failure", "korkunç başarısızlık"),
            ("landing headfirst", "kafa üstü çakılmak"),
            ("ooze", "balçık, cıvık çamur"),
            ("watering-place", "kaplıca, dinlenme yeri"),
            ("complexion", "ten, cilt rengi"),
            ("wholesome", "sağlıklı, şifalı"),
            ("webbed feet", "perdeli ayaklar")
        ]
    },

    # PAGE 11: The Encounter with the Philosophical Frog
    {
        "page_no": 11,
        "title": "The Philosophical Frog",
        "tr_title": "Felsefi Kurbağa ile Karşılaşma",
        "sentences": [
            ("'Croak, croak!' continued the Frog, perching himself comfortably on a broad water-lily leaf.",
             "Kurbağa geniş bir nilüfer yaprağının üzerine rahatça tüneyerek, 'Vrak, vrak!' diye devam etti.",
             "perching himself | Tünemek, konmak."),
            ("'I am a member of the Glee Club, which meets every evening by the old mill-pond.'",
             "'Ben her akşam eski değirmen göletinin kıyısında toplanan Koro Kulübü'nün bir üyesiyim.'",
             "Glee Club | Şarkı söyleme kulübü / koro cemiyeti."),
            ("'We sing in chorus for hours together, producing the most melodious harmony in the entire parish.'",
             "'Saatlerce hep birlikte koro halinde şarkı söyler ve bütün nahiyedeki en ahenkli melodiyi üretiriz.'",
             "parish | Dini nahiye, cemaat bölgesi."),
            ("'When we begin our nocturnal concert, people lie awake in their beds listening with absolute enchantment.'",
             "'Gece konserimize başladığımızda, insanlar yataklarında uyanık kalıp mutlak bir büyülenmeyle bizi dinlerler.'",
             "nocturnal concert | Gece konseri; 'enchantment' büyülenme."),
            ("'Indeed, the farmer's wife told her sister only yesterday that our music kept her awake all night long.'",
             "'Doğrusu çiftçinin karısı daha dün kız kardeşine müziğimizin kendisini bütün gece uyutmadığını söyledi.'",
             "all night long | Bütün gece boyunca."),
            ("'Is that not a gratifying tribute to our artistic abilities?' asked the Frog with immense pride.",
             "Kurbağa muazzam bir gururla, 'Bu bizim sanatsal yeteneklerimize yönelik gurur verici bir övgü değil midir?' diye sordu.",
             "gratifying tribute | Gurur verici / tatmin edici övgü."),
            ("The Rocket coughed dryly, attempting to summon his former grandeur from within the mud.",
             "Roket çamurun içinden eski heybetini toplamaya çalışarak kuru bir şekilde öksürdü.",
             "summon his former grandeur | Eski ihtişamını geri çağırmak."),
            ("'Ahem! Ahem!' he began in an icy voice, 'you have an extremely irritating habit of talking nonsense.'",
             "Buz gibi bir sesle, 'Öhö! Öhö!' diye söze başladı, 'son derece sinir bozucu bir saçmalama alışkanlığınız var.'",
             "talking nonsense | Saçmalamak, boş konuşmak."),
            ("'Do you know who I am? I am a pyrotechnic marvel of high aristocratic birth.'",
             "'Benim kim olduğumu biliyor musunuz? Ben yüksek aristokratik kökenden gelen piroteknik bir harikayım.'",
             "aristocratic birth | Asil doğum, soyluluk."),
            ("'I was manufactured from the finest materials to illuminate the wedding of the King's own son.'",
             "'Ben bizzat Kralın oğlunun düğününü aydınlatmak için en seçkin malzemelerden imal edildim.'",
             "manufactured | İmal edilmiş, üretilmiş."),
            ("'Croak!' chuckled the Frog, 'aristocratic birth is very charming, but it cannot catch flies.'",
             "Kurbağa kıkırdayarak, 'Vrak!' dedi, 'soylu doğum çok sevimli bir şeydir ama sinek yakalayamaz.'",
             "chuckled | Kıkırdamak, bıyık altından gülmek."),
            ("'In this ditch, practical ability is regarded as vastly superior to decorative lineage.'",
             "'Bu hendekte pratik beceriler, süslü bir soyağacından fersah fersah üstün kabul edilir.'",
             "vastly superior | Katbekat / fersah fersah üstün."),
            ("'How dare you speak of flies in my presence!' cried the Rocket, shuddering with intense disgust.",
             "Roket yoğun bir iğrentiyle ürpererek, 'Huzurumda sineklerden bahsetmeye nasıl cüret edersiniz!' diye haykırdı.",
             "shuddering with disgust | Tiksintiyle ürpermek."),
            ("'I feed upon gunpowder, glory, and universal acclaim, not on wretched insects.'",
             "'Ben sefil böceklerle değil barutla, şanla ve evrensel takdirle beslenirim.'",
             "universal acclaim | Evrensel alkış ve övgü."),
            ("'Every creature feeds on what suits its constitution,' replied the philosophical Frog serenely.",
             "Felsefi Kurbağa sükunetle, 'Her canlı kendi bünyesine ne uyuyorsa onunla beslenir,' diye yanıt verdi.",
             "constitution | Bünye, yaradılış."),
            ("'Personally, I find dragonflies delicious, though beetles have a slightly crisper texture.'",
             "'Şahsen ben yusufçukları pek lezzetli bulurum, gerçi kınkanatlı böceklerin dokusu biraz daha çıtırdır.'",
             "crisper texture | Daha çıtır doku."),
            ("'You are an insufferable peasant,' hissed the Rocket, trying in vain to raise his damp stick.",
             "Roket ıslak sopasını boş yere yukarı kaldırmaya çalışarak, 'Sen çekilmez bir köylüsün,' diye tısladı.",
             "insufferable peasant | Çekilmez / katlanılmaz köylü."),
            ("'I am accustomed to the refined compliments of princes and ambassadors, not the croaking of reptiles.'",
             "'Ben sürüngenlerin vıraklamasına değil, prenslerin ve elçilerin incelikli iltifatlarına alışkınım.'",
             "accustomed to | Bir şeye alışkın olmak."),
            ("'Well, good morning to you,' said the Frog cheerfully, preparing to dive into the cool water.",
             "Kurbağa neşeyle serin suya dalmaya hazırlanarak, 'Eh, size hayırlı sabahlar,' dedi.",
             "dive into | İçine dalmak."),
            ("'I must attend our morning rehearsal; we are practicing a magnificent chorus in B-flat minor.'",
             "'Sabah provamıza katılmam gerek; Si bemol minörde muhteşem bir koro çalışması yapıyoruz.'",
             "rehearsal | Prova; 'B-flat minor' Si bemol minör müzik tonu.")
        ],
        "vocab_focus": [
            ("Glee Club", "koro cemiyeti"),
            ("nocturnal", "geceye ait, geceleyin olan"),
            ("gratifying tribute", "gurur verici övgü"),
            ("aristocratic birth", "soylu köken"),
            ("vastly superior", "katbekat üstün"),
            ("universal acclaim", "evrensel takdir"),
            ("insufferable", "katlanılmaz, çekilmez"),
            ("rehearsal", "prova")
        ]
    },

    # PAGE 12: The Frog's Monologue on Noise and Society
    {
        "page_no": 12,
        "title": "Noise and Good Society",
        "tr_title": "Kurbağanın Gürültü ve Toplum Üzerine Nutku",
        "sentences": [
            ("With a graceful plop, the Frog disappeared beneath the green duckweed, leaving only widening ripples.",
             "Zarif bir 'şıp' sesiyle Kurbağa yeşil su mercimeklerinin altında kayboldu ve geride yalnızca genişleyen halkalar bıraktı.",
             "duckweed | Su mercimeği; 'widening ripples' genişleyen dalgacıklar."),
            ("The Rocket remained in the mud, fuming with unexpressed indignation at being treated so casually.",
             "Roket bu denli sıradan bir muamele görmenin getirdiği ifade edilememiş bir hiddetle çamurun içinde köpürerek kaldı.",
             "fuming | Köpürmek, öfkeden deliye dönmek."),
            ("'To think that a creature of my caliber should be exposed to such provincial insolence!' he muttered.",
             "'Benim çapımdaki bir varlığın böylesine taşralı bir küstahlığa maruz kalacağını düşünmek bile korkunç!' diye söylendi.",
             "provincial insolence | Taşralı küstahlığı / terbiyesizliği."),
            ("'The world has truly gone to ruin when a common batrachian presumes to lecture a master of pyrotechnics.'",
             "'Sıradan bir kurbağa bir piroteknik üstadına ders vermeye kalkıştığına göre dünya hakikaten çığırından çıkmış.'",
             "presumes to lecture | Ders vermeye cüret etmek / kalkışmak."),
            ("He shook his wet casing violently, but only succeeded in splattering muddy water over his nose.",
             "Islak gövdesini şiddetle sarstı ama yalnızca burnunun üzerine çamurlu su sıçratmayı başarabildi.",
             "splattering | Sıçratmak, püskürtmek."),
            ("A large white Dragonfly came skimming over the surface of the pool, hovering on iridescent wings.",
             "İri beyaz bir Yusufçuk, yanardöner kanatları üzerinde havada asılı kalarak havuzun yüzeyini sıyırıp geçti.",
             "iridescent wings | Yanardöner / gökkuşağı gibi parlayan kanatlar."),
            ("'What a dreadful noise those frogs make!' said the Dragonfly, alighting delicately on a reed.",
             "Yusufçuk narin bir sazın üzerine zarifçe konarak, 'Şu kurbağalar ne kadar da korkunç bir gürültü yapıyor!' dedi.",
             "alighting delicately | Narin bir şekilde konmak."),
            ("'They seem to think that nobody has ears except themselves and their dreadful chorus.'",
             "'Kendilerinden ve o korkunç korolarından başka kimsenin kulağı yokmuş gibi davranıyorlar.'",
             "dreadful chorus | Korkunç koro."),
            ("'I quite agree with you,' said the Rocket, delighted to find someone who shared his disgust.",
             "Roket kendi tiksintisini paylaşan birini bulmaktan ötürü sevinçle, 'Size tamamen katılıyorum,' dedi.",
             "quite agree with | Biriyle tamamen aynı fikirde olmak."),
            ("'They have no sense of manners, no appreciation of genius, and no knowledge of high society.'",
             "'Ne görgü kurallarından anlıyorlar ne dehadan ne de yüksek sosyeteden.'",
             "sense of manners | Görgü anlayışı, edep."),
            ("'I am myself a person of the greatest distinction, currently taking the mud-baths for my health.'",
             "'Ben şahsen şu anda sağlığım için çamur banyosu yapmakta olan, fevkalade seçkin bir şahsiyetim.'",
             "mud-baths | Çamur banyoları."),
            ("The Dragonfly tilted its head and looked at the Rocket with multifaceted, glittering eyes.",
             "Yusufçuk kafasını eğdi ve çok yönlü, parıltılı gözleriyle Roket'e baktı.",
             "multifaceted | Çok yönlü, petek gözlü."),
            ("'You look remarkably like an old stick that someone has thrown away after a bonfire.'",
             "'Bir kamp ateşinden sonra birinin fırlatıp attığı eski bir sopaya fevkalade benziyorsunuz.'",
             "thrown away | Fırlatıp atılmış."),
            ("'An old stick?' gasped the Rocket, turning purple with insulted dignity beneath his mud.",
             "Roket çamurun altında incinmiş haysiyetiyle morararak, 'Eski bir sopa mı?' diye soludu.",
             "insulted dignity | İncinmiş vakar / haysiyet."),
            ("'I am a Rocket! A Rocket of extraordinary power, capable of illuminating the entire cosmos!'",
             "'Ben bir Roketim! Bütün evreni aydınlatmaya muktedir, olağanüstü güce sahip bir Roketim ben!'",
             "cosmos | Evren, kozmos."),
            ("'Well, you are not illuminating anything at present,' remarked the Dragonfly in an airy tone.",
             "Yusufçuk havai bir tonla, 'Eh, şu anda hiçbir yeri aydınlatmıyorsunuz,' dedi.",
             "airy tone | Umursamaz, kayıtsız bir ses tonu."),
            ("'Except possibly a few tadpoles who are swimming around your damp cardboard neck.'",
             "'Belki nemli karton boynunuzun etrafında yüzen birkaç iribaş hariç tabii.'",
             "tadpoles | İribaşlar, kurbağa yavruları."),
            ("'I am biding my time,' said the Rocket haughtily, 'waiting for a truly magnificent opportunity.'",
             "Roket kibirle, 'Ben doğru zamanı kolluyorum,' dedi, 'gerçekten muazzam bir fırsat bekliyorum.'",
             "biding my time | Zamanını / sırasını beklemek deyimidir."),
            ("'When I go off, the sound of my explosion will shake the foundations of the royal palace.'",
             "'Ateşlendiğimde, patlamamın sesi kraliyet sarayının temellerini sarsacak.'",
             "shake the foundations | Temellerini sarsmak."),
            ("The Dragonfly laughed a tiny, shimmering laugh and darted away towards the water-lilies.",
             "Yusufçuk minik, ışıltılı bir kahkaha attı ve nilüferlere doğru hızla süzülüp uzaklaştı.",
             "darted away | Hızla fırlayıp uzaklaşmak.")
        ],
        "vocab_focus": [
            ("fuming", "öfkeden köpüren"),
            ("provincial insolence", "taşralı küstahlığı"),
            ("iridescent", "yanardöner, sedefli"),
            ("alighting", "konmak, yere inmek"),
            ("mud-baths", "çamur banyoları"),
            ("multifaceted", "çok cepheli, petek gözlü"),
            ("biding my time", "fırsatını beklemek"),
            ("darted away", "ok gibi fırlayıp uzaklaştı")
        ]
    },

    # PAGE 13: The Dragonfly, the Duck, and Common Sense
    {
        "page_no": 13,
        "title": "The Duck and Common Sense",
        "tr_title": "Yusufçuk, Ördek ve Sağduyu",
        "sentences": [
            ("Hardly had the Dragonfly departed when a fat, elderly Duck waddled leisurely down to the bank.",
             "Yusufçuk henüz yeni ayrılmıştı ki şişman, yaşlıca bir Ördek aheste aheste kıyıya doğru paytak paytak yürüdü.",
             "waddled leisurely | Aheste aheste paytak yürümek."),
            ("She dipped her broad yellow beak into the muddy water and began searching for succulent water-snails.",
             "Geniş sarı gagasını çamurlu suya daldırdı ve etli su salyangozları aramaya koyuldu.",
             "succulent | Etli, sulu, lezzetli."),
            ("As she paddled along the edge, her webbed foot struck against the Rocket's wooden stick.",
             "Kıyı boyunca kürek çekerken, perdeli ayağı Roket'in tahta sopasına çarptı.",
             "paddled along | Kıyı boyunca ayak çırparak yüzmek."),
            ("'Quack, quack!' exclaimed the Duck, peering down; 'what an exceedingly curious object!'",
             "Ördek aşağıya doğru bakarak, 'Vak, vak!' diye bağırdı; 'ne kadar da fevkalade tuhaf bir nesne!'",
             "peering down | Aşağıya dikkatle bakmak."),
            ("'I cannot imagine what you were made for, unless you are intended for an improved sort of turnip-cutter.'",
             "'Gelişmiş türde bir şalgam kesici olarak tasarlanmadıysanız, ne için yapıldığınızı hiç tahayyül edemiyorum.'",
             "turnip-cutter | Şalgam doğrayıcı alet."),
            ("'A turnip-cutter!' shrieked the Rocket, shuddering with horror at such unutterable vulgarity.",
             "Böylesine dile gelmez bir bayağılık karşısında dehşetle ürperen Roket, 'Bir şalgam kesici mi!' diye çığlık attı.",
             "unutterable vulgarity | Tarif edilemez bayağılık."),
            ("'Madam, you are speaking to an instrument of sublime artistic elevation, not a kitchen implement!'",
             "'Hanımefendi, bir mutfak aletiyle değil; ulvi bir sanatsal yükselişin vasıtasıyla konuşuyorsunuz!'",
             "kitchen implement | Mutfak aleti / gereci."),
            ("'I am a Rocket, the scion of celebrated inventors, designed to conquer the starry firmament.'",
             "'Ben meşhur mucitlerin soyundan gelen ve yıldızlı gökkubbeyi fethetmek üzere tasarlanmış bir Roketim.'",
             "starry firmament | Yıldızlı gökkubbe; 'scion' oğul, asil varis."),
            ("'Well, there is no need to shout,' replied the Duck placidly, shaking the water from her tail.",
             "Ördek kuyruğundaki suyu silkeleyerek sakince, 'Eh, bağırmaya hiç lüzum yok,' dedi.",
             "placidly | Sakince, uysalca."),
            ("'I judge everything by its practical utility; if a thing cannot be used, it has no genuine value.'",
             "'Ben her şeyi pratik faydasına göre değerlendiririm; bir şey kullanılamıyorsa hakiki bir değeri yoktur.'",
             "practical utility | Pratik fayda / yararlılık."),
            ("'Can you lay eggs? Can you swim across the pond? Can you dive down to the river-bed?'",
             "'Yumurta yumurtlayabilir misiniz? Göletin karşısına yüzebilir misiniz? Nehir yatağına dalabilir misiniz?'",
             "lay eggs | Yumurtlamak."),
            ("'Certainly not!' answered the Rocket with lofty disdain, 'such mundane occupations are beneath me.'",
             "Roket yüce bir küçümsemeyle, 'Elbette hayır!' dedi, 'bu tür dünyevi meşgaleler benim seviyemin çok altındadır.'",
             "mundane occupations | Sıradan, dünyevi meşgaleler."),
            ("'Then I have no opinion of you whatever,' stated the Duck firmly, preening her glossy white feathers.",
             "Ördek parlak beyaz tüylerini gagasıyla düzelterek kesin bir dille, 'Öyleyse hakkınızda zerre kadar müspet fikrim yok,' dedi.",
             "preening | Tüylerini gagasıyla temizleyip taramak."),
            ("'I am a domestic bird with family responsibilities, and I value common sense above all things.'",
             "'Ben ailevi sorumlulukları olan ehil bir kuşum ve her şeyin üzerinde sağduyuya kıymet veririm.'",
             "common sense | Sağduyu, aklıselim."),
            ("'Common sense is the refuge of the unimaginative,' retorted the Rocket passionately.",
             "Roket tutkuyla, 'Sağduyu, hayal gücünden yoksun olanların sığınağıdır,' diye lafı yapıştırdı.",
             "refuge of the unimaginative | Hayal gücü olmayanların sığınağı."),
            ("'Genius lives on ideals, aspirations, and magnificent dreams of transcendent glory.'",
             "'Deha; ideallerle, yüce gayelerle ve aşkın ihtişamın muhteşem rüyalarıyla yaşar.'",
             "transcendent glory | Aşkın / sınırları aşan ihtişam."),
            ("'That may be so,' murmured the Duck, swimming out towards the middle of the quiet stream.",
             "Ördek sakin derenin ortasına doğru yüzerek, 'Öyle olabilir,' diye mırıldandı.",
             "swimming out | Yüzerek açılmak."),
            ("'But ideals will not fill an empty stomach nor keep the cold wind from blowing through the reeds.'",
             "'Fakat idealler ne boş bir mideyi doyurur ne de soğuk rüzgarın sazlıkların arasından esmesini engeller.'",
             "empty stomach | Boş mide, aç karın."),
            ("She tipped her head down into the water, kicking her yellow paddles in search of small minnows.",
             "Küçük tatlı su balıklarını aramak için sarı ayaklarını çırparak kafasını suya daldırdı.",
             "minnows | Küçük tatlı su balıkları."),
            ("The Rocket remained solitary once more, convinced that the entire world was incapable of appreciating his worth.",
             "Tüm dünyanın kendi kıymetini takdir etmekten aciz olduğuna inanan Roket bir kez daha yapayalnız kaldı.",
             "appreciating his worth | Kıymetini / değerini takdir etmek.")
        ],
        "vocab_focus": [
            ("waddled", "paytak paytak yürüdü"),
            ("succulent", "etli ve sulu"),
            ("practical utility", "pratik yararlılık"),
            ("mundane", "dünyevi, sıradan"),
            ("preening", "tüylerini taramak/düzeltmek"),
            ("common sense", "sağduyu, aklıselim"),
            ("transcendent", "aşkın, üstün"),
            ("solitary", "yapayalnız, tek başına")
        ]
    },

    # PAGE 14: The Boys and the Bonfire
    {
        "page_no": 14,
        "title": "Two Boys and the Bonfire",
        "tr_title": "İki Çocuk ve Kamp Ateşi",
        "sentences": [
            ("Later that afternoon, two ragged village boys came strolling through the meadow carrying a tin kettle.",
             "O öğleden sonra, ellerinde teneke bir çaydanlık taşıyan hırpani giyimli iki köylü çocuğu çayırda dolaşmaya çıktı.",
             "ragged village boys | Hırpani / yırtık pırtık köylü çocukları."),
            ("They were gathering dry sticks and driftwood to kindle a fire and boil some water for tea.",
             "Ateş yakmak ve çay için biraz su kaynatmak maksadıyla kuru dallar ve odun parçaları topluyorlardı.",
             "driftwood | Sürüklenmiş odun parçası; 'kindle a fire' ateş yakmak."),
            ("'Look here!' shouted the younger boy, pointing his grimy finger into the muddy ditch.",
             "Daha küçük olan çocuk kirli parmağıyla çamurlu hendeği işaret ederek, 'Şuraya bak!' diye bağırdı.",
             "grimy finger | Kirli / pasaklı parmak."),
            ("'Here is an old stick floating in the mud; it will do famously to keep the kettle boiling.'",
             "'İşte çamurun içinde yüzen eski bir sopa; çaydanlığı kaynatmak için harika bir iş görür.'",
             "do famously | Harika iş görmek / çok iyi yaramak deyimidir."),
            ("The elder boy reached down with a crooked branch and fished the Rocket out of the weeds.",
             "Büyük çocuk eğri bir dalla uzanarak Roket'i su yosunlarının arasından çekip çıkardı.",
             "fished out | Çekip çıkarmak, oltayla yakalar gibi almak."),
            ("'Old stick!' cried the Rocket, feeling a thrill of sudden indignation run through his paper spine.",
             "Roket kağıttan omurgasından ani bir öfke ürpertisi geçtiğini hissederek, 'Eski sopa ha!' diye haykırdı.",
             "thrill of indignation | Öfke ürpertisi."),
            ("'They call me an old stick because they are rustic youths without any comprehension of pyrotechnics.'",
             "'Piroteknikten zerrece anlamayan köylü veletleri oldukları için bana eski sopa diyorlar.'",
             "rustic youths | Köylü çocukları / toy delikanlılar."),
            ("'No doubt they are royal messengers sent in disguise to conduct me to the capital.'",
             "'Hiç şüphesiz beni başkente götürmek üzere kılık değiştirip gönderilmiş kraliyet ulakları bunlar.'",
             "royal messengers | Kraliyet ulakları / habercileri."),
            ("The boys carried him over to the corner of the field, where they had built a small mound of dry twigs.",
             "Çocuklar onu, kuru çalılardan küçük bir yığın yaptıkları tarlanın köşesine kadar taşıdılar.",
             "mound of dry twigs | Kuru çalı çırpı yığını."),
            ("They placed the tin kettle on top of three flat stones and arranged the firewood underneath.",
             "Teneke çaydanlığı üç yassı taşın üzerine yerleştirdiler ve yakacak odunları altına dizdiler.",
             "firewood | Yakacak odun."),
            ("Then the younger boy laid the damp Rocket directly across the glowing red embers.",
             "Ardından küçük çocuk, nemli Roket'i doğrudan kor gibi parlayan kırmızı közlerin üzerine koydu.",
             "glowing red embers | Kor gibi parlayan kırmızı közler."),
            ("'Now we shall have a magnificent blaze!' the boy exclaimed, blowing upon the coals to make them flare.",
             "Çocuk kömürleri alevlendirmek için üzerine üfleyerek, 'Şimdi muhteşem bir alevimiz olacak!' diye haykırdı.",
             "magnificent blaze | Muhteşem alev / yangın."),
            ("The heat began to dry the Rocket's saturated cardboard, warming the damp black powder inside.",
             "Sıcaklık Roket'in sırılsıklam olmuş mukavvasını kurutmaya ve içindeki nemli kara barutu ısıtmaya başladı.",
             "saturated cardboard | Sırılsıklam olmuş mukavva."),
            ("'This is an official deputation,' reasoned the Rocket, luxuriating in the rising warmth.",
             "Yükselen sıcaklığın tadını çıkaran Roket, 'Bu resmi bir heyet kabulüdür,' diye akıl yürüttü.",
             "official deputation | Resmi heyet / temsilciler kurulu."),
            ("'They are applying artificial heat to restore my pristine vigour before my triumphant ascent.'",
             "'Şanlı yükselişimden önce o lekesiz zindeliğimi geri kazandırmak için bana yapay ısı tatbik ediyorlar.'",
             "pristine vigour | İlk günkü lekesiz canlılık, zindelik."),
            ("'Presently the Court will arrive with brass bands and golden banners to witness my great performance.'",
             "'Az sonra saray ahalisi bando takımları ve altın sancaklarla büyük gösterime şahit olmak için buraya varacaktır.'",
             "brass bands | Bando takımı, nefesli çalgılar."),
            ("The dry stick caught fire first, crackling cheerfully as the flames licked around the painted paper.",
             "Önce kuru sopa alev aldı; alevler boyalı kağıdın etrafını yaladıkça neşeyle çıtırdamaya başladı.",
             "licked around | Etrafını yalamak (alev için)."),
            ("The heat penetrated deeper and deeper, driving off all the remaining moisture in clouds of white steam.",
             "Isı gitgide daha derine işledi ve kalan tüm nemi beyaz buhar bulutları halinde dışarı attı.",
             "penetrated | İşlemek, içine nüfuz etmek."),
            ("The gunpowder inside dried completely, growing hotter and hotter until it reached its ignition point.",
             "İçindeki barut tamamen kurudu; ta ki tutuşma noktasına erişene kadar ısındıkça ısındı.",
             "ignition point | Tutuşma, alev alma noktası."),
            ("'I feel that I am going to explode with unparalleled brilliance!' shouted the Rocket in ecstasy.",
             "Roket kendinden geçmiş bir vecd ile, 'Emsalsiz bir parlaklıkla patlamak üzere olduğumu hissediyorum!' diye bağırdı.",
             "in ecstasy | Vecd içinde, kendinden geçmiş halde.")
        ],
        "vocab_focus": [
            ("ragged", "hırpani, yırtık pırtık"),
            ("kindle a fire", "ateş yakmak/tutuşturmak"),
            ("do famously", "fevkalade işe yaramak"),
            ("embers", "korlar, közler"),
            ("magnificent blaze", "muazzam alev"),
            ("pristine vigour", "lekesiz zindelik/kuvvet"),
            ("penetrated", "nüfuz etti, derine işledi"),
            ("in ecstasy", "vecd içinde, kendinden geçmiş")
        ]
    },

    # PAGE 15: The Solitary Explosion in Daylight
    {
        "page_no": 15,
        "title": "The Solitary Explosion",
        "tr_title": "Gün Ortasında Tek Başına Patlama ve Sönüş",
        "sentences": [
            ("Suddenly, the dried fuse caught a spark from the crackling twigs beneath the kettle.",
             "Ansızın, kurumuş fitil çaydanlığın altındaki çıtırdayan dallardan bir kıvılcım kaptı.",
             "caught a spark | Kıvılcım kapmak / almak."),
            ("Fizz! Fizz! went the powder, hissing sharply as the flame raced up into the main chamber.",
             "Cııız! Cııız! diye ses çıkardı barut; alev ana hazneye doğru hızla tırmanırken keskin bir şekilde tısladı.",
             "hissing sharply | Keskin bir şekilde tıslamak."),
            ("Bang! went the Rocket, shooting violently straight up into the clear midday sky.",
             "Güüm! diye fırladı Roket; dosdoğru öğle vaktinin apaydınlık gökyüzüne şiddetle yükselerek.",
             "shooting violently | Şiddetle yukarı fırlamak."),
            ("He soared higher and higher, leaving a long trail of grey smoke behind him in the bright sunlight.",
             "Ardında parlak güneş ışığında uzun bir gri duman izi bırakarak yükseldikçe yükseldi.",
             "trail of grey smoke | Gri duman izi."),
            ("'Look at me!' he cried exultantly, 'now the whole universe is watching my incomparable ascent!'",
             "Büyük bir zafer sarhoşluğuyla, 'Bana bakın!' diye haykırdı, 'artık bütün kainat benim eşsiz yükselişimi seyrediyor!'",
             "exultantly | Zafer sarhoşluğuyla, coşkuyla."),
            ("'The Prince and Princess are undoubtedly gazing up at me from their palace balcony with open mouths!'",
             "'Prens ile Prenses hiç şüphesiz saray balkonlarından açık kalmış ağızlarıyla bana bakıyorlar!'",
             "with open mouths | Ağzı açık kalmış vaziyette."),
            ("However, it was broad daylight, and the noon sun was shining so brightly that nobody could see any light at all.",
             "Halbuki güpegündüzdü ve öğle güneşi öyle parlak parlıyordu ki hiç kimse en ufak bir ışık bile göremiyordu.",
             "broad daylight | Güpegündüz."),
            ("The two boys had fallen fast asleep under the hedge, tired from their morning walk.",
             "İki çocuk sabah yürüyüşünden yorgun düşmüş halde çitin altında derin bir uykuya dalmıştı bile.",
             "fallen fast asleep | Derin uykuya dalmış."),
            ("Even the tin kettle went on boiling placidly, without paying the slightest heed to the Rocket's flight.",
             "Teneke çaydanlık bile Roket'in uçuşuna en ufak bir dikkat göstermeden usul usul kaynamaya devam etti.",
             "paying the slightest heed | En ufak bir dikkat göstermek / kulak asmak."),
            ("Higher still flew the Rocket, until he reached the very summit of his parabolic flight.",
             "Roket, parabolik uçuşunun tam zirvesine ulaşana dek daha da yükseklere uçtu.",
             "summit of flight | Uçuşun doruk noktası / zirvesi."),
            ("Then he burst into a thousand little stars of gold, silver, ruby, and violet.",
             "Ardından altın, gümüş, yakut ve menekşe renginde binlerce minicik yıldıza bölünerek patladı.",
             "burst into stars | Yıldızlar saçarak patlamak."),
            ("'What a magnificent sensation!' he gasped, 'I am electrifying the souls of millions of spectators!'",
             "Roket soluk soluğa, 'Ne muazzam bir his!' dedi, 'milyonlarca seyircinin ruhunu coşkuyla titretiyorum!'",
             "electrifying the souls | Ruhları coşkuyla titretmek / elektriklemek."),
            ("'I knew that I was destined to create an unprecedented impression upon humanity!'",
             "'İnsanlık üzerinde eşi benzeri görülmemiş bir tesir yaratmak üzere mukadder kılındığımı biliyordum!'",
             "unprecedented impression | Eşi benzeri görülmemiş etki."),
            ("Yet the stars burned out instantly in the blinding glare of the afternoon sun, unseen by any human eye.",
             "Fakat yıldızlar öğle güneşinin kör edici ışıltısı içinde, hiçbir insan gözü görmeden anında sönüp gitti.",
             "blinding glare | Kör edici parlaklık / ışıltı."),
            ("Nobody looked up; nobody clapped; nobody cheered; there was only the gentle rustle of the summer wind.",
             "Kimse yukarı bakmadı; kimse alkışlamadı; kimse tezahürat yapmadı; yalnızca yaz rüzgarının hafif hışırtısı vardı.",
             "rustle | Hışırtı, yaprak sesi."),
            ("Then the empty cardboard tube and the charred wooden stick began to tumble back towards the earth.",
             "Derken boş karton boru ve kömürleşmiş tahta sopa toprağa doğru hızla taklalar atarak düşmeye başladı.",
             "charred wooden stick | Kömürleşmiş tahta sopa."),
            ("Down, down they fell through the silent air, spinning over and over without any dignity or grace.",
             "Vakurdan ve zarafetten yoksun bir şekilde taklalar atıp dönerek sessiz havada aşağı, ta aşağılara düştüler.",
             "without dignity | Vakar ve haysiyetten yoksun."),
            ("Plump! fell the stick right onto the back of an old goose who was taking a walk by the mud-pool.",
             "Pataak! diye sopa, çamur havuzunun yanında yürüyüşe çıkmış yaşlı bir kazın tam sırtına indi.",
             "Plump! | Pat küt sesi (yere düşme nidası)."),
            ("'Good heavens!' shrieked the startled goose, 'it is raining sticks from the sky!' and she ran off honking frantically.",
             "Ürken kaz, 'Aman Tanrım, gökten sopa yağıyor!' diye feryat etti ve çılgınca vaklayarak kaçıp gitti.",
             "startled goose | Ürkmüş / korkmuş kaz; 'honking' kaz sesi çıkarmak."),
            ("'I knew I should create a tremendous sensation,' gasped the Rocket with his last breath, and he went out forever.",
             "Roket son nefesinde soluyarak, 'Muazzam bir sansasyon yaratacağımı biliyordum,' dedi ve sonsuza dek söndü.",
             "tremendous sensation | Muazzam yankı / sansasyon.")
        ],
        "vocab_focus": [
            ("exultantly", "zafer coşkusuyla"),
            ("broad daylight", "güpegündüz"),
            ("heed", "dikkat, kulak asma"),
            ("summit of flight", "uçuşun zirve noktası"),
            ("unprecedented", "eşi benzeri görülmemiş"),
            ("blinding glare", "kör edici ışıltı"),
            ("charred", "kömürleşmiş, yanmış"),
            ("tremendous sensation", "muazzam sansasyon/yankı")
        ]
    }
]

import os

output_file = os.path.join(os.path.dirname(__file__), "book_05_data.py")
with open(output_file, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""\n')
    f.write("Book 5: The Remarkable Rocket (Oscar Wilde)\n")
    f.write("Level 1 Graded Reader — 15 Pages x 20 Sentences = 300 Sentences.\n")
    f.write('"""\n\n')
    f.write('BOOK_TITLE = "The Remarkable Rocket (15 Sayfa / 300 Cümle / Graded Reader)"\n')
    f.write('AUTHOR = "Oscar Wilde"\n\n')
    f.write("PAGES_DATA = [\n")
    
    current_sentence_id = 1
    for page in pages_content:
        f.write("    {\n")
        f.write(f'        "page_no": {page["page_no"]},\n')
        f.write(f'        "title": "{page["title"]}",\n')
        f.write(f'        "tr_title": "{page["tr_title"]}",\n')
        f.write('        "sentences": [\n')
        for s in page["sentences"]:
            text = s[0].replace('"', '\\"')
            tr = s[1].replace('"', '\\"')
            notes = s[2].replace('"', '\\"')
            f.write("            {\n")
            f.write(f'                "id": {current_sentence_id},\n')
            f.write(f'                "text": "{text}",\n')
            f.write(f'                "translation": "{tr}",\n')
            f.write(f'                "notes": "{notes}"\n')
            f.write("            },\n")
            current_sentence_id += 1
        f.write("        ],\n")
        f.write('        "vocab_focus": [\n')
        for v in page["vocab_focus"]:
            v_en = v[0].replace('"', '\\"')
            v_tr = v[1].replace('"', '\\"')
            f.write(f'            ("{v_en}", "{v_tr}"),\n')
        f.write("        ]\n")
        f.write("    },\n")
    f.write("]\n")

print(f"Generated tools/book_05_data.py successfully with {current_sentence_id - 1} sentences!")
